Energy-Sparks/energy-sparks

.gitignore
Gemfile
Gemfile.lock

added rubocop through the govuk-lint gem

add rubocop with govuk-lint

---

app/controllers/stats_controller.rb
app/helpers/schools_helper.rb
app/models/school.rb
app/views/schools/show.html.erb
lib/usage.rb
spec/lib/usage_spec.rb

42 avg weekday usage

---

app/helpers/schools_helper.rb
app/views/schools/daily_usage.html.erb
app/views/schools/show.html.erb
lib/usage.rb
spec/lib/usage_spec.rb

40 day most energy consumption

---

app/assets/javascripts/open_tab.coffee
app/controllers/schools_controller.rb
app/controllers/stats_controller.rb
app/helpers/schools_helper.rb
app/models/school.rb
app/views/schools/daily_usage.html.erb
app/views/schools/hourly_usage.html.erb
app/views/schools/show.html.erb
config/routes.rb
lib/usage.rb
spec/controllers/schools_controller_spec.rb
spec/controllers/stats_controller_spec.rb
spec/lib/usage_spec.rb

43 usage by hour

---

Gemfile
Gemfile.lock
app/controllers/home_controller.rb
app/helpers/application_helper.rb
app/views/home/help.html.erb
app/views/schools/show.html.erb
config/routes.rb
markdown_pages/help/average_weekday_usage.md
markdown_pages/help/default.md

add route, controller method, helper method to render help pages (.md)

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/helpers/application_helper.rb
app/views/activities/_form.html.erb
app/views/activities/show.html.erb

using html editor rather than markdown
closes #51

51 activity description in markdown

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/helpers/application_helper.rb
app/views/activities/_form.html.erb
app/views/activities/show.html.erb
app/views/schools/index.html.erb

72 improve list of unenrolled schools

---

Gemfile
Gemfile.lock
app/assets/javascripts/activities.coffee
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/helpers/application_helper.rb
app/views/activities/_form.html.erb
app/views/activities/show.html.erb
app/views/schools/index.html.erb

71 add calendar widget

---

app/controllers/schools_controller.rb
app/helpers/calendars_helper.rb
app/models/ability.rb
app/models/calendar.rb
app/models/meter.rb
app/models/school.rb
app/views/calendars/edit.html.erb
app/views/calendars/show.html.erb
app/views/schools/show.html.erb
db/migrate/20161028062344_add_calendar_column_to_school.rb
db/schema.rb
lib/loader/schools.rb
spec/controllers/schools_controller_spec.rb
spec/lib/loader/schools_spec.rb
spec/models/calendar_spec.rb

create calendar for school from default, closes #70

70 school calendars

---

app/assets/javascripts/users.coffee
app/controllers/users_controller.rb
app/models/ability.rb
app/views/layouts/_header.html.erb
app/views/users/_form.html.erb
app/views/users/edit.html.erb
app/views/users/index.html.erb
app/views/users/new.html.erb
app/views/users/show.html.erb
config/routes.rb
spec/controllers/activity_types_controller_spec.rb
spec/controllers/users_controller_spec.rb

add user maintenance, closes #78

---

app/assets/javascripts/users.coffee
app/controllers/schools_controller.rb
app/controllers/users_controller.rb
app/models/ability.rb
app/views/layouts/_header.html.erb
app/views/users/_form.html.erb
app/views/users/edit.html.erb
app/views/users/index.html.erb
app/views/users/new.html.erb
app/views/users/show.html.erb
config/routes.rb
spec/controllers/activity_types_controller_spec.rb
spec/controllers/schools_controller_spec.rb
spec/controllers/users_controller_spec.rb

81 link for unenrolled schools

---

Gemfile
Gemfile.lock
app/controllers/schools_controller.rb
app/models/school.rb
config/initializers/friendly_id.rb
db/migrate/20161113141506_create_friendly_id_slugs.rb
db/migrate/20161113144240_add_slug_to_schools.rb
db/schema.rb
spec/factories/school.rb
spec/models/school_spec.rb

Friendlyid

---

.gitignore
Gemfile
Gemfile.lock
spec/rails_helper.rb

Add simplecov to generate reports from rspec

---

lib/merit/usage_calculations.rb

Fix a test that has just started failing in the build. I'm unclear why this has only just started failing because I can't see how it worked before!

Fix activity per week

---

db/migrate/20161210154449_change_integer_limit_on_meters.rb
db/schema.rb

Change column to specify limit. Was rejecting meter numbers due to length limits.

Change integer limit so actual meter ids can be stored

---

app/controllers/schools_controller.rb
app/helpers/schools_helper.rb
app/models/meter.rb
app/views/schools/_form.html.erb
db/migrate/20161211154744_add_name_to_meters.rb
db/schema.rb

Add names to meters, change colours on graphs

Graph improvements

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/base.scss
app/assets/stylesheets/colours.scss
app/assets/stylesheets/footer.scss
app/assets/stylesheets/nav.scss
app/assets/stylesheets/school.scss
app/assets/stylesheets/site.scss
app/views/activities/index.html.erb
app/views/activities/show.html.erb
app/views/home/about.html.erb
app/views/home/contact.html.erb
app/views/home/datasets.html.erb
app/views/home/enrol.html.erb
app/views/home/index.html.erb
app/views/schools/_activity_cards.html.erb
app/views/schools/_description.html.erb
app/views/schools/_electricity_cards.html.erb
app/views/schools/_gas_cards.html.erb
app/views/schools/_school_card.html.erb
app/views/schools/index.html.erb
app/views/schools/show.html.erb
app/views/shared/_footer.html.erb

Numerous layout improvements following feedback from Fizz :100:

Fizz layout improvements

---

app/views/home/about.html.erb
app/views/home/datasets.html.erb

Wording changes from Jeff

---

app/views/schools/_description.html.erb

Open award links in new window, fix urls

---

app/controllers/stats_controller.rb

Addresses comment in #138. But doesn't yet close it.

Reduce precision to one dp

---

app/assets/stylesheets/base.scss
app/assets/stylesheets/footer.scss
app/controllers/stats_controller.rb
app/helpers/schools_helper.rb
app/views/layouts/application.html.erb
app/views/schools/_daily_usage_panel.erb
app/views/schools/_hourly_usage_panel.erb
app/views/schools/daily_usage.html.erb
app/views/schools/hourly_usage.html.erb
config/initializers/chartkick.rb
lib/usage.rb

140 chart titles

---

app/assets/stylesheets/home.scss
app/views/shared/_footer.html.erb
app/views/shared/_head.html.erb

169 revise footer

---

Capfile
Gemfile
Gemfile.lock
config/database.yml
config/deploy.rb
config/deploy/production.rb
config/environments/staging.rb
config/nginx.conf
config/secrets.yml

Initial capistrano setup based on https://www.digitalocean.com/community/tutorials/deploying-a-rails-app-on-ubuntu-14-04-with-capistrano-nginx-and-puma with some tweaks.

Capistrano

---

Gemfile
Gemfile.lock
app/assets/stylesheets/base.scss
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
config/environments/development.rb
config/environments/production.rb
config/environments/staging.rb
config/initializers/devise.rb

Style devise forms, integrate mailgun

---

app/views/schools/_badges.html.erb
app/views/schools/_description.html.erb
app/views/schools/show.html.erb

Change school homepage text

---

app/assets/stylesheets/base.scss
app/controllers/activity_categories_controller.rb
app/controllers/activity_types_controller.rb
app/controllers/home_controller.rb
app/models/ability.rb
app/views/activities/_form.html.erb
app/views/activities/new.html.erb
app/views/activities/show.html.erb
app/views/activity_categories/index.html.erb
app/views/activity_types/_form.html.erb
app/views/activity_types/show.html.erb
app/views/home/badges.erb
app/views/home/getting_started.erb
app/views/shared/_nav.html.erb
config/routes.rb

Getting started

---

app/views/schools/achievements.html.erb

Add text to badge page to close #206

Closes #206

---

app/controllers/schools_controller.rb
app/models/school.rb
app/views/schools/_form.html.erb
db/migrate/20170611111653_add_datasets_to_school.rb
db/schema.rb
lib/loader/energy_importer.rb
spec/factories/school.rb
spec/lib/loader/energy_importer_spec.rb

Support per-school gas and electricity datasets

---

app/controllers/admin_controller.rb
app/controllers/reports_controller.rb
app/models/meter.rb
app/views/reports/index.html.erb
app/views/reports/loading.html.erb
app/views/shared/_nav.html.erb
config/routes.rb

Implement basic loading report. See #217.

Quick loading report to give summary of data

---

app/assets/javascripts/switch_meter.js

Change when event handlers are bound.
Hopefully should address #210

Move event handlers outside of turbolinks:load

---

app/helpers/schools_helper.rb

Switch to yellow for gas

---

app/views/schools/_electricity_cards.html.erb
app/views/schools/_gas_cards.html.erb

Default to a reading one week previous

---

app/assets/javascripts/switch_meter.js
app/views/schools/_hourly_usage_panel.erb

Should hopefully be the final attempt to fix #227.

Use separate ids based on supply to avoid clashes

---

app/assets/stylesheets/activities.scss
app/controllers/activities_controller.rb
app/controllers/activity_types_controller.rb
app/views/activities/index.html.erb
app/views/activities/show.html.erb
app/views/activity_types/show.html.erb
app/views/schools/_activity_cards.html.erb
spec/controllers/activities_controller_spec.rb

Activity list improvements

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/nav.scss
app/assets/stylesheets/school.scss
app/views/activities/show.html.erb
app/views/activity_types/show.html.erb
app/views/home/index.html.erb
app/views/home/team.html.erb
app/views/schools/_activity_cards.html.erb
app/views/schools/_electricity_cards.html.erb
app/views/schools/_gas_cards.html.erb
app/views/schools/_school_card.html.erb
app/views/schools/achievements.html.erb
app/views/schools/daily_usage.html.erb
app/views/schools/hourly_usage.html.erb
app/views/schools/index.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_head.html.erb
app/views/shared/_nav.html.erb

Requires a number of layout fixes based on changes to the selectors.
Also resolves a nagging layout issue with the school homepage cards.

Upgrade bootstrap to latest beta

---

app/controllers/activity_categories_controller.rb
app/models/activity_category.rb
app/views/activities/index.html.erb
app/views/activity_categories/_form.html.erb
app/views/activity_categories/index.html.erb
app/views/activity_categories/show.html.erb
config/locales/en.yml
db/migrate/20170823115504_add_description_to_activity_category.rb
db/schema.rb

249 improve activity list

---

app/assets/stylesheets/school.scss
app/controllers/schools_controller.rb
app/models/activity_category.rb
app/models/school.rb
app/views/activities/index.html.erb
app/views/activity_types/show.html.erb
app/views/schools/_activity_cards.html.erb
app/views/schools/suggest_activity.html.erb
config/routes.rb

248 select activity

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/switch_meter.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/school.scss
app/assets/stylesheets/smoothness.calendars.picker.css
app/views/schools/_electricity_cards.html.erb
app/views/schools/_gas_cards.html.erb
app/views/schools/hourly_usage.html.erb

Closes #271 
Closes #234 
Closes #268 
Closes #269

Hourly graph labelling and links

---

app/views/schools/_electricity_cards.html.erb
app/views/schools/_gas_cards.html.erb
config/locales/en.yml

Update links on school page. Closes 231

---

app/assets/javascripts/switch_meter.js
app/views/schools/hourly_usage.html.erb

Add interpretation tips to hourly chart

---

app/controllers/home_controller.rb
app/controllers/schools_controller.rb
app/models/ability.rb
app/views/activity_categories/index.html.erb
app/views/home/about.html.erb
app/views/home/getting_started.erb
app/views/home/scoring.erb
app/views/schools/_activity_cards.html.erb
app/views/schools/_awards.html.erb
app/views/schools/awards.html.erb
app/views/schools/index.html.erb
app/views/schools/show.html.erb
app/views/shared/_nav.html.erb
config/routes.rb
spec/controllers/schools_controller_spec.rb

Rename badges and achievements to awards

---

app/models/merit/point_rules.rb
spec/controllers/schools_controller_spec.rb

Remove 20 points awarded for enrolling

---

app/controllers/home_controller.rb
app/views/home/contact.html.erb
app/views/home/enrol.html.erb
app/views/home/for_pupils.html.erb
app/views/home/for_teachers.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_nav.html.erb
config/routes.rb
features/home.feature

Rename about to for teachers; add for pupils link

---

app/models/merit/point_rules.rb
spec/controllers/activities_controller_spec.rb

Don't add points for older events

---

app/views/activity_categories/index.html.erb

Tweaked styling

---

app/models/activity_category.rb
app/views/activity_types/show.html.erb

Don't show inactive activity types, or allow them to be recorded

---

app/controllers/stats_controller.rb
app/helpers/schools_helper.rb

Use meter display names in graph labels

---

app/models/ability.rb
spec/controllers/schools_controller_spec.rb

Closes #293

---

app/views/schools/_activity_cards.html.erb

Fix access check

---

app/controllers/schools_controller.rb
app/views/schools/suggest_activity.html.erb
spec/controllers/schools_controller_spec.rb

Use activity progression to help suggest next action.

Revised suggest_activity page

---

app/controllers/schools_controller.rb

Closes #302 (along with improvements in the progression branches)

Filter those that have been done

---

app/helpers/schools_helper.rb
app/views/schools/_electricity_cards.html.erb
app/views/schools/_gas_cards.html.erb

Part of addressing #297 
* Latest date is now more obvious
* Tweaked text to refer to latest date
* Added a muted "since" to clarify range

Improve supply cards

---

app/models/school.rb
app/views/schools/_whole_school_card.html.erb
app/views/schools/_within_school_card.html.erb

Remove active meters from data explorer

---

.gitignore
.overcommit.yml
Gemfile
Gemfile.lock

I'm getting fed up of breaking the linter - at least this should mean I catch it before commiting

Adding overcommit to auto run linting etc

---

Gemfile
Gemfile.lock
app/controllers/schools/chart_data_controller.rb

If the user is an admin user, show the reconciliation figures.

Toggle reconciliation benchmarks based on which user is logged in

---

app/views/schools/_interpretation.html.erb
app/views/schools/chart_data/generic_chart_template.html.erb
app/views/schools/index.html.erb
app/views/shared/_nav.html.erb

* Open blog in new tab
* Link back to school from Dashboard
* Don't show schools which are not enrolled yet

Some changes following user feedback including

---

Gemfile
Gemfile.lock
app/assets/javascripts/common_chart_options.js
app/assets/stylesheets/simulator.scss
app/controllers/concerns/school_aggregation.rb
app/helpers/application_helper.rb
app/services/alert_generator_service.rb

Also reduce cache time and fix chart sizes in simulator

Add degree day tool tip and fix test dashboard thing

---

app/models/amr_data_feed_config.rb
app/services/csv_importer.rb
db/migrate/20181114135310_drop_expect_headers_from_amr_config.rb
db/schema.rb
lib/amr/importer.rb
lib/tasks/amr_importer/import_banes_csv.rake
lib/tasks/amr_importer/import_frome_csv.rake
lib/tasks/amr_importer/import_sheffield_csv.rake
lib/tasks/amr_importer/set_up_frome_csv_config.rake
spec/lib/amr/importer_spec.rb
spec/services/csv_importer_spec.rb

Set up for Frome data import including handling headers/no headers dynamically and importing all available files in t'bucket.

New structure for data feeds 3 Frome

---

app/assets/stylesheets/base.scss
app/views/schools/simulations/_charts.html.erb
app/views/schools/simulations/index.html.erb

Removing d-flex bootstrap classes, which weren't really required and just messed things up on IE

Further internet explorer fixes

---

app/views/schools/show.html.erb
app/views/schools/times/edit.html.erb

Onboarding tweaks

---

app/controllers/reports_controller.rb
app/controllers/schools/meter_readings_validations_controller.rb
app/models/amr_data_feed_reading.rb
app/models/meter.rb
app/views/reports/amr_readings_show.html.erb
app/views/reports/amr_readings_show.json.jbuilder
app/views/reports/loading.html.erb
app/views/schools/meters/index.html.erb
app/views/schools/show.html.erb
config/routes.rb
spec/factories/amr_data_feed_readings_factory.rb
spec/factories/meters_factory.rb
spec/models/meter_spec.rb
spec/support/data_helpers.rb

Validating readings in app

---

Gemfile
Gemfile.lock
app/controllers/schools/simulation_details_controller.rb
app/controllers/schools/simulations_controller.rb
app/views/schools/show.html.erb
config/routes.rb

Change simulation detail to just use simulations controller - bump analytics to use version with patch for the simulator.

Patch for simulations

---

app/controllers/schools/alert_reports_controller.rb
app/models/ability.rb
app/views/schools/show.html.erb

Note that we're using AlertType as the CanCan authoriser at the moment, once we get in to persisting alert notifications or whatever call them, that will be the authorising class...

Allow any logged in user to look at alert reports

---

app/controllers/home_controller.rb
app/views/home/index.html.erb
app/views/layouts/home.html.erb

Seems like the home page is designed not to use the application container, so revert this for now - didn't check enough pages last time!

Add home page rendering layout back, fix missing markup

---

app/helpers/application_helper.rb
app/services/alert_generator_service.rb
app/views/schools/alert_reports/index.html.erb

Ecclesall Alerts has electricity, but only 170 days worth, so the alerts crash

Check you have enough data for alerts

---

app/helpers/schools_helper.rb

Need to see if this causes other problems

Render data values for charts which are over 1000 as integers, not using comma separators for thousands

---

app/controllers/schools/alert_reports_controller.rb
app/helpers/application_helper.rb
app/models/school.rb
app/services/alert_generator_service.rb
app/views/schools/alert_reports/index.html.erb
spec/factories/meters_factory.rb
spec/models/school_spec.rb

Alerts can use this, else you end up with the aggregated data being
earlier than the alert date

New method (with test) to work out the last common date for a supply.

---

Gemfile
Gemfile.lock
config/application.rb
config/initializers/rack_attack.rb

Adding until we can sort out nginx config or AWS WAF

Rack attack

---

Gemfile
Gemfile.lock
app/controllers/schools/analysis_controller.rb
app/controllers/schools/charts_controller.rb
app/views/schools/charts/show.html.erb
config/routes.rb

Render a single chart on a page (for debug at the moment)
Include analytics patch

Single chart rendering page and analytics patch

---

app/views/teachers/schools/show.html.erb

Less jumbotron padding on teacher dash

---

app/services/aggregate_school_service.rb

This reverts commit 994317a9e788b2a59786936ca9d2fd8e736a67d9.

Revert "Switch to using just aggregate for a validated meter collection"

---

lib/data_feeds/weather_underground_loader.rb
lib/tasks/data_feeds_weather_underground_loader.rake

Incorporating further changes from analytics version

Patch for weather underground loader

---

app/models/calendar_area.rb
app/models/dark_sky_area.rb
app/models/solar_pv_tuos_area.rb
app/models/weather_underground_area.rb

In the future we might want these in modules, but for now....

Move areas to stop annotation messages

---

lib/tasks/amr_importer/validate_amr_readings.rake

At the moment if a validation for an amr meter fails, the whole job stops - now, log the error and carry on....

Amr validation - Carry on if one school fails, log the error

---

app/assets/javascripts/application.js
app/assets/javascripts/date_pickers.js
app/assets/stylesheets/datepickers.scss
app/controllers/pupils/schools_controller.rb
app/controllers/schools/observations_controller.rb
app/inputs/tempus_dominus_date_input.rb
app/inputs/tempus_dominus_date_time_input.rb
app/models/ability.rb
app/models/location.rb
app/models/observation.rb
app/models/school.rb
app/models/temperature_recording.rb
app/views/pupils/schools/show.html.erb
app/views/schools/observations/_temperature_recording_fields.html.erb
app/views/schools/observations/index.html.erb
app/views/schools/observations/new.html.erb
app/views/schools/observations/show.html.erb
config/routes.rb
db/migrate/20190508135155_create_observations.rb
db/migrate/20190508135199_create_locations.rb
db/migrate/20190508135200_create_temperature_recordings.rb
db/schema.rb
spec/system/add_observation_spec.rb

Early structure for recording temperatures, including Observation, Location, Temperature Recordings to, in the future just have Observations (as interventions). 
There is more to be done on this really, but as it was started a month ago, would be good to get this version sorted, then we can enhance it further.

Online form for temperatures

---

app/assets/stylesheets/nav.scss
app/views/shared/_sub_nav.html.erb

The misalignment on the sub-nav has been driving me a bit nuts - minor tweak to align the items centrally.

Update styles accordingly

---

app/assets/javascripts/application.js
app/assets/javascripts/date_pickers.js
app/assets/javascripts/observations.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/observations.scss
app/inputs/tempus_dominus_date_input.rb
app/models/observation.rb
app/models/temperature_recording.rb
app/views/schools/observations/_temperature_recording_fields.html.erb
app/views/schools/observations/new.html.erb
spec/factories/locations_factory.rb
spec/factories/observations_factory.rb
spec/models/observation_spec.rb
spec/models/temperature_recording_spec.rb
spec/system/add_temperature_recordings_spec.rb

Date/time picker and validation shouldn't allow dates after today
Remove placeholders and give hints instead
Make it clear the temperature is C
Make temperature field a number field
Validate for extreme temperatures - 0 to 50
Remove what we did box
Tooltip flash messages
Add validation around date, including updating date picker
Change temperature to be a numeric field and show degrees
Update to validate temperatures
Check for temperatures and show a message
Handle error handling a bit better
Improve positioning of tooltips

Add copy, remove description

---

Gemfile
Gemfile.lock
Guardfile

Felt the need to have Guard in my life for a bit - run with ```bundle exec guard``` if you feel inclined, also remove spring and capistrano from Gemfile

Add guard, set up config and remove capistrano and spring

---

Gemfile
Gemfile.lock

Started getting the random readline error on laptop - this fixes it without requiring a Ruby re-install - I don't think there is a performance hit, but ¯\_(ツ)_/¯

Add readline

---

Gemfile
Gemfile.lock

BigDecimal, DegreeDays, HashDiff, ChartConfig and Chart Exceptions

Bump analytics

---

lib/tasks/deployment/20190716110808_add_new_alert_types.rake

New alerts

---

.ebextensions/02_install_yarn.config

Assumes that the environment variable has been set...

Set up Font Aweseome authentication

---

app/views/schools/_form.html.erb
app/views/teachers/schools/show.html.erb
spec/system/school_spec.rb

Makes sense to do this now whilst working on the teachers dashboard...

Move deactivate, copy activate

---

app/assets/stylesheets/colours.scss
app/assets/stylesheets/headers.scss
app/assets/stylesheets/links.scss
app/assets/stylesheets/pupils.scss
app/assets/stylesheets/teachers.scss
app/views/admin/calendar_areas/index.html.erb
app/views/pupils/schools/_equivalence.html.erb
app/views/pupils/schools/_podium.html.erb
app/views/pupils/schools/show.html.erb
app/views/schools/analysis/generic_chart_template.html.erb
app/views/shared/_sub_nav.html.erb

Includes restyling of buttons (in general) and Pupil's dashboard - including podium

Alert bars teachers pupils part 2

---

Gemfile
Gemfile.lock

Roundhill validation was failing, this simply adds a meter attribute to fix it.

Patch for Roundhill

---

Gemfile
Gemfile.lock

All PRs will fail until the Devise update is merged....

Update Devise (CVE) and trix gem to official release

---

app/models/scoreboard.rb
spec/models/scoreboard_spec.rb

Fix for change I made on a previous PR - related to this comment : https://github.com/BathHacked/energy-sparks/pull/760/files#r322210828

Fix join to show all schools

---

app/services/amr/low_carbon_hub_upserter.rb

Upserter wasn't updating log following upsert.

Update log post upsert

---

app/assets/javascripts/observations.js
app/helpers/application_helper.rb
app/views/schools/temperature_observations/_temperature_recording_fields.html.erb
app/views/schools/temperature_observations/index.html.erb
app/views/schools/temperature_observations/new.html.erb

Copy, form entry and display of temperatures - all improved....

Temperature recording updates part 1

---

app/services/alerts/alert_attributes_factory.rb
app/services/alerts/generate_alert_type_run_result.rb
app/services/alerts/generate_and_save_alerts.rb
app/services/alerts/generate_and_save_benchmarks.rb
spec/services/alerts/generate_alert_type_run_result_spec.rb
spec/services/alerts/generate_and_save_alerts_spec.rb

- Run on date not being set as not being saved at alert level
- Default to whatever the analytics adapter decides is the best asof rather than running today - lots of alerts fail if you run them for today...

Alert production issues

---

Gemfile
Gemfile.lock
app/services/amr/analytics_unvalidated_amr_data_factory.rb
app/services/amr/upsert_validated_readings_for_a_meter.rb
spec/factories/dashboard_one_day_amr_readings_factory.rb
spec/services/amr/analytics_unvalidated_amr_data_factory_spec.rb
spec/services/amr/upsert_validated_readings_for_a_meter_spec.rb

Based on meter attributes spike - but the Highlands fix and removal of upsert

BASED ON METER ATTRIBUTES SPIKE - Patch for highlands ordering and remove upsert

---

.ebextensions/setup_swap.sh
README.md

Minimising the risk of running out of memory, by increasing swap space to 4Gb and removing the old swap file

Increase swap space

---

spec/system/resources_spec.rb

@jhigman I was able to get the test to reliably fail locally using an rspec seed. 
This change seems to resolve the issue consistently.

Changed to before :each

---

app/views/admin/school_onboardings/configuration/edit.html.erb
app/views/schools/configuration/_form.html.erb

Add option for removing selected option in form fields.

Allow Dark Sky Areas to be blank

---

app/controllers/home_controller.rb
app/views/home/attribution.html.erb
app/views/shared/_footer.html.erb
config/routes.rb

Public attributions for datasets we're using.

Add attribution page

---

.ebextensions/cronjob.config

Add a new cron job to back fill Meteostat data.

Add meteostat back fill

---

lib/tasks/deployment/20210201151116_add_meteostat_stations_to_schools.rake

Add schools to new weather station with same title, lat, long as their Dark Sky Area (created in previous task).

Associate all schools with their new station, based on DSA

---

app/controllers/map_controller.rb

Add a sort order when querying schools to go into geojson

Add default order

---

app/views/activity_types/_activity_type_badges.html.erb
app/views/activity_types/_activity_type_resources.html.erb
app/views/activity_types/_prompt_complete_activity.html.erb
app/views/activity_types/show.html.erb
app/views/admin/activity_types/show.html.erb
app/views/schools/activity_types/show.html.erb
spec/system/schools/activity_types_spec.rb

Fixes bug in display of resources, refactoring the templates.
Added minimal test to check that image is added to page.

Display activity type resources to school users

---

Gemfile
Gemfile.lock
app/controllers/home_controller.rb
app/helpers/timeline_helper.rb
app/services/events/event.rb
app/services/events/list_events.rb
app/views/home/training.html.erb
app/views/schools/observations/_timeline.html.erb
app/views/shared/_about_menu.html.erb
config/routes.rb
spec/fixtures/events/events.json
spec/helpers/timeline_helper_spec.rb
spec/services/events/event_spec.rb
spec/services/events/list_events_spec.rb
spec/system/home_spec.rb

Add a training page that lists upcoming events from EventBrite

2021 training page

---

app/views/onboarding_mailer/activation_email.html.erb

Update school confirmation email

---

lib/tasks/deployment/20210216165410_add_new_impacts.rake

Add new impacts for categorising and filtering activity types

Add 2 new impacts

---

app/services/import_notifier.rb
app/views/import_mailer/_meter_table.html.erb
app/views/import_mailer/import_summary.html.erb

Sort by area, fuel type then school

Change sort and column order

---

app/views/admin/reports/amr_data_feed_import_logs/index.html.erb

Add `data-order` attribute so DataTables knows how to sort the table.

Add data-order attribute

---

app/controllers/admin/schools/meter_reviews_controller.rb
app/controllers/schools/meters_controller.rb
app/views/admin/schools/meter_reviews/index.html.erb
app/views/schools/meters/index.html.erb
spec/system/admin/meter_reviews/meter_reviews_spec.rb

Added some links from the meter page to historical meter reviews and performing a new review if there are any meters outstanding.

Add links to meter review functionality from meter mgt page

---

app/controllers/admin/schools/bill_requests_controller.rb
app/mailers/bill_request_mailer.rb
app/services/schools/bill_request_service.rb
app/views/admin/meter_reviews/index.html.erb
app/views/admin/schools/bill_requests/new.html.erb
app/views/bill_request_mailer/request_bill.html.erb
config/routes.rb
spec/factories/users_factory.rb
spec/services/schools/bill_request_service_spec.rb
spec/system/admin/meter_reviews/bill_requests_spec.rb

Form to allow admin to request bill from school, selecting where to send the email and which meters to mention.

1323 allow admin to request school submits an energy bill

---

app/controllers/concerns/non_public_schools.rb
app/controllers/pupils/schools_controller.rb
app/controllers/schools/private_controller.rb
app/controllers/schools_controller.rb
app/controllers/teachers/schools_controller.rb
app/models/ability.rb
app/views/schools/private/show.html.erb
app/views/schools/show.html.erb
app/views/shared/_school_login_prompt.html.erb
config/routes.rb
spec/models/ability_spec.rb
spec/system/management/dashboard_spec.rb
spec/system/pupils/school_spec.rb
spec/system/school_spec.rb
spec/system/teachers/school_spec.rb

* Add rspec for the abilities, as its getting complex. currently just covers dashboard
* Add system specs to check for access to various dashboards
* Add controller and page to prompt people to login when viewing non-public schools

1365 implement non public schools

---

.ebextensions/cronjob.config
Gemfile
Gemfile.lock

Add new cron entry
Bump version of analytics

add cron entry for tariff loading

---

app/models/ability.rb
spec/models/school_group_spec.rb
spec/models/school_spec.rb
spec/models/scoreboard_spec.rb

* Add missing permissions to staff/pupils
* Tidy up ability.rb slightly to gather common permissions together

Gdst permissions fixes

---

app/models/school_onboarding.rb
app/views/onboarding/show.html.erb
db/schema.rb
spec/system/school_onboarding_spec.rb

Makes the initial onboarding page a bit more user-friendly when resuming onboarding.
Branched from #1369.

1512 improve navigation when resuming onboarding

---

app/controllers/admin/meters_controller.rb
app/views/admin/index.html.erb
app/views/admin/meters/index.html.erb
config/routes.rb
spec/system/admin/meters_spec.rb

Adds a new admin option to find schools based on search by wildcard mpxn.
Also tidied up formatting on admin page.

Add find by mpxn, tidy admin page

---

app/models/school.rb
app/models/school_target.rb
db/migrate/20210720083618_create_school_targets.rb
db/schema.rb
spec/factories/school_targets.rb
spec/models/school_spec.rb
spec/models/school_target_spec.rb

* Revised model: added explicit start_date, renamed target to target_date
* Tidied up specs, improved testing
* Added helper methods for finding targets, current target, most recent target to aid creation of reports

1584 create data model for storing school targets start date

---

Gemfile
Gemfile.lock

Bump to 1.26.2

---

app/controllers/management/schools_controller.rb
app/controllers/schools/consent_documents_controller.rb
app/services/schools/bill_request_service.rb
app/views/management/schools/_prompt_for_bill.html.erb
app/views/management/schools/show.html.erb
app/views/schools/consent_documents/index.html.erb
app/views/schools/consent_documents/new.html.erb
db/migrate/20211111113436_add_bill_requested_to_school.rb
db/schema.rb
spec/services/schools/bill_request_service_spec.rb
spec/system/schools/consent_documents_spec.rb

* add a flag to school to indicate if we have requested that a bill be provided
* remove flag when a bill is uploaded or updated
* add a note on the dashboard to say that we've requested a bill, if flag is set
* add some instructions (previously only in the email) to the upload pages

1860 include prompt for bill upload on mgt dashboard

---

app/views/management/schools/_prompt_training.html.erb
spec/system/management/dashboard_spec.rb

Change link text on dashboard prompt

Fix link text

---

app/views/pupils/schools/_default_equivalences.html.erb
app/views/pupils/schools/show.html.erb
spec/system/pupils/dashboard_spec.rb

* add an info box
* add a comment in the equivalence section

Add clearer messaging on pupil dashboard

---

.elasticbeanstalk/config.yml
Procfile
config/puma.rb

Reintroduce app specific puma config.
Reduce threads from EB default, including EB socket and logging config, add preloading.

Puma config

---

Gemfile
Gemfile.lock

For use in development: https://scoutapm.com/devtrace
`SCOUT_DEV_TRACE=true rails server`

Install scout_apm

---

.ebextensions/cronjob.config

Only run Tuesday and Friday. Make it slightly earlier.

Change frequency of job

---

Gemfile
Gemfile.lock
spec/system/calendar_spec.rb

Switch to bug fix branch of analytics to allow testing of generating targets with limited data.

Switch to bug fixed version of analytics

---

Gemfile
Gemfile.lock

Includes:
- fix for solar panel report table
- issue with out of date alert
- improved date checking for whether annual estimates are useful
- fix for % issues in target reports

Analytics 1.40.3

---

db/migrate/20220329153127_add_unique_to_transport_type_name.rb
db/schema.rb
lib/tasks/deployment/20220329132401_populate_transport_types.rake

* Adds a unique constraint to transport_types#name
* Adds an afterparty task to populate the transport_types table

Populate transport types

---

Gemfile
Gemfile.lock

* bad annual estimate method
* missing weekend days for community use
* handle negative targets when estimate is too small
* handle target start date before first meter data
* only use full month for target

Analytics 1.40.7

---

Gemfile
Gemfile.lock

Bump to analytics-1.40.8

---

Gemfile
Gemfile.lock

Update analytics version to fix some links in help text.

Update to 1.50.1

---

.ebextensions/cronjob.config
bin/fetch_banes_files_and_push_to_S3.sh

Add clearer start/end time logging
Direct stdout/stderr to the usual log file.

2134 add logging to banes job

---

Gemfile
Gemfile.lock
app/controllers/benchmarks_controller.rb

* Additional fixes for targets and tracking charts
* Some largely non-functional changes, including tweaks to test framework
* Bug fix for WeatherCache
* Tweaks to FormatEnergyUnit
* Optimise benchmarks when running from app

Analytics 1.50.3

---

Gemfile
Gemfile.lock

Incorporate a typo fix in the analytics.

Analytics 1.50.5.1

---

app/assets/javascripts/templates/transport_surveys.hbs
app/controllers/schools/transport_surveys/responses_controller.rb
app/controllers/schools/transport_surveys_controller.rb
app/helpers/transport_surveys_helper.rb
app/javascript/packs/transport_surveys.js
app/javascript/packs/transport_surveys/carbon.js
app/javascript/packs/transport_surveys/charts.js
app/javascript/packs/transport_surveys/handlebars_helpers.js
app/models/transport_survey.rb
app/models/transport_survey_response.rb
app/models/transport_type.rb
app/views/schools/transport_surveys/_header_nav.html.erb
app/views/schools/transport_surveys/_intro.html.erb
app/views/schools/transport_surveys/_nav.html.erb
app/views/schools/transport_surveys/_pagy.html.erb
app/views/schools/transport_surveys/edit.html.erb
app/views/schools/transport_surveys/index.html.erb
app/views/schools/transport_surveys/responses/index.html.erb
app/views/schools/transport_surveys/show.html.erb
config/routes.rb
spec/models/transport_survey_response_spec.rb
spec/models/transport_survey_spec.rb
spec/models/transport_type_spec.rb
spec/system/schools/transport_surveys_app_spec.rb
spec/system/schools/transport_surveys_spec.rb

Covers both of these Trello cards as it made sense to rewrite the system rspec for both at the same time
- [Improve transport survey results page](https://trello.com/c/vb6K0EX6/2028-improve-transport-survey-results-page)
- [Improve transport survey list page](https://trello.com/c/SPANyvN5/2027-improve-transport-survey-list-page)
- Also attempts to make the navigation between pages better (up for discussion!)

Improve transport survey results & list pages

---

app/views/schools/transport_surveys/_intro.html.erb

Changes to the intro text as provided by Claudia

Update Transport survey start page

---

app/models/transifex_load.rb
app/models/transifex_load_error.rb
app/services/transifex/loader.rb
app/views/admin/reports/transifex_loads/index.html.erb
db/migrate/20220622121758_add_status_to_transifex_load.rb
db/schema.rb

* Add a status to TransifexLoad to indicate whether it is running or done
* Ensure status is set and updated during a run
* Display status on admin report
* Add a catch-all exception handler to the loader for unknown errors and then ensure these are logged
* Add some basic logging to rails logger to indicate progress

Improve logging of transifex loads

---

app/controllers/transport_types_controller.rb
app/javascript/packs/transport_surveys.js
app/javascript/packs/transport_surveys/carbon.js
app/javascript/packs/transport_surveys/storage.js
app/models/transport_survey_response.rb
app/models/transport_type.rb
app/views/schools/transport_surveys/_intro.html.erb
app/views/schools/transport_surveys/edit.html.erb
spec/models/transport_survey_response_spec.rb

* Changes park and stride to use 10 minutes rather than 15.
* Also makes park and stride configurable & tidies up how the general app config works
* Also refactors fetching of transport types via new app config rather than via a json query (less to go wrong in the js)

Change park and stride to 10 minutes & make it configurable

---

Gemfile
Gemfile.lock

* Includes [bug fixes](https://github.com/Energy-Sparks/energy-sparks_analytics/pull/276)
* Dependency update for rails-html-sanitizer
* Removes Mechanize
* Removes `profile` file
* [New benchmarks](https://github.com/Energy-Sparks/energy-sparks_analytics/pull/279)
* [Improve validation model failure when missing data](https://github.com/Energy-Sparks/energy-sparks_analytics/pull/280)
* [PV Live base URL change](https://github.com/Energy-Sparks/energy-sparks_analytics/pull/281)

Analytics 1.60.0

---

app/controllers/schools/transport_surveys/responses_controller.rb
app/models/transport_survey_response.rb
app/views/schools/transport_surveys/edit.html.erb
app/views/schools/transport_surveys/responses/index.html.erb
config/locales/activerecord.yml
config/locales/views/schools/transport_surveys.yml
spec/models/transport_survey_response_spec.rb
spec/system/schools/transport_surveys_app_spec.rb
spec/system/schools/transport_surveys_spec.rb

Realised I really needed to translate transport type name column first in order to finish this off properly.
Been working on that [here](https://github.com/Energy-Sparks/energy-sparks/pull/1909).

Allow responses to be downloaded to csv

---

app/views/shared/_about_menu.html.erb
app/views/shared/_common_nav_bar_menus.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_manage_menu.html.erb
app/views/shared/_manage_school.html.erb
app/views/shared/_mini_nav.html.erb
app/views/shared/_my_school_menu.html.erb
app/views/shared/_nav.html.erb
app/views/shared/_our_schools_menu.html.erb
app/views/shared/_our_services_menu.html.erb
app/views/shared/_switch_schools.html.erb
config/locales/cy/views/shared/shared.yml
config/locales/views/shared/shared.yml

This PR adds I18n support to main website navigation

Localise website navigation

---

Gemfile
Gemfile.lock
lib/tasks/deployment/20220725141319_rename_advice_gas_boiler_thermostatic.rake

* [text updates for thermostatic analysis](https://github.com/Energy-Sparks/energy-sparks_analytics/pull/284)
* [update annual comparison benchmark text](https://github.com/Energy-Sparks/energy-sparks_analytics/pull/285)

Analytics 1.60.2

---

app/controllers/admin/activity_types_controller.rb
app/controllers/admin/reports/activity_types_controller.rb
app/models/activity.rb
app/models/activity_type.rb
app/views/admin/activity_types/index.html.erb
app/views/admin/reports/activities/index.html.erb
app/views/admin/reports/activity_types/index.html.erb
app/views/admin/reports/activity_types/show.html.erb
app/views/admin/reports/index.html.erb
config/routes.rb
spec/system/admin/reports/activity_types_spec.rb

This PR adds a couple of new admin reports to allow us to better review and manage the activity types.
The main report is a summary of all activity types, along with some stats on how often they've been recorded and referenced from other parts of the system.
Then for each activity type there is a report that summarises which schools have recorded that activity, along with dates, etc.
I've also tidied up a couple of related pages to add some consistent navigation, table formatting, etc.
The tests are basic: just exercising that the reports display with the expected content and some navigation checks.

Admin activity type reports

---

app/views/intervention_type_groups/index.html.erb
app/views/intervention_type_groups/recommended.html.erb
app/views/intervention_type_groups/show.html.erb
app/views/intervention_types/_intervention_type_points.html.erb
app/views/intervention_types/_prompt_score.html.erb
app/views/intervention_types/search.html.erb
app/views/intervention_types/show.html.erb
app/views/programme_types/_cards.html.erb
app/views/programme_types/_completed.html.erb
app/views/programme_types/_prompt.html.erb
app/views/programme_types/_prompt_login.html.erb
app/views/programme_types/_started.html.erb
app/views/programme_types/index.html.erb
app/views/programme_types/show.html.erb
config/locales/views/intervention_type_groups/intervention_type_groups.yml
config/locales/views/intervention_types/intervention_types.yml
config/locales/views/programme_types/programme_types.yml
spec/system/interventions_spec.rb

This ticket covers adding I18n support to the ERB templates for 
The model content will already be translated, so this is just changes to the ERB templates.

Localise Intervention Type Group, Intervention Type, Programme Type

---

lib/tasks/deployment/20220802113838_smartest_energy_data_feed.rake

Adding a new data feed config for Smartest Energy Portal

Smartest Energy Portal Config

---

Gemfile
Gemfile.lock
app/controllers/benchmarks_controller.rb
lib/tasks/deployment/20220803113630_alert_electricity_usage_during_current_holiday.rake

New version of analytics, plus new Alert Type.
Includes a range of PRs from the analytics:
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/287
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/288
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/289
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/290
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/291
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/292
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/293
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/294
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/296
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/297

Analytics 1.70.0

---

app/assets/stylesheets/links.scss
app/views/benchmarks/index.html.erb
app/views/intervention_types/show.html.erb
config/locales/common.yml
config/locales/views/activity_categories/activity_categories.yml
config/locales/views/home/home.yml
config/locales/views/intervention_type_groups/intervention_type_groups.yml

Various text and formatting changes ahead of translation.

Tidy up text and formatting

---

.tx/config
lib/tasks/i18n/generate_tx_config.rake

Ran:
```
bundle exec rake i18n:copy_analytics_yaml
bundle exec rake i18n:generate_tx_config
```
To generate an updated config for the transifex command-line tool. The tool is used to push YAML files to transifex. 
Contents of this config has been pushed. Checking in update so we can pull down YAML when translated.

Update TX config

---

Gemfile
Gemfile.lock

* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/295
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/298
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/299
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/300

Update analytics to 1.80.0

---

app/models/alert.rb
app/views/schools/alerts/show.html.erb
config/locales/models/lists.yml
spec/system/activity_types_spec.rb
spec/system/admin/calendars_spec.rb

Add the Welsh template variables to the mgt report, to help with testing/debugging translations.

Show welsh template variables in mgt report

---

Gemfile
Gemfile.lock
config/i18n-tasks.yml
config/locales/analytics/alerts/common/common.yml
config/locales/analytics/alerts/electricity/baseload.yml
config/locales/analytics/alerts/electricity/electricity.yml
config/locales/analytics/alerts/electricity/tariffs.yml
config/locales/analytics/alerts/gas/boilercontrol.yml
config/locales/analytics/alerts/gas/gas.yml
config/locales/analytics/alerts/gas/hotwater.yml
config/locales/analytics/alerts/time_period_comparison/time_period_comparison.yml
config/locales/analytics/charts/chart_configuration.yml
config/locales/analytics/common.yml
config/locales/analytics/dates.yml
config/locales/analytics/energy_units.yml

* Bump analytics to tagged version
* Copy over and check-in YAML
* Tweak i18n-tasks configure to ignore chart_configuration
* Delete analytics copy of dates (need to fix this in the copying to avoid doing this repeatedly)

Analytics 2.0

---

app/views/schools/transport_surveys/_intro.html.erb
app/views/schools/transport_surveys/_no_javascript_warning.html.erb
app/views/schools/transport_surveys/_progress_bar.html.erb
app/views/schools/transport_surveys/edit.html.erb
config/locales/views/schools/transport_surveys.yml
spec/system/schools/transport_surveys_app_spec.rb
spec/system/schools/transport_surveys_spec.rb

This covers i18n for the non-javascript parts of the transport survey app.

Add I18N to the Transport Survey ERB templates

---

app/classes/tables/summary_table_data.rb
app/views/management/schools/_overview_charts.html.erb
app/views/management/schools/_overview_data.html.erb
app/views/schools/observations/_timeline.html.erb
app/views/shared/_dashboard_alerts.html.erb
app/views/shared/_dashboard_title.html.erb
app/views/shared/_dashboards.html.erb
app/views/shared/_manage_menu.html.erb
app/views/shared/_partners.html.erb
config/locales/classes/tables/tables.yml
config/locales/views/management/management.yml
config/locales/views/schools/schools.yml
config/locales/views/shared/shared.yml

This pr adds a bunch of missing extracted text for translations following a manual review of all pages (using the mirror backend).

Manual review of all pages to check for any untranslated text

---

app/assets/javascripts/templates/transport_surveys.hbs
app/javascript/packs/transport_surveys.js
app/javascript/packs/transport_surveys/charts.js
app/javascript/packs/transport_surveys/handlebars_helpers.js
app/javascript/packs/transport_surveys/helpers.js
app/javascript/packs/transport_surveys/storage.js
app/views/schools/transport_surveys/_app_config.html.erb
app/views/schools/transport_surveys/edit.html.erb
app/views/schools/transport_surveys/show.html.erb
config/i18n-tasks.yml
config/locales/views/schools/transport_surveys.yml

This PR adds the i18n required for the javascript portion of the Transport Survey App.

Add i18n support to the transport survey javascript

---

app/views/schools/timeline/show.html.erb
config/locales/views/schools/schools.yml

Just a couple of translations missing. Looks like other untranslated items have not yet come down from Transifex.

Add missing translations to timeline

---

app/views/schools/usage/show.html.erb
config/locales/views/schools/schools.yml

Also translates 'All meters' text

Translate 'Which meter?' text

---

config/locales/cy/views/pupils/pupils.yml

This pr fixes a typo in transifex - it has been fixed in transifex, marked reviewed and pulled down into this pr.

Fix welsh fuel types being preceded by a 1

---

.tx/config
config/locales/cy/common.yml
config/locales/cy/views/schools/schools.yml
config/locales/cy/views/schools/transport_surveys.yml
config/locales/cy/views/shared/shared.yml

This pr brings in some new translations and updates the transifex config to include pagy and tables yaml files - both have been pushed to transifex https://www.transifex.com/energy-sparks/energy-sparks/settings/timeline/

Add some more pulled tx translations & update tx config

---

lib/tasks/alerts/delete_alert_content.rake

This pr provides a Rake task to run the content deletion service merged in 
https://github.com/Energy-Sparks/energy-sparks/pull/1999/files

Rake task for content deletion service

---

app/controllers/admin/users_controller.rb
app/views/admin/users/_form.html.erb
app/views/admin/users/index.html.erb
spec/controllers/admin/users_controller_spec.rb

Send confirmation emails for all accounts created by an admin, to ensure that user sets password and agrees to the terms and conditions.
Tweak formatting of table to use Bootstrap 4 table class, not older Bootstrap 3 class.

Ensure confirmation emails sent for admin created accounts

---

app/views/admin/reports/alert_subscribers/index.html.erb

Add a drop-down similar to the users page.

Add school group navigation option to alert subscribers report

---

.github/workflows/rubyonrails.yml

Build and run tests against the Postgres 14 image rather than 10.

Switch Github Action to Postgres 14

---

Gemfile
Gemfile.lock
app/controllers/home_controller.rb
app/services/schools/reporting_statistics_service.rb
app/views/home/_country_summary.html.erb
app/views/home/_onboarding_status.html.erb
app/views/home/_school_details.html.erb
app/views/home/_school_meals.html.erb
app/views/home/_school_types.html.erb
app/views/home/school_statistics.html.erb
config/locales/cy/views/home/school_statistics.yml
config/locales/views/home/school_statistics.yml

Reworks the school statistics page so it's more suitable for our external reporting requirements.
Has new sections for:
- types of school
- onboarding status
- free school meals, by range
- schools by country
- list of school details

Rework school statistics page

---

app/models/school.rb
spec/models/school_spec.rb

* Percentage free school meals should be between 0..100
* Postcodes should match a known format. Added case insensitive regex for handling this

Add validators to school model

---

config/locales/analytics/charts/chart_configuration.yml
config/locales/analytics/energy_units.yml
config/locales/cy/analytics/alerts/electricity/baseload.yml
config/locales/cy/analytics/alerts/electricity/electricity.yml
config/locales/cy/analytics/alerts/gas/boilercontrol.yml
config/locales/cy/default.yml
config/locales/cy/models/chart_data_values.yml
config/locales/cy/views/admin/school_groups/school_groups.yml
config/locales/cy/views/home/home.yml
config/locales/cy/views/intervention_type_groups/intervention_type_groups.yml
config/locales/cy/views/intervention_types/intervention_types.yml
config/locales/cy/views/programme_types/programme_types.yml
config/locales/cy/views/schools/temperature_observations.yml
config/locales/cy/views/schools/transport_surveys.yml

Resync with transifex

---

app/views/shared/_manage_school.html.erb
config/locales/views/shared/shared.yml

Temporarily remove link to new forms, pending some rework of the UI and options.

Remove alt heating source menu option

---

app/controllers/admin/school_groups/notes_controller.rb
app/controllers/admin/schools/notes_controller.rb
app/models/concerns/csv_exportable.rb
app/models/note.rb
app/models/transport_survey_response.rb
app/views/admin/school_groups/_issues.html.erb
app/views/admin/school_groups/show.html.erb
app/views/admin/schools/notes/_note.html.erb
config/routes.rb
spec/models/note_spec.rb
spec/system/admin/school_groups_spec.rb

Trello card: [2484-allow-admins-to-export-open-issues-for-a-group](https://trello.com/c/YSHx9WXt/2484-allow-admins-to-export-open-issues-for-a-group)

Allow admins to export open issues for a group

---

Gemfile
Gemfile.lock

* Fix for annual energy use page
* Correct dates on Layer up/Power down benchmark

Analytics 2.1.2

---

lib/tasks/deployment/20221123174437_digital_energy_feed.rake

New feed config for Digital Energy. Have tested this against a sample file and parses OK.

Digital Energy Feed Config

---

app/assets/stylesheets/issues.scss
app/assets/stylesheets/links.scss
app/controllers/admin/issues_controller.rb
app/models/issue.rb
app/views/admin/issues/_form.html.erb
app/views/admin/issues/_issue.html.erb
app/views/admin/issues/index.html.erb
app/views/admin/school_groups/_active_schools.html.erb
app/views/admin/school_groups/_issues.html.erb
app/views/admin/school_groups/_issues_link.html.erb
app/views/admin/school_groups/_onboarding_schools.html.erb
app/views/admin/school_groups/_removed_schools.html.erb
app/views/admin/school_groups/_schools_tabs.html.erb
app/views/admin/school_groups/show.html.erb
spec/models/school_group_spec.rb
spec/system/admin/school_groups_spec.rb

* Adds counter badges to issues tabs on school group admin page
* Adds counter badges to issues buttons on school group admin page
* Also tidies the issues styles a bit
* Spotted that the issue owner was missing from the issues csv, so added that in too

Add issue counters

---

app/controllers/schools/audits_controller.rb
app/views/schools/audits/_audit_activity_type_fields.html.erb
app/views/schools/audits/_audit_intervention_type_fields.html.erb
app/views/schools/audits/_form.html.erb
app/views/schools/audits/edit.html.erb
app/views/schools/audits/index.html.erb
app/views/schools/audits/new.html.erb
app/views/schools/audits/show.html.erb
config/locales/common.yml
config/locales/views/schools/schools.yml

test coverage in `bundle exec rspec spec/system/schools/audits_spec.rb`

Translate Audit pages

---

app/assets/stylesheets/issues.scss
app/views/admin/issues/_form.html.erb
app/views/admin/issues/_issue.html.erb
app/views/admin/issues/_owned_by.html.erb
app/views/admin/issues/_status.html.erb
spec/system/admin/issues_spec.rb

Also makes sure page flow is correct after validation fail iterations (spotted while doing this fix).

Fix trix non-scrolling issue for notes/issues

---

app/helpers/application_helper.rb
app/views/admin/school_groups/_active_schools.html.erb
app/views/admin/school_groups/_removed_schools.html.erb
app/views/admin/school_groups/index.html.erb
app/views/admin/shared/_dashboard_message.html.erb
app/views/management/schools/_dashboard_message.html.erb
app/views/schools/show.html.erb
spec/support/admin_dashboard_messages.rb

+ Also adds a dashboard message icon for schools in the active tab with a dashboard message
+ Also removes an extra issues button that slipped in to the removed schools tab
+ Also reformats dashboard message html

Display per school dashboard messages

---

app/controllers/admin/issues_controller.rb
spec/system/admin/issues_spec.rb

This is forked off another PR awaiting review. Blocked for now

Add school context menu to school issues page

---

app/services/schools/reporting_statistics_service.rb
app/views/home/_country_summary.html.erb

Add total pupil numbers to statistics page country summary 

---

Gemfile
Gemfile.lock
config/locales/analytics/alerts/common/common.yml
config/locales/analytics/energy_units.yml
lib/tasks/deployment/20230105151513_new_comparison_benchmarks.rake

Contains changes from:
https://github.com/Energy-Sparks/energy-sparks_analytics/pull/375
* updates to YAML
* configuration for 6 new alert types for school comparisons
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/380
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/381

Analytics 2.3.8.1

---

Gemfile
Gemfile.lock

Hopefully fixes an issue in one of the advice pages

Analytics 2.3.8.2

---

Gemfile
Gemfile.lock
config/locales/analytics/modelling/heating/heating.yml

Updates analytics with a variety of changes including:
* [bug fix for solar pv advice page](https://github.com/Energy-Sparks/energy-sparks_analytics/pull/391)
* [fix for thermostatic charts](https://github.com/Energy-Sparks/energy-sparks_analytics/pull/390)
* [New Heating Time services](https://github.com/Energy-Sparks/energy-sparks_analytics/pull/388)
* Updates to [baseload services](https://github.com/Energy-Sparks/energy-sparks_analytics/pull/387)
* [improvements to baseload advice page](https://github.com/Energy-Sparks/energy-sparks_analytics/pull/386)
* [New Out Of Hours services](https://github.com/Energy-Sparks/energy-sparks_analytics/pull/385)
* New [variables for long term trend alerts](https://github.com/Energy-Sparks/energy-sparks_analytics/pull/384)

Analytics 2.3.9

---

app/views/admin/advice_pages/index.html.erb
lib/tasks/deployment/20230123105648_create_all_advice_pages.rake

Add AdvicePage records for all the pages.

Register all advice pages

---

app/assets/stylesheets/advice_page.scss
app/controllers/schools/advice/baseload_controller.rb
app/helpers/advice_page_helper.rb
app/helpers/chart_helper.rb
app/views/schools/advice/baseload/_assessment.html.erb
app/views/schools/advice/baseload/_meter_breakdown_charts.html.erb
app/views/schools/advice/baseload/_what_is_baseload.html.erb
app/views/schools/advice/baseload/analysis.html.erb
config/locales/views/advice_pages/baseload.yml

* Adds a call-out box to the top of the baseload page, to highlight the positive/negative message
* Adds notes on extra savings, if school can reach exemplar baseload
* Tidy up YAML to add nested keys for sections and charts

Baseload introduction

---

app/controllers/admin/issues_controller.rb
app/models/issue.rb
spec/models/issue_spec.rb
spec/models/school_group_spec.rb
spec/system/admin/school_groups_spec.rb

Allow issues csv to include open and closed issues (and notes). Add extra columns as requested.

Manage issues page

---

config/locales/cy/analytics/common.yml
config/locales/cy/views/schools/schools.yml
config/locales/cy/views/schools/transport_surveys.yml
config/locales/cy/views/shared/shared.yml

Pull latest translations from transifex. I've just pulled in new/updated keys and have not yet pushed up any new files, pending review of the advice pages.
Also fixes a problem with a translated variable name,

Pull updated translations

---

app/views/admin/school_onboardings/completed.html.erb
spec/system/admin/school_onboarding_spec.rb

Update admin report to add data required for funder reporting.

Add group and country

---

Gemfile
Gemfile.lock

Picks up some fixes in the analytics from [this pull request](https://github.com/Energy-Sparks/energy-sparks_analytics/pull/411)
- renames some utility services to another module to avoid class loading issues
- fixes bugs in use of meter date range checker
- added mixin to services

Analytics 2.4.3

---

app/controllers/schools/advice/electricity_out_of_hours_controller.rb
app/views/schools/advice/advice_base/not_enough_data.html.erb
spec/system/schools/advice_pages/advice_pages_spec.rb

Add not enough data redirect to out of hours electricity page

---

app/controllers/schools/advice/electricity_long_term_controller.rb
app/helpers/application_helper.rb
app/services/schools/advice/long_term_usage_service.rb
app/views/schools/advice/electricity_long_term/_analysis.html.erb
app/views/schools/advice/electricity_long_term/_comparison.html.erb
app/views/schools/advice/electricity_long_term/_comparison_with_benchmark_table.html.erb
app/views/schools/advice/electricity_long_term/_long_term_trend.html.erb
app/views/schools/advice/electricity_long_term/_meter_breakdown.html.erb
app/views/schools/advice/electricity_long_term/_recent_trend.html.erb
config/locales/views/advice_pages/advice_pages.yml
config/locales/views/advice_pages/electricity_long_term.yml
spec/system/schools/advice_pages/electricity_long_term_spec.rb

Implements the analysis part of the electricity long term progress page. Would like to get this merged before doing the insights and the gas equivalent.

2897 implement electricity long term progress page

---

app/views/schools/advice/baseload/_analysis.html.erb
config/locales/views/advice_pages/baseload.yml

Tweak the opening of the baseload analysis page.

Put the notice first on baseload analysis

---

Gemfile
Gemfile.lock
app/services/schools/advice/baseload_service.rb
app/services/schools/advice/long_term_usage_service.rb
app/views/schools/advice/baseload/_analysis.html.erb
app/views/schools/advice/electricity_long_term/_analysis_comparison.html.erb
app/views/schools/advice/gas_long_term/_analysis_comparison.html.erb
config/locales/views/advice_pages/baseload.yml
spec/system/schools/advice_pages/baseload_spec.rb

* Bumps analytics to 2.4.7
* Updated application for renamed method
* Added baseload as % of annual consumption to baseload page
* Change charts shown on long term analysis pages to use new charts defined in analytics

Analytics 2.4.7

---

Gemfile
Gemfile.lock
app/controllers/schools/advice/electricity_recent_changes_controller.rb
app/views/schools/advice/electricity_recent_changes/_insights.html.erb
app/views/schools/advice/electricity_recent_changes/_your_recent_electricity_use_table.html.erb
app/views/schools/advice/electricity_recent_changes/_your_recent_electricity_use_table_row.html.erb
config/locales/views/advice_pages/electricity_recent_changes.yml
spec/system/schools/advice_pages/electricity_recent_changes_spec.rb

Implement electricity recent progress insights page

---

app/controllers/schools/advice/baseload_controller.rb
app/services/schools/advice/baseload_service.rb

Updates baseload controller and service to properly check for whether we have enough data. Fixes an issue with a school with very limited, out of date data.

Check for enough data on for baseload page

---

Gemfile
Gemfile.lock
config/locales/analytics/common.yml

* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/422
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/423
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/424
Includes updates to YAML file.

Update to analytics 2.4.11

---

config/locales/views/advice_pages/heating_control.yml

Heating Control Page Review Updates

---

app/views/schools/advice/solar_pv/_insights_has_solar_pv_table.html.erb
app/views/schools/advice/solar_pv/_insights_no_solar_pv.html.erb
config/locales/views/advice_pages/solar_pv.yml

Photovoltaic production
Export to the networ
Self-consumption
Consumption from network
To:
Total solar electricity produced
Exported solar electricity (not consumed onsite)
Electricity consumed from solar pv
Electricity consumed from mains

Solar PV Page Review updates

---

config/locales/views/advice_pages/electricity_long_term.yml
config/locales/views/advice_pages/gas_long_term.yml

Long Term Usage Pages Review Updates

---

app/controllers/schools/advice/hot_water_controller.rb
app/views/schools/advice/hot_water/_analysis.html.erb
app/views/schools/advice/hot_water/_analysis_table.html.erb
app/views/schools/advice/hot_water/_insights.html.erb
app/views/schools/advice/hot_water/_insights_table.html.erb
config/locales/views/advice_pages/hot_water.yml
spec/system/schools/advice_pages/hot_water_spec.rb

Implement hot water advice page

---

app/helpers/issues_helper.rb
app/views/admin/school_groups/_active_schools.html.erb
app/views/admin/school_groups/_onboarding_schools.html.erb
app/views/admin/school_groups/_removed_schools.html.erb
app/views/admin/school_groups/show.html.erb
app/views/schools/meters/_meter_issues.html.erb
app/views/schools/meters/index.html.erb
app/views/schools/meters/show.html.erb
config/locales/cy/views/schools/schools.yml
config/locales/views/schools/schools.yml
spec/system/meter_management_spec.rb

Adds issues button to meter page. Also makes sure the same download icon is used in various places.

Add issues and notes to the meter page

---

spec/services/onboarding/service_spec.rb

This pr fixes intermittent test failures
```
Failures:
1) Onboarding::Service#complete_onboarding sets school visible if feature flag set
Failure/Error: EnergySparks::FeatureFlags.active?(:emails_with_preferred_locale) ? locale : :en
#<EnergySparks::FeatureFlags (class)> received :active? with unexpected arguments
expected: (:data_enabled_onboarding)
got: (:emails_with_preferred_locale)
Diff:
@@ -1 +1 @@
-[:data_enabled_onboarding]
+[:emails_with_preferred_locale]
2) Onboarding::Service#complete_onboarding does not set school visible if feature flag not set
Failure/Error: EnergySparks::FeatureFlags.active?(:emails_with_preferred_locale) ? locale : :en
#<EnergySparks::FeatureFlags (class)> received :active? with unexpected arguments
expected: (:data_enabled_onboarding)
got: …
```

Use climate control for onboarding service spec

---

app/controllers/compare_controller.rb
app/views/compare/_header.html.erb
app/views/compare/group.html.erb
config/locales/views/compare/compare.yml
config/routes.rb
spec/system/compare_spec.rb

Very basic outline and subject to change...

Create a new route (/compare) and controllers for the new comparison tool

---

app/views/admin/alert_types/edit.html.erb

Form field wasn't initialising with the right value.

Fix form field for alert type

---

app/views/schools/advice/total_energy_use/_analysis.html.erb

Table caption was included on the page and in the partial so was appearing twice.

Remove table caption

---

app/views/schools/advice/thermostatic_control/_analysis.html.erb
config/locales/views/advice_pages/thermostatic_control.yml
spec/system/schools/advice_pages/thermostatic_control_spec.rb

* Tweaks to some of the text
* Make the formula on the page and improve the formatting a bit

Thermostatic control page review

---

app/views/schools/users/_users.html.erb
app/views/schools/users/index.html.erb
spec/system/school_admin/user_management_spec.rb

The users for a school are managed in two tables, one for school admins and one for staff. The tables should use a consistent set of columns, to include preferred language.

Factor user table into partial

---

.tx/config
config/locales/cy/analytics/alerts/common/common.yml
config/locales/cy/analytics/common.yml
config/locales/cy/analytics/energy_units.yml
config/locales/cy/analytics/modelling/heating/heating.yml
config/locales/cy/views/activities/activities.yml
config/locales/cy/views/advice_pages/electricity_out_of_hours.yml
config/locales/cy/views/advice_pages/electricity_recent_changes.yml
config/locales/cy/views/calendars/calendars.yml
config/locales/cy/views/components/breadcrumbs.yml
config/locales/cy/views/email_unsubscription/email_unsubscription.yml
config/locales/cy/views/onboarding/onboarding.yml
config/locales/cy/views/scoreboards/scoreboards.yml

Latest content pulled from Transifex

Latest transifex content

---

app/controllers/admin/reports/dcc_status_controller.rb
app/views/admin/reports/dcc_status/index.html.erb
app/views/admin/reports/index.html.erb
config/routes.rb

Adds a simple status report for admins, showing status/configuration of all DCC meters.

DCC Status Report

---

app/views/schools/advice/hot_water/_insights.html.erb
config/locales/views/advice_pages/hot_water.yml

Some minor improvements to the wording.

Revise wording on hot water insights page

---

app/services/schools/advice_page_benchmarks/school_benchmark_generator.rb

Uncommitted change from previous PR. Adds the HeatingControlBenchmarkGenerator to the factory method in base class.

Add missing class to factory method

---

.tx/config

Add cost pages to transifex config so the content will be pushed.
Have pushed/pulled content but no new translation files.

Add cost pages to transifex config

---

app/controllers/schools/advice/thermostatic_control_controller.rb
app/views/schools/advice/thermostatic_control/_analysis.html.erb
config/locales/cy/views/advice_pages/thermostatic_control.yml
config/locales/views/advice_pages/thermostatic_control.yml

Fixes subtitle of chart on thermostatic page to add dynamically updating dates.

Add dynamic dates to thermostatic chart

---

config/locales/views/advice_pages/index.yml

Minor wording change for the priority actions.

Change priority tab text

---

app/controllers/schools/advice/storage_heaters_controller.rb
app/views/schools/advice/storage_heaters/_seasonal_control_notice.html.erb
config/locales/views/advice_pages/storage_heaters.yml

* Remove dev notes from insights page notice
* Revise warm weather days notice
* Add case study links

Changes from review of storage heaters page

---

app/assets/javascripts/select.js
app/assets/stylesheets/activities.scss
app/views/compare/tab_content/_groups.html.erb
config/locales/views/compare/compare.yml

Switches on the select2 picker for the school group multiselect. Had to add some custom css to get it to look like a dropdown when in multi-select mode and also to not break when the page is resized. Also added some custom js to get it to work inside bootstrap tabs.

Enhance choose groups picker

---

Gemfile
Gemfile.lock

Updates to the latest version of the analytics gem.
* Revised baseload benchmarking
* Revised peak kw benchmarking
* Revised out of hours benchmarking
* Incorporates fix for community use calculations
There are no new translation files

Analytics 2.5.0

---

.tx/config
config/locales/cy/common.yml
config/locales/cy/views/advice_pages/baseload.yml

* Updates the tx config to push the tariff editor and storage heater content for translation
* Pulls down latest translations.

Latest transifex sync

---

config/locales/views/advice_pages/advice_pages.yml
spec/system/schools/advice_pages/advice_pages_spec.rb

Updates the label for the total energy use page

Rename total energy use

---

app/services/benchmark_content_filter.rb

Small bugfix for benchmark parser

Benchmark content parser bugfix

---

app/helpers/advice_page_helper.rb
app/services/schools/advice/baseload_service.rb
app/views/schools/advice/baseload/_weekday_variation_breakdown_table.html.erb
app/views/schools/advice/baseload/_weekday_variation_table.html.erb
app/views/schools/advice/gas_long_term/_long_term_trend.html.erb
config/locales/views/advice_pages/gas_long_term.yml
spec/services/schools/advice/baseload_service_spec.rb
spec/system/schools/advice_pages/baseload_spec.rb

Updates the gas long term analysis page to add an extra note under the chart.

Add temperature compensation note

---

config/locales/cy/analytics/benchmarking/content_base.yml
config/locales/cy/analytics/common.yml
config/locales/cy/common.yml
config/locales/cy/models/lists.yml
config/locales/cy/views/advice_pages/advice_pages.yml
config/locales/cy/views/advice_pages/baseload.yml
config/locales/cy/views/advice_pages/electricity_intraday.yml
config/locales/cy/views/advice_pages/electricity_long_term.yml
config/locales/cy/views/advice_pages/electricity_recent_changes.yml
config/locales/cy/views/advice_pages/gas_long_term.yml
config/locales/cy/views/advice_pages/gas_recent_changes.yml
config/locales/cy/views/advice_pages/heating_control.yml
config/locales/cy/views/advice_pages/hot_water.yml
config/locales/cy/views/advice_pages/index.yml
config/locales/cy/views/advice_pages/solar_pv.yml
config/locales/cy/views/advice_pages/thermostatic_control.yml
config/locales/cy/views/compare/compare.yml
config/locales/cy/views/home/for_schools.yml
config/locales/cy/views/interventions/interventions.yml
config/locales/cy/views/schools/schools.yml
config/locales/cy/views/schools/user_tariffs.yml

At time of PR all content in transifex is 100% translated and reviewed. This PR updates the project with the latest content.

Transifex all reviewed files

---

app/views/schools/advice/electricity_out_of_hours/_holiday_usage_table.html.erb
app/views/schools/advice/gas_out_of_hours/_holiday_usage_table.html.erb
app/views/schools/advice/storage_heaters/_holiday_usage_table.html.erb

Fixes untranslated text on holiday usage tables. Uses existing keys

Ensure table columns are translated

---

Gemfile
Gemfile.lock
app/controllers/schools/advice/baseload_controller.rb
app/services/schools/advice/baseload_service.rb
app/views/schools/advice/baseload/_what_is_baseload.html.erb
config/locales/views/advice_pages/baseload.yml
spec/system/schools/advice_pages/baseload_spec.rb

Include co2 and cost savings on baseload insights notice

---

app/controllers/schools/advice/base_costs_controller.rb
app/views/schools/advice/electricity_costs/_agreed_capacity_notice.html.erb
app/views/schools/advice/electricity_costs/_meter.html.erb
config/locales/views/advice_pages/electricity_costs.yml

notice for agreed_capacity.percentage > 85%
or for agreed_capacity.percentage < 85%

Add ASC warning limit to cost pages

---

app/controllers/schools/advice_controller.rb
app/views/schools/advice/index/_priority_table.html.erb

Sort priority actions co2 column numerically, not alphabetically

---

app/controllers/concerns/school_aggregation.rb
app/views/schools/aggregated_meter_collections/show.html.erb

Reduce the database overheads of the holding page.

Remove statistics from holding page

---

app/helpers/application_helper.rb

Am hoping this fixes this error on the test server: https://test.energysparks.uk/admin/good_job/jobs/471fdb3d-342a-4b2c-89f7-55356ccd6e7c?locale=en

Hopefully fix missing asset issue

---

Procfile

Increases GoodJob regeneration queue size to three. 
Will initially test this on the test server to see if there's any improvement.

Try increase regeneration queue size

---

.tx/config
config/locales/cy/analytics/charts/chart_configuration.yml

This pr includes an update to the tx config with all new content pushed to transifex (see https://app.transifex.com/energy-sparks/energy-sparks/settings/timeline/) and pulling down any new translated content as of 3rd May 2023.

Transifex updates and pull (Wed 3rd May 2023)

---

app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb

This reverts commit aecd0c4de3e3b20597456b0a1f4a51252c516281.

Revert "Match positive numbers without + signs in up_downify"

---

app/services/schools/advice/heating_control_service.rb
spec/services/schools/advice/heating_control_service_spec.rb

Remove kitchen only meters from "Central heating operating times by meter charts

---

app/controllers/admin/school_groups/meter_reports_controller.rb
app/jobs/school_group_meter_report_job.rb
app/mailers/admin_mailer.rb
app/services/school_groups/meter_report.rb
app/views/admin/reports/meter_reports/index.html.erb
app/views/admin/school_groups/_email_meter_report_button.html.erb
app/views/admin/school_groups/meter_reports/show.html.erb
app/views/admin/school_groups/show.html.erb
app/views/admin_mailer/school_group_meters_report.html.erb
app/views/shared/_school_group_meter_report.html.erb
spec/mailers/admin_mailer_spec.rb
spec/services/school_groups/meter_report_spec.rb
spec/system/admin/reports/school_group_meter_reports_spec.rb
spec/system/admin/school_groups_spec.rb

-> Also moves the fields around in the CSV as requested

Add inactive meters to the School Group meter report

---

app/assets/javascripts/analysis.js
app/assets/javascripts/common_chart_options.js
app/components/chart_component.rb
app/helpers/chart_helper.rb

Improve display of exported charts

---

config/locales/views/advice_pages/electricity_long_term.yml

Remove reference to non-existent table.

Update electricity longterm trend description text

---

lib/tasks/deployment/20230522124055_npower_eon_format.rake

New feed format for a file format received from Npower/EON.

Configure new Npower/EON format

---

app/services/amr/data_feed_translator.rb
lib/tasks/deployment/20230522125738_my_sefe_portal_format.rake

* Fixes a minor bug in the data feed translator
* Adds new config for the My SEFE portal

Configure new My SEFE Portal config

---

Gemfile
Gemfile.lock

Incorporate bug fix to `Meter.analytics_name`.

Update to analytics 2.8.0

---

Gemfile
Gemfile.lock
config/locales/analytics/benchmarking/content_base.yml
lib/tasks/deployment/20230605161655_add_ooh_alerts.rake

* Update to version of analytics with new benchmarks
* Add latest YAML
* After party task to register 3 new alerts in the application

Analytics 2.8.1

---

app/views/admin/school_groups/index.html.erb

Fix formatting issue with school group list and make school group type into a pill

---

lib/tasks/deployment/20230622154519_add_corona_weekly_format.rake

New Corona Weekly format

---

app/views/school_groups/_priority_action_modal.html.erb
app/views/school_groups/priority_actions.html.erb
spec/system/school_groups_spec.rb

Clarify these are savings by adding extra header row as we do in other versions of the table

Add extra table header to priority action popup

---

Gemfile
Gemfile.lock

Bump version of analytics to include:
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/573
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/555

Analytics 2.8.8

---

app/models/energy_tariff.rb
spec/models/energy_tariff_spec.rb

Check for nil values for VAT rate before formatting string

Handle nil vat values

---

app/components/energy_tariffs_component/energy_tariffs_component.html.erb
app/views/energy_tariffs/energy_tariffs/_energy_tariffs_tab.html.erb
config/locales/views/schools/user_tariffs.yml

Remove text on the default tariff tab that doesn't apply to defaults.

Update text on default tariff tab

---

config/locales/cy/devise.yml
config/locales/cy/views/home/home.yml
config/locales/cy/views/programme_types/programme_types.yml
config/locales/cy/views/school_groups/school_groups.yml

Did a push and pull of latest translations in Transifex.
This looks like it has the updated text for the school group dashboards.

Transifex synch 2023-08-16

---

app/helpers/energy_tariffs_helper.rb
app/views/energy_tariffs/energy_tariff_charges/_charge_basic_row.html.erb
app/views/energy_tariffs/energy_tariff_flat_prices/_form.html.erb
config/locales/cy/views/schools/user_tariffs.yml
config/locales/views/schools/user_tariffs.yml

Display the form field as: "Rate in £ [...] per kWh" to match the standing charges, etc.

Sort out display of units on flat rate prices

---

Gemfile.lock

Reverts Energy-Sparks/energy-sparks#2940

Revert "Bump pg from 1.2.3 to 1.5.3"

---

app/helpers/locale_mailer_helper.rb
app/mailers/energy_sparks_devise_mailer.rb
app/mailers/locale_mailer.rb
app/mailers/onboarding_mailer.rb
spec/mailers/alert_mailer_spec.rb
spec/mailers/bill_request_mailer_spec.rb
spec/mailers/consent_grant_mailer_spec.rb
spec/mailers/consent_request_mailer_spec.rb
spec/mailers/energy_sparks_devise_mailer_spec.rb
spec/mailers/onboarding_mailer_spec.rb
spec/services/schools/bill_request_service_spec.rb
spec/services/schools/consent_request_service_spec.rb
spec/services/targets/target_mailer_service_spec.rb
spec/system/password_reset_spec.rb

Tidy emails_with_preferred_locale feature flag

---

app/models/activity.rb
app/models/activity_type.rb
app/models/audit.rb
app/models/energy_tariff.rb
app/models/energy_tariff_price.rb
app/models/funder.rb
app/models/intervention_type.rb
app/models/meter.rb
app/models/observation.rb
app/models/programme.rb
app/models/school.rb
app/models/school_group.rb
app/models/site_settings.rb
app/services/activity_creator.rb
app/views/activities/_form.html.erb
app/views/programme_types/_cards.html.erb
app/views/programme_types/show.html.erb
app/views/schools/audits/show.html.erb
app/views/schools/interventions/_form.html.erb
app/views/schools/interventions/show.html.erb
config/locales/cy/views/interventions/interventions.yml
config/locales/views/interventions/interventions.yml
spec/models/audit_spec.rb
spec/models/observation_spec.rb
spec/models/programme_spec.rb
spec/services/activity_creator_spec.rb
spec/system/interventions_spec.rb

* Removes use of activites_2023 features flag
* Also adds some missing system spec for bonus points in frontend
* Also annotated models

Tidy up feature flag activities_2023

---

app/views/management/schools/_complete_programmes.html.erb
app/views/management/schools/_record_activity.html.erb
app/views/management/schools/_record_intervention.html.erb
config/locales/cy/views/schools/schools.yml
config/locales/views/schools/schools.yml

schools/dashboard/_transport_surveys.html.erb is still used on the pupil dashboard so have left that there...

Remove unused partials

---

app/models/meter.rb

Recheck meters against n3rgy API every month rather than every 2 months.

Change frequency of checking against DCC

---

config/locales/analytics/common.yml
config/locales/common.yml

See also https://github.com/Energy-Sparks/energy-sparks_analytics/pull/601
Will need to sync the analytics yml when doing the next tag release (the i18n spec will warn that this needs doing)

Update the special school category on the Edit school details page

---

app/views/schools/show.html.erb
spec/system/schools/dashboard/prompts_spec.rb

Put prompt to complete programme on dashboard behind the activities_2023 feature flag

Temporarily hide dashboard prompt to complete programme

---

.ebextensions/cronjob.config

Moves the import notifier email to 9.45am UTC.
Also removes a couple of commented out jobs

Change timing of import notifier email

---

app/services/schedule_data_manager_service.rb

The daily regeneration process for schools is taking longer to complete. Some days its hitting 3+ hours.
This means that jobs running at the end of the process may end up having to reload some of the "schedule data" (temperatures, solar pv data, calendars, etc).
This PR increases the cache period by an hour to avoid that happening.

Increase cache expiry times

---

app/services/amr/analytics_unvalidated_amr_data_factory.rb

Change how we load the `AmrDataFeedReadings` for the validation process. We only need 4 fields from the model, so just `.pluck` those values rather than creating a full active record model. This should be more efficient
This change was already done for the validated readings, but not the unvalidated.

Pluck fields from amr_data_feed_reading

---

app/controllers/schools/recommendations_controller.rb
app/views/schools/recommendations/index.html.erb
config/locales/views/schools/schools.yml
config/routes.rb
spec/support/shared_examples/standard_page_elements.rb
spec/system/schools/recommendations_spec.rb

* Very basic recommendations page with title & intro
* Also has the logic for adult / pupil context switching
Need to clarify the title of the page. The wireframe has "Recommended activities" but there was some discussion in email about it which I don't think came to a final answer.

Recommendations page: build very basic recommended activities and actions page

---

spec/support/shared_examples/scorable.rb

See https://github.com/Energy-Sparks/energy-sparks/actions/runs/6624236158/job/17992797183?pr=3166

Fix flickering scorable test

---

Gemfile
Gemfile.lock

Update to latest analytics to pull in refactored baseload calculation code so we can test the new calculator:
https://github.com/Energy-Sparks/energy-sparks_analytics/pull/617

Analytics 4.0.9

---

lib/tasks/deployment/20231101140901_revise_npower_configuration.rake

Tweak the date format to match supplied files. Current format is now incorrect.

Update date format to match supplied data

---

app/views/admin/amr_data_feed_configs/_detail_table.html.erb
app/views/admin/amr_uploaded_readings/new.html.erb
lib/tasks/deployment/20231101171513_update_edf_date_format.rake
spec/system/admin/amr_uploaded_readings_spec.rb

Improves the more accessible summary of the feed formats on the manual upload / testing page.

Improve summary of data feed config for admins

---

Gemfile
Gemfile.lock
spec/system/admin/meter_attributes_spec.rb

Bump the analytics to pick up a minor config update: https://github.com/Energy-Sparks/energy-sparks_analytics/pull/622

Analytics 4.1.3

---

app/components/date_picker_form_component/date_picker_form_component.js
app/components/panel_switcher_component.rb
app/components/panel_switcher_component/panel_switcher_component.html.erb
app/components/panel_switcher_component/panel_switcher_component.js
app/controllers/schools/recommendations_controller.rb
app/javascript/components.js
app/models/intervention_type.rb
app/services/interventions/suggest_action.rb
app/services/next_activity_suggester_with_filter.rb
app/views/schools/recommendations/index.html.erb
config/locales/common.yml
config/locales/views/components/panel_switcher.yml
config/locales/views/schools/schools.yml
spec/components/panel_switcher_component_spec.rb
spec/components/recommendations_component_spec.rb
spec/system/schools/recommendations_spec.rb

The main part of this PR is a new view component called PanelSwitcher for switching contexts between Pupils / Adults. 
This also adds "Based on your energy usage' and 'Based on your recent activity' sections using this component and some prototyped algorithms. The algorithms need refining for these but as this branch is starting to get big, it's time for a review before it gets any bigger!

Recommendations page: panel switcher component & prototyped sections

---

app/controllers/admin/users_controller.rb
app/models/user.rb
spec/models/user_spec.rb

Adds two new columns to the admin user export. I moved the CSV generation to the model and added some specs for the existing and updated behaviour.

Add funder and region to user export

---

config/locales/views/schools/schools.yml
spec/services/audits/progress_spec.rb
spec/services/programmes/progress_spec.rb
spec/system/schools/recommendations_spec.rb

* update ampersand in title to and
* Change points to bold text rather than being within a green badge

Recommendations page changes after feedback

---

Gemfile
Gemfile.lock

Update to include this fix: https://github.com/Energy-Sparks/energy-sparks_analytics/pull/635

Bump analytics to 4.1.7

---

config/locales/cy/views/schools/schools.yml
config/locales/views/schools/schools.yml

mainly interested in hours when school is full

Update hours text to not mention school clubs

---

.github/workflows/knapsack.yml
spec/spec_helper.rb

- remove monkey patch to merge reports since we use run the whole suite automatically
- allow job to be triggered manually again

fix error trying to load non existant report

---

config/locales/views/components/observation.yml
spec/components/observation_component_spec.rb
spec/system/pupils/dashboard_spec.rb
spec/system/schools/dashboard/timeline_spec.rb

Other timeline change requested by Claudia

Small timeline wording change

---

.tx/config

Updated Transifex config after running:
`rake i18n:generate_tx_config`

Update tx config for new components

---

.github/workflows/knapsack.yml

Hopefully fixes: https://github.com/Energy-Sparks/energy-sparks/actions/runs/7399954958/job/20132520988

Bump node version in knapsack action

---

.elasticbeanstalk/config.yml

Change production eb environment

---

.ebextensions/cronjob.config

Fixed path to old Cloudwatch cronjob that has been replaced.

Fix typo in path

---

Gemfile
Gemfile.lock
config/locales/analytics/charts/chart_configuration.yml

Update version of the analytics to include these chart bug fixes:
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/658
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/655
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/653
And these non-functional changes:
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/641
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/657
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/652

Bump analytics to 5.0.1

---

lib/tasks/deployment/20240115110510_new_drax_configuration.rake

The Drax Portal has updated their CSV format. I've reviewed the sample file and tested this new configuration, but waiting for an additional example before completing.

New Drax Portal format

---

.erb-lint.yml
.github/workflows/rubyonrails.yml
.overcommit.yml
.overcommit_gems.rb
.overcommit_gems.rb.lock
Gemfile
Gemfile.lock
app/views/schools/advice/electricity_long_term/_analysis_comparison.html.erb
app/views/schools/advice/electricity_long_term/_comparison_with_benchmark_table.html.erb
app/views/schools/advice/electricity_long_term/_insights_intro.html.erb
app/views/schools/advice/electricity_long_term/_long_term_trend.html.erb
app/views/schools/advice/electricity_long_term/_meter_breakdown.html.erb
app/views/schools/advice/gas_long_term/_analysis_comparison.html.erb
app/views/schools/advice/gas_long_term/_comparison.html.erb
app/views/schools/advice/gas_long_term/_comparison_with_benchmark_table.html.erb
app/views/schools/advice/gas_long_term/_insights_intro.html.erb
app/views/schools/advice/gas_long_term/_long_term_trend.html.erb
app/views/schools/advice/gas_long_term/_meter_breakdown.html.erb
app/views/schools/advice/long_term/_comparison.html.erb
app/views/schools/advice/long_term/_current_usage.html.erb
app/views/schools/advice/long_term/_recent_trend.html.erb

- add erb_lint and config
- run via overcommit on changed files but not on CI as too many errors
- try on app/views/schools/advice/*long_term

try erb-lint

---

app/components/observation_component.rb
config/locales/views/components/observation.yml
spec/components/observation_component_spec.rb

Removes temperature recording locations from compact timeline

Change temperature observation message

---

lib/tasks/deployment/20240209180309_add_engie_data_feed_config.rake

Adds a new CSV format for data from Engie

Add Engie data feed config

---

.tx/config
config/locales/cy/analytics/benchmarking/content_base.yml
config/locales/cy/analytics/charts/chart_configuration.yml
config/locales/cy/views/advice_pages/solar_pv.yml

- update the transifex config to add in a missing YML file
- do a push/pull to pull in some new translations

Transifex Sync 2024-02-09

---

config/locales/cy/views/advice_pages/baseload.yml

Revises the Welsh translation files to add in a missing argument pending pulling down new translations from Transifex.

Update argument name in translation key

---

config/locales/cy/views/components/panel_switcher.yml
config/locales/cy/views/components/scoreboard_summary.yml

Adds in 2 new files created by pulling from transifex.

Additional Welsh translations

---

config/locales/cy/views/advice_pages/baseload.yml

Found another key that was renamed but not in the Welsh translations.

Fix argument name

---

Gemfile
Gemfile.lock

Update the analytics to pull in this bug fix: https://github.com/Energy-Sparks/energy-sparks_analytics/pull/672

Analytics 5.1.1

---

app/models/concerns/scorable.rb
app/views/scoreboards/_table.html.erb
app/views/scoreboards/show.html.erb
spec/system/scoreboard_spec.rb

* Also fixes scoreboard_prizes feature flag spec failing locally

Fix link on national scoreboard

---

app/services/amr/n3rgy_downloader_dates.rb
app/services/meters/n3rgy_metering_service.rb
spec/services/meters/n3rgy_metering_service_spec.rb

Better handle issue where API doesn't return any cached dates.

Improve error handling in metering service

---

lib/generators/comparison_report/templates/_table.html.erb.tt

Accidentally broke the generator by copying in raw ERB. Have escaped the code correctly so runs successfully now.

Fix ERB syntax in template

---

app/components/comparison_table_component.rb
spec/components/comparison_table_component_spec.rb

We use DataTables to support table sorting in the browser.
By default DataTables uses the values of the cells to perform its sort. But this doesn't work for numbers, dates, etc. This PR updates the comparison table component so that it automatically adds the [data-order attribute](https://datatables.net/manual/data/index#DOM) supported by DataTables.
There's support for providing the sort directly via the `data_order` key on the var, but otherwise it provides a default `data-order` attribute. This is just the original unformatted numeric value, unless we're using a date in which case its formatted to ISO 8601.
The existing comparison tables already do this, so this is just bringing that into the new framework.

Add support for data-order attribute

---

.ebextensions/cronjob.config

Moved to 2pm to hopefully be clear of all of their daily import processes

Moved n3rgy loads to 2pm

---

app/controllers/comparisons/hot_water_efficiency_controller.rb
app/models/comparison/hot_water_efficiency.rb
app/views/comparisons/hot_water_efficiency/_table.csv.ruby
app/views/comparisons/hot_water_efficiency/_table.html.erb
config/routes.rb
db/migrate/20240315164815_create_hot_water_efficiencies.rb
db/schema.rb
db/views/hot_water_efficiencies_v01.sql
spec/system/comparisons/annual_storage_heater_out_of_hours_use_spec.rb
spec/system/comparisons/change_in_solar_pv_since_last_year_spec.rb
spec/system/comparisons/hot_water_efficiency_spec.rb

This is another one where a column (the last one) was using up_downify but I think a green down arrow was possibly wrong - should it be red as down I think is bad in this case...

Hot Water Efficiency

---

Gemfile
Gemfile.lock

Update to new version of analytics which includes: https://github.com/Energy-Sparks/energy-sparks_analytics/pull/682

Update to analytics 5.1.8

---

app/views/home/for_local_authorities.html.erb
app/views/home/for_multi_academy_trusts.html.erb
app/views/home/for_schools.html.erb
config/locales/views/home/marketing.yml

Add some extra links to each of the "for X" pages

Add pricing and other links

---

lib/tasks/deployment/20240430081601_remove_points_from_noisy_recording.rake

Removes points from 4 schools with large numbers of duplicate recordings. 
Have confirmed updates work locally.

Remove noisy recordings

---

app/controllers/admin/activity_types_controller.rb
app/controllers/admin/intervention_types_controller.rb
app/models/concerns/recordable.rb
app/views/activities/_form.html.erb
app/views/admin/activity_types/_form.html.erb
app/views/admin/intervention_types/_form.html.erb
app/views/schools/interventions/_form.html.erb
config/locales/views/activities/activities.yml
config/locales/views/interventions/interventions.yml
spec/system/activities_spec.rb
spec/system/admin/activity_type_spec.rb
spec/system/admin/intervention_types_spec.rb
spec/system/interventions_spec.rb

Allow admins to edit max frequency, show frequency to users

---

.tx/config
config/locales/cy/views/advice_pages/electricity_costs.yml
config/locales/cy/views/advice_pages/gas_costs.yml

Updates the transifex config for synchronisation. Latest versions of YML were then pushing using that config.
Also pulls in a couple of minor changes.

Transifex update 2024-05-01

---

app/views/comparisons/shared/change_in_consumption/_table.html.erb

Flag difference in kwh value as a change so the component adds up/down arrows.

Add up/down arrows for change column

---

Gemfile
Gemfile.lock

Update to latest version of the analytics.
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/692
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/693
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/684

Analytics 5.2.5

---

app/helpers/comparisons_helper.rb
app/views/admin/comparisons/reports/_display_custom_period.html.erb
app/views/admin/comparisons/reports/_form.html.erb
app/views/compare/benchmarks.html.erb
spec/helpers/comparisons_helperer_spec.rb
spec/system/compare_spec.rb

- fix for custom period fields not showing on load
- make report name a link

Issues with editing and viewing custom period reports

---

Gemfile
Gemfile.lock

https://github.com/Energy-Sparks/energy-sparks_analytics/pull/699

Analytics 5.2.9

---

app/views/admin/school_groups/users/show.html.erb

Add button to allow users to be locked, as well as unlocked on school group page.
Only functional change is to add this:
```
<% if user.access_locked? %>
<%= link_to 'Unlock', unlock_admin_school_group_users_path(user_id: user.id),
class: 'btn btn-warning btn-sm' %>
<% else %>
<%= link_to 'Lock', lock_admin_school_group_users_path(user_id: user.id), class: 'btn btn-warning btn-sm' %>
<% end %>
```
Rest is ERB Lint changes

Add lock button to admin page

---

app/assets/stylesheets/home.scss
app/views/home/_case_studies.html.erb
app/views/home/_funnels.html.erb
app/views/home/_mailchimp.html.erb
app/views/home/_videos.html.erb
app/views/landing_pages/find_out_more.html.erb

Adds margin and padding back in to where is was before.
Not a long term solution as these pages will be replaced, just putting back in like for like.

Fix application container margin / padding issue

---

lib/tasks/deployment/20240619131827_remove_points_from_narberth.rake

Removes points from some duplicate activity recordings from a single school, and then sets the maximum frequency for that activity type.

Remove points from some activities

---

app/controllers/comparisons/annual_energy_use_controller.rb
app/controllers/comparisons/base_controller.rb
app/controllers/comparisons/change_in_electricity_since_last_year_controller.rb
app/controllers/comparisons/holiday_and_term_controller.rb
app/controllers/comparisons/shared/arbitrary_period_controller.rb
app/views/comparisons/change_in_electricity_since_last_year/_table.csv.ruby
app/views/comparisons/change_in_solar_pv_since_last_year/_table.csv.ruby
app/views/comparisons/holiday_and_term/_electricity.csv.ruby
app/views/comparisons/holiday_and_term/_gas.csv.ruby
app/views/comparisons/holiday_and_term/_storage_heater.csv.ruby
app/views/comparisons/shared/arbitrary_period/_electricity.csv.ruby
app/views/comparisons/shared/arbitrary_period/_gas.csv.ruby
app/views/comparisons/shared/arbitrary_period/_storage_heater.csv.ruby
app/views/comparisons/shared/arbitrary_period/_total.csv.ruby
spec/helpers/advice_page_helper_spec.rb

refactor comparisons using column groups
- use csv_colgroups helper
- use header_groups method to clarify wanted headers

Comparison code tidying

---

app/models/ability.rb

This PR:
- adds some documentation to the CanCan abilities file
- tidies the file a bit by condensing some of the repeated assertions
There's more that could be done to refactor this, but this makes a start.

Tidy abilities file

---

app/controllers/schools/users_controller.rb

Fixes a small issue in which a user is not correctly removed from a school.

Use better method for removing users

---

app/controllers/school_groups_controller.rb
app/models/management_priority.rb
app/services/school_groups/priority_actions.rb
app/services/school_groups/priority_actions_csv_generator.rb
app/services/school_groups/recent_usage_csv_generator.rb
app/services/school_groups/schools_priority_action_csv_generator.rb
app/views/school_groups/show.html.erb
spec/services/school_groups/priority_actions_csv_generator_spec.rb
spec/services/school_groups/priority_actions_spec.rb
spec/services/school_groups/recent_usage_csv_generator_spec.rb
spec/services/school_groups/schools_priority_action_csv_generator_spec.rb
spec/support/shared_examples/school_groups.rb
spec/system/school_groups_spec.rb

From #3720 
Ensure the schools included on the school group age and in the CSV downloads are filtered by user permissions.

Filter priority actions on school group page by user permissions

---

app/controllers/school_groups_controller.rb
app/models/school_group.rb
app/services/school_groups/categorise_schools.rb
app/services/school_groups/comparisons_csv_generator.rb
app/services/school_groups/recent_usage_csv_generator.rb
app/views/school_groups/comparisons.html.erb
app/views/school_groups/show.html.erb
spec/services/school_groups/categorise_schools_spec.rb
spec/services/school_groups/comparisons_csv_generator_spec.rb
spec/services/school_groups/recent_usage_csv_generator_spec.rb
spec/support/shared_contexts/school_groups.rb
spec/support/shared_examples/school_groups.rb
spec/system/school_groups_spec.rb

Ensure the schools included in the comparisons only include those that are visible to the user

Filter school comparisons on school group comparison tab by user permissions

---

Gemfile
Gemfile.lock
spec/mailers/admin_mailer_spec.rb
spec/models/data_source_spec.rb
spec/models/procurement_route_spec.rb
spec/models/programme_spec.rb
spec/services/school_groups/csv_generator_spec.rb
spec/services/school_groups/meter_report_spec.rb
spec/services/schools/funder_allocation_report_service_spec.rb
spec/system/admin/issues_spec.rb
spec/system/admin/reports/unvalidated_readings_spec.rb
spec/system/admin/school_groups_spec.rb
spec/system/sign_in_spec.rb

- use TimeHelpers
- after blocks not needed as done automatically - https://www.rubydoc.info/gems/rubocop-rails/2.13.1/RuboCop/Cop/Rails/RedundantTravelBack

migrate to TimeHelpers

---

app/controllers/schools/advice/baseload_controller.rb
config/locales/views/advice_pages/electricity_long_term.yml
config/locales/views/advice_pages/electricity_meter_breakdown.yml
config/locales/views/advice_pages/gas_long_term.yml
config/locales/views/advice_pages/gas_meter_breakdown.yml

Couple of minor text changes. Also removes "Whole school" from baseload breakdown chart options.

Meter comparison page bug fixes

---

app/views/robots_txts/allow.raw

Did some more checking of time periods with a large number of requests in a short space of time. These two were more examples. Yandex did about 800 requests in ~30s.

Couple more impolite bots

---

.tx/config

Adds the new meter breakdown YML files.

Update Transifex config

---

app/components/dashboard_insights_component/dashboard_insights_component.html.erb
config/locales/views/components/dashboard_insights.yml
config/locales/views/schools/schools.yml
spec/components/dashboard_insights_component_spec.rb

Change title to "Reminders and alerts". Also moved text into component specific YML file and added a spec.

Update title for "Insights and actions"

---

app/controllers/schools/school_targets_controller.rb
app/views/schools/advice/_nav.html.erb
app/views/schools/school_targets/_current.html.erb
app/views/schools/school_targets/_edit.html.erb
app/views/schools/school_targets/_expired.html.erb
app/views/schools/school_targets/_first.html.erb
app/views/schools/school_targets/_new.html.erb
app/views/schools/school_targets/_target_timeline.html.erb
app/views/schools/school_targets/current.html.erb
app/views/schools/school_targets/edit.html.erb
app/views/schools/school_targets/expired.html.erb
app/views/schools/school_targets/first.html.erb
app/views/schools/school_targets/new.html.erb
spec/system/schools/school_targets_spec.rb

Brings these existing pages into the new design.
The only changes are in the layout, so updating controllers to use the dashboard layout if feature is active. And changing the ERB templates to work within a different layout.
I've moved the existing content for the pages into partials to try and reduce duplication.

Rework school targets overview and forms to add advice nav

---

Gemfile
Gemfile.lock

also move rubocop to development block as seems most appropriate

add rubocop factory bot and rspec_rails gems per rubocop's suggestion

---

app/views/admin/activations/index.html.erb

- make page a single table with group and admin added as columns

improvements to Schools awaiting activation report

---

spec/services/activity_type_search_service_spec.rb

from https://github.com/Energy-Sparks/energy-sparks/actions/runs/10808971250/job/29983090776?pr=3891

intermittent test failure

---

spec/models/audit_spec.rb

e.g. https://github.com/Energy-Sparks/energy-sparks/actions/runs/10809975653/job/29986222848

guessing this sometimes fails due to relation ordering

---

Gemfile
Gemfile.lock

Update analytics to version with fix.

Fix holiday comparison when calendars are not up to date

---

Gemfile
Gemfile.lock

* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/718
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/716

Analytics 6.0.6

---

Gemfile
Gemfile.lock
config/locales/views/pupils/public_displays.yml

* Tweak chart config in analytics to use calendar week not work week
* Tweak text

Update dates in public display chart

---

spec/models/user_spec.rb

- try to prevent not being able to read pupil password field as with upgrade to rails 7.1.4

update spec to catch not being able to read existing field

---

Gemfile
Gemfile.lock

https://github.com/Energy-Sparks/energy-sparks_analytics/pull/724

Revise how date times are added to RBee API calls

---

app/views/admin/reports/user_logins/index.html.erb
spec/system/admin/reports/user_logins_spec.rb

always show school group selection box

---

lib/tasks/deployment/20241016141056_bam_config.rake

Creates a new variant of an existing configuration which finds meters based on serial number.

Add BAM Config

---

app/assets/stylesheets/redesign/footer.scss
app/views/shared/_footer.html.erb
app/views/shared/_head.html.erb
config/initializers/colours.rb
config/locales/views/shared/shared.yml
spec/system/footer_spec.rb
spec/system/navigation/top_nav_spec.rb

See Trello card for screen grab of how this now looks: 
https://trello.com/c/dVXgPG17/4345-implement-new-footer-design#comment-671bb091e934a15578063dd9

New footer changes

---

.ebextensions/cronjob.config
Gemfile
Gemfile.lock
lib/tasks/amr_importer/asl_copy.rake
lib/tasks/deployment/20241022150736_asl_centrica_historic_solar_data.rake

- not sure about naming e.g. of environment variables, config identifer

Create script and config to fetch Centrica solar data via SFTP

---

app/views/schools/meters/index.html.erb

Minor change to add a title to the icons on the revised meter page. Allows user to hover to confirm meaning.

Add tooltips to columns

---

Gemfile
Gemfile.lock

Pulls in minor bugfix in alert constructor
https://github.com/Energy-Sparks/energy-sparks_analytics/pull/737

Update analytics to 6.0.18

---

Gemfile
Gemfile.lock

https://github.com/Energy-Sparks/energy-sparks_analytics/pull/739

Analytics 6.0.19

---

app/models/user.rb
spec/models/user_spec.rb

Update the user export to include:
- whether school is active
- whether school is data enabled
- whether user is confirmed

Add school status and user confirmation status

---

lib/tasks/deployment/20241111092357_remove_unconfirmed_users_from_archived.rake

Remove unconfirmed users from inactive schools.

Remove unconfirmed users from archived and deleted schools

---

lib/tasks/deployment/20241118145735_funders_november2024.rake
lib/tasks/deployment/funders-nov-2024.csv

Update schools with latest funder list

Update funders for schools

---

app/views/admin/index.html.erb

feels like would be good to break up the other section, not exactly sure on naming

break up other section of admin index

---

Gemfile
Gemfile.lock
app/jobs/daily_regeneration_on_finish_job.rb
lib/energy_sparks/log.rb
lib/tasks/schools/daily_regeneration.rake

- keep going if one refresh fails
- analytics changes

comparison refresh improvements

---

.tx/config
config/locales/cy/analytics/benchmarking/content_base.yml

* Update transifex configuration to add new files
* Pull down a couple of new translations
Have pushed latest content using the updated config.

Transifex updates

---

app/views/alert_mailer/_alerts.html.erb
app/views/layouts/mailer.html.erb
bootstrap-email.scss

- change primary button colour and border radius to match web design
- change main font size to match web design (18px)
- other tweaks to alerts list to be more inline with web design

Revise styling in emails

---

app/views/admin/schools/bill_requests/new.html.erb

Should be UK not US format. Suspect a typo.

Fix date format on bill request page

---

app/views/admin/programme_types/programmes/index.html.erb
spec/system/admin/programme_type_spec.rb

Also adds ended_on date and adds links to schools

Add started_on date to admin interface for programmes

---

lib/tasks/deployment/20250110100004_datavision_custom.rake

Add a new configuration for a custom format the ops team will create for some downloads from DataVision portal.

Custom DataVision format

---

Gemfile
Gemfile.lock
app/jobs/perse_reload_job.rb
app/services/amr/perse_upsert.rb
app/views/schools/meters/show.html.erb
lib/data_feeds/perse_api.rb
lib/energy_sparks/log.rb
lib/tasks/amr_importer/import_perse_readings.rake
spec/lib/data_feeds/perse_api_spec.rb
spec/services/amr/perse_upsert_spec.rb
spec/system/schools/audits_spec.rb

since rollbar has `[{"type":"Too_Many_Request","message":"API Hourly Limit Reached"}]`  added limiter

Perse rate limiting

---

app/views/intervention_type_groups/index.html.erb
spec/system/intervention_types_spec.rb

About to create a new feature flag, so it's only fair to squash an old one

Remove intervention_type_search feature flag

---

app/assets/stylesheets/base.scss
app/assets/stylesheets/headers.scss
app/assets/stylesheets/home.scss
app/assets/stylesheets/links.scss
app/components/dashboard_header_component/dashboard_header_component.html.erb
app/helpers/application_helper.rb
app/views/home/funders.html.erb
app/views/home/index.html.erb
app/views/layouts/home.html.erb
app/views/shared/_head.html.erb
lib/tasks/deployment/20250129161443_add_new_home_page_feature.rake
spec/system/home_spec.rb

This does a number of things:
* Creates a new feature flag :new_home_page and allows the new home to be switched on by it
* There is a new home page in place but it's only got a few html blocks on the page from the design - it's not component-ised or translated yet, just so we had something to look at as a starter. You'll notice I picked a random photo from the repository until we have a better one.
* Moved the classes used by the current home page (and other pages using the home.html.erb layout) to be scoped to .home-page - and all other pages apart from the home page use these still. The new home page has it's classes scoped to .home.
* Tidied up some css and also removed some classes that are no longer used.
* Took the plunge and removed / commented out the css that changes the header …

Home page feature and placeholder

---

app/controllers/admin/reports/mailchimp_status_controller.rb
app/views/admin/reports/mailchimp_status/index.html.erb
spec/system/admin/reports/mailchimp_status_spec.rb

Testing this further I realised I was using a different scope in the controller than the service. So have fixed that to make sure the figures reflect actual number of pending updates.

Use same scope as AudienceUpdater service

---

app/models/mailchimp/contact.rb
spec/models/mailchimp/contact_spec.rb

Should be array of tags, not nested array

Bug fix to cluster admin tagging

---

app/views/schools/school_targets/_form.html.erb

- margin and float right button
- erblint fixes

layout tweaks for school targets form

---

Gemfile.lock

dependabot is raising a security issue but fails updating for unknown reason

manually update uri

---

config/locales/cy/views/terms_and_conditions/terms_and_conditions.yml
config/locales/views/terms_and_conditions/terms_and_conditions.yml

Update references in terms and conditions.

Refer to n3rgy as n3rgy data Ltd

---

spec/tasks/amr/stopped_data_feeds_email_spec.rb
spec/tasks/data_feeds/national_gas_calorific_values_spec.rb

fix failures on https://github.com/Energy-Sparks/energy-sparks/actions/workflows/knapsack.yml

fix loading rake tasks multiple times in tests breaking single rspec run

---

app/models/energy_tariff_price.rb
app/views/energy_tariffs/energy_tariff_differential_prices/_form.html.erb
app/views/energy_tariffs/energy_tariff_flat_prices/_form.html.erb
config/locales/activerecord.yml
config/locales/models/energy_tariff_price.yml
spec/models/energy_tariff_price_spec.rb

improve energy tariff value validation message

---

lib/tasks/deployment/20250404140312_digital_energy_serial.rake

Minor variant of the existing Digital Energy format that uses serial numbers and slightly different column headings

Add Digital Energy variant format

---

app/jobs/amr_import_job.rb
config/application.rb
spec/components/pupil_reminders_component_spec.rb

correct amr job total limit to perform limit

---

app/jobs/amr_import_job.rb

Remove concurrency limit on jobs

---

.tx/config

Updates transifex content to include new YML files. I've used that to push content to Transifex for translation.

Update Transfiex Config

---

app/controllers/admin/reports/baseload_anomaly_controller.rb
app/views/admin/reports/baseload_anomaly/index.html.erb
spec/system/admin/reports/baseload_anomaly_spec.rb

Add the admin user name. Add some intro text.

Add admin name to baseload anomaly report

---

lib/tasks/deployment/20250611154519_create_energy_assets_regent_config.rake

tested on example files with preview

add Energy Assets Regent data feed config

---

app/controllers/case_studies_controller.rb

The old code was picking the right layout locally but not on test.
This fix determines the layout per request and not just once when the class is loaded.

Fix case studies container issue

---

app/views/newsletters/index.html.erb
spec/factories/newsletters_factory.rb
spec/models/newsletter_spec.rb
spec/system/home_spec.rb

Fix sign-up link for logged-out users

Fix newsletters page sign-up link

---

lib/tasks/deployment/20250716150018_update_solar_overrides.rake

Fixes logic error in the database update I made yesterday.
This won't run again automatically, but I'll manually run later.

Fix database update

---

app/services/schools/priorities.rb

Priorities should be in descending order of cost

Fix sort order on priorities

---

app/controllers/landing_pages_controller.rb
app/mailers/campaign_mailer.rb
app/services/campaigns/contact_handler_service.rb
app/views/campaign_mailer/notify_admin.html.erb
app/views/landing_pages/_form.html.erb
config/locales/mailers/mailer.yml
config/locales/views/home/home.yml
config/locales/views/home/marketing.yml
spec/mailers/campaign_mailer_spec.rb
spec/services/campaigns/contact_handler_service_spec.rb
spec/system/landing_pages_spec.rb

- text updates for buttons, email
- fix for email formatting
- change example school group
- change form and code to use single org_type not multiple

Text and layout improvements for marketing workflows

---

app/views/cms/categories/index.html.erb
app/views/cms/categories/show.html.erb
app/views/cms/pages/show.html.erb

Add a cache to the support page views for non-admin users.

Cache support pages
