Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/switch_meter.js
app/controllers/schools_controller.rb
app/controllers/stats_controller.rb
app/helpers/schools_helper.rb
app/views/schools/_electricity_cards.html.erb
app/views/schools/_hourly_usage_panel.erb
config/routes.rb
lib/usage.rb

Changes hourly usage reporting to take two dates rather than compare weekday/weekend usage.
Defaults to comparing last two days of readings.

Chart filtering dates

---

app/assets/javascripts/switch_meter.js
app/assets/stylesheets/colours.scss
app/controllers/stats_controller.rb
app/helpers/schools_helper.rb
app/views/home/team.html.erb
app/views/schools/_daily_usage_panel.erb
app/views/schools/_electricity_cards.html.erb
app/views/schools/_gas_cards.html.erb
app/views/schools/_hourly_usage_panel.erb
lib/usage.rb
spec/lib/usage_spec.rb

* Change school homepage to use latest date and last 7 days for key figures
* Key figures are now averages and highest usage for last 7 days, not full week/weekday
* Change links to graphs so they consistently use latest date, not last full week
* Swap links to graphs, so they're most aligned with the figures. Closes #208 
* Change the gas colours so the latest data colour is darker
* Make graphs consistently use darker colour for recent data
* Add month/year selectors to date pickers
* Daily usage chart shows last 7 days, and previous 7 days. Added dates. Closes #207 
* Fix initial date format. Closes #209 
* Add a note on date availability on hourly usage chart. Closes #222 
* Change ids on date pickes. Closes #221 
* Fix typo on team page

Last 7 days

---

config/schedule.rb
lib/loader/energy_importer.rb
lib/tasks/loader.rake
spec/fixtures/vcr_cassettes/socrata-energy-import.yml
spec/lib/loader/energy_importer_spec.rb

Fixes a performance bug in the loader caused by not checking whether meters are active, and using the latest date across all meters, not per meter.
Now queries for each meter individually. This is more requests to Socrata, but each one should retrieve less data and be quicker to process.

Loader bug fixes

---

app/assets/javascripts/data_explorer.js

Store current chart options before updating colours. Stops the graph configuration overwritten and axes labels being lost.

Don't overwrite current options, append new colours

---

Gemfile
Gemfile.lock

Until ElasticBeanstalk production environment is *fixed* or replaced, if a new version of Puma or Rack is deployed, then it requires a ```gem install puma -v X.Y.Z``` as root for it to work.

Freeze Puma & Rack

---

app/assets/javascripts/application.js
app/assets/javascripts/common_chart_options.js
app/assets/javascripts/open_tab.js
app/views/activity_types/show.html.erb
app/views/layouts/application.html.erb
app/views/schools/_meter_cards.html.erb
app/views/schools/show.html.erb

To fix it:
* Close any open tags (like Strongs - typos)
* Move chartkick JS in to body instead of being between body & html
tags
* polyfill startsWith as not supported in IE
* Remove unused tab code with back ticks which IE didn't like

Internet Explorer chart rendering was broken

---

lib/amr/importer.rb

Now we have sheffield and sheffield-gas the prefix bucket checker was picking up stuff in sheffield-gas when it shouldn't have...

Ensure prefixer works post folder name, not for files

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/calendar_year_view.js
app/assets/javascripts/calendars.js
app/assets/stylesheets/application.scss
app/views/calendars/_event_modal.html.erb
app/views/calendars/calendar_events/_form.html.erb

This is removing the old school data picker and using the current one on the calendar event pages - further refactoring could take place when we get the chance.

Switching calendar event date picker

---

spec/services/activity_type_filter_spec.rb

Running ```bundle exec rspec ./spec/services/activity_type_filter_spec.rb --seed 12201``` caused a test to fail which checked the order of the array of three elements, when it only needed to check that the last one as the custom one. I've amended the test, but am interested to know whether a) I'm right in my assumption b) The rspec style is ok bearing in mind the other tests in this class :)

New taxonomy structure with test patch

---

app/assets/stylesheets/colours.scss

This caused a deprecation warning, so convert to normal 6 digit colour

Colour was a 8 digit hex - which included transparency

---

app/models/amr_validated_meter_collection.rb

This was something we tried with memory usage - no point in creating AmrValidatedReadings when we are just going to whack them in another object - pluck doesn't instantiate the AMR objects. 
Might be worth keeping?

Switch to using pluck instead of instantiating AmrValidatedReadings

---

app/services/aggregate_school_service.rb

Previously the validated meter collection retrieved from the database didn't know what the meter attributes would be for a meter, they were only added during the validation process.
Now the meter attributes are accessible from the normal meter, we don't need to re-validate the readings (which are already retrieved from the DB validated).

Switch to using just aggregate for a validated meter collection

---

Gemfile
Gemfile.lock
lib/tasks/deployment/20190514130807_enable_remaining_alerts.rake
lib/tasks/deployment/20190514131048_add_alerts_non_school_days_heating.rake

Latest analytics release including new Solar PV (not yet implemented), Equivalences (not yet complete) and various other patches for aggregation and alert generation.
This is on test at the moment.

Latest analytics - enable remaining alerts (apart from impending holidays alert)

---

app/views/shared/_head.html.erb

Bug related to font loading on Safari when fonts are applied to the whole page: https://github.com/google/fonts/issues/2155
Not entirely sure about this fix. Extra http requests, but they probably have decent caching and aren't on our servers. Only affects a handful of safari versions but affects the second most recent one.

Split font loading for Safari

---

Gemfile
Gemfile.lock
app/services/amr/analytics_unvalidated_meter_collection_factory.rb
app/services/amr/upsert_validated_readings_for_a_meter.rb
spec/factories/dashboard_one_day_amr_readings_factory.rb
spec/services/amr/analytics_unvalidated_meter_collection_factory_spec.rb
spec/services/amr/upsert_validated_readings_for_a_meter_spec.rb

Tricky to put this on test at the moment, it could go straight to prod if we're happy with the changes - the thing we have to remember is to implement the ordering for the 'new' version of the meter collection factory otherwise this change will be lost.
It also includes removing the upsert gem.

Patch for removing all upsert and fixing order

---

.ebextensions/cronjob.config
app/controllers/admin/dark_sky_areas_controller.rb
app/controllers/admin/solar_pv_tuos_areas_controller.rb
app/views/admin/dark_sky_areas/index.html.erb
app/views/admin/solar_pv_tuos_areas/index.html.erb
config/routes.rb
lib/data_feeds/dark_sky_temperature_loader.rb
lib/data_feeds/solar_pv_tuos_v2_loader.rb
lib/tasks/data_feeds/data_feeds_dark_sky_back_fill.rake
lib/tasks/data_feeds/data_feeds_solar_pv_tuos_back_fill.rake

Simply backfills 4 years worth of data if it's missing - it's not super clever, but does batch into a year per time. If data exists, the loader backfills anyway.

Back fill dark sky and solar pv areas

---

config/database.yml

Add credentials for test database.
On ubuntu at least, postgres needs to be configured to allow local connections for postgres user and recommended approach is to set a password for that.
So I needed to specify these for my environment to work.
Expect travis may need the default values populating...?

Add credentials for test db

---

lib/tasks/deployment/20210125105759_update_solar_for_schools_config.rake

New Solar for Schools config
- update meter column
- revise data format
- update reading fields and header example to match sample file.

Add new Solar for Schools config

---

lib/tasks/deployment/20210125113137_add_edf_historic_config.rake

Add a new `edf-historic` feed to be used instead of the "Highlands" format.
Uses latest configuration based on sample provided.

Add EDF Historic feed, using latest format

---

app/controllers/case_studies_controller.rb
app/controllers/resource_files_controller.rb
app/helpers/storage_helper.rb
app/views/home/_case_studies.html.erb
app/views/resource_files/index.html.erb
config/routes.rb
spec/system/case_studies_spec.rb
spec/system/resources_spec.rb

Spiked implementation of streaming resources via the app. This is still a WIP for discussion.
* Adds new route `/resources/:serve/:id` to stream resource files from active storage. Use `/resources/inline/:id` for inline display, `/resources/attachment/:id` to force a download
* URLs use id of the resource file which will be stable over time, even if the attached files are changed or updated
* Uploaded file names are preserved as now and these are used for downloads, so you'll get whatever name is provided by the ES admin
Produces urls like: `test.energysparks/resources/attachment/18`
Files should get caught by the CDN I think (although I haven't check the config) and cached.
@jhigman do you think this is a sensible option? It preserves all uploaded content so quick to implement and apply. …

Streaming resources via stable URL

---

lib/tasks/deployment/20210129154542_add_meteostat_stations.rake

AfterParty task to create new Meteostat weather stations for existing Dark Sky Areas.
Doesn't regenerate if there's a station with same title, lat, long already.

Automatically generate stations from DSA

---

app/controllers/admin/weather_stations_controller.rb
app/views/admin/weather_stations/_form.html.erb
spec/system/admin/weather_stations_spec.rb

Allow admin to edit lat/long of a weather station. Remove old observations if they do.

Allow lat/long to be edited

---

app/controllers/admin/videos_controller.rb
app/controllers/home_controller.rb
app/helpers/video_helper.rb
app/models/meter.rb
app/models/video.rb
app/views/admin/index.html.erb
app/views/admin/videos/_form.html.erb
app/views/admin/videos/edit.html.erb
app/views/admin/videos/index.html.erb
app/views/admin/videos/new.html.erb
app/views/home/_videos.html.erb
app/views/home/for_management.html.erb
app/views/home/for_pupils.html.erb
app/views/home/for_teachers.html.erb
app/views/home/user_guide_videos.html.erb
app/views/shared/_about_menu.html.erb
config/routes.rb
db/migrate/20210208102622_create_videos.rb
db/schema.rb
spec/factories/videos.rb
spec/helpers/video_helper_spec.rb
spec/models/video_spec.rb
spec/system/admin/videos_spec.rb
spec/system/videos_spec.rb

* Admin functionality to create, edit, delete videos, specifying their order and also whether they are to be featured
* New "user guide videos" link in navbar to show videos
* Home page now displays any of the featured videos in the system
* If no featured videos are available, as the moment it defaults to the current video on the homepage (only)

First implementation of user help videos

---

app/mailers/onboarding_mailer.rb
app/models/user.rb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/onboarding_mailer/welcome_email.html.erb
spec/controllers/admin/users_controller_spec.rb
spec/models/user_spec.rb
spec/system/school_admin/user_management_spec.rb

Revise confirmation email text.
Send welcome email after account is confirmed.

1228 update wording of user account confirmation email

---

.ebextensions/cronjob.config
app/helpers/application_helper.rb
app/helpers/rollbar_mailer_helper.rb
app/mailers/rollbar_mailer.rb
app/services/alerts/generate_alert_type_run_result.rb
app/services/amr/n3rgy_download_and_upsert.rb
app/services/content_batch.rb
app/services/equivalences/generate_equivalences.rb
app/services/rollbar_notifier_service.rb
app/views/rollbar_mailer/_rql_report_table.html.erb
app/views/rollbar_mailer/report_errors.html.erb
lib/data_feeds/dark_sky_temperature_loader.rb
lib/data_feeds/meteostat_loader.rb
lib/data_feeds/solar_pv_tuos_v2_loader.rb
lib/rollbar_api/rql_jobs.rb
lib/tasks/amr_importer/validate_amr_readings.rake
lib/tasks/equivalences/create_equivalences.rake
lib/tasks/utility.rake
spec/lib/rollbar_api/rql_jobs_spec.rb
spec/services/rollbar_notifier_service_spec.rb

We want to produce a more detailed reports about failures to validate API readings, listing individual meters. Doing this will require some changes to how the application generates, captures and log errors around the analytics code.
In order to report on failures we need to keep track of when and where they occur. Rollbar already does this for us. It also allows us to provide additional metadata when we record errors. For example, we currently log school ids, names and other information in a few places. That information can be queried using [the RQL query language](https://docs.rollbar.com/docs/rql).
So, rather than create a new set of tables to manage logging of errors, we can use Rollbar to capture the issues. This will allow us to trap all errors, including unforseen problems, not just …

First iteration of code to generate emails from custom RQL reports

---

app/controllers/schools/meters_controller.rb
app/services/meter_management.rb
app/views/schools/meters/show.html.erb
lib/tasks/utility.rake

We're assuming DCC meters always have a single element. But this might not always be the case.
To give us a way to check/confirm this when testing, have added:
* a lookup on the meter details page, which displays number of elements
* a `utility:check_elements` rake raks that dumps a simple CSV export of school, mpan, element count

Add elements check

---

app/mailers/onboarding_mailer.rb
app/services/school_creator.rb
spec/services/school_creator_spec.rb

Send the activation email to all school admins, staff and group users.
Sends a single email with everyone in the to: field

Send email to multiple users

---

app/controllers/concerns/school_aggregation.rb
spec/controllers/teachers/school_controller_spec.rb
spec/system/teachers/school_spec.rb

Test for presence of MeteoStat and Dark Sky stations.
Also handle missing solar pv area.
Add test for the single page(?) that displays these values if school is not in cache.

Correctly assign weather and solar observations when stations not set

---

app/services/school_creator.rb
spec/services/school_creator_spec.rb

If a school is setup manually, it won't have an "created user" associated with the onboarding. But may have other users.
This fixes up error when sending the activation email by checking if the user is nil.

Add check to see if onboarding user is nil

---

app/models/user.rb
app/services/school_creator.rb
spec/models/user_spec.rb
spec/services/school_creator_spec.rb

Users don't have to have named, but Contacts to.
During onboarding we create Contacts from Users. So it can fail if a name isn't set (or is empty)
So use `display_name` instead.
Also ensure `display_name` returns a useful value if name is empty.

User display name when creating onboarding contact

---

app/controllers/admin/meter_reviews_controller.rb
app/models/school.rb
app/views/admin/index.html.erb
app/views/admin/meter_reviews/index.html.erb
config/routes.rb
spec/factories/consent_grants_factory.rb
spec/factories/consent_statement_factory.rb
spec/models/school_spec.rb
spec/system/admin/meter_reviews/meter_reviews_spec.rb

Provides a page listing DCC meters that haven't yet been activated via a trusted consent call on N3RGY API.
Admin can use this to check to see if the school consent is up to date (and view docs). And if they have supplied a bill as proof.
The buttons for requesting consent, emailing to request bills and completing a review a placeholders (covered by different cards in the backlog).

1318 dcc meter review status page

---

app/controllers/admin/meter_reviews_controller.rb
app/controllers/admin/schools/meter_reviews_controller.rb
app/models/consent_document.rb
app/models/meter.rb
app/models/meter_review.rb
app/models/school.rb
app/services/meter_review_service.rb
app/views/admin/meter_reviews/index.html.erb
app/views/admin/schools/meter_reviews/new.html.erb
app/views/admin/schools/meter_reviews/show.html.erb
config/routes.rb
db/migrate/20210318120341_create_meter_reviews.rb
db/migrate/20210318120534_add_meter_review_to_meter.rb
db/migrate/20210318144544_associate_consent_documents_and_meter_reviews.rb
db/schema.rb
spec/factories/meter_reviews.rb
spec/factories/users_factory.rb
spec/services/meter_review_service_spec.rb
spec/system/admin/meter_reviews/meter_reviews_spec.rb

Still work in progress but:
- displays list of DCC meters that need an admin review
- provides a form for admin to view relevant consent docs, meter setup and bills
- allows admin to complete review
- displays previous reviews
Need to complete the rspecs and tidy the code. Also consider where best to show previous meter reviews.

1320 complete a review for a dcc meter

---

app/views/schools/consent_documents/index.html.erb
spec/system/schools/consent_documents_spec.rb

Display edit link on list of consent documents.
Allow admins to delete these from the list

Move controls for edit/delete a bill

---

app/controllers/benchmarks_controller.rb
app/controllers/scoreboards_controller.rb
app/models/ability.rb
app/models/scoreboard.rb
app/services/comparison_service.rb
config/sitemap.rb
spec/models/scoreboard_spec.rb
spec/rails_helper.rb
spec/system/scoreboard_spec.rb

* Users can only see public scoreboards, plus those associated with their school. Admins see all.
* Add access control to scoreboard page
* Restrict list of scoreboards listed on benchmark page, to match public list
* Remove private scoreboards from sitemap

Implement private scoreboards

---

Gemfile
Gemfile.lock
app/models/tariff_import_log.rb
app/models/tariff_price.rb
app/models/tariff_standing_charge.rb
app/services/amr/analytics_meter_factory.rb
app/services/amr/analytics_tariff_factory.rb
spec/factories/tariff_prices_factory.rb
spec/factories/tariff_standing_charges_factory.rb
spec/services/amr/analytics_tariff_factory_spec.rb
spec/services/amr/analytics_unvalidated_amr_data_factory_spec.rb

This is an initial version of integrating tariffs and prices from n3rgy with existing analytics
* `AnalyticsTariffFactory` -- handles call to the analytics code to convert TariffPrice and TariffStandingCharge into meter attributes
* `AnalyticsMeterFactory` -- revised to add in additional attributes (as `accounting_tariff_generic`) for DCC meters
This provides a complete pass-through of the data we're fetching.
Future optimisations:
* instead of converting to meter attributes on the fly, we can convert and store in an earlier step (e.g. as part of job to actually fetch the tariff data). This code would then simply load these attributes.
Note: this is currently pinned to latest commit in analytics, so need to create a proper branch or release before merging.

First version of integrating tariffs with analytics

---

app/models/ability.rb
spec/models/school_spec.rb

* ensure that staff, volunteers, pupils can see schools and dashboards for other schools in their group
* ensure that staff, volunteers, pupils can only see real cost data, if their school is public
* allow staff and volunteers to see management dashboard for schools in same group

Further access control changes

---

Gemfile
Gemfile.lock
app/helpers/chart_helper.rb
app/views/schools/analysis/_chart_name.html.erb
app/views/schools/analysis/show.html.erb
spec/system/schools/analysis_pages_spec.rb

Because of dependencies on analytics branch, this now includes several related changes:
* Adjusting the analysis page to display per-meter charts, adding an mpan_mprn parameter when requesting data
* Uses the latest analytics code which includes the revised charts (and other changes, including bug fix for content batch issues)
* Tweaks to titles of accordions on analysis page so they're no longer buttons
* As the analytics is also now adding a span with `float-right` around its total prices, this will also pick up that change
Pending nice to have would be to add a down-arrow icon + toggle for the accordion opening. Bootstrap 5 seems to do that automatically but Bootstrap 4 needs some more CSS.

1381 allow analysis pages to serve meter specific charts - WIP

---

app/controllers/schools/low_carbon_hub_installations_controller.rb
app/services/amr/low_carbon_hub_download_and_upsert.rb
app/services/amr/low_carbon_hub_downloader.rb
app/services/amr/low_carbon_hub_installation_factory.rb
app/views/schools/low_carbon_hub_installations/_form.html.erb
app/views/schools/low_carbon_hub_installations/edit.html.erb
app/views/schools/low_carbon_hub_installations/index.html.erb
app/views/schools/low_carbon_hub_installations/new.html.erb
app/views/schools/low_carbon_hub_installations/show.html.erb
app/views/shared/_manage_school.html.erb
config/routes.rb
db/migrate/20210609102549_add_credentials_to_low_carbon_hub.rb
db/schema.rb
spec/services/amr/low_carbon_hub_installation_factory_spec.rb
spec/support/low_carbon_hub_data.rb
spec/system/low_carbon_hub_installation_spec.rb

* Relabel navigation and forms to refer to "Rtone" and not low carbon hub
* Allow username and password to be configured
* Use username and password if configured, defaulting to environment variable (for now)
* Allow editing of username and password
I've kept the existing environment variable for now, until we've updated the data for the Oxford schools, then we can remove.

1431 allow admin to configure password for rtone solar api

---

app/controllers/schools/low_carbon_hub_installations_controller.rb
app/services/amr/low_carbon_hub_download_and_upsert.rb
app/services/amr/low_carbon_hub_installation_factory.rb
spec/system/low_carbon_hub_installation_spec.rb

Incorrectly calling the constructor, so api lookups were broken. Fixed this, ensure errors are logged in rollbar and separate out saving model from API calls.

Fix bug with passing credentials, & ensure errors are caught and logged

---

lib/tasks/alerts/create_alerts.rake
lib/tasks/alerts/generate_content.rake
lib/tasks/alerts/generate_subscriptions.rake
lib/tasks/amr_importer/notifier.rake
lib/tasks/amr_importer/validate_amr_readings.rake
lib/tasks/content_batch.rake
lib/tasks/equivalences/create_equivalences.rake
lib/tasks/generate_benchmarks.rake

Some of the background tasks weren't using consistent log messages to record start/end times, backing it difficult to identify run times.
This fixes up some of the tasks.

Added start/end log messages with consistent timestamp

---

app/controllers/concerns/alert_contact_creator.rb
app/controllers/schools/cluster_admins_controller.rb
app/controllers/schools/school_admins_controller.rb
app/controllers/schools/staff_controller.rb
app/views/schools/cluster_admins/new.html.erb
app/views/schools/school_admins/_form.html.erb
app/views/schools/school_admins/edit.html.erb
app/views/schools/school_admins/new.html.erb
app/views/schools/staff/_form.html.erb
app/views/schools/staff/edit.html.erb
app/views/schools/staff/new.html.erb
app/views/schools/users/_auto_create_alert_contact.html.erb
spec/system/school_admin/user_management_spec.rb

Some of the school admin and staff form fields didn't actually do anything on edit. This: 
* removes the mailchimp sign-up (pending separate changes) on the edit form
* improves label of checkbox for alert contacts
* makes the checkbox functional a new contact is created, existing one updated, or removed depending on option selected

Rename alert contact field; remove newsletter from edit

---

.ebextensions/cronjob.config
Gemfile
Gemfile.lock
app/controllers/schools/rtone_variant_installations_controller.rb
app/controllers/schools/solar_feeds_configuration_controller.rb
app/models/amr_data_feed_config.rb
app/models/meter.rb
app/models/rtone_variant_installation.rb
app/models/school.rb
app/models/user_tariff_charge.rb
app/services/solar/rtone_variant_download_and_upsert.rb
app/services/solar/rtone_variant_downloader.rb
app/services/solar/rtone_variant_upserter.rb
app/views/schools/rtone_variant_installations/_form.html.erb
app/views/schools/rtone_variant_installations/edit.html.erb
app/views/schools/rtone_variant_installations/new.html.erb
app/views/schools/solar_feeds_configuration/_rtone_feeds.html.erb
app/views/schools/solar_feeds_configuration/_rtone_variant_feeds.html.erb
app/views/schools/solar_feeds_configuration/_solar_edge_feeds.html.erb
app/views/schools/solar_feeds_configuration/index.html.erb
config/routes.rb
db/migrate/20210707085818_create_rtone_variant_installations.rb
db/schema.rb
lib/tasks/deployment/20210707093230_rtone_variant_config.rake
lib/tasks/solar_importer/import_rtone_variant_readings.rake
spec/factories/rtone_variant_installations.rb
spec/services/solar/rtone_variant_download_and_upsert_spec.rb
spec/services/solar/rtone_variant_upserter_spec.rb
spec/system/rtone_variant_installation_spec.rb

This:
* add a new model for a variation of Solar feeds, used in Newport which need extra configuration and special handling
* adds new pages to manage those installations for admin users
* adds new loader to load readings from those meters. This uses a different way of accessing the API and relies on meters existing vs the existing approach which creates meters on the fly
* new cron job to load the data 
@jhigman One question is whether we need a new cron job, or do we just add it to the existing low carbon hub load?

1528 rework of rbee interface for newport

---

app/controllers/concerns/non_public_schools.rb
app/controllers/schools/aggregated_meter_collections_controller.rb
spec/controllers/schools/aggregated_meter_collections_controller_spec.rb
spec/models/user_spec.rb
spec/system/school_spec.rb

Two fixes:
* for the non-public school check, test if the school is public before issuing a redirect based solely on permissions. As this triggers a redirect from non-visible schools too.
* for the aggregate meter post, do the authorize check in the controller method so authorisation failures are caught and handled.

1565 redirect loops with invisible public schools

---

.travis.yml
Gemfile
Gemfile.lock

This fixes a long standing bug where attempting to log a NoMethodError triggers the script or server process to hang because its in an infinite loop. Any attempt to log a NoMethodError when calling an object method in my development server triggered the issue. Previously this has been observed on the test server.
Debugging with gdb shows that `did_you_mean` was the cause. Upgrading resolves the issue.
There's also a change to the Travis config to try and [work around this issue](https://github.com/ruby/did_you_mean/issues/117). Explicitly running bundle install with did you mean disabled ensures the right versions of the gems are used for later scripts.
This should all be resolved in Ruby 2.7 later which has Did You Mean 1.5.0 by default I believe.

Upgrade to 1.5.0 of did_you_mean

---

app/models/ability.rb
spec/models/school_spec.rb
spec/system/management/dashboard_spec.rb

Allow pupils to access the management dashboard now that we've replaced the teacher dashboard.

Give pupils access to mgt dashboard

---

Gemfile
Gemfile.lock
app/controllers/concerns/school_progress.rb
app/controllers/schools/progress_controller.rb
app/controllers/schools/school_targets_controller.rb
app/helpers/application_helper.rb
app/models/school.rb
app/services/targets/fuel_type_event_listener.rb
app/services/targets/progress_service.rb
app/services/targets/school_target_service.rb
app/views/schools/school_targets/_form.html.erb
app/views/schools/school_targets/edit.html.erb
app/views/schools/school_targets/first.html.erb
app/views/schools/school_targets/new.html.erb
app/views/schools/school_targets/show.html.erb
spec/services/targets/fuel_type_event_listener_spec.rb
spec/services/targets/progress_service_spec.rb
spec/system/schools/progress_spec.rb
spec/system/schools/school_targets_spec.rb

* Update to Analytics 1.26.4 with revised target interface
* Ensure we're checking whether there's targets set and enough data to generate reports when prompting to add or review targets
* Add guards around displaying progress to ensure targets are set and enough data is available.

Analytics 1.26.4

---

app/controllers/concerns/school_progress.rb
app/controllers/schools/progress_controller.rb
app/controllers/schools/school_targets_controller.rb
app/controllers/schools_controller.rb
app/models/school.rb
app/services/alerts/generate_email_notifications.rb
app/services/programmes/enroller.rb
app/services/school_creator.rb
app/services/targets/progress_service.rb
app/services/targets/school_target_service.rb
app/services/targets/target_mailer_service.rb
app/views/admin/schools/target_data/show.html.erb
app/views/schools/_details_form.html.erb
app/views/shared/_manage_school.html.erb
db/migrate/20210914121624_add_targets_feature_flag_to_schools.rb
db/schema.rb
spec/services/alerts/generate_email_notifications_spec.rb
spec/services/targets/progress_service_spec.rb
spec/services/targets/target_mailer_service_spec.rb
spec/system/management/dashboard_spec.rb
spec/system/school_spec.rb
spec/system/schools/progress_spec.rb
spec/system/schools/school_targets_spec.rb

Allow an admin to disable targets feature for individual schools.
Refactored checking for feature flag into SchoolTargetsService, revised the logic and updated tests.
Also ensure that any bookmarked links, etc trigger redirects in case we disable this for a school that currently has targets.

Allow targets to be disabled for individual schools

---

app/controllers/activity_categories_controller.rb
app/views/activity_categories/_cards.html.erb
app/views/activity_categories/_programme_types.html.erb
app/views/activity_categories/_pupil_categories.html.erb
app/views/activity_categories/index.html.erb
app/views/intervention_type_groups/_cards.html.erb
app/views/intervention_type_groups/index.html.erb
spec/system/activity_category_spec.rb
spec/system/schools/activity_category_spec.rb

Turns out that `card-deck` in bootstrap isn't responsive. While on small screen sizes the cards do wrap, at larger sizes (e.g. with ipad) you end up with very narrow columns.
Easiest fix was to remove use of `card-deck` in favour of switching to use a 4 card row, with explicit column widths (`col-sm-4`) and use of `pr-1` and `h-100` to force cards to be same height.
This works better across all screen sizes. Made changes to both the activity category and intervention pages.

Remove card-deck in favour of columns

---

app/views/activity_categories/index.html.erb
app/views/activity_categories/show.html.erb
app/views/activity_types/show.html.erb
app/views/intervention_type_groups/index.html.erb
app/views/intervention_type_groups/show.html.erb
app/views/intervention_types/show.html.erb
spec/system/activity_category_spec.rb
spec/system/interventions_spec.rb
spec/system/schools/activity_category_spec.rb

Intervention page templates didn't have code to display description and download links
Changed button styling, to match elsewhere on the site we have links in the top right
Tweaked button labels to reduce amount of text.

Intervention pages should display description and links

---

app/controllers/schools/users_controller.rb
app/models/school.rb
app/services/school_creator.rb
app/services/schools/bill_request_service.rb
app/services/schools/consent_request_service.rb
app/services/targets/target_mailer_service.rb
spec/models/school_spec.rb
spec/services/schools/bill_request_service_spec.rb

Fixes specific issue with requests for bills not including cluster admins by adding new helper methods to school for different groups of users: `all_school_admins`, `staff`, `all_adult_users`. Change controllers and services that select individual user types to use these consistently.

Ensure bill and consent requests go to all school admins

---

.ebextensions/cronjob.config
app/classes/targets/school_targets_progress.rb
app/mailers/target_mailer.rb
app/services/targets/admin_report_service.rb
app/services/targets/school_group_progress_reporting_service.rb
app/services/targets/school_group_target_data_reporting_service.rb
app/services/targets/school_group_targets_testing_service.rb
app/views/target_mailer/admin_target_report.html.erb
lib/tasks/amr_importer/notifier.rake
lib/tasks/targets/admin_report.rake
lib/tasks/targets/enough_data_report.rake
lib/tasks/targets/send_review_target.rake
lib/tasks/targets/test_targets.rake
spec/services/targets/admin_report_service_spec.rb
spec/services/targets/school_group_progress_reporting_service_spec.rb

* Adds new services to generate reports on target progress and available data for school groups
* Extract the code used to test the targets and tracking feature into a new service
* Ensures that tasks used to send reminders, import notifications and admin targets only execute in production / environment where email sending is enabled
* Adds a service, mailer and template to send a weekly report to admins with 2 attachments, one reporting on target related data another on progress
* Add crontab entry to run the weekly report at 8.30 on a Friday morning

Initial version of service to generate report data

---

app/controllers/schools/meters_controller.rb
app/models/meter.rb
app/views/schools/meters/_active_meters.html.erb
app/views/schools/meters/_form.html.erb
app/views/schools/meters/_meter_notes.html.erb
app/views/schools/meters/edit.html.erb
app/views/schools/meters/index.html.erb
app/views/schools/meters/show.html.erb
app/views/shared/meter_attributes/_details_table.html.erb
spec/system/dcc_consent_spec.rb
spec/system/meter_management_spec.rb

* Display created/updated dates for meter attributes
* Only show n3rgy / DCC specific fields to admins, not school admins 
* Add a notes field to individual meters
* Allow admin to add notes from the form to edit meters
* Display notes as a pop-up modal on the meter management page, for admins only
* Display notes on the meter view page, for admins only
* Tidy up the meter page a bit

Add meter notes to record and track issues and changes with meters

---

app/controllers/schools_controller.rb
app/views/schools/_details_form.html.erb
spec/system/admin/school_creation_spec.rb

* Schools created manually are set to not visible to allow admin to complete other parts of the setup process
* Allow admin to configure whether a school is public or not when editing, so it can be configuring during manual creation

Manually created schools should not be visible

---

app/controllers/schools/meters_controller.rb
app/views/schools/meters/_form.html.erb
app/views/schools/meters/edit.html.erb
app/views/schools/meters/index.html.erb
app/views/schools/meters/show.html.erb
spec/system/meter_management_spec.rb

Edit meters, e.g. to add notes, is currently slow because we're always calling the n3rgy API.
Remove this call and rely on a) system checking this behind the scenes and b) admin being able to check this on the details page for a meter and then update accordingly.
We may decide to recheck DCC status more regularly, but that will be covered by a separate PR.

Dont make n3rgy api call on edit page

---

lib/amr/importer.rb
spec/lib/amr/importer_spec.rb

An error processing one file can still cause an entire amr config to fail. This change adds an exception handler so we process all the files we can in each run, rather than failing at the first error.
This avoids a single incorrect file breaking the loads, as has happened recently.

Add extra exception handling to amr importer

---

app/services/targets/progress_service.rb
app/services/targets/school_target_service.rb
app/services/targets/target_mailer_service.rb
spec/services/activation_email_sender_spec.rb
spec/services/alerts/generate_email_notifications_spec.rb
spec/services/targets/generate_progress_service_spec.rb
spec/services/targets/progress_service_spec.rb
spec/services/targets/school_target_service_spec.rb
spec/services/targets/target_mailer_service_spec.rb
spec/system/schools/school_targets_spec.rb

For the v2 of the targets feature we will allow any school to set a target, even if they don't have enough data.
This changes the logic in the school targets service based on a feature flag. If v2 is active, we only need to check if they have the right fuel type.
The background tasks to actually check what data they have has been left in place, as this allows us to enable/disable the feature cleanly.

2057 allow any school to set a target

---

app/models/schools/configuration.rb
app/services/schools/generate_configuration.rb
app/services/targets/generate_fuel_types.rb
db/migrate/20220316140302_add_estimates_to_school_configuration.rb
db/schema.rb
spec/services/targets/generate_fuel_types_spec.rb

Extends overnight run to generate list of fuel types where adding an annual estimate would unlock a more detailed target report.

Suggest use of estimate

---

app/assets/stylesheets/targets.scss
app/classes/tables/summary_table_data.rb
app/controllers/schools/school_targets_controller.rb
app/helpers/targets_helper.rb
app/views/schools/school_targets/_generating_report.html.erb
app/views/schools/school_targets/_limited_data.html.erb
app/views/schools/school_targets/_prompt_to_review_target.html.erb
app/views/schools/school_targets/_warn_recent_data.html.erb
app/views/schools/school_targets/show.html.erb
spec/system/schools/school_targets_spec.rb

When we have limited data, display an alternate view of the school targets progress overview.

Ensure progress summaries are tolerant of limited data

---

app/services/schools/generate_configuration.rb
spec/services/targets/school_target_service_spec.rb

Change how the GenerateConfiguration service loads (or creates) the Configuration for a school. Accessing via the school model avoids us having potentially cached data later in the content batch.

2080 bug after setting a target and an estimate 2 regenerations are required to get a bullet chart

---

app/assets/javascripts/bullet_charts.js
app/views/schools/progress/_row.html.erb
app/views/schools/progress/index.html.erb
app/views/schools/school_targets/_bullet_chart.html.erb
app/views/schools/school_targets/_limited_data.html.erb
app/views/schools/school_targets/_prompt_to_add_estimate.html.erb
app/views/schools/school_targets/show.html.erb
spec/system/schools/progress_spec.rb
spec/system/schools/school_targets_spec.rb

* Tweak wording on prompt to add estimates
* Don't show 0% in table if there's no target for that month
* Don't show 0% change as a positive
* Improve layout, altering spacing around charts and elements
* Make limited data view more consistent with richer view with bullet char
* Remove some unneeded CSS classes from prototyping.

2081 improve ux of target summary and progress pages page

---

app/views/schools/progress/index.html.erb
app/views/schools/school_targets/_prompt_to_add_estimate.html.erb
app/views/schools/school_targets/show.html.erb
spec/system/schools/progress_spec.rb
spec/system/schools/school_targets_spec.rb

On the progress report, only prompt for an estimate if we need one for the specific fuel type.
On the target summary page, prompt for all estimates as before.

Only show estimate prompt for specific fuel type

---

app/classes/targets/fuel_progress.rb
app/controllers/schools/progress_controller.rb
app/views/schools/progress/index.html.erb

Check whether there is target consumption in the month before giving user feedback.

Handle missing targets in feedback logic

---

Gemfile
Gemfile.lock
app/controllers/schools/charts_controller.rb
app/controllers/schools/simulations_controller.rb
app/models/chart_data.rb
lib/tasks/deployment/20220411122056_season_analysis_alerts.rake

Switches to `aws-eb-test` branch of analytics to allow testing of:
* energy-sparks/energy-sparks_analytics#241
* energy-sparks/energy-sparks_analytics#240
* energy-sparks/energy-sparks_analytics#242

Analytics test release

---

app/services/alerts/collate_benchmark_data.rb

Use pluck to pull the 2 columns we want. Only saves a small amount of memory, but marginally more efficient.

Tweak loading of benchmark data

---

app/models/transport_survey_response.rb

Smallest pull request ever...
Provide the option to select up to 6 passengers per journey rather than 4.

Transport surveys - allow up to 6 passengers per journey (rather than 4)

---

app/javascript/packs/transport_surveys.js
app/javascript/packs/transport_surveys/storage.js
app/views/schools/transport_surveys/edit.html.erb

Also hides the app button if localStorage is not present.
This has been manually tested in firefox where you can easily disable localStorage. 
(In Chrome, you can't turn off localStorage without turning off cookies)

Transport surveys UI - present an error if localStorage is not available

---

Gemfile
Gemfile.lock
app/models/benchmark_result.rb
app/models/calendar_event.rb
app/models/transport_survey.rb
app/models/transport_type.rb
app/services/alerts/collate_benchmark_data.rb
app/services/alerts/generate_and_save_benchmarks.rb
db/migrate/20220517085403_add_json_column_to_benchmark_result.rb
db/schema.rb
lib/tasks/deployment/20220517150229_migrate_benchmark_result_data.rake
spec/services/alerts/collate_benchmark_data_spec.rb
spec/services/alerts/generate_and_save_benchmarks_spec.rb

* Add new JSON column for storing benchmark data, rather than YAML
* AfterParty task to convert benchmark results in latest run to JSON and store
* Store both JSON and YAML versions of benchmarks (for now, until we have completed switching over)
* Change how benchmark result data is loaded to use alternative column based on feature flag (`FEATURE_FLAG_JSON_BENCHMARKS`)
Relies on some code changes in analytics to handle round-tripping of Date/TimeOfData objects that are convered to strings when the benchmarks are stored as JSON

Change storage model for benchmark data

---

app/assets/javascripts/templates/transport_surveys.hbs
app/assets/stylesheets/links.scss
app/javascript/packs/transport_surveys.js
app/javascript/packs/transport_surveys/notifier.js
app/javascript/packs/transport_surveys/storage.js
app/views/schools/transport_surveys/edit.html.erb
app/views/schools/transport_surveys/index.html.erb
spec/system/schools/transport_surveys_spec.rb

- Rather than using js alerts, use bootstrap ones. Unless alerts are fatal / blocking, they fade after a period. See what you think, the alternative would be to allow them to be dismissed rather than fading.
- Spruce up the 'remove and save unsaved responses' styling and functionality on the main page. Have re-styled the buttons - couldn't find any working button css that did primary / secondary styling, so I improvised with a tiny bit of custom css and along with other standard bootstrap styles.
- Also remove the "reset and clear" functionality from the app (https://trello.com/c/zr26HkFa/2181-transport-survey-ui-remove-ability-to-reset-and-clear-results) as it relied on changes in this PR.

Transport Survey Alerts

---

app/controllers/admin/transport_types_controller.rb
app/models/transport_survey.rb
app/models/transport_survey_response.rb
app/models/transport_type.rb
app/views/admin/transport_types/_form.html.erb
app/views/admin/transport_types/index.html.erb
app/views/admin/transport_types/show.html.erb
db/migrate/20220523102554_add_category_to_transport_type.rb
db/migrate/20220523104145_remove_unused_column_from_transport_type_responses.rb
db/migrate/20220523152918_make_transport_type_category_optional.rb
db/schema.rb
lib/tasks/deployment/20220523110209_add_transport_type_categories.rake
spec/factories/transport_types.rb
spec/system/admin/transport_types_spec.rb

Quick question before this is merged. I have put "motorbike" in the "car" category but this doesn't seem totally right. Or do we need to rename / broaden the "car" category to "motorised" or similar? I have put "park and stride" in the "car" category too?
Summary of changes:
* Add new enum field to transport types
* Make changes to admin interface to support new field + associated rspec
* This includes an after party task to assign a category to each transport type
* This also changes the image for the electric car transport type to be "🔌🚘" as requested by Claudia
* While I was doing this, I noticed an extra column had sneaked into the transport_survey_responses because of a mistake in a previous migration, so there is a migration to remove this too.

Add category to transport type

---

app/controllers/admin/transport_types_controller.rb
app/controllers/transport_types_controller.rb
app/models/transport_type.rb
app/views/admin/transport_types/_form.html.erb
app/views/admin/transport_types/index.html.erb
app/views/admin/transport_types/show.html.erb
app/views/schools/transport_surveys/edit.html.erb
db/migrate/20220523135758_add_position_to_transport_types.rb
db/schema.rb
lib/tasks/deployment/20220524100658_update_transport_type_position.rake
spec/factories/transport_types.rb
spec/models/transport_type_spec.rb
spec/system/admin/transport_types_spec.rb

* Adds new position column to transport types
* Includes an after party task to order existing transport types
* Hook up new column in the transport types admin interface
* Use the new position column to order transport types in the javascript app
Just waiting on Claudia to check the default order I have set in the after party task (have added it to the Trello card).

Add an order column to transport types

---

app/models/concerns/transifex_serialisable.rb
spec/models/activity_type_spec.rb
spec/services/transifex/synchroniser_spec.rb

Changes to use string based keys in the hash generated by `tx_serialise` and assumes string keys in `tx_update` this makes it compatible with round-tripping to Transifex.
Locale parameter remains a symbol, e.g. `:cy` to match what is returned by, e.g. `I18n.available_locales`.

Use string keys when serialising to/from YAML

---

app/services/transifex/synchroniser.rb
spec/services/transifex/synchroniser_spec.rb

If we have just pulled down some updated translations then the ActivityType (or other record) will have been updated.
We don't want to immediately trigger a push based on that, so we need to check both the dates of last push and pull before deciding whether we have a local change.

Change push logic to avoid pushing immediately after a pull

---

app/controllers/schools/transport_surveys_controller.rb
app/javascript/packs/transport_surveys.js
app/javascript/packs/transport_surveys/carbon.js
app/javascript/packs/transport_surveys/handlebars_helpers.js
app/javascript/packs/transport_surveys/helpers.js
app/models/transport_survey.rb
app/views/admin/transport_types/index.html.erb
app/views/schools/transport_surveys/edit.html.erb
app/views/schools/transport_surveys/responses/index.html.erb
config/routes.rb
spec/system/schools/transport_surveys_app_spec.rb

This PR revises the carbon calculation & equivalences code as follows:
* Ensures a non-zero equivalence statement is returned
* Now takes the conversion rates from Analytics. I've only taken the rates and not the statements themselves. The statements in analytics seemed a bit too long winded / grown up but I could be wrong.
* Hook pluralisation up in equivalences and in a couple of other places too
* Formats dates better
* Also fixes a results / pagey issue on the responses page
* Also removes unused functionality that allowed users to survey on a day other than today

2174 revise transport survey carbon calculations

---

lib/tasks/deployment/20220622170636_upate_transport_types_kg_co2e_per_km.rake
lib/tasks/deployment/20220622170636_update_transport_types_kg_co2e_per_km.rake

Update the transport type kg_co2e_per_km values based on the latest data from gov.uk
I have a query on this: For Taxi, in the file downloaded from gov.uk, a "Regular taxi" has a value of 0.20826, however, it looks like that previously, the same value as Car (new value 0.17148) has been used instead. Should we use the value for "Car" or "Regular Taxi" for Taxi?
Thank you!

Update kg_co2e_per_km for transport types from the latest gov.uk figures

---

app/models/concerns/transifex_serialisable.rb
spec/models/activity_type_spec.rb

Thought the syntax was `{{...}}` but its: `{{#chart}...{{/chart}}` so fixed the regexp.

Fix handling of custom tags

---

app/javascript/packs/transport_surveys.js
app/views/schools/transport_surveys/responses/index.html.erb

There was an issue where the response surveyed_at times were out by an hour. I thought I had fixed it but alas, no.
After some investigation, it looks like DateTimes in the database are stored as UTC and also displayed as UTC by default (sounds obvious now I say it I know). Which is fine in the winter but not BST. This PR makes sure the dates are sent from the javascript in UTC and then formatted in localtime when displayed in rails.

Make response survey time locale aware

---

lib/tasks/deployment/20220712130546_add_van_and_electric_bike_transport_types.rake

* Adds new van and electric bike transport types
* Also updates park and stride note to say 10 minutes rather than 15
* Reorders transport types to position new ones
* As part of this, have [created a document on creating and updating transport types](https://docs.google.com/document/d/1uEmInQwth9xjLm3SLk8FWh8i0PqKYERMStE5Amtri2k/edit?usp=sharing)

Add e-bike and van transport types

---

app/helpers/application_helper.rb
app/views/schools/transport_surveys/responses/index.html.erb
config/application.rb
spec/helpers/application_helper_spec.rb
spec/system/schools/transport_surveys_spec.rb

This one is up here for discussion really. I could have just used datetime.in_time_zone('London') in the code where the time needed presenting in the right zone, but I already needed to do it 3 times for this bit of code, so it seemed right to attempt to make it configurable and reusable.
* I added a config item in application.rb for the display_timezone. Not sure how you feel about this going in here - seemed like as good a place as any for configuration but I might have missed somewhere else that is in use.
* Allow nice_date_times helper method to use the timezone if configured (and has the option localtime: true passed). These changes shouldn't affect any other times presented by nice_date_times helper as it is.
I know we will be revisiting this soon for i18n so it's not particularly …

Display transport survey response times in London time zone

---

app/controllers/admin/transport_types_controller.rb
app/controllers/schools/transport_surveys/responses_controller.rb
app/controllers/schools/transport_surveys_controller.rb
app/helpers/application_helper.rb
app/models/transport_type.rb
app/services/transifex/loader.rb
app/views/admin/transport_types/_form.html.erb
app/views/admin/transport_types/show.html.erb
config/locales/activerecord.yml
config/locales/views/schools/transport_surveys.yml
db/migrate/20220718174747_allow_null_transport_type_name.rb
db/schema.rb
lib/tasks/deployment/20220718130842_copy_transport_type_names_to_mobility_tables.rake
spec/models/transport_type_spec.rb
spec/services/transifex/loader_spec.rb
spec/system/admin/transport_types_spec.rb
spec/system/schools/transport_surveys_spec.rb

First pass at translating a database field - transport_types#name. Feedback welcome!
Also translates a couple of transport survey flash messages.
Needed to do this before finishing the [download to csv functionality](https://github.com/Energy-Sparks/energy-sparks/pull/1908)

Translate transport type name

---

app/javascript/packs/transport_surveys.js
app/javascript/packs/transport_surveys/carbon.js
app/models/transport_survey.rb
app/views/schools/transport_surveys/_equivalences.html.erb
app/views/schools/transport_surveys/edit.html.erb
app/views/schools/transport_surveys/show.html.erb
config/i18n-tasks.yml
config/locales/common.yml
config/locales/views/schools/transport_surveys.yml
spec/system/schools/transport_surveys_app_spec.rb
spec/system/schools/transport_surveys_spec.rb

* This task has meant that the equivalences have needed to be moved out of the js and into rails & passed through to the JS via config. 
* A side effect of this is that they are now translatable (which is also part of another task coming up).
The carousel now looks like this:
An alternative would be this (with the % information formatted as it was originally):
* Point to note here (and as before) is that responses with transport types in no category are not included in this summary (happy to add if required)!
* Also happy to move the emojis out of the equivalence statements used on the results page (or otherwise) if it looks too much (with the svg images being there too).

Add jquery carousel to results page

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/school.scss
app/assets/stylesheets/scoreboard.scss
app/controllers/scoreboards_controller.rb
app/models/academic_year.rb
app/models/podium.rb
app/models/scoreboard.rb
app/models/scored_schools_list.rb
app/views/scoreboards/_table.html.erb
app/views/scoreboards/index.html.erb
app/views/scoreboards/show.html.erb
config/locales/common.yml
config/locales/views/scoreboards/scoreboards.yml
spec/models/scoreboard_spec.rb
spec/models/scored_schools_list_spec.rb
spec/system/scoreboard_spec.rb

Improving the UX of the scoreboard pages

Revise layout of the scoreboard pages

---

app/helpers/application_helper.rb
app/models/podium.rb
app/views/pupils/analysis/_top_level.html.erb
app/views/pupils/analysis/electricity.html.erb
app/views/pupils/analysis/electricity_bar.html.erb
app/views/pupils/analysis/electricity_line.html.erb
app/views/pupils/analysis/gas.html.erb
app/views/pupils/analysis/gas_bar.html.erb
app/views/pupils/analysis/gas_line.html.erb
app/views/pupils/analysis/index.html.erb
app/views/pupils/analysis/show.html.erb
app/views/pupils/analysis/solar.html.erb
app/views/pupils/analysis/solar_bar.html.erb
app/views/pupils/analysis/solar_line.html.erb
app/views/pupils/analysis/storage_heaters.html.erb
app/views/pupils/analysis/storage_heaters_bar.html.erb
app/views/pupils/schools/_default_equivalences.html.erb
app/views/pupils/schools/_equivalences.html.erb
app/views/pupils/schools/_no_points_podium.html.erb
app/views/pupils/schools/_podium.html.erb
app/views/pupils/schools/show.html.erb
config/environments/development.rb
config/locales/common.yml
config/locales/views/pupils/pupils.yml
spec/helpers/application_helper_spec.rb

Extracting text strings from the templates for pupil dashboard and analysis pages.
A few points:
- some strings have embedded html tags (mostly "strong") and so have "_html" suffixes on keys
- those strings may be used in title tags, in which case they need to have "strip_tags" applies
- some strings have ellipses, which are encoded as &hellip; , in which case they need "sanitize" to be applied
- some strings have interpolated values which are themselves translated
- the values for interpolation are converted to i18n keys (these are basically energy types)
- "Storage Heaters" gets converted to 'storage_heaters'
- "Electricity+Solar PV" gets converted to 'electricity_and_solar_pv' (original string is used as part of url path, hence "+" character)
- some common strings for links (e.g. …

2330 localise pupil dashboard templates to use i18n

---

.platform/hooks/predeploy/99_after_party.sh
bin/run_as_webapp

In the upgrade from Amazon Linux 1 to Amazon Linux 2 we had to change how we load environment variables. There were some helper scripts and files created in AL1 which were no longer available.
In AL2 I started using this to load the variables:
```
export $(cat /opt/elasticbeanstalk/deployment/env | xargs)
```
This works fine. However, when attempting to clone an existing environment I found that the file `/opt/elasticbeanstalk/deployment/env` does not seem to be created until right at the end of a successful deployment **after** the after party tasks are run.
This means I was getting an error in the log from the script as it could not load the environment variables. 
I think this also means that the first deployment of code to a new platform version has previously been failing to run …

Change how we load environment variables

---

.ebextensions/cronjob.config

Move the S3 jobs to Sunday nights, to further minimise any disruption due to CPU/Memory overheads.

Reschedule s3 uploads

---

app/controllers/interventions_controller.rb
app/views/activities/_form.html.erb
spec/system/activities_spec.rb

We encourage schools to record activities and actions, they can record what they do each day but more frequently they log activities in a series of updates, specifying when they did them.
Currently we default the dates on the forms to the current date. This isn't encouraging users to pick the actual date they record an activity.
We've decided to remove the defaults for now

Remove default dates on activity and action forms

---

app/models/transport_survey.rb
app/views/schools/transport_surveys/show.html.erb
config/locales/common.yml
config/locales/views/schools/transport_surveys.yml
spec/models/transport_survey_spec.rb
spec/system/schools/transport_surveys_spec.rb

This adds a table at the bottom of the transport survey results page, which shows the amount of journeys taken by car for each journey time.
This is now ready for review / merging if all ok.

Display table of journey times by car

---

app/helpers/timeline_helper.rb
app/views/home/training.html.erb
spec/helpers/timeline_helper_spec.rb

There's a helper used in formatting the timeline shown on the training page. It's not used elsewhere.
It previously accepted the name of the month, this has been changed to pass in the month number and then look up the month name via the I18n API.

Localise display of months in timeline helper

---

app/views/benchmarks/index.html.erb
app/views/schools/analysis/index.html.erb
app/views/schools/analysis/show.html.erb
app/views/schools/find_out_more/show.html.erb
app/views/shared/_translation_coming_soon.html.erb

This pr adds a "coming soon" message to untranslated sections of the platform
The message will be display in a neutral blue bar, prominently at the top of the page. See `_prompt_to_review_target.html.erb` as a reference for styling.
With suggested initial text:
"We're still working towards having Energy Sparks fully translated into Welsh. We've prioritised translating our educational activities and pupil facing activities. Translating this section of the site is still in progress, so for now we are defaulting to English."

Add coming soon message to untranslated sections

---

app/services/solar/low_carbon_hub_upserter.rb
app/services/solar/solar_edge_upserter.rb
spec/services/solar/low_carbon_hub_download_and_upsert_spec.rb
spec/services/solar/solar_edge_upserter_spec.rb

The Solar Edge and Low Carbon Hub loaders were using `first_or_create!` with a set of attributes that included the meter `name`.
But meters can be renamed by admins. This caused a bug where a meter wasn't being properly found after being renamed, but then data failed to insert as the meter did exist.
Switch to use `find_or_create_by!` and passed in a block to set attributes on create.

Fix finder to not use meter name

---

app/models/activity_type.rb
app/services/template_interpolation.rb

From https://trello.com/c/H62XMjMj/2371-typeerror-from-mobility-backend
This pr (hopefully) fixes the error seen occasionally in development when there have been some code changes in the application
```
TypeError - no implicit conversion of Mobility::Backends::ActionText::RichTextTranslation into String:
app/services/template_interpolation.rb:40:in `process_string_template'
app/services/template_interpolation.rb:23:in `block in interpolate'
app/services/template_interpolation.rb:18:in `interpolate'
app/controllers/concerns/dashboard_alerts.rb:14:in `block in setup_alerts'
app/controllers/concerns/dashboard_alerts.rb:5:in `setup_alerts'
app/controllers/pupils/schools_controller.rb:36:in `setup_data_enabled_features'
app/controllers/pupils/schools_controller.rb:22:in `show' …
```

Fix TypeError from Mobility Backend

---

app/controllers/schools/alert_reports_controller.rb
app/controllers/schools/content_reports_controller.rb
app/controllers/schools/equivalence_reports_controller.rb
app/models/equivalence.rb
app/services/equivalences/calculator.rb
app/services/equivalences/generate_equivalences.rb
app/views/schools/equivalence_reports/index.html.erb
app/views/schools/equivalence_reports/show.html.erb
app/views/schools/reports/index.html.erb
config/routes.rb
db/migrate/20220825134314_add_welsh_template_data_to_equivalence.rb
db/schema.rb
spec/models/equivalence_spec.rb
spec/services/equivalences/calculator_spec.rb
spec/system/admin/equivalence_management_spec.rb
spec/system/admin/school_batch_reports_spec.rb
spec/system/management/dashboard_spec.rb
spec/system/pupils/dashboard_spec.rb

Generate and store English and Welsh formatted variable data for Equivalences. And then ensure this is used when generating text for display.

Equivalence generation localisation

---

app/assets/javascripts/common_chart_options.js
app/models/chart_data_values.rb

Some school comparison charts return "infinite" values, e.g. percent change in gas usage between last week and this week, where last week there was no gas consumption i.e. this week divided by last week = Infinity. 
The analytics has been updated to add configuration specifying min/max values for charts. See code changed in: https://github.com/Energy-Sparks/energy-sparks_analytics/pull/292
This pr fixes the front-end application needs by applying the max x axis value to highcharts
from
to

Infinite increases on school comparison charts

---

config/locales/cy/en.yml

The `en.yml` file is translated and fully reviewed. Have managed to pull that down, so this is the provided text.
The command I used was:
```
tx pull --mode onlyreviewed --all
```
The `mode` parameter ensures that the client only pulls reviewed translations. I think we need this and the `minimum_perc` setting in order to ensure we only pull down 100% complete YAML files with properly reviewed translations. (see [tx client code](https://github.com/transifex/cli/blob/f5034553805c2c726b3b2b23e32f88297b3c1ab8/internal/txlib/pull.go#L521)).
The `-a` (or `--all`) param controls "Whether to download all files". I found that without this, because the Welsh version of the file (`config/locales/cy/en.yml`) didn't exist locally, then it just skipped the download completely. So we need that parameter …

Translations from Transifex

---

app/assets/javascripts/common_chart_options.js

This pr makes all data series with a name starting `trendline_` plot with a line instead of as individual scatter plot points.

Update scatter charts to plot regression as a line

---

app/models/benchmark_result.rb
app/services/alerts/collate_benchmark_data.rb
app/services/alerts/generate_and_save_benchmarks.rb
spec/factories/benchmark_result_generation_run_factory.rb
spec/factories/benchmark_result_school_generation_run_factory.rb
spec/models/benchmark_result_spec.rb
spec/services/alerts/collate_benchmark_data_spec.rb
spec/services/alerts/generate_and_save_benchmarks_spec.rb

We have started to store benchmark results as JSON, as it uses less memory when fetching from database.
The analytics is sending some special values (`Float::INFINITY`, `-Float::INFINITY`, `Float::NAN`) for some benchmark comparisons. These currently aren't being round-tripped properly with the new JSON column, but were ok in the YAML version.
The default json serialiser converts these values to nil. So when re-parsed and passed to the analytics, the code is not working as expected.
This add some code to `BenchmarkResult` which round-trips these values using strings [similar to YAML](https://yaml.org/refcard.html). 
This code is called when we save the benchmark results, and when its read back from the database.
Note: I've not used a before/after callback here as ActiveRecord seems to do …

Handle Infinite and NaN values in benchmark results

---

config/webpacker.yml
spec/i18n_spec.rb

`month_names` and `abbr_month_names` are still being pulled from TX with a missing empty 0th element (needed as there's no zero month see https://github.com/rails/rails/blob/main/activesupport/lib/active_support/locale/en.yml).  
This pr adds a a test to ensure `month_names` and `abbr_month_names` for both `en` and `cy` locales are in the correct format in case the missing empty 0th element is accidentally checked in.

Ensure correct month name and abbr month name array formatting

---

app/controllers/application_controller.rb
app/helpers/application_helper.rb
config/i18n-tasks.yml
config/initializers/pagy.rb
config/locales/cy/pagy.yml
config/locales/pagy.yml

This PR covers i18n for pagy, which is used by transport surveys but also site-wide.
When doing this, I found that the pagy.rb, the pagy config file, was not being picked up by the app and so moved it to config/initializers where pagy expects it to be.
Also, I have added config/locales/pagy.yml, and config/locales/cy/pagy.yml. The Welsh version is actually English at the moment, but since I had to configure the app to use a locale file and did not have the welsh version yet, I thought this would be the best thing to do for now. Also technically, we do not need an English yml file for pagy as the translations are inbuilt but since we need to put one there for transifex, I thought it worth linking to from pagy.

i18n for pagy

---

app/views/schools/usage/show.html.erb

This pr makes the date time picker slightly wider so year isn't hidden when the selected locale is cy
from
to

Make date time picker under usage charts a bit wider

---

app/assets/javascripts/common_chart_options.js

This pr fixes the trend line plotting to work for series names starting 'Trendline ...' as well as 'trendline_' it also replaces the first and last point code with `connectNulls: true` to conserve data points (the line was previously breaking due to missing (null) values).

Fix trendlines for series name starting with Trendline

---

app/assets/stylesheets/nav.scss
app/models/user.rb
app/views/shared/_switch_schools.html.erb

When a user is associated with a large number of schools, the list of schools in the "Switch schools" menu gets very long.
This PR:
* Ensures the list is sorted by name (previously it was in an arbitrary order)
* Sets a max height (arbitrary value) for the menu to make it scrollable. ([Example](https://www.codeply.com/p/pHbaRmjRgn)

Improve display of switch school menu

---

app/models/equivalence.rb
app/views/schools/equivalence_reports/index.html.erb
app/views/schools/equivalence_reports/show.html.erb
spec/models/equivalence_spec.rb

This pr adds an extra column to the [tabular summary](https://test.energysparks.uk/schools/king-james-1-community-academy/equivalence_reports) for the ‘via unit’ (as per Philips suggestion)
http://localhost:3000/schools/king-james-1-community-academy/equivalence_reports
"Each of the equivalences e.g. a smartphone can be converted via one or more of £, kWh or CO2 and you get different results depending on the conversion.  In theory you could have 3 lines on the [tabular summary report](https://test.energysparks.uk/schools/king-james-1-community-academy/equivalence_reports/2718924) for a given equivalence, time period and fuel type, one for each of CO2, £ or kWh but at the moment you couldn’t differentiate between each of the £, CO2 and kWh conversions. In practice we are only likely to …

Update the Equivalences report to show via units

---

lib/tasks/deployment/20220913102909_clean_up_dashboard_alerts.rake

We no longer generate DashboardAlert records for teacher or public dashboard types.
This pr covers writing an AfterParty tasks to delete the older records for these dashboards.

Clean up DashboardAlert records to remove all unused public & teacher alerts

---

app/views/schools/dashboard/_info_bar.html.erb

"Record a pupil activity" text, as shown in dashboard prompt, is too long when shown in Welsh. This pr makes the button size full width and height so no text breaks out of the pill button. 
from
to

Make dashboard info button full width and height

---

app/models/chart_data_values.rb
spec/models/chart_data_values_spec.rb

This PR provides (another) fix for the broken chart trendline data.  This time reducing the trendlines to 2 data points in ruby, instead of doing the post processing javascript.

Chart trendline fix

---

app/views/activities/show.html.erb

Extra `%>` in template, possibly added as part of i18n work meant that link was broken and code showing on page.

Fix typo in template

---

app/helpers/schools_helper.rb
app/models/meter.rb
app/views/schools/meters/_active_meters.html.erb
app/views/schools/meters/_form.html.erb
spec/models/meter_spec.rb

The Meter Management page does not provide a link to edit pseudo meters. But there is a link to edit them via the detail page.
The editing was originally disabled due to a limitation in the data loader, which has now been removed.
This pr:

Allow editing of pseudo meters

---

app/models/school_group.rb
app/services/comparison_service.rb
spec/models/school_group_spec.rb

The list of school groups on the Benchmark page, e.g. [here](https://energysparks.uk/benchmark?benchmark%5Bschool_types%5D%5B%5D=0&benchmark%5Bschool_types%5D%5B%5D=1&benchmark%5Bschool_types%5D%5B%5D=2&benchmark%5Bschool_types%5D%5B%5D=3&benchmark%5Bschool_types%5D%5B%5D=4&benchmark%5Bschool_types%5D%5B%5D=5&benchmark%5Bschool_types%5D%5B%5D=6&benchmark_type=annual_energy_costs_per_pupil) is produced by the `ComparisonService`
It's possible for a school group that doesn't yet have any visible schools to appear on this list. This is occasionally causing an analytics error.  This PR removes this from happening to ensure that any Rollbar issues are actually with the benchmarking code.

Do not include school groups with no schools on benchmark page

---

app/controllers/schools/aggregated_meter_collections_controller.rb
spec/controllers/schools/aggregated_meter_collections_controller_spec.rb

If a school isn't in the aggregated school cache we serve a holding page. This gives time for the school to be added to the cache and then the user is redirected to the appropriate dashboard. This ensures that the charts will work correctly. The holding page polls to check to see if the school is cached by doing a XHR POST request.
If a school is not public, then there's a bug here as the controller checks to see if the user is authorised to `:show` the school, but authentication isn't actually required. So the user gets an error, rather than a redirect to a login form.
This removes the auth check and updates the status code for any error response. This is safe to do as any subsequent redirect will do the appropriate access control checks.
This error is unlikely to happen in practice, as …

Remove auth check on holding page

---

app/jobs/manual_data_load_run_job.rb
app/services/database/vacuum_service.rb
lib/tasks/amr_importer/import_all.rake
lib/tasks/amr_importer/import_n3rgy_readings.rake
lib/tasks/solar/import_low_carbon_hub_readings.rake
lib/tasks/solar/import_rtone_variant_readings.rake
lib/tasks/solar/import_solar_edge_readings.rake
spec/jobs/manual_data_load_run_job_spec.rb
spec/services/database/vacuum_service_spec.rb
spec/support/database_cleaner.rb

Enables vacuum service for the following:
See note against import_all.rake about moving the Vacuum Service call out of the loop. I've not particularly been able to manually test the rake tasks, so suggest this needs doing on the test server (as you'd expect really I guess!)?
Worth noting for future implementation that a VACUUM can't be run inside a transaction block - this tripped me up for a while trying to work out why my rspec wasn't working.

Ensure statistics for amr_data_feed_readings table are always up to date

---

app/controllers/schools/charts_controller.rb
app/views/robots_txts/allow.raw
spec/controllers/schools/charts_controller_spec.rb

We are getting a flurry of Rollbar errors due to a missing chart_type parameter:
https://rollbar.com/energysparks/EnergySparksProduction/items/1238/?item_page=0&#instances
Its not clear why this is happening, but looking at the error, these all(?) seem to have a From header of "googlebot(at)googlebot.com".
So this might be a search engine error, e.g. following a URL in the response but without adding a parameter (which might have been injected via JS?)
Need to:
Returns 
`{"error":"param is missing or the value is empty: chart_type","status":400}`

Missing chart_type param

---

app/views/schools/show.html.erb
spec/system/schools/dashboard/prompts_spec.rb

There are a few dashboard prompts that were only shown on the management dashboard, which could only have been accessed by signed in users from that schools, or users from other schools.
With the dashboard refactoring these were being shown to all users, including guests. While some are actually just links to other areas of the site, the transport survey actually requires authentication.
Rather than display the links and prompt for login, I've instead hidden them from unauthorised users. This aligns them better with other prompts, e.g. to set targets, so that they're only shown to users with permissions to take action.
This PR:
- adds a conditional around these prompts, so that they're only shown to users linked to this school and with the management dashboard permission
- adds a new set …

Change visibility of fixed dashboard prompts

---

app/controllers/admin/manual_data_load_runs_controller.rb
app/models/manual_data_load_run.rb
app/views/admin/reports/data_loads/index.html.erb
config/routes.rb
spec/models/manual_data_load_run_spec.rb

Allow an Energy Sparks admin to delete uploaded readings, by adding a delete button to this view:
https://energysparks.uk/admin/reports/data_loads

Allow admin to delete uploaded readings

---

lib/tasks/deployment/20220927125827_rename_smartest_energy_data_feed_config.rake
lib/tasks/deployment/20220927130324_create_stark_portal_energy_data_feed_config.rake
lib/tasks/deployment/20220927131214_rename_stark_oxfordshire_data_feed_config.rake

We are now receiving 2 different formats of daily datafeeds from Stark - 1 format is processed and the other is not. The 1 that we don't process has been set up for schools that are customers of Smartest energy. It is similar, but not identical to the data we get from the Stark portal. The data we get from the Stark portal also now can't be easily loaded into Energy Sparks without data manipulation which is a pain. Please can you make the following changes to the data formats. We should be able to use the subject of the email to differentiate them.  This pr:

Update different Stark datafeeds

---

app/controllers/schools_controller.rb
app/views/schools/show.html.erb
spec/system/schools/dashboard/prompts_spec.rb

Further tweak to the dashboards.  Allows an admin to see the default standard prompts, even though they're not linked to the school.
Extracted logic from templated into controller method. Added tests.

Allow admins to see all dashboard prompts

---

app/models/ability.rb
app/services/school_creator.rb
app/views/onboarding/clustering/new.html.erb
app/views/onboarding/completion/new.html.erb
spec/factories/staff_role.rb
spec/models/user_spec.rb
spec/services/school_creator_spec.rb
spec/system/school_admin/user_management_spec.rb
spec/system/school_onboarding_spec.rb

This PR revises the onboarding workflow to allow group admins to complete onboarding on behalf of the schools in their groups.
- ensures group admins have the right permissions to manage the onboardings for their group
- tweak message on login page
- revise School Creator to not associate user with school, or sign them up for alerts
- tweak confirmation page to not show staff role if not present, as group admins do not have them
- add tests for the ability, service and the workflow

Allow group admins to complete onboarding for schools

---

app/views/admin/school_groups/index.html.erb
spec/system/admin/school_groups_spec.rb

This is as outlined, however, maintains the original buttons for each school group, as they're needed until the "Manage school group" ticket has been completed.

Revise admin school group index

---

.ebextensions/jobs-log.config
config/application.rb

We need to configure some good job settings so we're not relying just on default values.
For the moment we want:

Review/revise GoodJob configuration

---

Procfile
app/jobs/dcc_checker_job.rb
app/jobs/dcc_grant_trusted_consents_job.rb
app/jobs/manual_data_load_run_job.rb
app/jobs/school_batch_run_job.rb

We will have the following jobs executing via Good Job:
- `DccCheckerJob`, checks meter status after it has been setup. Runs intermittently
- `GrantTrustedConsentsJob`, runs when admin completes review of a meter. So intermittently
- `ManualDataLoadRunJob` runs when admin uploads CSV file. Done regularly during the day
- `SchoolBatchRunJob` runs when admin regenerates a school. Done regularly during the day
- "DailyRegenerationJob" a new job (wip) to run validation and content generation, which will schedule several hundred jobs (one per school) every morning
So we want to ensure that we process the daily regeneration jobs as quickly as possible, so it is faster than the current batch processes. Whilst also ensuring that admin jobs are run as soon as possible, and that the daily …

Queue configuration for Good Job

---

app/controllers/admin/school_groups/partners_controller.rb
app/helpers/nav_helper.rb
app/helpers/transport_surveys_helper.rb
app/models/school_group.rb
app/views/admin/school_groups/index.html.erb
app/views/admin/school_groups/show.html.erb
spec/models/school_group_spec.rb
spec/system/admin/meter_attributes_spec.rb
spec/system/admin/school_groups_spec.rb

This PR contains the school group admin page outlined in the trello card, minus, the tabbed list of schools functionality (which has been broken out in to another card):
[Add list of schools tabs to manage school group admin page](https://trello.com/c/tlBW6Ou1/2501-add-list-of-schools-tabs-to-manage-school-group-admin-page)

Manage school group page

---

app/controllers/management/schools_controller.rb

This controller should only be hit if a user has a bookmarked link, but its possible there are some older links on the site.
I've removed the check for whether the school is cached as this will happen after the redirect.

Remove check for whether school is in cache on old controller

---

app/views/schools/batch_runs/show.html.erb

Some of the steps in the school regeneration job are quite quick but we don't log seconds.
Just tweak the page so it adds seconds to help with identifying any bottlenecks, etc.

Include seconds in timestamp for school batch run job

---

app/assets/javascripts/trix_customisations.js

Trix only allows absolute URLs by default. But we want to allow relative links so that we don't have to maintain English and Welsh versions of links for simple links within the site.
This adds an event listener, as per: https://github.com/basecamp/trix/issues/624 to enable relative links

Allow relative links in Trix

---

app/services/amr/checking_validated_readings_for_a_meter.rb
app/services/amr/upsert_validated_readings.rb
spec/services/amr/checking_validated_readings_for_a_meter_spec.rb

During validation, we could up the rows to be deleted. But the delete method actually returns the number of affected rows.

Remove explicit count when deleting readings

---

app/models/school.rb
spec/models/school_spec.rb

When we either validate or aggregate schools we identify which of their meters have readings.
This query currently uses `includes` to join to either `amr_data_feed_readings` or `amr_validated_readings`. But this can be slow for schools with a lot of meters. Lots of examples of >500ms queries in the logs.
This PR changes the code to do an explicit `join` which is much quicker. Needed to add a `distinct` to just get the list of meters. Now takes a few milliseconds.

Optimise loading of meters with readings

---

app/services/amr/data_feed_upserter.rb
app/services/content_regenerator.rb

Rather than count all records, which is slow, just count those that are likely to match based on the provided list of mpans.

Count amr readings by mpan

---

app/controllers/admin/activity_types_controller.rb
app/controllers/admin/intervention_types_controller.rb
app/models/activity_type.rb
app/models/concerns/transifex_serialisable.rb
app/models/intervention_type.rb
app/models/link_rewrite.rb
app/views/admin/activity_types/_form.html.erb
app/views/admin/activity_types/_link_rewrites.html.erb
app/views/admin/activity_types/edit.html.erb
app/views/admin/intervention_types/_form.html.erb
app/views/admin/intervention_types/edit.html.erb
db/migrate/20221012100700_rich_text_link_rewrites.rb
db/schema.rb
spec/factories/link_rewrites_factory.rb
spec/models/activity_type_spec.rb

We often need to link to alternate URLs in the Welsh translated version of our activity and action descriptions and download links. E.g. to our own translated resources.
Currently the workflow for this requires admins to use Transifex to modify the links, then wait for content to sync back to the database. This is awkward and might great issues if Welsh text and translations are not properly recreated, re-reviewed, etc.
This PR allows an admin to associate a set of link rewrites to an activity type and intervention type. 
These link rewrites will be applied when the content is updated from Transifex. They will also be applied whenever the model is edited.
This allows us to limit replacement of URLs to the Energy Sparks content management tools.

Support link rewriting in transifex sync

---

config/initializers/new_framework_defaults_6_0.rb

ActiveStorage apparently uses a couple of jobs for analysing/purging content.
The existing defaults for these use queues we don't have on test or production, so they'd don't run. This puts the jobs onto the default queue.

Change queues for active storage

---

app/jobs/solar_area_loader_job.rb
app/services/solar/solar_area_lookup_service.rb
app/views/admin/school_onboardings/configuration/edit.html.erb
app/views/schools/configuration/_form.html.erb
spec/services/solar/solar_area_lookup_service_spec.rb

Final changes to allow activation of the auto-assignment of solar area feature.
- removes the solar pv field when creating a school onboarding, as its not required
- adds a background job to load 30 days of data for any solar area that is made active and does not yet have any readings

Auto assign solar pv areas

---

app/controllers/onboarding/school_times_controller.rb
app/controllers/schools/times_controller.rb
app/models/school_time.rb
spec/models/school_time_spec.rb

Recently discovered a few invalid school time records in the database. Turned out there were some issues with how the current validation rules were being applied.
This PR refactors how the rules around overlapping time periods is done, to make sure it works for both new and stored data.
Will separately tidy up existing data.

Improve school time validation

---

app/views/admin/school_groups/index.html.erb
app/views/admin/school_groups/show.html.erb
app/views/management/schools/_dashboard_message.html.erb
app/views/schools/show.html.erb
spec/factories/dashboard_messages.rb
spec/models/dashboard_message_spec.rb
spec/support/admin_dashboard_messages.rb
spec/system/schools/dashboard/prompts_spec.rb

This displays the school group message on the dashboard - hopefully in the right place @ldodds - let me know if it needs changing! 
In the admin / school groups index, I also added a little info symbol against school groups with a dashboard message set - just to give quick visibility on those with messages set (otherwise you have to click through to each school group to check which ones had messages). Hope that's ok, if not, I can take it out.

Display school group wide messages

---

app/models/concerns/transifex_serialisable.rb
app/models/link_rewrite.rb
spec/models/activity_type_spec.rb

Turns out that during round-trip to database and converting to string, the links in the HTML description may have escaping applied. This means that link rewriting is failing for some links which have parameters.
A small change (and restructured tests) to escape the URLs before we do the replacement.

Handle escaped parameters in rewrite

---

app/views/management/schools/_overview_data.html.erb
app/views/schools/observations/timeline/_audit.html.erb
app/views/schools/observations/timeline/_intervention.html.erb
app/views/schools/observations/timeline/_temperature.html.erb
app/views/shared/_dashboard_title.html.erb
config/locales/views/schools/schools.yml
spec/system/schools/dashboard/navigation_spec.rb

Adds translations for:
- Carbon emissions link on dashboard
- Fuel types in management table
- School timeline partials which didn't have translated timeline entries and button text.

Welsh translation snagging list 2

---

app/services/alerts/delete_alert_generation_run_service.rb
app/services/alerts/delete_benchmark_run_service.rb
app/services/alerts/delete_content_generation_run_service.rb
lib/tasks/alerts/delete_benchmark_runs.rake
lib/tasks/database/content_deletion.rake

The changes made in https://github.com/Energy-Sparks/energy-sparks/pull/1999 will work fine when we're running the database cleanup on a regular basis.
However, for the initial run, when we have ~3 years of data to delete, it's very slow and could potentially interfere with the live system.
This PR implements a separate rake task (and any other code changes) to allow us to run the database cleanup for 6/12 months at a time, so we can do this progressively and in smaller chunks. E.g. first deleting 2019 data.
We can run the rake task manually for each year and it will delete all content older than the date passed
```
bundle exec rake 'database:content_deletion['2019-12-31']'
bundle exec rake 'database:content_deletion['2020-12-31']'
bundle exec rake …
```

Add rake task for database content deletion

---

Gemfile
Gemfile.lock
app/controllers/admin/school_groups/school_onboardings_controller.rb
app/controllers/admin/school_groups_controller.rb
app/controllers/admin/school_onboardings_controller.rb
app/models/school.rb
app/models/school_onboarding.rb
app/services/school_groups/csv_generator.rb
app/views/admin/school_groups/_onboarding_schools.html.erb
app/views/admin/school_groups/index.html.erb
app/views/admin/school_groups/show.html.erb
app/views/admin/school_onboardings/index.html.erb
spec/models/school_onboarding_spec.rb
spec/models/transport_survey_response_spec.rb
spec/services/school_groups/csv_generator_spec.rb
spec/system/admin/school_groups_spec.rb

This PR allows detail for school groups to be exported.
While I was there, I switched out all use of select(&:incomplete?) and select(&:complete?) on school onboardings for new .incomplete and .complete scopes that should be much more efficient.
I put the school export code in it's own service as it didn't feel right to fill up the model or controller with it. Hope this is ok!
Also be aware that when breaking down onboarding counts by school type, that most onboardings don't have an associated school and therefore don't have a school type either - so for example, a school group may show 3 schools onboarding in total but when being broken down by school type, have 0 for each (see example here): [school-groups-2022-10-21t15-58-45z.csv](https://github.com/Energy-Sparks/energy-sparks/files/984 …

Export detail for school groups

---

app/assets/javascripts/analysis.js
app/assets/javascripts/content.js
app/helpers/chart_helper.rb
app/views/management/schools/_overview_charts.html.erb

Currently we load all charts on the adult and mgt dashboard on page load.  But potentially 2 of them will never be displayed if a user doesn't switch tabs.
This pr covers changing how we load charts on the dashboards:

Optimise chart loading on dashboards

---

app/services/aggregate_school_service.rb
app/services/alerts/generate_and_save_alerts.rb
app/services/alerts/generate_and_save_alerts_and_benchmarks.rb
app/services/content_batch.rb
spec/services/aggregate_school_service_spec.rb
spec/services/alerts/generate_and_save_alerts_and_benchmarks_spec.rb

At the moment in the Content Batch / SchoolBatchRunJob we have separate steps for:
- GenerateAndSaveAlerts
- GenerateAndSaveBenchmarks
Both of these services:
- loop through a list of alerts
- run them for a specific school
- insert new records into the database
This PR creates a new service that combines these steps into one.

Optimise the Alert and Benchmark Generation Service

---

app/assets/javascripts/analysis.js
app/controllers/schools/charts_controller.rb
app/helpers/chart_helper.rb
app/models/chart_data.rb
app/views/admin/analysis/generic_chart_template.html.erb
app/views/management/schools/_overview_charts.html.erb
app/views/management/schools/report.html.erb
app/views/pupils/analysis/show.html.erb
app/views/schools/analysis/_chart_name.html.erb
app/views/schools/find_out_more/_chart.html.erb
app/views/schools/usage/show.html.erb
app/views/shared/_chart_with_controls.html.erb

The ChartManager is responsible for generating some of the advice that is added displayed above and below the charts on the advice pages. This includes both static and dynamic text, with the latter including content generated by running additional analysis code.  By default it is always generated, but there is an option to disable it.
This wasn't being used by the application, possibly because we used to have a mixture of pages that did rely on adding some of this content dynamically to the web page. This was done in the old "Expert Analysis" pages which have now largely been removed. None of the other pages on the site now rely on fetching the `advice_header` and `advice_footer` content from the chart JSON.
This PR changes how we run the charts so by default we no longer generate the …

Disable advice generation on charts

---

spec/system/admin/school_groups_spec.rb

Fix use of Timecop to freeze time before page load not just before test. Caused test failure (once) - test was still brittle though and needs fixing

Small time-based test fix

---

app/controllers/schools/analysis_controller.rb

There are a couple of the analysis pages which don't work properly in Welsh. This is because in a couple of places they are reparsing data from charts to build page content, rather than using the underlying variables from the alert classes.
This parsing fails when the pages are generated in Welsh, because the chart series end up being translated.
This PR wraps the calls to the analytics that generates the content in an `I18n.with_locale` block, so they're run using an English locale. This avoids the bug until we've properly translated the pages.
This also avoids small sections of the page, eg. references to units being formatted in Welsh. At the moment the content that does work can end up having a mixture of English and Welsh phrases, which isn't ideal.
We've already got a disclaimer on …

Request advice pages in English only

---

app/services/schedule_data_manager_service.rb

This PR adds a minimum 4 day offset for all loaded temperature schedule data.  This is related to changes in https://github.com/Energy-Sparks/energy-sparks_analytics/pull/351

Fix temperature range error for targets

---

app/classes/targets/progress_summary.rb
app/controllers/concerns/school_progress.rb
app/controllers/schools_controller.rb
app/helpers/targets_helper.rb
app/models/school.rb
app/models/school_target.rb
app/views/management/schools/targets/_progress_notice.html.erb
app/views/management/schools/targets/_set_new_target.html.erb
app/views/schools/show.html.erb
config/locales/views/schools/schools.yml
spec/models/school_spec.rb
spec/system/schools/dashboard/school_targets_spec.rb

We have some schools that are coming to the end of their energy saving target period.
This is first of some improvements to application views, prompts and other functionality for expired targets.
This PR has:
* new methods on School and School Target to identify expired vs current targets, with tests
* revised logic for school dashboard so that we don't show progress reports for expired targets
* adds a new dashboard prompt to set a new target if the current one has expired

Revise dashboard for expired targets

---

Gemfile
Gemfile.lock
app/controllers/schools/progress_controller.rb
app/services/targets/generate_progress_service.rb
app/views/schools/progress/index.html.erb
spec/services/targets/generate_progress_service_spec.rb
spec/system/schools/progress_spec.rb

The progress report for a school target is broken when a target has expired as the analytics is returning >12 months of data, leading to some duplicate columns in the tables.
This PR
* picks up changes in the analytics which key the `TargetsProgress` data using dates, not strings
* changes the `Targets::GenerateProgressService` to use the new interface
* changes the `ProgressController` to use the interface
* updates the templates so that we only report the first 12 months of data, which is the period for the target
* for both the `Targets::GenerateProgressService` and `ProgressController` we now key the data via `reporting_month`. For current targets this is just the current month. But if the target has expired, it uses the last month of data for the data. This avoids us displaying …

Fix progress reporting when target is expired

---

app/models/observation.rb
spec/models/observation_spec.rb
spec/system/temperature_recordings_spec.rb

Allow schools to record activities for future dates, e.g. as part of a campaign pledge.

Allow future observations

---

app/controllers/schools/benchmark_reports_controller.rb
app/controllers/schools/benchmark_results_controller.rb
app/views/schools/benchmark_reports/index.html.erb
app/views/schools/benchmark_reports/show.html.erb
app/views/schools/benchmark_results/show.html.erb
app/views/schools/reports/index.html.erb
config/routes.rb

We've had some issues with the benchmark generation recently. It's hard to debug because of lack of easy access to the result / error data.
This PR is a quick and dirty copy of the similar reports that we have for alerts and equivalences, making it possible to browse the data as an admin.

Add admin reports to view benchmark result data

---

app/views/schools/school_targets/_bullet_chart.html.erb
app/views/schools/school_targets/_limited_data.html.erb
spec/system/schools/school_targets_spec.rb

Feedback has been that its not clear what the bullet charts are showing on the school targets page.
So for now we'll remove then in favour of just showing their % progress.

Remove bullet charts from school target overview

---

app/models/school_target.rb
app/services/targets/generate_progress_service.rb
db/migrate/20221110133928_add_progress_reports_to_school_target.rb
db/schema.rb
spec/models/school_target_spec.rb
spec/services/targets/generate_progress_service_spec.rb

Save a full copy of the progress report for each school target to the School Target model
* Adds new JSONB columns to store the progress reports
* Updates the `GenerateProgressService` to save the progress for each fuel type, alongside the existing summary
* Adds support to `SchoolTarget` for turning the saved JSON data back into a `TargetsProgress` instance which can be used by the reports
* Removed feature flag from the service
* Tests for the above
This should add little overhead as the full progress report has to be generated anyway and this is cached in the `GenerateProgressService`.
This PR proceeds further changes to the feature, e.g. using cached progress report for expired target and removal of the feature flags

Save target progress report to School Target

---

app/models/calendar_event.rb
app/views/admin/calendars/_regional_calendars.html.erb

Make it easier for admins to see at a glance how far ahead the term dates are for a regional calendar.

Add last term date to calendar overview

---

app/views/schools/school_targets/_limited_data.html.erb

If we're showing the `_limited_data.html.erb` partial then we can't currently provide a progress report for a school, so removing this link as it shouldn't be shown. Avoids users seeing an error.
Am leaving in the helper for now as I continue to rework these pages.

Remove link to report if we have limited target data

---

app/controllers/admin/school_groups_controller.rb
app/controllers/admin/schools/notes_controller.rb
app/models/note.rb
app/models/school_group.rb
app/views/admin/school_groups/_form.html.erb
app/views/admin/school_groups/_issues.html.erb
app/views/admin/schools/notes/_form.html.erb
app/views/admin/schools/notes/_fuel_type.html.erb
app/views/admin/schools/notes/_header.html.erb
app/views/admin/schools/notes/_note.html.erb
app/views/admin/schools/notes/_owned_by.html.erb
app/views/admin/schools/notes/edit.html.erb
app/views/admin/schools/notes/index.html.erb
app/views/admin/schools/notes/new.html.erb
app/views/admin/schools/notes/show.html.erb
db/migrate/20221114113102_add_default_notes_admin_user_to_school_groups.rb
db/migrate/20221114133851_add_owned_by_to_notes.rb
db/schema.rb
spec/models/note_spec.rb
spec/system/admin/school_groups_spec.rb
spec/system/admin/schools/notes_spec.rb

When an issue is recorded or updated it should be possible to assign it to an EnergySparks admin who will be responsible for resolving it. This card covers:

Assign Issues to Users

---

app/views/admin/school_groups/_issues.html.erb
app/views/admin/school_groups/_onboarding_schools.html.erb
app/views/admin/school_groups/_removed_schools.html.erb
app/views/admin/schools/issues/_form.html.erb
app/views/admin/schools/issues/edit.html.erb
app/views/admin/schools/issues/new.html.erb
spec/support/admin_school_group_onboardings.rb
spec/system/admin/school_groups_spec.rb
spec/system/admin/school_onboarding_spec.rb
spec/system/admin/schools/issues_spec.rb

This PR does the following:
- Add "Not applicable" label to select for fuel type
- Add issue links to Onboarding and Removed
- Add school name to issues tab
- Also adds some further styling to issue form to have the same styling as when viewing
- Also removes the ability to be able to set the issue type (issue or note) on create as it simplifies form
- Makes tests more obvious in terms of the setup flow

2620 Issues Improvements

---

app/controllers/concerns/dashboard_timeline.rb
app/models/issue.rb
app/models/observation.rb
app/models/school.rb
app/models/school_group.rb
app/models/school_onboarding.rb
app/models/school_target.rb
app/views/schools/observations/timeline/_school_target.html.erb
db/migrate/20221123143039_add_target_id_to_observation.rb
db/schema.rb
lib/tasks/deployment/20221123145618_add_school_target_observations.rake
spec/models/school_target_spec.rb
spec/system/schools/dashboard/timeline_spec.rb
spec/system/schools/school_targets_spec.rb

Adds support for including school targets into the schools timeline of activities
* adds a new `:school_target` `Observartion` type and links to `SchoolTarget` model
* automatically add an Observation when creating a target
* add template for displaying school target observations in timeline
* exclude these observations from the custom timeline we should on the expired target page
* adds an after party task to create observations for all existing targets, to populate the database

Add school targets to main school timeline

---

app/controllers/admin/amr_data_feed_configs_controller.rb
app/models/amr_data_feed_config.rb
app/views/admin/amr_data_feed_configs/edit.html.erb
app/views/admin/amr_data_feed_configs/show.html.erb
app/views/admin/reports/amr_data_feed_import_logs/index.html.erb
db/schema.rb

To support review of existing data feed configs, this PR:

Data Feed Config Changes

---

config/initializers/rollbar.rb

Add ActiveRecord::RecordNotFound exceptions to ignore list.
Rollbar currently logs these as warnings. But we're getting quite a few of them and they're either from crawlers accessing scoreboards or schools that no longer exist, or crawlers/bots  requesting random ids. So lets exclude for now.
https://docs.rollbar.com/docs/ruby#exception-level-filters

Add ActiveRecord::RecordNotFound to filter

---

spec/system/activity_types_spec.rb
spec/system/admin/issues_spec.rb
spec/system/intervention_types_spec.rb

Background: This build failed (which passed locally): https://github.com/Energy-Sparks/energy-sparks/actions/runs/3628959858/jobs/6120599772
For the issues tests, I am wondering if sometimes that let! and before statements, if in the same block, do not always execute in their given order. So I am thinking in the case of the issues tests, that sometimes the test data might not have been setup before the page loaded.
./spec/system/activity_types_spec.rb:49 & ./spec/system/intervention_types_spec.rb:55
For these two, it could be because when doing a search, postgres is calculating a rank for the results, and then ordering by this rank. Wonder if this can be different sometimes.
./spec/system/activity_types_spec.rb:86
For this one, I think it could be a similar issue as for issues tests. i.e. …

Fix flickering tests

---

app/models/staff_role.rb
app/views/schools/contacts/_form.html.erb
app/views/schools/users/_form.html.erb
spec/models/staff_role_spec.rb

We have a few places where we use the same sort pattern for the staff role dropdown.
```
<%= f.input :staff_role_id, label: t('schools.contacts.form.labels.role'), collection: StaffRole.all.map { |staff_role| [staff_role.translated_title, staff_role.id] }.sort %>
```
This pr extracts this to a method

Add helper for staff role dropdown

---

app/views/alert_mailer/alert_email.html.erb
config/environments/development.rb
config/locales/mailers/mailer.yml

This pr adds some text to the alert mailer 
Get your pupils involved
Energy Sparks offers in-person and virtual half day education workshops and assemblies to participating schools across the UK.
Button - Book a workshop (directing them to https://energysparks.uk/education-workshops
Need more help
Energy Sparks offers online virtual energy audits and on-site energy audits to support you to develop your school's energy action plan.
Button - Book an audit (directing them to https://energysparks.uk/energy-audits)

Add a prompt to book a pupil workshop in the weekly alert text

---

app/views/schools/meters/index.html.erb

Found this (tiny thing) when working on something else.
Just thought the button ought to be inside the if statement (see code!). However I don't think it'd make much difference anyway, as the whole thing is only displayed if a user is an admin.

Fix logic in school meters page

---

.ebextensions/cloudwatch.config

Update CloudWatch configuration to add disk space usage and availability metrics, this will let us monitor disk usage on test and production machines.

Add disk usage logging

---

Gemfile
Gemfile.lock

Downgrade sass-rails and sprockets gems to avoid segfaults.
See:
https://github.com/sass/sassc-ruby/issues/207#issuecomment-1058148376

Downgrade sass-rails and sprockets

---

app/assets/stylesheets/advice_page.scss
app/assets/stylesheets/application.scss
app/controllers/schools/advice/baseload_controller.rb
app/helpers/advice_page_helper.rb
app/views/schools/advice/_advice_page.html.erb
app/views/schools/advice/_section_title.html.erb
app/views/schools/advice/baseload/analysis.html.erb
config/locales/common.yml
config/locales/views/advice_pages/advice_pages.yml
spec/helpers/advice_page_helper_spec.rb
spec/system/schools/advice_pages_spec.rb

This PR expands on the analysis page template:
- clickable table of contents at the top
- scroll top adjustment for the section titles in the advice pages
- month/year text for the chart description
- test that the analysis tab renders
- move the page title to sit with the content tabs
- add back-to-top links for each section

2761 further baseload advice page analysis

---

app/controllers/admin/advice_pages/activity_types_controller.rb
app/models/advice_page.rb
app/models/advice_page_activity_type.rb
app/views/admin/advice_pages/activity_types/show.html.erb
app/views/admin/advice_pages/index.html.erb
config/routes.rb
db/migrate/20230105162523_create_advice_page_activity_type_join_table.rb
db/schema.rb
spec/system/admin/advice_pages_spec.rb

Updates the AdvicePage model to have an associated list of activity types.
Provides a simple admin interface for managing the activities, with a priority number. The interface is basic, but similar to what is used to manage similar relationships across the site.
This will be used to recommend activities from the advice page Insights tab.

Allow advice pages to have associated activities

---

app/assets/javascripts/analysis.js

Testing some of the charts I was getting a Javascript error about an undeclared variable.
Tweaked the javascript to add `var label` and everything seems OK now. Am unsure why this isn't causing problems elsewhere, but it might depend on the specific chart and the available axis choices.
This should be safe to merge.

Declare label var

---

app/models/alert_type_rating_content_version.rb
spec/models/alert_type_rating_content_version_spec.rb

Fixes the transifex synchronisation of content for email and sms alerts:
* add all the variables to `tx_valid_attribute` methods, checking if email or sms is active
* configure `email_title` and `sms_content` as templated values, so we do variable escaping correctly
* add tests to ensure the fields are correctly serialised when the sms and email content is marked as active
* revise existing spec to check that sms and email active content ratings are serialised

Fix synchronisation of sms and email fields

---

package.json
yarn.lock

Upgrades the fontawesome node package so we can use FA 6 rather than 5. This gives us 400+ more available icons. See: https://fontawesome.com/v6/search?m=free

Upgrade fontawesome node package from 5 to 6

---

app/assets/stylesheets/advice_page.scss
app/assets/stylesheets/analysis.scss
app/controllers/concerns/advice_pages.rb
app/controllers/schools/advice/baseload_controller.rb
app/helpers/application_helper.rb
app/models/meter.rb
app/views/schools/advice/_advice_page.html.erb
app/views/schools/advice/baseload/_long_term_trends_table.html.erb
app/views/schools/advice/baseload/_meter_breakdown_table.html.erb
app/views/schools/advice/baseload/_seasonal_variation_breakdown_table.html.erb
app/views/schools/advice/baseload/_seasonal_variation_table.html.erb
app/views/schools/advice/baseload/_weekday_variation_breakdown_table.html.erb
app/views/schools/advice/baseload/_weekday_variation_table.html.erb
app/views/schools/advice/baseload/analysis.html.erb
config/locales/views/advice_pages/baseload.yml
spec/controllers/concerns/advice_pages_spec.rb
spec/system/schools/advice_pages/baseload_spec.rb

* show average annual kw values for school and benchmark, not the kwh usage across the whole year
* cache the baseload services to take advantage of cached values
* fix formatting of weekly variation table (extra column showing `r2`?)
* add `format_unit` helper and use that rather than version used on school target report
* fix CSS for `table-with-totals`, so head row isn't selected
* fix padding around tab page content and chart title/sub-title
* fix long term trend table to show `kw` not `kwh` and update table columns and units used when formatting
* change "Whole school, aggregated meters" to "All meters"
* label meters according to their name, not just the mpan
* change meter breakdown table so last round isn't a sum. It should be the average usage for the whole school != the sum of …

Initial round of bug fixes for the baseload analysis

---

app/assets/stylesheets/advice_page.scss
app/controllers/schools/advice/advice_base_controller.rb
app/controllers/schools/advice/baseload_controller.rb
app/helpers/advice_page_helper.rb
app/services/schools/advice/baseload_service.rb
app/views/schools/advice/baseload/_comparison.html.erb
app/views/schools/advice/baseload/_current_baseload.html.erb
app/views/schools/advice/baseload/_what_is_baseload.html.erb
app/views/schools/advice/baseload/insights.html.erb
config/locales/views/advice_pages/advice_pages.yml
config/locales/views/advice_pages/baseload.yml
spec/services/schools/advice/baseload_service_spec.rb
spec/system/schools/advice_pages/baseload_spec.rb

Implements the initial version of the baseload insights section:
- add definition
- add current baseload
- add comparison
- link to benchmark comparison for school
TODO:
Further work to be done in other PRs to handle limited data.

2762 integrate the baseload advice page insights section

---

app/controllers/admin/advice_pages_controller.rb
app/models/advice_page.rb
spec/system/schools/advice_pages/advice_pages_spec.rb

There was already a link from the admin pages to the advice page management, so this PR just adds a test (and also ensures that the index page list is sorted).

Test link from admin pages and sort index by key

---

app/controllers/schools/advice/advice_base_controller.rb
app/controllers/schools/advice_controller.rb
app/views/schools/advice/advice_base/error.html.erb
config/locales/views/advice_pages/advice_pages.yml
spec/system/schools/advice_pages/advice_pages_spec.rb

When an error occurs in the advice pages, we rescue the exception in the advice pages base class, log it to Rollbar, and show a styled error page (which includes the usual advice page navigation).

2863 error handling for advice page controllers

---

app/controllers/schools/advice/advice_base_controller.rb

Please can we try this out for the advice section? It stops content disappearing under the top nav. It's in place in other sections (transport, issues, data sources... etc).

Prevent content disappearing under the top nav

---

app/assets/javascripts/trix_customisations.js

Change the validation for links to properly support relative paths.
Required to support links to other analysis pages and page sections from the advice page editor.

Allow relative links

---

app/components/chart_component.html.erb
app/components/chart_component.rb
app/views/schools/advice/baseload/_analysis.html.erb
app/views/schools/advice/baseload/_meter_breakdown_charts.html.erb
spec/components/chart_component_spec.rb

A chart component allows charts to be added to a page, specifying a chart type, school, and chart config.
Some other parameters (analysis controls, zoom, html class) can also be provided.
The title, subtitle, header and footer text can be optionally added - implemented as slots.
The title tag has an id to enable linking to that specific chart.

Created chart component and replaced charts on baseload analysis

---

app/assets/javascripts/usage_charts.js

This is a PR to update the javascript that displays usage charts so that multiple charts can be displayed on the same page.
Previously, the usage js functions relied on element ids (#period, #supply etc) to fetch arguments from the page markup and render charts. The PR changes to using named elements within a specified section of the page so that the chart, config and form settings can appear multiple times.
Duplicate ids shouldn't really be rendered in the page (not valid html) but that could be cleaned up in a separate PR if necessary (possibly using prefixes for any form tag input elements).

Update js to handle fields within chart section

---

app/assets/stylesheets/advice_page.scss
app/components/notice_component.html.erb
app/components/notice_component.rb
app/components/notice_component.scss
app/helpers/application_helper.rb
app/views/schools/advice/_advice_page.html.erb
app/views/schools/advice/_advice_tabs.html.erb
app/views/schools/advice/_data_warning.html.erb
app/views/schools/advice/_nav.html.erb
app/views/schools/advice/advice_base/error.html.erb
app/views/schools/advice/advice_base/insights.html.erb
app/views/schools/advice/baseload/_assessment.html.erb
app/views/schools/advice/baseload/_what_is_baseload.html.erb
app/views/schools/advice/show.html.erb
spec/components/notice_component_spec.rb

This PR implements the Notice Component and moves existing notices over to use the component.
As part of this, I've created a new components helper, so you are able to write the following (which I think reads better):
`<%= component 'notice', status: :negative do |c| %>
`
Rather than:
`<%= render(NoticeComponent.new(status: :negative)) do |c| %>`
Happy to move other components over to using it as part of this PR if all ok.

Create notice view component

---

app/assets/javascripts/analysis.js
app/components/chart_component.html.erb
app/models/chart_data_values.rb
app/views/admin/analysis/generic_chart_template.html.erb
app/views/pupils/analysis/show.html.erb
app/views/schools/advice/baseload/_analysis.html.erb
app/views/schools/analysis/_chart_name.html.erb
config/locales/views/advice_pages/baseload.yml
spec/models/chart_data_values_spec.rb

Our existing chart templates and javascript support dynamically changing the chart titles and subtitles. This is currently used:
- on the pupil charts. Here the title changes as you drill down, and some of the subtitles change to reflect the dates being viewed
- on the existing analysis pages, which have subtitles that change to reflect the date range being viewed
- some admin only pages which have both dynamic titles and subtitles
The text injected into those charts is generated by the analytics.
On the new advice pages we don't (currently) want to dynamically change the whole title and subtitle, but we do want to ensure that dates in the subtitles update as a user moves forward and backward on a chart.
This PR does several things:
- refactors the existing templates and JS code so that …

Implement dynamic chart date ranges for subtitles

---

app/controllers/schools/advice/advice_base_controller.rb
app/views/schools/advice/_nav.html.erb
app/views/schools/advice/advice_base/error.html.erb
app/views/schools/advice/advice_base/no_fuel_type.html.erb
app/views/schools/advice/advice_base/not_enough_data.html.erb
config/locales/views/advice_pages/advice_pages.yml
spec/factories/advice_pages.rb
spec/support/advice_pages_shared_contexts.rb
spec/system/schools/advice_pages/advice_pages_spec.rb
spec/system/schools/advice_pages/total_energy_use_spec.rb

Enforces a consistent approach for checking whether we have the right data available to run some analysis across all the advice page controllers.
This PR changes the base class so that:
- if a school doesn't have the right fuel type, we render a custom error page. This is only likely to happen if all the meters for a specific fuel type has been disabled, but a user has previously bookmarked a url. Ensures we provide a more helpful message
- if we can't run the analysis because we don't have enough data, then we render a custom error page which will ideally indicate when the analysis will be available
- improves the existing custom error handling to preserve the page tabs as these should have already been set in the request cycle. The error page also now returns a 500 status code …

Add checks for fuel type and enough data to advice base controller

---

app/controllers/schools/advice/advice_base_controller.rb
app/controllers/schools/advice/baseload_controller.rb
app/controllers/schools/advice/electricity_intraday_controller.rb
app/views/schools/advice/electricity_intraday/_analysis.html.erb
config/locales/views/advice_pages/electricity_intraday.yml
spec/support/advice_pages_shared_contexts.rb
spec/system/schools/advice_pages/electricity_intraday_spec.rb

This PR implements the analysis tab of the electricity intraday advice page, with charts and text.
It includes support for the Analysable checks for date ranges.
It also factors out some support methods into the AdviceBaseController for setting up analysis dates.

Initial analysis page layout and first chart

---

app/controllers/application_controller.rb
spec/controllers/application_controller_spec.rb

Error during login when trying to redirect to a locale subdomain, and the session[:user_return_to] was not set.

Handle missing user_return_to in session during redirects

---

spec/system/meter_management_spec.rb

Looks like some of the tests were calling the sandbox api rather than being properly stubbed out.

Stub out n3rgy api

---

app/controllers/schools/advice/electricity_long_term_controller.rb
app/services/schools/advice/long_term_usage_service.rb
app/views/schools/advice/baseload/_comparison.html.erb
app/views/schools/advice/baseload/_current_baseload.html.erb
app/views/schools/advice/electricity_long_term/_analysis.html.erb
app/views/schools/advice/electricity_long_term/_analysis_comparison.html.erb
app/views/schools/advice/electricity_long_term/_comparison.html.erb
app/views/schools/advice/electricity_long_term/_current_usage.html.erb
app/views/schools/advice/electricity_long_term/_insights.html.erb
app/views/schools/advice/electricity_long_term/_insights_intro.html.erb
config/locales/views/advice_pages/advice_pages.yml
config/locales/views/advice_pages/baseload.yml
config/locales/views/advice_pages/electricity_long_term.yml
spec/system/schools/advice_pages/electricity_long_term_spec.rb

Implements the insights section for the electricity long term use page
- adds the introductory text in a notice
- adds table with summary of usage over last 12 months
- adds comparison with exemplar
- adds "next steps" text
Also tweaks a couple of keys used in the baseload yml so they're shared across advice pages

Electricity long term use insights

---

app/helpers/advice_page_helper.rb
app/views/schools/advice/baseload/_meter_breakdown_table.html.erb
app/views/schools/advice/baseload/_seasonal_variation_breakdown_table.html.erb
app/views/schools/advice/baseload/_weekday_variation_breakdown_table.html.erb

Change default sort order for tables on baseload analysis:
- meter breakdown sorted by % baseload (desc)
- seasonal and intraday variation sorted by estimated saving (desc)

Sorting of meter tables

---

app/models/school.rb
spec/models/intervention_type_spec.rb
spec/models/school_spec.rb
spec/system/activity_types_spec.rb

We have some flickering tests in the suite. This PR aims to fix a couple of them
* When returning activities and observations required in the academic year, order them by increasing creation date, rather than leaving the order undefined
* Revise the school spec to adjust `at` value for third intervention. Using the same value leaves us open to an ordering problem
* For the intervention type search use `match_array` rather than `eq` as we expect both results. I would normally expect the exact match to be first, but it's possible the postgres stemming ignores that, leaving us with two records that might end up having identical search rank.

Revise ordering to reduce likelihood of tests flickering

---

app/views/schools/advice/electricity_out_of_hours/_analysis.html.erb
app/views/schools/advice/electricity_out_of_hours/_analysis_table.html.erb
app/views/schools/advice/electricity_out_of_hours/_insights.html.erb
app/views/schools/advice/electricity_out_of_hours/_insights_table.html.erb
app/views/schools/advice/gas_out_of_hours/_analysis.html.erb
app/views/schools/advice/gas_out_of_hours/_analysis_table.html.erb
app/views/schools/advice/gas_out_of_hours/_insights.html.erb
app/views/schools/advice/gas_out_of_hours/_insights_table.html.erb
config/locales/views/advice_pages/electricity_out_of_hours.yml
config/locales/views/advice_pages/gas_out_of_hours.yml

* The community use section wasn't working (no variables injected into the page templates)
* Reworked YAML slightly to structure into named sections rather than "one"/"two" paragraphs
* Add missing links to the school comparison pages
* Move the table below the pie chart

Out of hours usage page changes

---

app/helpers/advice_page_helper.rb
app/views/schools/advice/baseload/_analysis.html.erb
app/views/schools/advice/baseload/_long_term_trends_table.html.erb
config/locales/views/advice_pages/advice_pages.yml

Adds a "(partial") note next to years with limited data. Extracted the logic into a helper so it can potentially be reused elsewhere/

Add notes about partial years to long term trend table

---

.github/workflows/rubyonrails.yml

We currently check status of i18n files whilst running the specs.
Proposing that we change the workflow to explicitly run the `i18n-tasks health` task before the specs so that they fail early, rather than at the end of the build.
At the moment I've left the rspec test in place, but this could possibly be removed now. In testing I've noticed that its takes up to 45 seconds to run the i18n-spec file so we probably don't want to run these checks twice.

Run i18n tasks earlier in build

---

app/views/schools/advice/electricity_intraday/_analysis.html.erb
config/locales/views/advice_pages/electricity_intraday.yml
spec/system/schools/advice_pages/electricity_intraday_spec.rb

* Removes the dynamic dates in the subtitle for an intraday chart.
* Revises title of first chart
* Parameterise description of benchmark schools using school type.
* Improved the rspec to check the right charts are on the page.
The chart framework doesn't return the correct date range for intraday charts. Am unclear how to fix that currently without potentially impacting other code. Because in this case the chart date ranges are clearly labelled as series, I've removed the dates on the chart for now.

Remove chart subtitle for intraday chart plus cosmetic fixes

---

Gemfile
Gemfile.lock
app/controllers/schools/advice/advice_base_controller.rb
app/controllers/schools/advice/base_long_term_controller.rb
app/controllers/schools/advice/total_energy_use_controller.rb
app/helpers/advice_page_helper.rb
app/views/management/schools/_overview_data.html.erb
app/views/schools/advice/advice_base/analysis.html.erb
app/views/schools/advice/advice_base/insights.html.erb
app/views/schools/advice/electricity_long_term/_comparison.html.erb
app/views/schools/advice/electricity_long_term/_insights_benchmark_table.html.erb
app/views/schools/advice/gas_long_term/_comparison.html.erb
app/views/schools/advice/gas_long_term/_insights_benchmark_table.html.erb
app/views/schools/advice/total_energy_use/_analysis.html.erb
app/views/schools/advice/total_energy_use/_insights.html.erb
config/i18n-tasks.yml
config/locales/views/advice_pages/heating_control.yml
config/locales/views/advice_pages/total_energy_use.yml
spec/system/schools/advice_pages/advice_pages_spec.rb
spec/system/schools/advice_pages/total_energy_use_spec.rb

Adds the Total Energy Use page
This page has a combination of information from other sources, so there's some reuse of partials, etc.
* Updates advice base controller to allow subtitles and "next steps" to be optional
* Removes some unneeded variables in the long term controller (spotted while testing)
* Incorporates the table from the school dashboard, so reuses partial and existing code. Partial has been updated to allow cost saving to be hidden
* Extracts partials for the tables from electricity/gas long term analysis so they can be reused
Page uses the new advice page translation helper (`advice_t`) to reduce length of keys. However I found that this was tripping up `i18n-tasks`, so I have also:
* revised the helper to require passing in the page key, e.g. `total_energy_use` rather …

Implement total energy use page

---

app/views/schools/advice/electricity_out_of_hours/_analysis.html.erb
app/views/schools/advice/electricity_out_of_hours/_insights_table.html.erb
app/views/schools/advice/gas_out_of_hours/_analysis.html.erb
app/views/schools/advice/gas_out_of_hours/_insights_table.html.erb
config/locales/views/advice_pages/electricity_out_of_hours.yml
config/locales/views/advice_pages/gas_out_of_hours.yml

This PR adds some fixes & updates to the out of hours pages following review:

Out of Hours Usage Pages Review Fixes

---

app/controllers/schools/advice/electricity_recent_changes_controller.rb
app/controllers/schools/advice/gas_recent_changes_controller.rb
app/views/schools/advice/electricity_recent_changes/_insights.html.erb
app/views/schools/advice/electricity_recent_changes/_your_recent_electricity_use_table.html.erb
app/views/schools/advice/gas_recent_changes/_insights.html.erb
app/views/schools/advice/gas_recent_changes/_your_recent_gas_use_table.html.erb
config/locales/views/advice_pages/advice_pages.yml
config/locales/views/advice_pages/gas_recent_changes.yml

This PR covers a few updates & fixes raised during the review of the new Recent Changes Page:

Recent Progress Page Review Fixes

---

app/views/schools/advice/gas_long_term/_analysis_comparison.html.erb
config/locales/views/advice_pages/gas_long_term.yml
spec/system/schools/advice_pages/gas_long_term_spec.rb

The benchmarking data for the long term trend chart is not robust enough for display on the chart. So removing this for now.

Remove comparison with benchmark chart from gas long term page

---

app/controllers/onboarding/consent_controller.rb
app/controllers/schools/consents_controller.rb
app/mailers/alert_mailer.rb
app/mailers/application_mailer.rb
app/mailers/bill_request_mailer.rb
app/mailers/consent_grant_mailer.rb
app/mailers/consent_request_mailer.rb
app/mailers/locale_mailer.rb
app/mailers/target_mailer.rb
app/models/contact.rb
app/services/alerts/generate_email_notifications.rb
app/services/schools/bill_request_service.rb
app/services/schools/consent_request_service.rb
app/services/targets/target_mailer_service.rb
config/locales/cy/mailers/mailer.yml
spec/mailers/alert_mailer_spec.rb
spec/mailers/bill_request_mailer_spec.rb
spec/mailers/consent_grant_mailer_spec.rb
spec/mailers/consent_request_mailer_spec.rb
spec/mailers/previews/bill_request_mailer_preview.rb
spec/mailers/previews/consent_grant_mailer_preview.rb
spec/mailers/previews/consent_request_mailer_preview.rb
spec/mailers/previews/target_mailer_preview.rb
spec/services/schools/bill_request_service_spec.rb
spec/services/schools/consent_request_service_spec.rb
spec/services/targets/target_mailer_service_spec.rb

Emails should be sent with a users preferred locale.
This PR introduces a LocaleMailer base class, extended by the mailers that need to be locale aware. A constructor method allow the mailers to be constructed with a collection of users, which are split into groups by preferred locale, and sent with the appropriate i18n locale. Another constructor allows mailers to be created for a Contact, to support the alert emailers (though Contacts will eventually all have Users, so this constructor will be removed).
The PR covers the mailers for Alerts, BillRequests, ConsentGrants, ConsentRequests, and Targets.
The Devise emails and Onboarding emails will be covered in separate PRs.

Use locale mailer and yield block to send locale-specific emails

---

app/models/chart_data_values.rb
spec/models/chart_data_values_spec.rb

Fixes a bug introduced in my earlier PR to update the colours on benchmark charts.
When a chart has multiple fuel types, the new code wasn't assigning the right colours for each fuel type. So this PR fixes that and introduces a spec.

Fix bug in multiple fuel benchmark series colours

---

app/assets/stylesheets/base.scss
app/models/meter.rb
app/views/admin/data_sources/show.html.erb
app/views/admin/issues/_issue.html.erb
app/views/admin/issues/_issues_list.html.erb
app/views/admin/issues/_meters.html.erb
app/views/admin/issues/index.html.erb
app/views/admin/school_groups/_schools_tabs.html.erb
app/views/admin/school_groups/show.html.erb
app/views/schools/meters/show.html.erb
spec/system/admin/data_sources_spec.rb
spec/system/admin/school_groups_spec.rb

Revises the list of "Issues" on the manage school group page so that there are separate sortable columns for:
* school name
* fuel type
The trello card also specifies adding a data source column, but I'm not sure this makes sense with the model we have, as an issue can have multiple meters and each can have a data source. So an issue could have multiple data sources effectively, which would not work well with a sortable column.
So where meters are listed under the issue title, I've added a tooltip to also show the meter data source. This links through to the meter, where the data source can be accessed.
Also as part of this ticket, the issues lists for school and school group now include both open and closed issues.

Add extra columns to school issue list

---

app/controllers/application_controller.rb
app/helpers/default_url_options_helper.rb
app/mailers/application_mailer.rb
app/mailers/energy_sparks_devise_mailer.rb
spec/mailers/bill_request_mailer_spec.rb
spec/system/password_reset_spec.rb

When emails are sent using a specific locale, the links in the email should use the same locale subdomain.
The functionality to format links is in the url helpers, but call a default_url_options helper method which can override to supply a specific host, dependent on locale.
If no host names are available in the APPLICATION_HOST or WELSH_APPLICATION_HOST env vars, we just use the default url options.

Factor out default url options and test from bill request email

---

.tx/config

Just updates the transifex config with the finished advice pages.
Has been used to push text to transifex.

Rebuild tx config with finished pages

---

app/assets/stylesheets/nav.scss
app/views/admin/school_groups/index.html.erb
app/views/admin/school_groups/show.html.erb
app/views/shared/_manage_school.html.erb
config/locales/views/shared/shared.yml
spec/system/admin/school_groups_spec.rb
spec/system/schools/dashboard/manage_school_spec.rb

- Displays default issues admin against school group & links to issues for user
- Adds school group to manage school menu & tidies spec. Also makes the menu scrollable as it was dropping down out of view.
- Adds issues admin to school group index page (if page is wide enough)

Make issues admin user more visible

---

app/controllers/admin/school_groups_controller.rb
app/controllers/admin/school_onboardings/configuration_controller.rb
app/models/school_group.rb
app/models/school_onboarding.rb
app/views/admin/school_groups/_form.html.erb
app/views/admin/school_onboardings/configuration/edit.html.erb
db/migrate/20230224111422_add_country_to_school_groups.rb
db/migrate/20230224111422_add_default_country_to_school_groups.rb
db/migrate/20230224111633_add_country_to_school_onboardings.rb
db/schema.rb
spec/system/admin/school_groups_spec.rb
spec/system/admin/school_onboarding_spec.rb

The onboarding process will send emails in multiple languages if the onboarding is for a school in Wales.
To support this, the onboarding has a country specified. The country is initially set according to a default country on the school group.
The country fields are implemented as enums, sharing the same values as the country field on the School model.

Add country to school group and onboarding

---

app/mailers/locale_mailer.rb
app/mailers/onboarding_mailer.rb
app/models/school_onboarding.rb
app/views/onboarding_mailer/onboarding_email.html.erb
app/views/onboarding_mailer/onboarding_email_content.html.erb
app/views/onboarding_mailer/reminder_email.html.erb
app/views/onboarding_mailer/reminder_email_content.html.erb
config/locales/cy/mailers/mailer.yml
spec/mailers/onboarding_mailer_spec.rb
spec/models/school_onboarding_spec.rb

During onboarding, we don't yet have users set up in the system, so we don't know what their preferred language is. If the onboarding is for a Welsh school, then we will send emails in both languages - the subject line and body will contain the English and Welsh text (though the overall layout, headers etc will be the English ones).

Onboarding emails have subject and body in 2 languages if Welsh enabled

---

spec/system/schools/advice_pages/baseload_spec.rb

Fixes up a system spec: the expected content is no longer included on the page, its been replaced by the modal.

Fix up failing spec

---

app/models/advice_page.rb
app/models/alert_type.rb
app/models/school_group.rb
app/models/school_onboarding.rb
db/migrate/20230302122743_add_advice_page_and_group_to_alert_type.rb
db/schema.rb
lib/tasks/deployment/20230302123836_assign_group_to_alert.rake
lib/tasks/deployment/20230302140543_assign_advice_page_to_alert_type.rake

Adds some extra fields to `AlertType`:
* a reference to `AdvicePages` which will allow us to link alerts to their pages, as well as redirect users from the old analysis pages to the new versions
* a `group` attribute that will be used to categorise the alerts based on whether they are carrying out benchmarking of a school, reporting on short term changes, indicate some priority areas for attention, or are just general advice. This will allow us to improve the display and prioritisation of alert content on the advice page index
* a `link_to` property to indicate which tab of the advice page to link to, defaulting to insights
* a `link_to_section` property, to indicate a section of the insights or analysis page to link to
The last two are to allow admins to have some control over where to …

Add extra fields to alert type

---

app/controllers/admin/alert_types_controller.rb
app/models/advice_page.rb
app/views/admin/alert_types/_table.html.erb
app/views/admin/alert_types/edit.html.erb
app/views/admin/alert_types/index.html.erb
app/views/admin/alert_types/show.html.erb

Updates the admin pages for managing Alert Types
* Tidy up the index page to make tables sortable, add in the extra fields
* Add extra fields for the overview tab of individual alert types
* Update the form to allow admin to set group, advice page, link to, etc.

Update alert type management forms

---

app/controllers/compare_controller.rb
app/models/user.rb
app/views/compare/_header.html.erb
app/views/compare/_tabs.html.erb
app/views/compare/categories.html.erb
app/views/compare/group.html.erb
app/views/compare/groups.html.erb
app/views/home/_school_details.html.erb
app/views/home/_school_types.html.erb
app/views/schools/_details_form.html.erb
app/views/schools/advice/_how_have_we_analysed_your_data.html.erb
app/views/schools/advice/baseload/_comparison.html.erb
app/views/schools/advice/electricity_intraday/_analysis.html.erb
app/views/schools/advice/electricity_long_term/_analysis_comparison.html.erb
app/views/schools/advice/electricity_long_term/_comparison.html.erb
app/views/schools/advice/electricity_out_of_hours/_insights.html.erb
app/views/schools/advice/gas_long_term/_analysis_comparison.html.erb
app/views/schools/advice/gas_long_term/_comparison.html.erb
app/views/schools/advice/gas_out_of_hours/_insights.html.erb
app/views/schools/advice/total_energy_use/_analysis.html.erb
app/views/schools/advice/total_energy_use/_insights.html.erb
config/locales/activerecord.yml
config/locales/common.yml
config/locales/cy/activerecord.yml
config/locales/cy/common.yml
config/locales/views/compare/compare.yml
config/routes.rb
spec/models/user_spec.rb
spec/system/compare_spec.rb

Implements the 'Your group' tab for the new compare pages.
NB: I have moved the analytics.school_types.* key to common.school_types.* (and removed another key in root called school_types.mixed_primary_and_secondary and changed code accordingly)

Compare pages - Implement 'your group' tab

---

app/controllers/management/management_priorities_controller.rb
app/controllers/schools/find_out_more_controller.rb
app/helpers/schools_helper.rb
app/mailers/alert_mailer.rb
app/models/alert_type.rb
app/models/find_out_more.rb
app/views/alert_mailer/alert_email.html.erb
app/views/management/management_priorities/_list.html.erb
app/views/pupils/schools/show.html.erb
app/views/schools/find_out_more/show.html.erb
app/views/shared/_dashboard_alerts.html.erb
config/locales/cy/views/pupils/pupils.yml
config/locales/views/pupils/pupils.yml
config/locales/views/schools/schools.yml
spec/controllers/schools/find_out_more_controller_spec.rb
spec/helpers/schools_helper_spec.rb
spec/services/alerts/generate_email_notifications_spec.rb

Changes whether the "find out more" pages are accessible to users. This is part of retiring that part of the application, replacing them with direct links to the new advice pages.
Uses a Feature Flag to control the behaviour change (`FEATURE_FLAG_REPLACE_FIND_OUT_MORES`)
The majority of the work is done in some new helper methods in the `SchoolsHelper`. This checks the status of the feature flag and then returns either the path to the find out more page (if its off) or the advice page (if there is one). I've added an rspec test which exercises the majority of the paths through this code.
The rest of the changes are then largely in the templates, which now call these methods.
Summary of changes:

Change find out more linking

---

app/helpers/advice_page_helper.rb
app/models/alert.rb
app/models/alert_type.rb
app/views/schools/advice/index/_alerts.html.erb
app/views/schools/advice/index/_priority_table.html.erb
spec/helpers/schools_helper_spec.rb

Updates the list of priorities and recent alerts to link to the actual advice pages (and sections where configured).

Add real links to advice index page tabs

---

app/controllers/schools/advice/hot_water_controller.rb
app/views/schools/advice/hot_water/_analysis.html.erb
app/views/schools/advice/hot_water/_analysis_table.html.erb
app/views/schools/advice/hot_water/_insights.html.erb
app/views/schools/advice/hot_water/not_relevant.html.erb
config/locales/views/advice_pages/hot_water.yml
spec/system/schools/advice_pages/hot_water_spec.rb

Revises the hot water advice page

Revise hot water analysis

---

app/controllers/schools/contacts_controller.rb
app/models/contact.rb
app/views/schools/contacts/_form.html.erb
app/views/schools/contacts/index.html.erb
spec/system/schools/dashboard/manage_school_alert_contacts_spec.rb

When a contact has an associated user, the contact form should include a preferred language field, which reflects the preferred locale set on the user.
The language should be changeable from the contact form, and applied to the user.
If the contact doesn't have a user, then we don't show the preferred locale field.

Added preferred locale field to contact form

---

app/controllers/admin/school_onboardings_controller.rb
app/models/school_onboarding.rb
app/views/admin/school_onboardings/completed.html.erb

Revises the admin recent onboarding report:
* Order so most recent first
* Change "Onboarding event" column to be date-time when onboarding completed, not last event date
* Add column for whether school is data enabled
* Add column for date-time when school was data enabled
* Calculate number of days between onboarding completed and data being enabled
Pushed most of the logic into the SchoolOnboarding model.

Revise recent onboarding report

---

app/controllers/schools/advice/base_costs_controller.rb
app/controllers/schools/advice/electricity_costs_controller.rb
app/controllers/schools/advice/gas_costs_controller.rb
app/views/schools/advice/electricity_costs/_meter_breakdown.html.erb
app/views/schools/advice/gas_costs/_analysis.html.erb
app/views/schools/advice/gas_costs/_cost_breakdown_by_charge.html.erb
app/views/schools/advice/gas_costs/_cost_breakdown_by_meter.html.erb
app/views/schools/advice/gas_costs/_cost_comparison.html.erb
app/views/schools/advice/gas_costs/_insights.html.erb
app/views/schools/advice/gas_costs/_meter.html.erb
app/views/schools/advice/gas_costs/_meter_breakdown.html.erb
app/views/schools/advice/gas_costs/_tariff_note.html.erb
app/views/schools/advice/gas_costs/meter_costs.js.erb
config/i18n-tasks.yml
config/locales/views/advice_pages/gas_costs.yml
spec/system/schools/advice_pages/gas_costs_spec.rb

Implements the gas costs advice page.
* Extracts code from electricity costs controller to create a common base class to be used for gas and electricity controllers
* Copies over the templates, specs and translation text for the gas page, adjusting values/keys as required

Implement gas cost advice page

---

app/controllers/schools/advice/baseload_controller.rb
app/models/advice_page.rb
app/models/advice_page_school_benchmark.rb
app/models/school.rb
app/services/schools/advice/baseload_service.rb
app/services/schools/advice_page_benchmarks/baseload_benchmark_generator.rb
app/services/schools/advice_page_benchmarks/school_benchmark_generator.rb
db/migrate/20230314141937_create_advice_page_school_benchmarks.rb
db/schema.rb
spec/factories/advice_page_school_benchmarks.rb
spec/models/advice_page_school_benchmark_spec.rb
spec/services/schools/advice/baseload_service_spec.rb
spec/services/schools/advice_page_benchmarks/baseload_benchmark_generator_spec.rb
spec/services/schools/advice_page_benchmarks/school_benchmark_generator_spec.rb
spec/system/schools/advice_pages/baseload_spec.rb

An initial PR a small framework for generating the benchmark school comparisons to be shown on the advice index page.
For each of the advice pages, we will aim to generate a comparison of that schools data against a "benchmark" or "exemplar" school. E.g. a comparison of their current baseload against what we consider to be good values.
We will generate each of these benchmarks, for each school, every day.
This initial PR covers:
* Added a new model `AdvicePageSchoolBenchmark` which holds the relationship between a page and a school, along with the result of the benchmark
* A base class `SchoolBenchmarkGenerator` which can be extended to implement the benchmarks for each page. The base class just handles creating/updating/removing the above model, but delegates to sub-classes to perform …

Implement advice index page benchmarking framework

---

app/services/content_batch.rb
app/services/schools/advice_page_benchmarks/generate_benchmarks.rb
spec/services/content_batch_spec.rb
spec/services/schools/advice_page_benchmarks/generate_benchmarks_spec.rb

Integrates advice page benchmark generation into the content batch.
* Adds new service to generate the benchmarks for all pages
* Adds the service to the content batch
* Specs for the above

Integrate advice page benchmarks into content batch

---

app/assets/stylesheets/advice_page.scss
app/assets/stylesheets/colours.scss
app/controllers/schools/advice_controller.rb
app/views/schools/advice/index/_page_list.html.erb
app/views/schools/advice/show.html.erb

Adds the school advice page benchmarks into the index page
* Loads the benchmarks
* Where a benchmark is available, add a column with the appropriate label and background colour
* Further tweaks to page styling.

Integrate benchmarks into advice page index

---

app/components/school_comparison_component/school_comparison_component.html.erb
app/controllers/schools/advice/advice_base_controller.rb
app/controllers/schools/advice/base_long_term_controller.rb
app/controllers/schools/advice/total_energy_use_controller.rb
app/models/advice_page.rb
app/services/schools/advice/long_term_usage_service.rb
app/services/schools/advice_page_benchmarks/long_term_usage_benchmark_generator.rb
app/services/schools/advice_page_benchmarks/school_benchmark_generator.rb
config/locales/views/advice_pages/advice_pages.yml
spec/services/schools/advice_page_benchmarks/long_term_usage_benchmark_generator_spec.rb
spec/services/schools/advice_page_benchmarks/school_benchmark_generator_spec.rb

Adds an advice page benchmark for the long term usage pages
* Move method from `AdviceBaseController` to `AdvicePage` so there's a consistent approach to checking if school has right fuel type for page for benchmarks and display of pages
* Move method from `BaseLongTermController` to `LongTermUsageService` so that benchmark comparison is reusable
* Changes long term usage advice controllers to request benchmark comparison from service
* Ensure school has right fuel type before generating an advice page benchmark
* Adds new `LongTermUsageBenchmarkGenerator` to produce benchmark for index page, and adds it to the factory method in base class
* Ensure `SchoolComparisonComponent` and advice page index are using same translation keys
* Tests for the above

3074 implement long term usage benchmark

---

app/classes/schools/comparison.rb
app/controllers/schools/advice/thermostatic_control_controller.rb
app/helpers/advice_page_helper.rb
app/services/schools/advice/thermostatic_analysis_service.rb
app/services/schools/advice_page_benchmarks/school_benchmark_generator.rb
app/services/schools/advice_page_benchmarks/thermostatic_control_benchmark_generator.rb
app/views/schools/advice/thermostatic_control/_insights.html.erb
config/locales/views/advice_pages/advice_pages.yml
config/locales/views/advice_pages/thermostatic_control.yml
spec/services/schools/advice_page_benchmarks/thermostatic_control_benchmark_generator_spec.rb
spec/system/schools/advice_pages/thermostatic_control_spec.rb

Implements the school comparison component and advice page benchmark for the thermostatic control page
* Extract some common code into a new `ThermostaticAnalysisService` to be shared by controller and benchmark
* Add the benchmark comparison, which is a simple comparison of r2 values
* Update `Schools::Comparison` to accept a parameter to indicate whether high or low in ranges is good. (So far in all other cases we have been aiming for schools to, e.g. reduce consumption, but here they need to increase r2)
* Implement the benchmark for the advice page index
I've also slightly simplified the insights page as there was duplication between the "What is your baseload" and comparison section. So these have been combined. I've also aligned the page title better with the navbar.

Implement thermostatic benchmark

---

app/controllers/schools/advice/heating_control_controller.rb
app/helpers/advice_page_helper.rb
app/services/schools/advice/heating_control_service.rb
app/services/schools/advice_page_benchmarks/heating_control_benchmark_generator.rb
app/views/schools/advice/heating_control/_analysis.html.erb
app/views/schools/advice/heating_control/_comparison.html.erb
app/views/schools/advice/heating_control/_insights.html.erb
app/views/schools/advice/heating_control/_seasonal_control.html.erb
app/views/schools/advice/heating_control/_warm_weather_notice.html.erb
config/locales/views/advice_pages/heating_control.yml
spec/services/schools/advice_page_benchmarks/heating_control_benchmark_generator_spec.rb

Implements the school comparison component and advice page benchmark for the heating control page.
We'll be benchmarking schools based on how often they have heating on during warm weather.
This PR:
* Extracts some code currently in a helper, moving it to the `HeatingControlService` and then adding methods to access the rating
* Revises the controller and templates to use the above when displaying notices about warm weather days
* Fixes a potential issue where we still try and run the seasonal analysis, even though there is limited data
* Updates the `HeatingControlService` to benchmark the school usage and adds the school comparison component to the insight page
* Adds a benchmark generator for the advice index page.

Implement heating control benchmark

---

app/assets/stylesheets/advice_page.scss
app/helpers/advice_page_helper.rb
app/services/schools/advice_page_benchmarks/school_benchmark_generator.rb
app/views/schools/advice/index/_page_list.html.erb
config/locales/views/advice_pages/index.yml
spec/services/schools/advice_page_benchmarks/school_benchmark_generator_spec.rb

* Add a method and a helper to indicate whether we have an benchmark for a benchmark page
* Add a "not applicable" or "not available" message to advice index page to better indicate whether we do have a benchmark, or whether its not yet available
* Link the colour coded blocks to the relevant insights page
* Styling improvements.

Improve benchmark labelling on advice index page

---

app/views/shared/_google_analytics.html.erb

Updates out Google Analytics custom dimensions to include the advice page key and tab where available.
This should allow us to better report based on which pages users are visiting, rather than relying on page titles.

Log advice page and tab to GA

---

app/assets/stylesheets/dashboards.scss
app/views/pupils/schools/_pupil_dashboard_buttons.html.erb
app/views/pupils/schools/show.html.erb
app/views/schools/_adult_dashboard_buttons.html.erb
app/views/schools/show.html.erb
app/views/shared/_dashboard_title.html.erb
config/locales/cy/views/schools/schools.yml
config/locales/views/schools/schools.yml
spec/system/admin/alert_type_management_ratings_spec.rb
spec/system/admin/school_onboarding_spec.rb
spec/system/home_spec.rb
spec/system/school_alerts_spec.rb
spec/system/school_spec.rb
spec/system/schools/advice_pages/advice_pages_spec.rb
spec/system/schools/analysis_pages_spec.rb
spec/system/schools/dashboard/manage_school_spec.rb
spec/system/schools/dashboard/navigation_spec.rb
spec/system/schools/live_data_spec.rb

Changes school dashboard so the school name, type and address is displayed at the top.
Common markup is factored out into a partial.
The PR also fixes up a number of tests that are broken when these feature flags are on:
```
FEATURE_FLAG_REPLACE_ANALYSIS_PAGES="true"
FEATURE_FLAG_REPLACE_FIND_OUT_MORES=true
```

Add school name type and address to adult and pupil dashboard

---

app/views/alert_mailer/alert_email.html.erb
app/views/bill_request_mailer/request_bill.html.erb
app/views/onboarding_mailer/activation_email.html.erb
app/views/onboarding_mailer/data_enabled_email.html.erb
app/views/onboarding_mailer/onboarded_email.html.erb
app/views/onboarding_mailer/onboarding_email_content.html.erb
app/views/onboarding_mailer/reminder_email_content.html.erb
app/views/onboarding_mailer/welcome_email.html.erb
app/views/shared/mailer/_first_target_prompt.html.erb
config/locales/mailers/mailer.yml

This PR:
* fixes some layout issues in some of the application mailers. Buttons weren't floating right as templates were using wrong class, and not enough space between paragraphs
* adds some buttons to the activation and data enabled emails to better call out next action to users

Improve layout of mail templates

---

app/controllers/analysis_page_finder_controller.rb
app/controllers/concerns/analysis_pages.rb

The benchmark pages use a custom route to link to the old analysis pages. That route uses the school url and class name. This is then used to find the latest version of that analysis page and the user is redirected to it.
We need to ensure these urls continue to work for the moment, but as the new advice pages have a predictable URL it shouldn't be needed longer term. 
For now this PR changes the controller to find the right AdvicePage instead and redirects to it. It uses the same feature flag we're using to hide the old analysis pages from the rest of the site.

Redirect from benchmarks to advice pages

---

app/controllers/schools/advice/advice_base_controller.rb
app/models/advice_page.rb
app/models/intervention_type.rb
app/services/intervention_type_filter.rb
spec/services/intervention_type_filter_spec.rb

This PR updates the advice base controller to revise how it loads recommended actions and activities
* Returns up to four of each type, so we can fully populate the page with recommendations
* Sorts the recommendations by their priority, so they are presented in order
* Filters the results to include just those that haven't already been recorded this academic year
For the filtering we have the existing `ActivityTypeFilter`. I've added a simpler version of this for filtering intervention types. These have less fields, so there's less to filter on, but I think the service is still useful as we can use it to better present suggestions elsewhere on the site.

Fix number of recommended activities and actions on new advice pages

---

app/controllers/calendars_controller.rb
app/controllers/pupils/analysis_controller.rb
app/controllers/pupils/schools_controller.rb
app/controllers/schools/audits_controller.rb
app/controllers/schools/contacts_controller.rb
app/controllers/schools/downloads_controller.rb
app/controllers/schools/estimated_annual_consumptions_controller.rb
app/controllers/schools/meters_controller.rb
app/controllers/schools/school_targets/progress_controller.rb
app/controllers/schools/school_targets_controller.rb
app/controllers/schools/temperature_observations_controller.rb
app/controllers/schools/timeline_controller.rb
app/controllers/schools/times_controller.rb
app/controllers/schools/transport_surveys_controller.rb
app/controllers/schools/user_tariffs_controller.rb
app/controllers/schools/users_controller.rb
app/controllers/schools/your_school_estates_controller.rb
app/controllers/schools_controller.rb
config/locales/views/schools/schools.yml

Improves the display of breadcrumbs across the school pages by adding a default breadcrumb for all controllers.
There's a lot of changes, but these are mostly just adding a `before_action` to each controller and a method to set the default breadcrumb. Where possible I've used existing keys, e.g. from the Manage School menu, to make the navigation clearer.

Improve school page breadcrumbs

---

app/views/schools/interventions/_points.html.erb
app/views/schools/interventions/completed.html.erb
app/views/schools/interventions/index.html.erb
config/locales/views/interventions/interventions.yml

This PR provides translations for strings on the intervention (action) pages.
Pluralized strings are handled by providing "one" and "other" keys.
Ordinals (1st, 2nd etc) are already supported in the translation files.
Translation strings that start with interpolation placeholders need to be quoted.

Translations for text on intervention completion partials

---

app/controllers/schools/advice/base_out_of_hours_controller.rb
app/services/schools/advice/peak_usage_service.rb
app/services/schools/advice_page_benchmarks/out_of_hours_usage_benchmark_generator.rb

With the latest analytics updates, we can now calculate peak kw values and out of hours usage values for a `benchmark_school`.
This PR updates the relevant services/benchmarks to use the new feature.

Integrate new benchmarks

---

app/helpers/locale_helper.rb
app/views/schools/interventions/index.html.erb
spec/helpers/locale_helper_spec.rb

The month name, buttons and actions counts need to be translated on the interventions index page.

Translate month names, buttons, action counts

---

app/helpers/advice_page_helper.rb
app/services/schools/advice/baseload_service.rb
app/views/schools/advice/baseload/_seasonal_variation_breakdown_table.html.erb
app/views/schools/advice/baseload/_weekday_variation_breakdown_table.html.erb
config/locales/views/advice_pages/advice_pages.yml
spec/services/schools/advice/baseload_service_spec.rb

The baseload page tries to display the seasonal and intraweek baseload variation for all meters if the school has >1 years of data.
But some of the individual meters may have <1 year of data.
This PR revises the `BaseloadService` and the templates to:
* Check whether there is enough data for both seasonal and intraweek variation
* If there is not enough data, then return a limited variation object that indicates this and provides a date when the analysis can be run for that meter
* Displays a custom row in the table for these meters to indicate to the user that there is limited data and, hopefully when the analysis can be run

Fix baseload page when some meters have limited data

---

app/helpers/application_helper.rb
app/views/devise/sessions/new.html.erb
spec/helpers/application_helper_spec.rb
spec/system/pupils/pupil_password_spec.rb

This PR adds the school group name to the dropdown of school names when using the pupil login page (to disambiguate schools with the same names)

3056 add school group to pupil login select box

---

app/views/schools/advice/baseload/_analysis.html.erb

There's no forward/back navigation, but you can drill down so the controls need to be displayed.

Reinstate controls on baseload chart

---

app/services/schools/advice/baseload_service.rb
spec/services/schools/advice/baseload_service_spec.rb

Fixes an issue when the meter has data over several years, but the school only uses electricity from this meter for a portion of the year (in this case a swimming pool only used in the summer).
Checks for whether the seasonal analysis returned any results.

Check if seasonal analysis was unsuccessful

---

app/controllers/schools/advice/base_out_of_hours_controller.rb
app/services/schools/advice_page_benchmarks/out_of_hours_usage_benchmark_generator.rb
spec/services/schools/advice_page_benchmarks/out_of_hours_usage_benchmark_generator_spec.rb

We were incorrectly calculating the benchmark and exemplar out of hours usage as a % of the schools out of hour usage, rather than the school's total usage.
This PR fixes that issue.

Calculate correct out of hours usage benchmark

---

app/views/schools/advice/index/_page_list.html.erb
config/locales/views/advice_pages/advice_pages.yml
config/locales/views/advice_pages/index.yml

* Rename "Improving" to "Action needed" across the advice page index and insight page benchmarks
* Make title more obvious on advice page index
* Change labels for "not applicable" and "not available" to clarify what they mean

Advice page index and benchmark labels

---

app/mailers/onboarding_mailer.rb
app/services/activation_email_sender.rb
app/views/onboarding_mailer/activation_email.html.erb
config/locales/mailers/mailer.yml
spec/services/activation_email_sender_spec.rb

Removes a section from the activation email prompting a school to set a target.

Remove prompt for target from activation email

---

app/views/schools/advice/electricity_recent_changes/_analysis.html.erb
app/views/schools/advice/gas_recent_changes/_analysis.html.erb
config/locales/views/advice_pages/electricity_recent_changes.yml
config/locales/views/advice_pages/gas_recent_changes.yml
spec/system/schools/advice_pages/electricity_recent_changes_spec.rb
spec/system/schools/advice_pages/gas_recent_changes_spec.rb

Adds an intraday 7 day breakdown chart to the gas and electricity recent changes pages.
Fairly simple change to add sections to the analysis page, the chart component and the translations for the chart text.

Add new charts to recent changes pages

---

app/assets/stylesheets/colours.scss
app/assets/stylesheets/toggler.scss
app/components/page_nav_component.rb
app/components/page_nav_component/page_nav_component.scss
app/views/schools/advice/_nav.html.erb

Restyles the navbar:
- Adds support for adding classes to individual items
- Changes section styling to use "dark" version of standard fuel type colours
- Adds colour border to items to help group them
- Adds some negative margin to the icon to align text better
- Add custom hover and "current" item colours to better identify which page is being selected, or is currently selected

Revise colours on navbar

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/compare.scss
app/controllers/compare_controller.rb
app/views/compare/_school_type_filter.html.erb
app/views/compare/_school_type_summary.html.erb
app/views/compare/_summary.html.erb
app/views/compare/benchmarks.html.erb
app/views/compare/index.html.erb
app/views/compare/tab_content/_country.html.erb
app/views/compare/tab_content/_group.html.erb
app/views/compare/tab_content/_groups.html.erb
app/views/compare/tab_content/_type.html.erb
config/locales/views/compare/compare.yml
spec/system/compare_spec.rb

See what you think @ldodds - I have made the benchmark list page groups into cards - not 100% convinced on the way it looks but easy enough to change. Also see what you think about the search filters. Also I'm not such a fan of the massive header on the front page but it does match the other pages...
Index / search filter page:
Benchmark list page:
Benchmark & Results pages
Any other feedback…

Enhance style of new pages

---

Gemfile
Gemfile.lock
app/controllers/schools/advice/advice_base_controller.rb
app/controllers/schools/advice/base_out_of_hours_controller.rb
app/helpers/advice_page_helper.rb
app/views/schools/advice/electricity_out_of_hours/_analysis.html.erb
app/views/schools/advice/electricity_out_of_hours/_current_holiday_usage_row.html.erb
app/views/schools/advice/electricity_out_of_hours/_holiday_comparison_row.html.erb
app/views/schools/advice/electricity_out_of_hours/_holiday_usage_table.html.erb
app/views/schools/advice/electricity_out_of_hours/_previous_holiday_usage_row.html.erb
config/locales/views/advice_pages/advice_pages.yml
config/locales/views/advice_pages/electricity_out_of_hours.yml
spec/system/schools/advice_pages/electricity_out_of_hours_spec.rb
spec/system/schools/advice_pages/gas_out_of_hours_spec.rb

This adds a new "Holiday usage" section to the Electricity Out of Hours Page. Other pages to be updated in subsequent PRs.
* Bumps version of analytics to access new service
* Add new section to the page
* If there is > 14 months of data, then show a chart with breakdown of usage by day of week, holiday, etc
* Add table summarising usage for recent school holidays, with comparison with previous years holiday where available
Screenshot of portion of table:

3066 implement holiday breakdown tables for advice pages

---

app/controllers/schools/advice/storage_heaters_controller.rb
app/views/schools/advice/electricity_out_of_hours/_analysis.html.erb
app/views/schools/advice/storage_heaters/_analysis.html.erb
app/views/schools/advice/storage_heaters/_current_holiday_usage_row.html.erb
app/views/schools/advice/storage_heaters/_holiday_comparison_row.html.erb
app/views/schools/advice/storage_heaters/_holiday_usage_table.html.erb
app/views/schools/advice/storage_heaters/_previous_holiday_usage_row.html.erb
config/locales/views/advice_pages/storage_heaters.yml
spec/system/schools/advice_pages/storage_heaters_spec.rb

Adds holiday use table to storage heater page
- Updates controller to load the necessary analysis
- Adds section to the page with necessary translations
- Updated specs to check for presence of all charts
There's no new chart for the holiday use

Add holiday use to storage heater page

---

app/controllers/schools/advice/advice_base_controller.rb
config/locales/cy/analytics/benchmarking/content_base.yml
config/locales/cy/analytics/charts/chart_configuration.yml
config/locales/cy/analytics/energy_units.yml
config/locales/cy/views/home/attribution.yml

Transifex synchronisation removed a unit, which is causing thermostatic insights pages to fail in Welsh.
This also expose an issue with the advice error page which isn't rendering with a locale. So have wrapped that in calls to ensure its translated.

Restore missing unit, ensure error page is translated

---

app/views/schools/_details_form.html.erb
app/views/schools/edit.html.erb
app/views/schools/new.html.erb
config/locales/views/schools/schools.yml

There was still some untranslated text on the school details forms:
* Page titles for New/Editing School
* Update School button
* Back button
* Funding Status
* Countries
Where possible I've used existing translations to fill in the missing words.

Missing translations on school details form

---

app/views/schools/school_targets/progress/current.html.erb

This PR removes a spurious print of the latest progress value in the target progress page..

Removed spurious output of latest progress value

---

app/services/schools/advice/baseload_service.rb

The baseload service wasn't correctly counting meters. It was including inactive meters when it shouldn't

Baseload multiple meter check

---

app/models/meter.rb

This needs to be blocked until 2961-migration-to-remove-old-notes-field has been run

Remove notes field from meter model

---

app/models/meter.rb
app/models/user_tariff.rb
spec/models/user_tariff_spec.rb

User tariffs are defined in a multi-step process, adding prices and charges, but can be left in an incomplete state. This causes errors when passed to the analytics as meter attributes.
This PR applies a scope to the user tariffs to ensure that only tariffs that have either prices or charges (or both) as passed to the analytics.

3211 avoid passing incomplete user tariffs to analytics

---

app/models/user_tariff_price.rb
app/views/schools/user_tariff_differential_prices/index.html.erb
app/views/schools/user_tariffs/_rates_table.html.erb
config/locales/cy/views/schools/user_tariffs.yml
config/locales/views/schools/user_tariffs.yml
spec/models/user_tariff_spec.rb
spec/system/schools/user_tariffs_spec.rb

This PR removes the option to add or delete differential user tariff prices - we only allow 2prices (night and day) which are created automatically. 
The actual price and start and end times can still be edited.
There is now validation to ensure that time ranges can't overlap for a given user tariff.

3212 dont allow users to delete rates for day night tariffs

---

app/assets/javascripts/analysis.js
app/services/charts/annotate.rb
spec/services/charts/annotate_spec.rb

For some charts we add annotations that indicate when the school took action. At the moment this is limited to the dashboard charts and one of the baseload charts.
The javascript is expecting that if there are annotations then the chart point labels (a date for these charts) should match the label given in the JSON produced for each annotation.
The date format for the baseload chart seems to have changed. But the `Charts::Annotate` class was producing a different format. The mismatched caused an error.
This PR:
* Changes the date format in the `Annotate` class to match the baseload chart
* Adds a check in the JS for whether we have a point before trying to create an annotation

Fix javascript error on baseload chart

---

app/models/chart_data_values.rb
spec/models/chart_data_values_spec.rb

Avoids trying to translate the series names on the scatter charts. This currently breaks the charts as the float values end up as strings.
The series names aren't actually displayed to users, so it isn't an issue to not translate the dates.

Dont translate series labels for scatter plots

---

app/services/alerts/adapters/report.rb
spec/services/alerts/adapters/report_spec.rb

The alert base class (`ContentBase`) has a method `enough_data` which is used to indicate if there is enough data to run an alert. It can return three values: `:enough`, `:not_enough`, ':minimum_might_not_be_accurate`.
Only two alerts actually return the third value: `AlertImpendingHoliday` and `AlertChangeInElectricityBaseloadShortTerm`, all other alerts return the other values.
The `ContentBase` class also has a method called `make_available_to_users?` which only returns true if an alert is relevant for a school and `enough_data` returns a value of `:enough_data`. The application uses this method to decide whether to store the variables generated by the alert.
So it does _not_ store variables if an alert returns `:minimum_might_not_be_accurate`.
This PR updates the …

Ignore "minimum_might_not_be_accurate"

---

app/controllers/admin/school_groups/meter_reports_controller.rb
app/controllers/admin/school_groups_controller.rb
app/controllers/schools/meters_controller.rb
app/models/admin_meter_status.rb
app/models/meter.rb
app/models/school_group.rb
app/views/admin/index.html.erb
app/views/admin/school_groups/_form.html.erb
app/views/admin/school_groups/meter_reports/show.html.erb
app/views/import_mailer/_meter_table.html.erb
app/views/import_mailer/import_summary.html.erb
app/views/schools/meters/_active_meters.html.erb
app/views/schools/meters/_form.html.erb
app/views/schools/meters/index.html.erb
config/locales/common.yml
config/locales/cy/common.yml
config/locales/views/schools/schools.yml
db/migrate/20230404132453_add_admin_meter_status_id_to_meter.rb
db/migrate/20230404135501_add_admin_meter_statuses_id_to_school_group.rb
db/schema.rb
spec/system/meter_management_spec.rb

Allow admins to assign meter status to individual meters (2)

---

app/controllers/admin/meter_statuses_controller.rb
app/controllers/admin/school_groups_controller.rb
app/models/admin_meter_status.rb
app/models/meter.rb
app/models/school_group.rb
app/views/admin/meter_statuses/index.html.erb
app/views/admin/school_groups/_form.html.erb
app/views/schools/meters/_active_meters.html.erb
db/migrate/20230405085418_add_extra_meter_status_defaults_to_school_groups.rb
db/schema.rb

Allow admins to assign meter status to individual meters (3)

---

Gemfile
Gemfile.lock
app/models/chart_data.rb
config/locales/analytics/charts/chart_timescale_descriptions.yml
config/locales/cy/analytics/charts/chart_timescale_descriptions.yml
config/locales/cy/models/chart_data.yml
config/locales/models/chart_data.yml

Updates the version of the analytics to incorporate translations for chart periods.
Removes previous approach implemented in the application which only supported a couple of period types.
Manually added Welsh translations for day, week, year, up to a year so the current translations are used until the full set is done.
There's a small functional change here which is a side-effect of the code changes: if there's no Welsh version of some timescales it will default to "period". I think that's reasonable for the moment and is what we use elsewhere.

Translate chart period

---

app/controllers/admin/school_groups/meter_reports_controller.rb
app/models/meter.rb

Couple of smallish performance tweaks to the school group report
- use `.any?` instead of `.count`
- just `select` the fields we need for display of gaps
- do checks for modified readings against the model attribute (`.status`) rather than using a secondary query (`.modified`)

Small tweaks to the performance of school group reports

---

app/classes/targets/fuel_progress.rb
app/services/targets/generate_progress_service.rb
app/views/schools/school_targets/_target_table_row.html.erb
lib/tasks/deployment/20230411111243_remove_target_advice.rake
spec/services/targets/generate_progress_service_spec.rb

Fixes several issues with school targets feature:

Fix some issues with school target reporting

---

app/services/targets/generate_progress_service.rb
spec/services/targets/generate_progress_service_spec.rb

We currently end up reporting the same issue to Rollbar multiple times when generating the target progress reports. 
This PR alters the GenerateProgressService so it will report errors for a given fuel type only once. This ensures we get some error reporting without having duplicates which differ only in their stack trace.

Report GenerateProgress errors only once

---

Gemfile
Gemfile.lock
app/controllers/schools/solar_edge_installations_controller.rb
app/services/solar/base_download_and_upsert.rb
app/services/solar/low_carbon_hub_upserter.rb
app/services/solar/solar_edge_download_and_upsert.rb
app/services/solar/solar_edge_installation_factory.rb
app/services/solar/solar_edge_upserter.rb
app/views/schools/meters/_inactive_meters.html.erb
app/views/schools/meters/index.html.erb
app/views/schools/solar_edge_installations/show.html.erb
app/views/schools/solar_feeds_configuration/_solar_edge_feeds.html.erb
config/routes.rb
lib/tasks/solar/import_solar_edge_readings.rake
spec/services/solar/low_carbon_hub_upserter_spec.rb
spec/services/solar/solar_edge_download_and_upsert_spec.rb
spec/services/solar/solar_edge_upserter_spec.rb
spec/system/solar_edge_installation_spec.rb

A range of improvements to the setup and management of SolarEdge API feeds
* Updates the analytics to incorporate bug fixes in the SolarEdgeAPI class, including ability to import only partially metered data
* Fixes a long standing issue that Solar Edge imports fail if an admin has already created the pseudo meters
* Populates the `information` field at setup and after editing a feed config, to provide some debug information if there are problems
* Triggers some API requests, including a small data load at creation of a new Solar Edge feed to flush out API issues early and ensure that necessary pseudo meters are created
* Improves the logging and error reporting to clarify which import has failed, if it occurs

Improve SolarEdge feed setup process

---

app/models/ability.rb

The ability.rb has a check on number of amr_data_feed_readings to stop anyone deleting meters that have data in the system.
This is called once for all inactive meters, whenever an admin and school admin users view the page.

Replace count with any?

---

app/controllers/admin/school_groups/meter_updates_controller.rb
app/controllers/admin/school_groups_controller.rb
app/models/school_group.rb
app/views/admin/school_groups/_form.html.erb
app/views/admin/school_groups/meter_updates/index.html.erb
app/views/admin/school_groups/show.html.erb
app/views/schools/meters/_form.html.erb
config/routes.rb
db/migrate/20230405110515_add_default_data_sources_to_school_group.rb
db/schema.rb

Support default school group data sources

---

app/models/amr_reading_data.rb
lib/tasks/deployment/20230413153813_remove_readings_with_all_dashes.rake
spec/models/amr_reading_data_spec.rb

The Smartest Energy CSV data includes rows which have:
- all 48 half-hourly readings as "-"
- portions of the day as dashes, e.g. 1-2 hours in the morning then dashes
These are currently being passed through for storing. When processed the array of dashes is processed via (`readings.map(&:to_f)`) which converts the dashes to zeroes. Which means it treats the data as zero readings.
When the real data appears the data is backfilled and replaced, but the behaviour isn't correct.
This PR makes a system wide change to treat "-" characters as missing values, which means rows containing that data will be rejected. This may lead to more rejected data, but is better behaviour overall.
The PR also includes an AfterParty task to clean up some existing missing data
The task:
- removes …

Treating '-' as missing data

---

app/services/import_notifier.rb

Only check to see what configs we've used to load data for a meter in the last 12 months, not all time.
This significantly improves the "meters running behind" check and should involve less paging through data on the database.

Add a date limit to the amr data feed reading lookup

---

Gemfile
Gemfile.lock
config/locales/analytics/benchmarking/content_base.yml
db/schema.rb

Update to analytics 2.6.2 and copy over updated YAML file.
Changes the definition of the Easter shutdown benchmark tables and introductory text.

Update to 2.6.2

---

app/services/import_notifier.rb

Currently we loop over every data feed config and run the same query so that we can check its warning days, if it has one.
For some configs this is very quick, others very slow.
This changes the code to just join against the `amr_data_feed_configs` table, where the `import_warning_days` is not null, then check whether the latest meter data is older than the minimum value of the warning days.
This means we do one query rather than several. Overall I think this version is faster!

Push entire "meters running behind" query into database

---

app/controllers/admin/procurement_routes_controller.rb
app/controllers/schools/meters_controller.rb
app/models/meter.rb
app/models/procurement_route.rb
app/views/admin/index.html.erb
app/views/admin/procurement_routes/_form.html.erb
app/views/admin/procurement_routes/_header.html.erb
app/views/admin/procurement_routes/_procurement_route.html.erb
app/views/admin/procurement_routes/edit.html.erb
app/views/admin/procurement_routes/index.html.erb
app/views/admin/procurement_routes/new.html.erb
app/views/admin/procurement_routes/show.html.erb
app/views/import_mailer/_meter_table.html.erb
app/views/import_mailer/import_summary.html.erb
app/views/schools/meters/_active_meters.html.erb
app/views/schools/meters/_form.html.erb
app/views/schools/meters/_inactive_meters.html.erb
app/views/schools/meters/index.html.erb
config/locales/views/schools/schools.yml
config/routes.rb
db/migrate/20230419100900_create_procurement_routes.rb
db/migrate/20230419130712_add_procurement_route_id_to_meter.rb
db/schema.rb
spec/factories/procurement_routes.rb
spec/models/procurement_route_spec.rb
spec/system/admin/procurement_routes_spec.rb

This PR adds a new "Procurement Route” meter field similar to the existing “Data Source”:

Add meter procurement routes

---

app/controllers/admin/school_groups/meter_reports_controller.rb
app/models/meter.rb
app/services/school_groups/meter_report.rb
app/views/admin/reports/meter_reports/index.html.erb
app/views/admin/school_groups/meter_reports/show.html.erb
app/views/admin/school_groups/show.html.erb
spec/system/admin/reports/school_group_meter_reports_spec.rb
spec/system/admin/school_groups_spec.rb

* Don't include counts of zero days on the interactive report, to see if this version works OK and at least provides some information.
* Remove the old CSV download link on the admin school group page, the main meter report page and the individual meter report page
* Add the "request report by email" button to the admin index page and to the individual report page
* Ensure the "all meters" option is added to the request when needed

Further tweaks to interactive report

---

.ebextensions/cronjob.config
app/jobs/daily_regeneration_job.rb
app/jobs/generate_subscriptions_job.rb
app/models/school.rb
lib/tasks/alerts/generate_subscriptions.rake
spec/models/school_spec.rb

Every Weds ES reruns alerts:generate_subscriptions. This loops through all schools and invokes the Alerts::GenerateSubscriptions service for each school.  The process is getting slower (and CPU intensive) as we add more schools. Further, because the process starts via cron, it may begin before we’ve finished the daily regeneration of schools which creates the potential that the email contents don’t have the very latest alert content from schools.
In order to address these issues, this PR:

Parallelize weekly alert run (subscriptions)

---

app/services/events/event.rb
app/views/home/training.html.erb
config/locales/views/home/home.yml
spec/fixtures/events/events.json
spec/system/home_spec.rb

I tried very hard to find a count of tickets remaining to also add to the page but could not find an easy way... so I stuck with the original plan of just showing "sold out" or "tickets available".

Make it more obvious when events are sold out

---

app/views/schools/school_targets/progress/current.html.erb

This fixes an error where a chart config is requested for the pluralised storage heater fuel type which doesn't exist e.g.
```
>> @chart_name
=> :targeting_and_tracking_weekly_storage_heaters_to_date_cumulative_line
>> ChartManager.build_chart_config(ChartManager::STANDARD_CHART_CONFIGURATION[@chart_name])
!! #<NoMethodError: undefined method `key?' for nil:NilClass>
>> ChartManager.build_chart_config(ChartManager::STANDARD_CHART_CONFIGURATION[:targeting_and_tracking_weekly_storage_heater_to_date_cumulative_line])
=> {:name=>"Cumulative progress versus target", :chart1_type=>:line, :chart1_subtype=>nil, :meter_definition=>:storage_heater_meter, :x_axis=>:week, :series_breakdown=>:none, :yaxis_units=>:kwh, :yaxis_scaling=>:none, :timescale=>:up_to_a_year, …
```

Fix broken storage heater progress report

---

app/models/meter.rb
app/views/schools/advice/_meter_breakdown_charts.html.erb

https://trello.com/c/VMvOODVX/3277-baseload-chart-error-when-meter-has-no-readings

Fix baseload chart error when meter has no readings

---

app/views/shared/_usage_controls.html.erb

This fixes an error with the usage report datepicker where a date is updated manually in the field (e.g. `Sunday, 7 May 2023`) rather than through the date picker pop up (even if it’s a valid date but the day is wrong).  Setting `onkeydown: 'return false'` prevents the field from being manually updated but still allows arrow key navigation around the datepicker component.

Fix invalid date error on pupil charts

---

.github/workflows/rubyonrails.yml

There's an open issue with the alpine linux version of the PostgreQSL image we use for running our github actions test jobs see  https://github.com/docker-library/postgres/issues/1076 so changing here to an equivalent versioned tag.

Update PostgreSQL image for both github actions test jobs

---

app/assets/javascripts/common_chart_options.js

This pr adds some additional updates to the chart export title & subtitle style to match whats in the UI, e.g. bold title, both left-aligned

Chart export updates

---

app/components/meter_costs_table_component.rb
config/locales/views/advice_pages/advice_pages.yml

```
irb(main):045:0> MeterAttributes.default_tariff_rates.keys
=> [:standing_charge, :climate_change_levy, :renewable_energy_obligation, :feed_in_tariff_levy, :agreed_capacity, :agreed_availability_charge, :excess_availability_charge, :settlement_agency_fee, :reactive_power_charge, :data_collection_dcda_agent_charge, :nhh_automatic_meter_reading_charge, :half_hourly_data_charge, :fixed_charge, :nhh_metering_agent_charge, :meter_asset_provider_charge, :site_fee, :other]
```

Fix table issue with group level accounting charges and costs

---

Gemfile
Gemfile.lock
app/controllers/schools/advice/advice_base_controller.rb
app/controllers/schools/advice/base_long_term_controller.rb
spec/mailers/admin_mailer_spec.rb

Fixes issue with school dashboard charts skipping a week:
* Updates to analytics 2.7.5 which has the actual bug fix
* Adjust date calculations in advice controllers to reflect changes
There's an unrelated fix to a spec that was failing for me due to an environment difference.

3228 school dashboard charts skip a week

---

app/services/amr/single_read_converter.rb
spec/services/amr/single_read_converter_spec.rb

I recently added support for processing CSV files where the rows do not have timestamps and are just 48 rows of readings for each day. This is currently used in the Opus HH format.
There was a bug in the original code in which it was only processing the first meter correctly. Then the rest of the data wasn't imported. 
This was due to a bug in the logic that determined which array index should be populated for each row. I'd written it to support multiple days for a single meter, but failed where there were multiple days and multiple meters.
The revised logic properly tracks which mpan is being processed. I've added a test for this situation.

Fix for indexed reading format

---

app/assets/javascripts/application.js
app/assets/javascripts/depends_on.js
app/helpers/tariffs_helper.rb
app/models/user_tariff.rb
app/models/user_tariff_charge.rb
app/views/schools/user_tariff_charges/_charge_availability.html.erb
app/views/schools/user_tariff_charges/_charge_basic_row.html.erb
config/locales/models/user_tariff_charge.yml
spec/models/user_tariff_spec.rb

* Adds "tips" to the agreed / excess availability charge fields (see below)
* Uses JS to add a tooltip to the asc limit field if it has not been provided when one of the above two fields have (see below)
* Only sends asc limit to Analytics if agreed or excess availability charge are present

Tariffs with only agreed/excess availability charges need to have an asc limit

---

app/assets/stylesheets/analysis.scss
app/controllers/schools/advice/base_long_term_controller.rb
app/controllers/schools/advice/baseload_controller.rb
app/controllers/schools/advice/electricity_costs_controller.rb
app/views/schools/advice/baseload/_meter_breakdown_table.html.erb
app/views/schools/advice/baseload/_seasonal_variation_breakdown_table.html.erb
app/views/schools/advice/baseload/_weekday_variation_breakdown_table.html.erb
app/views/schools/advice/electricity_costs/_cost_breakdown_by_meter.html.erb
app/views/schools/advice/electricity_long_term/_meter_breakdown.html.erb
app/views/schools/advice/gas_costs/_cost_breakdown_by_meter.html.erb
app/views/schools/advice/gas_long_term/_meter_breakdown.html.erb
config/locales/views/advice_pages/baseload.yml
config/locales/views/advice_pages/electricity_costs.yml
config/locales/views/advice_pages/electricity_long_term.yml
config/locales/views/advice_pages/gas_costs.yml
config/locales/views/advice_pages/gas_long_term.yml

Improve sorting of gas & electricity meter breakdown tables

---

app/services/amr/single_read_converter.rb
spec/services/amr/single_read_converter_spec.rb

It seems like Excel sometimes adds extra blank rows to the end of exported CSV files. This is causing some manually converted files to fail to load as the system is not expecting an empty row.
Improve tolerance of the SingleReadConverter to skip rows without an mpan or date. Normally these would be caught and rejected in the next step of processing.

Ignore invalid rows in single read converter

---

app/controllers/school_groups_controller.rb
app/helpers/application_helper.rb
app/helpers/school_groups_helper.rb
app/models/alert_type.rb
app/models/management_priority.rb
app/services/school_groups/priority_actions.rb
app/views/school_groups/_priority_action_modal.html.erb
app/views/school_groups/priority_actions.html.erb
config/locales/views/school_groups/school_groups.yml
spec/services/school_groups/priority_actions_spec.rb
spec/system/school_groups_spec.rb

Initial spike of creating a summary of priority actions for school groups.
Things to ensure we've tested and resolved:

Priority actions for school groups

---

lib/tasks/jobs/send_good_job_queue_metrics_to_cloudwatch.rake

When we first starting using GoodJob we started logging all available metrics for the queues.
Now that we've had it running for a while, its clear that the main thing we want to monitor is the size of the queue. As this shows how quickly the queues get processed.
This PR updates the rake task that logs the metrics to just record that information.

Reduce CloudWatch logging of GoodJob queues

---

app/views/school_groups/recent_usage.html.erb
spec/support/school_groups_shared_examples.rb
spec/system/school_groups_spec.rb

Makes the recent usage page tolerant of 2 cases of limited data:
* If a school is not yet data enabled, then there isn't a summary of recent usage. But the school should be in the list
* If a school has <1 year of data, then there is no year data in the summary of recent usage
The PR also includes some display tweaks:
* Ensure table values are right aligned
* Switch table ordering, to put school names on left, which feels more natural
* Put "School" title on second header row
* Replace "n/a" with a "-"
The PR also tidies up the system spec for the page:
* remove unneeded declared variables
* move other variables inside the 'describe' block where they are used, to make it clearer how they are used
* DRY up repeated checks by adding some shared examples
* Add placeholders where we don't …

Make recent usage tab tolerant of limited data

---

app/services/equivalences/generate_equivalences.rb

Help to track down an intermittent bug generating equivalances, add the id of the equivalence to the Rollbar error.

Tweak rollbar error reporting for equivalence errors

---

app/models/user_tariff.rb
spec/models/user_tariff_spec.rb

When entering a tariff, users can enter
- an agreed supply capacity (asc_limit_kw)
- an agreed availability charge
- an excess availability charge
To calculate their agreed availability cost we need the asc limit + the agreed availability charge. Similarly for the excess availability cost we need the supply capacity and the charge.
A previous bug fix stopped the asc supply capacity being provided if the other charges weren't present. But we weren't checking for whether the asc_limit_kw was present before adding the charges. This means that the analytics still produces an error.
This PR ensures we only provide the charges if the asc limit is present. This matches the note we have on the tariff editor to prompt users to enter the extra charge.

Only include agreed availability and excess availability charges if asc_limit_kw is present

---

app/controllers/admin/reports/solar_panels_controller.rb
app/models/meter_attribute.rb
app/views/admin/reports/index.html.erb
app/views/admin/reports/solar_panels/index.html.erb
config/routes.rb
spec/models/meter_attribute_spec.rb

Adds a new admin report to summarise the solar panel configuration across the site.
* Adds a new query to extract the configuration from the MeterAttributes model
* Adds new report to the admin reports section with a simple tabular view of the attributes, with links to school, meter and the configuration
This should help us take stock of which schools are using synthetic solar data and the size of the installations across the service.

Solar panel report

---

app/controllers/school_groups/chart_updates_controller.rb
app/views/layouts/application.html.erb
app/views/school_groups/_enhanced_header.html.erb
app/views/school_groups/chart_updates/index.html.erb
config/locales/views/school_groups/school_groups.yml
spec/support/school_groups_shared_examples.rb
spec/system/admin/school_groups_spec.rb
spec/system/group_admin/permissions_spec.rb

This pr 
For consistency with other group pages it also adds a breadcrumb

Add navbar to school group chart updates page

---

Gemfile
Gemfile.lock
app/models/management_priority.rb
app/services/school_groups/priority_actions.rb
app/views/school_groups/_priority_action_modal.html.erb
app/views/school_groups/priority_actions.html.erb
app/views/schools/advice/index/_priority_table.html.erb
config/locales/analytics/benchmarking/content_base.yml
config/locales/views/advice_pages/index.yml
spec/services/school_groups/priority_actions_spec.rb
spec/system/school_groups_spec.rb
spec/system/schools/advice_pages/advice_page_index_spec.rb

Updates the priority actions tables on the individual school group advice pages, plus the new school group dashboard to include the one year saving in energy use if the action is tackled.
The main code changes are in the analytics and this PR bumps the analytics version.
Otherwise there are changes to:
- the priority actions service which loads the data for the school groups
- the priority actions tab on the school advice page
- the priority actions tab and modal on the school group dashboard

Add one_year_saving_kwh to priority actions

---

app/components/school_group_comparison_component/school_group_comparison_component.html.erb
app/models/school_group.rb
app/services/school_groups/categorise_schools.rb
app/views/school_groups/comparisons.html.erb
config/locales/views/advice_pages/advice_pages.yml
spec/services/school_groups/categorise_schools_spec.rb

The general formatting tweaks were fine, the school comparisons stuff was rather complex just to add in fuel type...
This covers:
- Add in subtitles for each fuel type, with the relevant comparisons within each. The subtitles should be h2 to match the formatting of the section headings on the analysis pages
- The side of the various comparison components is misaligned with the rest of the page body. Looks like it might need a bootstrap row/col to align better.
- The font-size on the cards inside the comparison components is too large. Make them match the school comparison component (see screenshots)
This was already done:
- Change title in popup model. From, e.g. “ Baseload analysis • Well managed” to “Baseload analysis > Well managed” so its consistent with the breadcrumb
Where there is …

Formatting tweaks to school group comparisons tab

---

config/locales/views/advice_pages/gas_long_term.yml
config/locales/views/advice_pages/gas_out_of_hours.yml
config/locales/views/school_groups/school_groups.yml

Have changed this for all the gas comparisons on the school group pages.
Have changed the text on the gas_out_of_hours and gas_recent_changes advice pages - however the other gas ones seem to work differently so I have left those as is.

Change wording on gas insights "how do you compare" section

---

Gemfile
Gemfile.lock
lib/tasks/deployment/20230609115956_alert_solar_generation.rake
spec/system/schools/advice_pages/electricity_recent_changes_spec.rb
spec/system/schools/advice_pages/gas_recent_changes_spec.rb

This PR bumps the version of the analytics to 2.8.3
The two key changes in that version are these PRs which change how the costs for a solar installation are calculated, as well as how the solar self consumption and export is estimated when we are using synthetic data.
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/546
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/557
The PR also adds a new alert that is used to generate some data for a solar benchmark

Analytics 2.8.3 - solar changes

---

app/controllers/admin/reports/dcc_status_controller.rb
app/controllers/schools/meters_controller.rb
app/helpers/meters_helper.rb
app/services/meter_management.rb
app/views/admin/reports/dcc_status/index.html.erb
app/views/schools/meters/_form.html.erb
app/views/schools/meters/show.html.erb
config/locales/cy/views/schools/schools.yml
config/locales/views/schools/schools.yml
config/routes.rb
spec/services/meter_management_spec.rb
spec/system/meter_management_spec.rb

This PR has some improvements to our admin pages to help to support debugging and investigation of issues with n3rgy meters.
This includes improvements to the dcc meter report to list:
* ignore sandbox meters
* include number of schools with meters
* add a check to see if n3rgy think the meter has been consented
* include a list of the mpans that n3rgy think are consented
And some changes to the meter page for admins:
* Remove the "elements" data
* Remove the "earliest available date" field as its unused
* Improve some of the labelling to explain fields
* Show the symbol describing the status of the meter in n3rgy, rather than just a true/false flag
* Check to see if the mpan_mprn is in the list of consented meters in n3rgy
* Include the available date range

N3rgy tooling

---

app/controllers/schools/meters_controller.rb
app/services/meter_management.rb
app/services/meter_review_service.rb
app/views/schools/meters/_inactive_meters.html.erb
app/views/schools/meters/index.html.erb
app/views/schools/meters/show.html.erb
config/locales/cy/views/schools/schools.yml
config/locales/views/schools/schools.yml
spec/services/meter_management_spec.rb
spec/services/meter_review_service_spec.rb
spec/system/admin/meter_reviews/meter_reviews_spec.rb
spec/system/meter_management_spec.rb

Changes to admin interface to better display information from the n3rgy API introduced an issue with the Meter Review process. A method that should have been returning a boolean was not returning a symbol. This meant that reviews cannot be processed.
This PR fixes that issue by adding a new method in MeterManagement to check whether a meter is in n3rgy, separate from its "status" which returns one of several different symbols.
As part of implementing the fix I've further tidied up the diagnostic information to:
* ensure its only displayed to admins
* reduce number of API calls if a meter isn't known to n3rgy
* fix up some minor display issues and further improve the diagnostics

Fix bug with n3rgy status check

---

app/models/meter.rb
app/views/admin/school_groups/_default_issues_admin_user.html.erb
app/views/admin/school_groups/show.html.erb
app/views/schools/meters/index.html.erb
app/views/shared/_manage_school.html.erb
config/locales/cy/views/schools/schools.yml
config/locales/views/schools/schools.yml
spec/models/meter_spec.rb
spec/system/admin/meter_reviews/meter_reviews_spec.rb
spec/system/admin/school_creation_spec.rb
spec/system/meter_management_spec.rb
spec/system/schools/user_tariffs_spec.rb

This PR covers a number of small cosmetic changes to the meters index page to tidy up the page for admin users:

Tidy up admin options on school manage meters page

---

app/views/admin/index.html.erb
app/views/admin/scoreboards/index.html.erb
spec/system/admin/school_groups_spec.rb

Update links and titles for managing school groups and scoreboards on admin page

---

app/controllers/admin/reports/unvalidated_readings_controller.rb
app/models/amr_data_feed_reading.rb
app/views/admin/reports/index.html.erb
app/views/admin/reports/unvalidated_readings/show.html.erb
config/routes.rb
spec/models/amr_data_feed_reading_spec.rb

This PR adds a new admin report that summarises data the unvalidated data in the `AmrDataFeedReading` table for a list of mpans.
The admins need to be able to confirm the latest reading dates for a given list of mpans. Sometimes those mpans are associated with meters, but sometimes they are not yet linked to meters. E.g. if they are starting to load data before the school has been onboarded.
Checking the dates allows them to re-request data from suppliers on a weekly basis, where those feeds are not fully automated.
Creating this type of report is tricky as the `AmrDataFeedReading` `reading_date` column is an unparsed date: we parse it when validating the data. That will get changed in the next few months but, for now I've written a query that is capable of converting the range of date …

Provide tool for admin to check ranges of unvalidated data for a list of meters

---

app/services/school_groups/recent_usage_csv_generator.rb
app/services/school_groups/schools_priority_action_csv_generator.rb
config/locales/views/school_groups/school_groups.yml
spec/services/school_groups/recent_usage_csv_generator_spec.rb
spec/services/school_groups/schools_priority_action_csv_generator_spec.rb
spec/system/school_groups_spec.rb

Have used an existing translation floor_area from activerecord.yml that is “Floor area in square metres”. Do we want to use this or just “Floor area” with no units?

Add floor area and pupil numbers to CSV download for recent usage tab and priority downloads

---

lib/amr/importer.rb
spec/lib/amr/importer_spec.rb

When looking at disk space issues on the servers I noticed that were weren't removing local copes of CSV files after they had been successfully processed.
This PR just adds an extra File.delete step if a file is successfully archived in S3. 
The rest of the changes are just refactoring of the importer and the spec to reduce the amount of code/configuration.

Remove local files when archived to s3

---

app/models/amr_reading_data.rb
app/views/admin/amr_uploaded_readings/new.html.erb
spec/services/amr/csv_parser_and_upserter_spec.rb
spec/system/admin/amr_uploaded_readings_spec.rb

A data feed config can be configured to lookup meters by serial number. The admins need to add these to the database. 
If all the serial numbers in a file are missing, then this leads to an error as we have no valid readings in the file. This PR just tweaks the error reporting on the admin form to prompt them to check for this where necessary.
Also ensured there's different messages for "unable to parse file" and "no valid readings" as those are different situations.

Clarify error message for admin when uploading files that find meters using serial numbers

---

app/assets/stylesheets/colours.scss
app/assets/stylesheets/school.scss
app/components/school_group_comparison_component/school_group_comparison_component.html.erb
app/helpers/advice_page_helper.rb
app/models/alert_type_rating.rb
app/models/school.rb
app/services/school_groups/priority_actions_csv_generator.rb
app/services/school_groups/schools_priority_action_csv_generator.rb
app/views/school_groups/_enhanced_header.html.erb
app/views/school_groups/_priority_action_modal.html.erb
app/views/school_groups/comparisons.html.erb
app/views/school_groups/current_scores.html.erb
app/views/school_groups/map.html.erb
app/views/school_groups/priority_actions.html.erb
app/views/school_groups/recent_usage.html.erb
app/views/schools/advice/index/_priority_table.html.erb
config/i18n-tasks.yml
config/locales/views/advice_pages/advice_pages.yml
config/locales/views/advice_pages/index.yml
config/locales/views/school_groups/school_groups.yml
spec/components/school_group_comparison_component_spec.rb
spec/services/school_groups/current_scores_csv_generator_spec.rb
spec/services/school_groups/priority_actions_csv_generator_spec.rb
spec/services/school_groups/recent_usage_csv_generator_spec.rb
spec/services/school_groups/schools_priority_action_csv_generator_spec.rb
spec/support/school_group_shared_contexts.rb
spec/support/school_groups_shared_examples.rb
spec/system/school_groups_spec.rb
spec/system/schools/advice_pages/advice_page_index_spec.rb

This PR has a number of text and UX improvements to the school group dashboard. 
Unfortunately it's snowballed a bit as I've been tweaking. The changes are primarily to add new text to the pages, tidy up styling and layout.
Summary of changes:
* Add introductory text to each tab to explain what is on the page
* Styling updates for all of the buttons to match school dashboard
* Addition of fuel type icons and in-page navigation on the comparison tab
* Additional of explanatory text to the popups for school comparison, along with styled category names
* Moving scoreboard link into the current scores tab, and tweaked font size to more prominently show schools with scores
* Added introductory text to the priority action modals so there's some explanation of the analysis
* Moved the units in …

Tidy UX and add extra explanatory text to school group pages

---

app/controllers/school_groups_controller.rb
app/services/school_groups/recent_usage_csv_generator.rb
app/views/school_groups/recent_usage.html.erb
config/locales/views/school_groups/school_groups.yml
spec/services/school_groups/recent_usage_csv_generator_spec.rb
spec/support/school_group_shared_contexts.rb
spec/system/school_groups_spec.rb

This PR changes the CSV downloads for the Recent usage tab on the school group dashboard.
Instead of having separate downloads for each metric, we instead have a single download that includes all of the metrics (%, kwh, £, co2) for both periods (last week, last year) for all fuel types. This is intended to be a convenience for anyone intending to do any analysis that would otherwise involve downloading and combining separate files.
The tests have been revised to use separate values for each fuel type to better check that the right values are in the right columns. 
I've also simplified the system spec so its just checking that the download is available and that the generated file name is correct. The service spec already covers the format and content of the CSV.

Combine csv downloads for recent usage tab on school group dashboard

---

app/controllers/admin/settings_controller.rb
app/models/activity.rb
app/models/observation.rb
app/models/site_settings.rb
app/views/activities/_form.html.erb
app/views/admin/settings/show.html.erb
app/views/schools/interventions/_form.html.erb
config/locales/views/activities/activities.yml
config/locales/views/interventions/interventions.yml
db/migrate/20230719141228_add_photo_bonus_points_to_site_settings.rb
db/schema.rb
spec/models/observation_spec.rb

This PR changes the scoring system for both pupil and adult lead activities so that bonus points are awarded if the school adds one or more photos to the description.

Award bonus points for adding photos to activities and actions

---

app/models/energy_tariff.rb
app/models/energy_tariff_charge.rb
app/models/energy_tariff_price.rb
app/models/meter.rb
app/models/school.rb
app/models/school_group.rb
app/models/user_tariff.rb
db/migrate/20230724142054_create_energy_tariffs.rb
db/schema.rb
spec/factories/energy_tariffs.rb
spec/models/energy_tariff_spec.rb

This PR creates a new set of data models and relationships for managing energy tariffs.
It builds on the existing "user tariff" models used by the tariff editor, but generalises them so they are a bit more flexible and extensible. Specifically it allows tariffs to be owned by any `tariff_holder` model which will include the system, groups and schools.
This PR will just add the models, a later PR will include some data migration code.

New common data model for storing energy tariffs

---

spec/rails_helper.rb

Fix for an issue with incorrect Chrome driver version being used.
Issue described here: https://github.com/titusfortner/webdrivers/issues/247
For the moment pinning the version looks like best approach, as switching to use Selenium only has other issues (a number of deprecations and latest version of the gem isn't available for our version of Ruby).

Pin version of chrome driver

---

Gemfile
Gemfile.lock
app/views/shared/meter_attributes/_new_select.html.erb
lib/tasks/deployment/20230725161734_remove_meter_consolidation_alert.rake

Removes the meter consolidation alerts:

Remove unused meter consolidation alerts

---

app/models/energy_tariff.rb
app/models/site_settings.rb
app/services/database/energy_tariff_migration_service.rb
lib/tasks/deployment/20230725132841_migrate_to_energy_tariffs.rake
spec/services/database/energy_tariff_migration_service_spec.rb

This PR adds another step to the data migration for tariffs:
* Creates a separate service to do the migration of user tariffs and global meter attributes. This makes it easier to test and possibly re-run the migration
* Update the after party task to call this step, but remove the "delete all", so we're a little more cautious when doing the migration
* Allows EnergyTariff to be owned by SiteSettings
* Adds some basic specs for the initial migration steps
I'll do the migration of SchoolGroup and School attributes in a later PR. This is a little more involved as we need to selectively migrate some attributes and finesse some of the time ranges.

Add migration for global meter attributes

---

Gemfile
Gemfile.lock

Update analytics to version that has unneeded tariff code removed https://github.com/Energy-Sparks/energy-sparks_analytics/pull/577
Want to release this to test to rule out any issues when run against test database.

Analytics 2.9.0

---

app/services/database/energy_tariff_migration_service.rb
spec/services/database/energy_tariff_migration_service_spec.rb

This PR adds extra code to migrate SchoolGroup meter attributes to the new tariff data model.
The main entry point is the `migrate_school_group_meter_attributes` method. This decides whether to migrate the group's economic tariffs or accounting tariffs.
As the team are currently prioritising populating the economic tariffs to follow latest prices, we use those over the accounting tariffs which may be incomplete or out of date. 
When migrating the economic tariffs if the tariff specifies both flat and differential rates, then we just migrate the differential rates. This is because the MeterAttribute editor has the flat rate marked as a required field. But we won't need both tariff types once migrated.
As economic tariffs don't have charges, we just migrate the prices.
If a school group has …

Add code for migrating school group tariffs

---

app/services/database/energy_tariff_migration_service.rb
spec/services/database/energy_tariff_migration_service_spec.rb

Updates the Energy Tariff migration code to finalise the basic migration code for the following:
In a follow-up PR I'll add:
- some code for running the set of migrations
- some code for doing some precondition checks to confirm that basic assumptions are correct prior to doing a migration

Migrate school and meter tariffs

---

spec/system/admin/reports/unvalidated_readings_spec.rb

The spec is checking for the meter id to be present, although that's no longer included on the page.
I think this is sometimes passing when the meter id matches another value on the page. But this is seems to be regularly failing in builds:
https://github.com/Energy-Sparks/energy-sparks/actions/runs/5726381033/job/15516710682

Remove meter id check in unvalidated meter report spec

---

Gemfile
Gemfile.lock
app/models/energy_tariff.rb
app/views/shared/meter_attributes/_date_time.html.erb
spec/models/energy_tariff_spec.rb

Updates the EnergyTariff model so that when it serialises as a meter attribute it identifies the type of tariff holder and the date that the tariff was created.
Requires updates to analytics from this PR: https://github.com/Energy-Sparks/energy-sparks_analytics/pull/580. Until then tests will fail.

Add tariff holder and creation date to tariff meter attribute

---

app/helpers/energy_tariffs_helper.rb
app/views/energy_tariffs/energy_tariff_charges/index.html.erb
app/views/energy_tariffs/energy_tariff_differential_prices/index.html.erb
app/views/energy_tariffs/energy_tariff_flat_prices/edit.html.erb
app/views/energy_tariffs/energy_tariff_flat_prices/new.html.erb
app/views/energy_tariffs/energy_tariffs/_energy_tariffs_summary_table.html.erb
app/views/energy_tariffs/energy_tariffs/_header.html.erb
app/views/energy_tariffs/energy_tariffs/_meters.html.erb
app/views/energy_tariffs/energy_tariffs/edit.html.erb
app/views/energy_tariffs/energy_tariffs/new.html.erb
app/views/schools/user_tariff_charges/index.html.erb
app/views/schools/user_tariff_differential_prices/index.html.erb
config/locales/common.yml
config/locales/cy/views/schools/user_tariffs.yml
config/locales/views/schools/user_tariffs.yml

This PR tidies up some of the wording on the SiteSettings version of the Energy Tariff editor:

Tidy up wording on SiteSettings version of Tariff editor

---

app/controllers/school_groups_controller.rb
spec/system/school_groups_spec.rb

We seem to have crawlers or bots hitting the school group comparison page to download CSV, but not adding the parameter for the advice page key. This is adding a bunch of errors to Rollbar.
Update the controller plus add spec to return a 400 error if the parameter isn't replied. This should hopefully discourage them!

Return error if require param is missing

---

app/controllers/admin/reports/energy_tariffs_controller.rb
app/models/energy_tariff.rb
app/views/admin/index.html.erb
app/views/admin/reports/energy_tariffs/index.html.erb
app/views/admin/reports/index.html.erb
app/views/admin/reports/tariffs/index.html.erb
config/routes.rb
spec/factories/energy_tariffs.rb
spec/models/energy_tariff_spec.rb
spec/system/admin/reports/energy_tariffs_report_spec.rb

Creates a new report for admins that lists:
- which school groups have Energy Tariffs configured
- how many schools in those groups have their own school level tariffs
- how many schools in those groups have DCC tariffs
...along with links to more information where currently available. This is intended to give an overview of current state of tariffs. The individual group and school pages will provide more information.
The PR declares two new associations on EnergyTariffs which makes it possible to do:
```
EnergyTariff.joins(:school)
EnergyTariff.joins(:school_groups)
```
Which allows joining against those models when doing queries.

Admin report for school group tariffs

---

app/controllers/energy_tariffs/energy_tariffs_controller.rb
app/models/meter.rb
app/views/energy_tariffs/energy_tariffs/choose_meters.html.erb
config/locales/views/schools/user_tariffs.yml
spec/support/energy_tariff_shared_examples.rb

Currently we require users to choose one or more meters when creating a School tariff.
But we want to allow the creation and editing of tariffs that apply to all meters of a type at a school, not just specific meters.
This PR updates the "choose meters" stage of tariff creation to allow user to decide whether to add meters.
- add a check box to the form to prompt user whether they want to add meters, default is now that a tariff is for any meter
- update validation check to be aware of users choice
- update specs to check for validation changes and selections
- add missing translation for error message and new translations for extra form text.

Allow meters to be optional on School tariff editor

---

app/models/ability.rb
app/views/energy_tariffs/energy_tariffs/_energy_tariffs_summary_table.html.erb
app/views/energy_tariffs/energy_tariffs/_energy_tariffs_tab_school.html.erb
app/views/energy_tariffs/energy_tariffs/_energy_tariffs_tab_school_groups.html.erb
app/views/energy_tariffs/energy_tariffs/_energy_tariffs_tab_site_settings.html.erb
app/views/energy_tariffs/energy_tariffs/index.html.erb
spec/factories/users_factory.rb
spec/support/energy_tariff_shared_examples.rb
spec/support/energy_tariffs_shared_contexts.rb
spec/system/admin/settings/energy_tariffs_spec.rb
spec/system/school_groups/energy_tariffs_spec.rb
spec/system/schools/energy_tariffs_spec.rb

This PR tries to DRY up the tariff editor specs a bit more by:
- introducing some shared context
- removing `let` calls variables where they are not required, or can be defaulted
- refactoring the specs to make more use of shared examples
It also fixes an issue with the ability file which as causing an intermittent test failure.

Tidy up tariff specs

---

app/controllers/energy_tariffs/energy_tariff_charges_controller.rb
app/controllers/energy_tariffs/energy_tariff_differential_prices_controller.rb
app/controllers/energy_tariffs/energy_tariff_flat_prices_controller.rb
app/controllers/energy_tariffs/energy_tariff_prices_controller.rb
app/services/energy_tariff_default_prices_creator.rb
app/views/energy_tariffs/energy_tariff_charges/index.html.erb
app/views/energy_tariffs/energy_tariff_differential_prices/edit.html.erb
app/views/energy_tariffs/energy_tariff_differential_prices/index.html.erb
app/views/energy_tariffs/energy_tariff_differential_prices/new.html.erb
app/views/energy_tariffs/energy_tariff_flat_prices/edit.html.erb
app/views/energy_tariffs/energy_tariff_flat_prices/new.html.erb
app/views/energy_tariffs/energy_tariffs/_smart_meter_tariffs_tab_school.html.erb
app/views/energy_tariffs/energy_tariffs/show.html.erb
spec/support/energy_tariff_shared_examples.rb

There were several issues with the tariff editor:
- Differential Prices weren't being added for School tariffs if there were no meters. Fixed the logic to use the defaults in that case
- There were a lot of partials that were called with a `school: @school` variable but the variable wasn't being used in the partials. So have removed that to avoid confusion and clarify the interface to the partials
- Updated the other tariff controllers to use `tariff_holder` as the instance name for the loaded model
- Fixed some redirect routes in controllers. One of which was stopping prices being edited for School Group tariffs
- Fix up the tariff show page to ensure that the Edit links for Prices and Charges are displayed for all tariff holder types (they were missing for School Group) and added a spec …

Fix additional issues with tariff editor

---

Gemfile
Gemfile.lock
app/models/global_meter_attribute.rb
app/models/meter.rb
app/models/parent_meter_attribute_holder.rb
app/models/school.rb
spec/models/meter_spec.rb
spec/models/school_spec.rb
spec/system/admin/settings/energy_tariffs_spec.rb
spec/system/school_groups/energy_tariffs_spec.rb
spec/system/schools/energy_tariffs_spec.rb

Switch to use `FEATURE_FLAG_NEW_ENERGY_TARIFF_EDITOR` / `:new_energy_tariff_editor`
Includes a bump to the analytics as the feature flag is in use there too.

Change feature flag name for new tariff editor

---

app/helpers/energy_tariffs_helper.rb
app/views/energy_tariffs/energy_tariff_charges/_charge_basic_row.html.erb
app/views/energy_tariffs/energy_tariff_flat_prices/_form.html.erb

Improves the display of errors on the flat rate price and charges forms.
Originally the errors were just using a default error block. I've updated the form fields to check for errors and then provide a custom error message via the SimpleForm `error` attribute on the field.
I've also fixed an issue with form values not displaying properly if they don't match the underlying type. See the `value_allowing_for_errors` helper. This was mainly to catch problems with a user typing a string into the field.
However I also noticed that while we were adding `pattern` to the form fields they were being ignored in some cases. So I've tweaked the fields to be numeric which means you can no longer enter anything except a number. 
So the `value_allowing_for_errors` helper is probably not needed, but have …

Improve error reporting on tariff forms

---

app/components/energy_tariff_table_component.rb
app/components/energy_tariff_table_component/energy_tariff_table_component.html.erb
app/components/energy_tariffs_component/energy_tariffs_component.html.erb
config/locales/cy/views/schools/user_tariffs.yml
config/locales/views/schools/user_tariffs.yml
spec/components/energy_tariffs_table_component_spec.rb
spec/support/energy_tariff_shared_examples.rb

When people are reviewing and editing tariffs the most common things to do will be to check dates and prices.
This PR updates the tariff table component to:
- include consumption charges column (but these can be switched off as an option)
- remove the "View details" link in favour of making the tariff name a link
- tidy up the table alignment by adding some `col-x` and text alignment classes

Add option to show prices

---

app/models/energy_tariff.rb
app/views/energy_tariffs/energy_tariffs/_charges_table.html.erb
app/views/energy_tariffs/energy_tariffs/show.html.erb
config/locales/views/schools/user_tariffs.yml
spec/support/energy_tariff_shared_examples.rb

Adds a note to to say if there's no standing charges configured, rather than leaving an empty space.
Also adds a proper page title and replaces use of `<br/>` with bootstrap spacers.

Add a note if there are no standing charges

---

app/views/energy_tariffs/energy_tariffs/_form_meter_choices.html.erb
app/views/energy_tariffs/energy_tariffs/choose_meters.html.erb
app/views/energy_tariffs/energy_tariffs/edit_meters.html.erb
spec/support/energy_tariff_shared_examples.rb

Revises the "edit meters" flow so that it uses the same form as the "choose meters" step. I've retained the routes and form due to the different contexts (with and without a tariff).

Allow user to change tariff to all meters

---

app/models/chart_data_values.rb
spec/models/chart_data_values_spec.rb

We have a number of dependabot PRs which are all failing with the same error:
https://github.com/Energy-Sparks/energy-sparks/actions/runs/5713575489/job/15900364828?pr=2939
```
+"Translation missing: en.analytics.series_data_manager.series_name.Electricity consumed from mains" => "#007EFF",
+"Translation missing: en.analytics.series_data_manager.series_name.Exported solar electricity (not consumed onsite)" =>        -"translation missing: en.analytics.series_data_manager.series_name.Electricity consumed from mains" => "#007EFF",
-"translation missing: en.analytics.series_data_manager.series_name.Exported solar electricity (not consumed onsite)" =>      # ./spec/models/chart_data_values_spec.rb:155:in `block (3 levels) in <top (required)>'
```
Looks like somewhere in the recent dependency …

Add I18N key constants

---

Gemfile
Gemfile.lock
app/services/energy_tariff_default_prices_creator.rb
app/services/meters/economy7_times.rb

Update to new version of analytics with fix to tariff manager that stops an error on pages where we display the "tariff  caveats".

Fix error when reporting tariffs have changed

---

app/components/energy_tariffs_component/energy_tariffs_component.html.erb
app/models/tariff_price.rb
app/models/tariff_standing_charge.rb
lib/tasks/deployment/20230821130012_remove_duplicate_dcc_tariffs.rake
spec/models/tariff_standing_charge_spec.rb

Removes duplicate TariffPrice and TariffStandingCharge records if they are the same as the previous record for that meter.
Also fixes a bug in display of migrated smart meter tariffs

Remove duplicate dcc tariffs and charges

---

app/components/energy_tariff_table_component.rb
app/components/energy_tariff_table_component/energy_tariff_table_component.html.erb
app/components/energy_tariffs_component.rb
app/components/energy_tariffs_component/energy_tariffs_component.html.erb
app/helpers/energy_tariffs_helper.rb
app/models/concerns/energy_tariff_holder.rb
app/models/energy_tariff.rb
app/models/energy_tariff_charge.rb
app/models/energy_tariff_price.rb
app/views/energy_tariffs/energy_tariffs/show.html.erb
app/views/energy_tariffs/energy_tariffs/toggle_enabled.js.erb
config/locales/views/schools/user_tariffs.yml
spec/components/energy_tariffs_table_component_spec.rb
spec/support/energy_tariff_shared_examples.rb

If a tariff is disabled then
* Flag the table row in a different colour
* Do not include it in the list of default tariffs
If a tariff is not usable
* Flag the table row in a different colour
* Add a notice to the tariff page with a link to edit the prices

Add visual cues to tariffs table

---

app/models/energy_tariff.rb
spec/models/energy_tariff_spec.rb

I didn't add a test for this originally and then tweaked the SQL before committing which broke the ordering.
Have fixed the SQL and added a basic test.

Fix sort order on tariffs table

---

app/components/date_picker_form_component.rb
app/views/energy_tariffs/energy_tariffs/_form.html.erb
spec/components/date_picker_form_component_spec.rb

The DateTimePicker component currently defaults to today's date if a value isn't provided.
This isn't the intended behaviour when editing tariffs, where an empty date should remain unpopulated. Rather than set a default in the form I've made the default value configurable on the component.
This preserves behaviour elsewhere in the application but allows an empty value to be provided on the tariff form.

Allow tariffs dates to be empty

---

app/views/energy_tariffs/energy_tariff_charges/_charge_basic.html.erb
app/views/energy_tariffs/energy_tariff_charges/_charge_basic_row.html.erb
app/views/energy_tariffs/energy_tariff_charges/_charges_edit_electricity.html.erb
app/views/energy_tariffs/energy_tariff_charges/_charges_edit_gas.html.erb
app/views/energy_tariffs/energy_tariff_charges/index.html.erb
config/locales/views/schools/user_tariffs.yml

Smart meter tariffs, when imported have prices and a single type of standing charge.
We want to allow users to edit the other charges associated with the tariff but not the prices or that standing charge.
This PR fixes a bug with editing charges by disabling the form field for the `:standing_charge` `charge_type` but allows others types of charges to be updated.

Disable standing charge form fields for smart meter tariffs

---

app/components/date_picker_form_component.rb
app/components/date_picker_form_component/date_picker_form_component.html.erb
app/components/energy_tariff_form_title_component.rb
app/components/energy_tariff_table_component.rb
app/components/energy_tariffs_component/energy_tariffs_component.html.erb
app/views/energy_tariffs/energy_tariff_charges/_charge_ccl.html.erb
app/views/energy_tariffs/energy_tariff_charges/_charge_tnuos.html.erb
app/views/energy_tariffs/energy_tariff_charges/index.html.erb
app/views/energy_tariffs/energy_tariff_differential_prices/index.html.erb
app/views/energy_tariffs/energy_tariff_flat_prices/edit.html.erb
app/views/energy_tariffs/energy_tariff_flat_prices/new.html.erb
app/views/energy_tariffs/energy_tariffs/_energy_tariffs_tab.html.erb
app/views/energy_tariffs/energy_tariffs/_form.html.erb
app/views/energy_tariffs/energy_tariffs/choose_type.html.erb
app/views/energy_tariffs/energy_tariffs/edit.html.erb
app/views/energy_tariffs/energy_tariffs/index.html.erb
app/views/energy_tariffs/energy_tariffs/new.html.erb
config/locales/cy/views/schools/user_tariffs.yml
config/locales/views/schools/user_tariffs.yml
spec/components/date_picker_form_component_spec.rb
spec/components/energy_tariffs_table_component_spec.rb
spec/support/energy_tariff_shared_examples.rb

**Site Setting Tariffs**
**New and Edit Tariff forms**
**Choose tariff type form**
**Standing charges form**
**Default tariffs tab**
**User supplied tariffs tab**
**All energy tariff forms/pages:**

Tariff editor text updates

---

app/components/energy_tariff_table_component/energy_tariff_table_component.html.erb
app/controllers/energy_tariffs/energy_tariff_charges_controller.rb
app/controllers/energy_tariffs/energy_tariff_differential_prices_controller.rb
app/controllers/energy_tariffs/energy_tariff_flat_prices_controller.rb
app/controllers/energy_tariffs/energy_tariffs_controller.rb
app/helpers/energy_tariffs_helper.rb
app/views/energy_tariffs/energy_tariff_charges/index.html.erb
app/views/energy_tariffs/energy_tariff_differential_prices/index.html.erb
app/views/energy_tariffs/energy_tariff_flat_prices/edit.html.erb
app/views/energy_tariffs/energy_tariff_flat_prices/new.html.erb
app/views/energy_tariffs/energy_tariffs/_form.html.erb
app/views/energy_tariffs/energy_tariffs/choose_meters.html.erb
app/views/energy_tariffs/energy_tariffs/choose_type.html.erb
app/views/energy_tariffs/energy_tariffs/edit_meters.html.erb
app/views/energy_tariffs/energy_tariffs/show.html.erb
config/locales/common.yml
config/locales/cy/views/schools/user_tariffs.yml
config/locales/views/schools/user_tariffs.yml
config/routes.rb
spec/support/energy_tariff_editors_shared_examples.rb
spec/support/energy_tariffs_shared_examples.rb
spec/system/admin/settings/energy_tariffs_spec.rb
spec/system/school_groups/energy_tariffs_spec.rb
spec/system/schools/energy_tariffs_spec.rb

This is a large refactor of the editor flow and the associated specs.
The key changes are to:
* Remove the "wizard" style interface with previous and next buttons in favour of providing an initial form, then allowing the user to navigate from the energy tariff page to add specific elements
* Use this to refactor the specs to allow more reuse and make it easier to test specific parts of the editor interface
* Allow the type of tariff to be changed, e.g. switch between flat rate and differential, although this requires removing prices
Along the way I also fixed an issue with the EnergyTariff.last_updated_by not updating if we just edit tariffs and charges.
Following this, there's a need to do UX tidy, but this is the basic changes.

Remove use of previous next buttons

---

app/controllers/admin/settings_controller.rb
spec/system/admin/settings_spec.rb

The admin site settings controller currently creates a new record when settings are updated, rather than updating the existing record. This works because we use `SiteSettings.current` to access the settings, so older records are ignored.
However, now that the energy tariffs are linked to the SiteSettings record creating a new record means we lose the association with tariffs, which causes a major problem with regenerating schools.
I think the intention is that the SiteSettings is meant to be a "singleton" rather than maintaining a history (which we don't need as we don't display or report on the history). So I've updated the controller to do a more conventional update to the existing record rather than creating a new one.
The PR has a small change to the controller and revisions to the …

Update existing SiteSettings record

---

lib/tasks/deployment/20230725132841_migrate_to_energy_tariffs.rake

Database::EnergyTariffMigrationService.migrate_user_tariffs was removed in this PR: https://github.com/Energy-Sparks/energy-sparks/pull/3025, however it is still referenced by 20230725132841_migrate_to_energy_tariffs.rake which I've just been trying to run.
I have removed the reference for now as it was tricky to unpickle otherwise (think I would have needed to rollback irreversible migrations). Is really only is me that it will affect for now, just means I could run all the other after_party tasks.
I might need to grab a database dump at some point though with the migrated user tariffs in, assuming that's what it does.

Remove reference to deleted service in after party task

---

app/controllers/schools/meters_controller.rb
app/mailers/import_mailer.rb
app/models/data_source.rb
app/models/energy_tariff.rb
app/models/meter.rb
app/models/procurement_route.rb
app/services/school_groups/meter_report.rb
app/views/admin_mailer/school_data_source_report.html.erb
app/views/import_mailer/_meter_table.html.erb
app/views/schools/meters/_active_meters.html.erb
app/views/schools/meters/_form.html.erb
app/views/schools/meters/_inactive_meters.html.erb
app/views/schools/meters/index.html.erb
app/views/shared/_school_group_meter_report.html.erb
config/locales/models/meter.yml
config/locales/views/schools/schools.yml
db/migrate/20230907122423_add_meter_system_to_meter.rb
db/migrate/20230907123002_remove_half_hourly_column_from_meter.rb
db/schema.rb
spec/mailers/import_mailer_spec.rb
spec/models/data_source_spec.rb
spec/models/procurement_route_spec.rb

Add an meter system options to Energy Tariff

---

app/controllers/schools_controller.rb
app/views/schools/show.html.erb
spec/system/schools/dashboard/prompts_spec.rb

Logic for training prompt should be: if we are showing the data enabled features (and so its worth the school attending training) then prompt the user to sign up if they confirmed their account in the last 60 days. Currently it always seems to be displaying? Also suggest we reduce the window for the training prompt to 30 days.
Refactored the rspec after removing the standard prompts spec - now also includes spec for school dashboard messages (as well as school group dashboard messages), along with spec for the training prompt.

Reduce clutter on adult dashboard

---

app/views/devise/sessions/new.html.erb

Small change to checkbox css that was merged earlier...

Make checkbox align left on mobile (not centre as it was doing)

---

app/helpers/chart_helper.rb
app/views/pupils/analysis/show.html.erb
spec/helpers/chart_helper_spec.rb

Schools can set their default preferences for how we display charts.
However some of the pupil pages involve exploring the data, allowing users to request specific views. At the moment, for some of these charts (those on the "pupil analysis" pages) the school level preference is overriding what the user has requested to see.
Some of these charts also currently have hard-coded titles and descriptions that refer to costs. 
This PR fixes that bug by displaying use of the preference for just those charts. Other charts will use the school preference.

Disable use of preferences on the pupil analysis charts only

---

app/mailers/onboarding_mailer.rb
app/views/onboarding_mailer/completion_email.html.erb
config/locales/mailers/mailer.yml
spec/mailers/onboarding_mailer_spec.rb
spec/mailers/previews/onboarding_mailer_preview.rb
spec/support/admin_school_group_onboardings.rb
spec/system/admin/school_onboarding_spec.rb
spec/system/school_onboarding_spec.rb

Small request from ops team: add the school group name to the internal emails sent when schools have completed onboarding.
The PR also adds mailer previews for all the onboarding emails.

Add school group to admin email

---

app/assets/javascripts/schools.js
app/components/info_bar_component/info_bar_component.html.erb
app/controllers/concerns/dashboard_alerts.rb
app/views/schools/_engagement_prompts.html.erb
app/views/schools/show.html.erb
app/views/shared/_dashboard_alerts.html.erb
config/locales/cy/views/schools/schools.yml
config/locales/cy/views/shared/shared.yml
config/locales/views/schools/schools.yml
config/locales/views/shared/shared.yml
spec/components/info_bar_component_spec.rb

Until we have implemented the rest of the new engagement options, add back in the prompts to record adult and pupil lead activities on the dashboard.
Also, rather than have a dynamic section with up to 3 alerts on the dashboard, we will now show 2 by default and then a link to all of the "Recent alerts" in the advice pages.

Add back in adult dashboard prompts

---

app/assets/stylesheets/energy_tariffs.scss
app/models/energy_tariff_price.rb
app/views/energy_tariffs/energy_tariff_flat_prices/_form.html.erb
spec/factories/energy_tariffs.rb
spec/models/energy_tariff_price_spec.rb
spec/models/energy_tariff_spec.rb
spec/support/energy_tariff_editors_shared_examples.rb
spec/support/energy_tariffs_shared_examples.rb

Also widens field, as previously, any longer numbers were being partially covered by the up/down arrows: 
After PR changes:

Prevent prices of £1 and above being saved & widen field

---

.ebextensions/00_sysctl.config

We had some 502 errors from the application yesterday afternoon. There were no obvious issues with the application or database, but there were a large number of requests from a crawler.
The application log had no 502 errors, but nginx and the load balancer both logged them. This suggests requests were being rejected before being received by the application.
This PR updates the net.core.somaxconn OS setting to increase the number of connections above the nginx default, as noted here:
* https://www.nginx.com/blog/tuning-nginx/
* https://www.getpagespeed.com/server-setup/nginx/maximizing-nginx-performance-a-comprehensive-guide-to-tuning-the-backlog-and-net-core-somaxconn-parameters
This could cause other problems, e.g. more load on the application, but we don't want users to see rejected …

Update net.core.somaxconn system setting on deploy

---

lib/tasks/deployment/20231002081435_validated_reading_vacuum.rake

Changes the `autovacuum_vacuum_cost_delay` parameter on the `amr_validated_readings` table to zero.
This should ensure that a vacuum runs as fast as possible, with minimal timeout. Hoping this reduces the "Timeout:VacuumDelay" waits we're seeing in the database and ensure that when a vacuum is required its done as quickly as possible. At the moment it looks like the system is timing out trying to complete timeouts, so the period when performance is slow / space has not been recovered is longer.
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/wait-event.timeoutvacuumdelay.html
https://www.cybertec-postgresql.com/en/tuning-autovacuum-postgresql/

Change autovacuum delay for amr_validated_readings

---

app/controllers/admin/schools_controller.rb
app/controllers/schools_controller.rb
app/models/school.rb
app/services/import_notifier.rb
app/services/meter_management.rb
app/services/school_groups/meter_report.rb
app/services/school_remover.rb
app/views/admin/school_groups/_removed_schools.html.erb
app/views/admin/schools/removal.html.erb
app/views/admin/schools/removals/index.html.erb
app/views/shared/_school_status_buttons.html.erb
app/views/shared/_sub_nav.html.erb
config/routes.rb
spec/services/import_notifier_spec.rb
spec/services/school_groups/meter_report_spec.rb
spec/services/school_remover_spec.rb
spec/system/admin/school_removal_spec.rb

When we remove schools we do a soft delete, setting the `active` flag to false. The admin forms for doing this require user accounts to be locked and meters to be deactivated before the flag can be set.
This PR has some updates to the removal process to allow for "archiving" schools. If a school is archived, rather than deleted then we want to:
* retain the alert contacts for users, otherwise they can be deleted
* retain the links between the meters and the unvalidated readings, so when the school is re-enabled we can reload their data
When a school is deleted we should:
* remove alert contacts
* remove the links to the unvalidated readings
In both cases we want to:
* redirect admins to the removal page to clarify that the school has been removed
* disable use of the visibility, process …

Allow archiving of schools

---

app/services/amr/analytics_validated_amr_data_factory.rb
app/services/amr/checking_validated_readings_for_a_meter.rb
spec/factories/dashboard_meters_factory.rb
spec/services/amr/checking_validated_readings_for_a_meter_spec.rb

Reviewing the code and logs for when we are processing validated readings I noticed that:
- we order readings when loading from the database, but these are later added to an `AmrData` object which is a hash. So the ordering is unnecessary
- when we delete readings we were deleting all the dates present in the `AmrData.keys`. This isn't necessary as the `AmrData` returned by the analytics is guaranteed to have a continuous time series between its start and end dates. So we only have to delete data before the `start_date` or after the `end_date`. 
This PR fixes both of those issues. These are unlikely to have a huge impact on performance, but might make some of the data processing slightly quicker.

Tweaks to loading and deleting readings

---

app/views/admin/alert_types/show.html.erb

Trivial change to add an `AlertType` flag to the show page.
Helps identify whether an alert type is used to also generate benchmark metrics. If not, and we've not set up any ratings then its safe to disable.
Adding this flag will make it easier to review the settings.

Show benchmark flag on description

---

Gemfile
Gemfile.lock
app/services/schools/advice_page_benchmarks/out_of_hours_usage_benchmark_generator.rb
spec/services/schools/advice_page_benchmarks/out_of_hours_usage_benchmark_generator_spec.rb

This PR updates the out of hours usage benchmark generator to use a new method on `AnnualUsageBreakdownService` in the analytics. It avoids generating additional variables (co2, £, £current) when we only need the kwh values for the benchmark assessment.
This PR relies on this change: https://github.com/Energy-Sparks/energy-sparks_analytics/pull/606. 
Cannot be merged until we have a new tagged version of the analytics.

Optimise generation of out of hours usage benchmark

---

app/controllers/admin/school_groups/users_controller.rb
app/controllers/admin/users_controller.rb
app/views/admin/school_groups/users/show.html.erb
app/views/admin/users/_other_users.html.erb
app/views/admin/users/_user_search.html.erb
config/initializers/devise.rb
config/routes.rb

The `SchoolRemover` tries to lock user accounts using the Devise locking feature. However the current Devise config allows locks to automatically expire after an hour.  This PR

Properly lock accounts when school is deleted

---

db/migrate/20231009123308_remove_unused_validated_reading_index.rb
db/schema.rb

Checking [the statistics in `pg_stat_all_indexes` table](https://www.postgresql.org/docs/current/monitoring-stats.html#MONITORING-PG-STAT-ALL-INDEXES-VIEW) shows that there is an index on the `amr_validated_readings` table on the `meter_id` column which is unused. The stats have zero reads using that index.
Looks like postgres prefers to use the compound, unique index when doing all loads.
This PR removes the index, which will reclaim space and avoid need to maintain the index during inserts, vacuums, etc.

Remove unused index on amr_validated_readings

---

Gemfile
Gemfile.lock
app/services/amr/analytics_unvalidated_amr_data_factory.rb
app/services/amr/analytics_validated_amr_data_factory.rb
spec/services/amr/analytics_unvalidated_amr_data_factory_spec.rb
spec/services/amr/analytics_validated_amr_data_factory_spec.rb

Currently when we load the unvalidated and validated readings from the database we build a hash for each reading, for each meter.
This is passed to a second factory in the analytics (`MeterCollectionFactory`) which then turns the hash of meter data into `Dashboard::Meter` and `AMRData` objects populated with `OneDayAMRReading` values.
This PR alters this so that the application just creates the `OneDayAMRReading` objects as it reads data from the dashboard. This saves on creating potentially thousands of Hash objects which are just immediately thrown away. So should be more memory efficient.
There's no other benefits to the indirection as elsewhere we just create the analytics objects directly. Having clearer dependencies also helps understand how and where data is created. Suspect this …

Create OneDayAMRReading when loading readings

---

app/mailers/admin_mailer.rb
app/mailers/import_mailer.rb
app/views/admin_mailer/issues_report.html.erb
app/views/admin_mailer/school_group_meters_report.html.erb
app/views/import_mailer/import_summary.html.erb
app/views/layouts/admin_mailer.html.erb
app/views/shared/_school_group_meter_report.html.erb
spec/mailers/previews/admin_mailer_preview.rb

This PR removes the use of `bootstrap-email` for the admin mailers.
Internally `bootstrap-email` delegates to `premailer` which seems to be the standard Rails gem for inlining CSS into HTML emails. Premailer has some optimisations to work around performance issues for large emails. This poor performance is particularly bad for emails with tables and manifests itself as very high CPU usage
Bootstrap uses a lot of CSS selectors that cannot be optimised by Premailer. This results in very slow performance. That performance is actually due to nokogiri/libxml2 being slow at searching larger DOMs. 
So there doesn't seem to be another workaround for our high CPU issues other than removing bootstrap-email.
This PR:
* Adds a new custom layout for the `AdminMailer` and `ImportMailer`
* Removes …

Remove use of bootstrap-email for admin mailers

---

app/services/schools/school_regeneration_service.rb
spec/services/schools/school_regeneration_service_spec.rb

Testing the updated school regeneration workflow highlighted that if the validation stage failed, then we end up with further downstream failures.
The previous workflow would have raised an error but would have continued to regenerate the school using the existing validated readings (if any).
This PR adds a fallback step if an exception is thrown by the validation process. In that case we build a new meter collection, using the existing validated data in the database, and then continue processing. 
This ensures that the school is properly regenerated any will see warnings about out of date data, etc. The

Attempt to regenerate following validation failure

---

Gemfile
Gemfile.lock
app/helpers/premailer_override_helper.rb
app/mailers/application_mailer.rb
app/mailers/energy_sparks_devise_mailer.rb
config/initializers/premailer.rb

A follow-up to https://github.com/Energy-Sparks/energy-sparks/pull/3133.
While the previous PR appeared to work fine, with emails showing up as styled in mailcatcher and rails previews, this is because the browser was rendering the styles. They weren't actually being inlined into the emails.
To make this work correctly we also need to add `premailer-rails`. This automatically processes ALL outgoing emails using premailer. This helps fix styling on the admin emails but interferes with the bootstrap-email gem, so as part of customising we force the premailer processing to be disabled there.

Add premailer-rails

---

app/controllers/admin/reports/good_jobs_controller.rb
app/views/admin/reports/good_jobs/export.csv.erb
app/views/admin/reports/good_jobs/index.html.erb

Reviewing the job times I noticed there was a small bug on the admin report. It should be showing the slowest jobs in last 24 hours, but is actually showing slowest jobs in the database (which is up to 30 days).
This PR tweaks the query to limit to the last 48 hours instead.
Also modify the CSV download to adjust the columns and add a date. Makes it easier to work with in a spreadsheet.

Tweak admin good jobs report

---

app/controllers/admin/reports/amr_data_feed_import_logs_controller.rb
app/controllers/admin/reports/data_loads_controller.rb
app/models/amr_data_feed_import_log.rb
app/views/admin/reports/amr_data_feed_import_logs/index.html.erb
app/views/admin/reports/data_loads/index.html.erb
spec/factories/amr_data_feed_config_factory.rb
spec/system/admin/manual_data_loading_spec.rb
spec/system/admin/reports/amr_data_feed_import_logs_spec.rb

Allow admins to page through the list of manual data load reports. 
- Add pagy support to the controller and template
- Change page size to 20 rather than 50
Also revises the recent amr import reports page to:
- Apply a 30 day window to the summary counts in the tabs
- Use 30 rather than 7 days as the window for totalling counts by identifier, but leaves summary of changes in last 48 hours
- Highlight disabled configs so we can see if we are still loading data using them

Improve data load reports

---

lib/tasks/deployment/20231018135908_remove_invalid_mpans_from_readings.rake

When the admins export from Excel to CSV, its possible for the MPANs to be accidentally reformatted based on how they are shown on screen rather than as the full string. This has lead to data in the database with data like "7.22E+13".
Delete all these records from the AmrDataFeedReading table.

Remove mpans reformatted by Excel

---

app/jobs/school_batch_run_job.rb
app/services/schools/school_regeneration_service.rb
spec/services/schools/school_regeneration_service_spec.rb

Some further improvements to the service responsible for regenerating schools each day, and on demand by admins.
Reviewing Rollbar we are getting some errors from the analysis which are due to the aggregation process failing. This leaves the meter collection in an inconsistent state and we end up trying to calculate, e.g. equivalences, without the necessary data. We log each of these errors which just adds noise: the actual problem is the failure to aggregate properly.
This PR updates the service so that if the aggregation step throws an exception then we don't continue with the final steps. The school is just removed from the rails cache.
So the new process is:
- validate the school's meter data and update the database if sucessful
- if the validation step fails and we cant update their …

Halt regeneration if aggregation fails

---

Gemfile
Gemfile.lock
app/services/targets/generate_estimated_usage.rb
spec/services/targets/generate_estimated_usage_spec.rb

For schools with less than a year of data, we offer the option of them providing an estimate of their annual usage so that they can still set a target even if we have limited historical data.
If we have some data for the school (e.g. a few months) we try and help them produce a decent estimate by providing a calculation of our own. The school `Configuration` class stores whether an estimate is necessary for a fuel type and our best guess.
Debugging a problem regenerating some schools I found to issues with this code.
- there was a bug in the truncation of the schedule data, which meant that calculating some estimates was failing. This is fixed in the analytics (https://github.com/Energy-Sparks/energy-sparks_analytics/pull/613)
- we are currently producing estimates for all fuel types, …

Correct truncation of schedule data and only produce estimates when required

---

app/jobs/manual_data_load_run_job.rb
app/models/amr_data_feed_reading.rb
app/models/amr_validated_reading.rb
app/services/database/vacuum_service.rb
lib/tasks/amr_importer/import_all.rake
lib/tasks/amr_importer/import_n3rgy_readings.rake
lib/tasks/deployment/20231019160154_customise_vacuuming_of_reading_tables.rake
lib/tasks/solar/import_low_carbon_hub_readings.rake
lib/tasks/solar/import_rtone_variant_readings.rake
lib/tasks/solar/import_solar_edge_readings.rake
spec/jobs/manual_data_load_run_job_spec.rb
spec/services/database/vacuum_service_spec.rb

Some time ago we introduced the `VacuumService` to manually VACUUM and ANALYSE on the `amr_data_feed_readings` table as running `count` on the table was becoming very slow after updates. The analyse process recalculates the table statistics and avoids need to do a full scan to do the count.
Since then we've learned some more about how to tune the autovacuum process that should be running the VACUUM and ANALYSE process automatically. 
It turns out that due to the fact that the `amr_data_feed_readings` and `amr_validated_readings` are largely append-only, with lots of updates, the default postgres settings in RDS won't ensure that the autovacuum runs as frequently as needed.
This PR is an experiment in tuning [the autovacuum settings](https://www.postgresql.org/docs/current/runtime-config-au …

Tune vacuum analyse for reading tables

---

app/services/programmes/progress.rb
app/views/schools/_prompt_to_complete_program.html.erb
app/views/schools/recommendations/index.html.erb
config/locales/views/schools/schools.yml
spec/services/programmes/progress_spec.rb
spec/system/schools/recommendations_spec.rb

Add prompts to complete programmes to recommendations page - now looks like this:
* Changed points logic to only display points remaining
* Added some styling
* Present singular text for when there is only one activity left

Add prompt to complete programme

---

.overcommit.yml

This PR enables the forbidden branche(s) pre-commit hook to prevent committing to master.
It can be overidden by `SKIP=ForbiddenBranches git commit -m "my commit message" `

Re-enable overcommit forbidden branch hook

---

lib/tasks/data_feeds/solar_pv_tuos_loader.rake

Every day we load data from the PV Live API. Currently we (re)load a 10 day period that starts 2 days before the job runs (`Date.yesterday - 1`). This gives us a 1 day lag in our data, but the API has data up until yesterday.
This PR changes the loading window to be the previous 7 days.

Change loading period for sheffield solar

---

.ebextensions/cronjob.config

We have a rake tasks that pushes a subset of school data to S3. The meter collections have been used for doing bulk testing of the analytics. We are no longer doing this on a regular basis, as we're moving towards more rspec based testing. 
As the job involves a big spike in CPU and memory usage to generate and then upload the data to S3 I'm disabling the job.
I've retained the rake task so we can re-run on demand if we do find we need access to meter collection files in bulk. It's still possible to manually download data for specific schools from the test and production servers.

Remove scheduled upload of unvalidated meter collections to S3

---

app/models/amr_data_feed_reading.rb
spec/models/amr_data_feed_reading_spec.rb

Some of the incorrectly loaded data uses a single digit format. Revise the regex that matches these to capture them properly.

Add matching for single digits in 'DD-MON-YY' format

---

app/services/amr/single_read_converter.rb
spec/services/amr/single_read_converter_spec.rb

Fix bug in single read converter: the period needs to be converted to string. The specs had integer values which is why it was missed.
[Testing this has highlighted a local test failure in the same spec, which I'll investigate separately]

Convert strings to integers in SingleReadConverter

---

app/controllers/admin/reports/community_use_controller.rb
app/controllers/admin/reports/solar_panels_controller.rb
app/models/meter_attribute.rb
app/models/school.rb
app/models/school_time.rb
app/views/admin/reports/community_use/index.html.erb
app/views/admin/reports/index.html.erb
app/views/admin/reports/solar_panels/index.html.erb
app/views/schools/times/edit.html.erb
config/routes.rb
spec/factories/meter_attribute.rb
spec/factories/school_time_factory.rb
spec/models/meter_attribute_spec.rb
spec/system/admin/reports/community_use_spec.rb
spec/system/admin/reports/solar_panels_spec.rb

To properly review and test some of the recent changes to the baseload analysis we need better reports on:
- which schools have synthetic solar data
- which schools have community use periods
The first list help us identify schools affected by the change in algorithm, the second so that we can review impacts on community use reporting in charts.
This PR
- revises the existing solar report to add a school count, remove an unneeded column and some small optimisations
- adds a report that summarises which schools have community use periods configured with a summary of which days and calendar periods those periods cover

Revise admin reports to support reviewing analysis

---

app/services/alerts/system/missing_data.rb
app/services/alerts/system/missing_electricity_data.rb
app/services/alerts/system/missing_gas_data.rb
spec/services/alerts/system/missing_electricity_data_spec.rb
spec/services/alerts/system/missing_gas_data_spec.rb

This recent change introduced a bug in the alert that warns about missing data: https://github.com/Energy-Sparks/energy-sparks/pull/3181
The code calls `#meter_list` on the aggregate meter, but this isn't a method that is implemented by that class. The failure wasn't seen earlier because the specs mocked out that method so the tests pass.
As we're no longer checking individual meters it doesnt make sense to add a list of mpans to the alert report anyway, so I've just removed support for that, as well as calls to the method.

Fix out of date alert

---

app/controllers/admin/schools/single_meter_attributes_controller.rb

Helper as removed in earlier PR. Reference didn't cause any issues, except when released to test. The missing class caused the rails app to fail to start.

Remove reference to MeterAttributes helper

---

app/models/low_carbon_hub_installation.rb
app/models/rtone_variant_installation.rb
app/models/solar_edge_installation.rb
app/services/solar/base_download_and_upsert.rb
lib/tasks/solar/import_low_carbon_hub_readings.rake
lib/tasks/solar/import_rtone_variant_readings.rake
lib/tasks/solar/import_solar_edge_readings.rake
spec/factories/low_carbon_hub_installations_factory.rb
spec/factories/solar_edge_installations_factory.rb
spec/models/low_carbon_hub_installation_spec.rb
spec/models/solar_edge_installation_spec.rb

The check for existence of `amr_data_feed_readings` for the electricity meter associated with a solar installation is incorrect, it should be checking for `.any?`. 
Currently if the meter doesn't have readings, then we attempt to find the latest. This throws an exception during loading.
This should be throwing an exception which is caught and then logged in rollbar via `BaseDownloadAndUpsert#perform`. This hasn't been happening when this error occurs because the logging includes the `start_date` for the loading. This ends up calling the `latest_electricity_reading` method again which triggers the error.
The uncaught exception results in the whole loading run rake task to fail, but this only ends up in the logs not Rollbar.
This PR: 
- fixes the checks in the models
- adds specs for the …

Fix loading error when solar installations have no readings

---

app/controllers/admin/reports/engaged_schools_controller.rb
app/models/academic_year.rb
app/models/observation.rb
app/models/programme.rb
app/models/school.rb
app/models/school_target.rb
app/models/transport_survey.rb
app/models/user.rb
app/services/schools/engaged_school_service.rb
app/views/admin/reports/engaged_schools/index.html.erb
app/views/admin/reports/index.html.erb
config/routes.rb
spec/factories/programme_factory.rb
spec/services/schools/engaged_school_service_spec.rb
spec/system/admin/reports/engaged_services_spec.rb

An initial attempt at producing an admin report that lists "engaged schools".
The definition of an engaged school is one that has recently logged in users, or has used features of the site to record activities, actions, etc. The `:engaged` scope on the School model encompasses this. A number of other scopes have been added to other models to make it easier to build the required queries.
A new admin report page with a CSV download has been added, but depending on performance this might need to be turned into an emailed report. This prototype will be deployed to test for further review before merging.
Still to do:

Initial version of report for identifying engaged schools

---

app/views/schools/meters/index.html.erb

Fix the colspan for admins, otherwise headings are misaligned.

Fix column alignment on meters table

---

app/components/info_bar_component.rb
app/components/info_bar_component/info_bar_component.html.erb
app/components/notice_component.rb
app/components/notice_component/notice_component.html.erb
app/components/panel_switcher_component/panel_switcher_component.html.erb
app/services/audits/progress.rb
app/services/programmes/progress.rb
app/views/schools/_prompt_audit.html.erb
app/views/schools/_prompt_to_complete_programme.html.erb
app/views/schools/recommendations/index.html.erb
config/locales/views/schools/schools.yml
spec/components/info_bar_component_spec.rb
spec/components/notice_component_spec.rb
spec/services/audits/progress_spec.rb
spec/services/programmes/progress_spec.rb
spec/system/schools/recommendations_spec.rb

* This also makes notice and info_bar classes more configurable. 
* Also makes info_bar buttons use two columns rather than 3. This makes more space for the text.
* Also now adds a "style" option to info_bar so we can choose :compact or :normal.

Prepare recommendations page for feedback

---

app/controllers/compare_controller.rb
app/models/funder.rb
app/services/school_filter.rb
app/views/compare/_funder_filter.html.erb
app/views/compare/_funder_summary.html.erb
app/views/compare/_summary.html.erb
app/views/compare/tab_content/_country.html.erb
spec/factories/funders.rb
spec/services/school_filter_spec.rb
spec/system/compare_spec.rb

Adds a new admin-only option on the "Choose country" tab of the school comparison page.
The new select box and filter allows an admin to further refine the list of schools to just those associated with a specific funder.
As the admins need to also narrow by country and school type it seemed better to add this as a new option rather than a new tab.

Allow filtering by funder on school comparison pages

---

app/services/school_creator.rb
lib/tasks/deployment/20231108184512_set_activation_dates.rake
spec/services/school_creator_spec.rb

Schools have an "activation date" attribute which can be edited by admins to set the date the school became active on energy sparks. This date is used by the analytics as the start date for some of the school comparison reports (specifically, the report looking at change in energy use since activation).
If the activation date is nil then the analytics defaults to the school record creation date.
In some cases this can be quite different. A few schools have taken a number of months before they've become data enabled.
This PR does 2 things:
- set the activation date when a school first becomes data enabled
- retrospectively sets the activation dates for existing schools to the date they first became data enabled, where we have that information
This will improve some of the historical …

Ensure activation date is set

---

app/assets/javascripts/application.js
app/assets/javascripts/loading.js
app/controllers/schools/solar_edge_installations_controller.rb
app/models/solar_edge_installation.rb
app/services/solar/solar_edge_installation_factory.rb
app/views/schools/solar_edge_installations/_form.html.erb
app/views/schools/solar_edge_installations/check.js.erb
app/views/schools/solar_edge_installations/edit.html.erb
app/views/schools/solar_edge_installations/new.html.erb
app/views/schools/solar_edge_installations/show.html.erb
app/views/schools/solar_feeds_configuration/_solar_edge_feeds.html.erb
app/views/schools/solar_feeds_configuration/index.html.erb
config/routes.rb
spec/factories/solar_edge_installations_factory.rb
spec/system/solar_edge_installation_spec.rb

First of several PRs aimed at improving the setup and management of API feeds from the SolarEdge platform.
This initial PR:
* Tidies up the Solar API feed page and forms, to add hints, disable fields that shouldn't be edited and display date when a site was last edited
* Improve the page for viewing the configuration of a feed to include a bit of context and some direct links to API endpoints to facilitate debugging of issues
* Adds a "Check API" button for admins to allow them to confirm that the saved credentials are working without having to wait for an overnight run of the solar data loader
Follow on PRs will refactor and improve the services supporting management of the feeds and adding option for admin to trigger a manual data load from the API.

Improve solar edge forms and allow testing of API access

---

Gemfile
Gemfile.lock
Guardfile

Decided guard might be a better place to run rubocop with autocorrect (seeing as though I already run it). Will try it out anyway, hopefully won't get too annoying.

Make guard run rubocop with autocorrect

---

lib/tasks/deployment/20231115100612_additional_british_gas_configs.rake

Two new configurations one for gas meters and one for electricity meters.
The basic spreadsheet formats are the same, the only significant difference for us is the use of a column called "MPAN" for electricity and "MPRN" for gas. These are the correct labels for the identifiers, but means we have to have 2 configurations.
There are some other differences in the Excel files but not that impacts our data loading currently.

Add additional British Gas portal configs

---

app/models/ability.rb
app/views/shared/_manage_school.html.erb
spec/models/abilities_spec.rb
spec/system/schools/energy_tariffs_spec.rb

Revises the ability and adds specs to confirm that a group admin can edit tariffs for any school in their group.
There's a test for the ability, and new system specs for the tariff editor.

Allow group admins to edit tariffs for schools in their group

---

app/models/observation.rb
app/models/school.rb
app/views/schools/observations/timeline/_event.html.erb
lib/tasks/deployment/20231115133946_remove_event_observations.rake
spec/models/observation_spec.rb
spec/system/admin/school_configuration_spec.rb

We were creating an `:event` observation type for schools when their activation date was set. This was originally used to add a message "X school has joined Energy Sparks" and later "X became an active user of Energy Sparks" to the school timeline.
But this hasn't been working properly as activation dates weren't being routinely set until this PR was completed: https://github.com/Energy-Sparks/energy-sparks/pull/3210.
This has lead to a number of schools having recent entries in their timeline, which is incorrect. The callback to add the Observation in the School class should have been using the activation date, not the current date.
As this feature of the timeline hasn't been working correctly for some time, and because its not adding much value, we've decided to just remove the events, …

Remove :event Observation

---

lib/tasks/deployment/20231115140506_load_funders.rake
lib/tasks/deployment/funders.csv

Adds an after party task to load contents of a CSV file to populate list of funders.
This is a one-off, if we do this again we'll provide a better starting point for matching to avoid looking for schools/funders by name.

Add task to load funders

---

Guardfile

Still run the rubocop check though, this is useful. Having autocorrect run every time I saved a file was not ideal, as quite often I save a file without finishing what I'm doing and rubocop would autocorrect it mid-task...
Having the rubocop linter in my editor is proving to negate the need for autocorrecting. I also (hopefully) am more likely to learn the "right" way to be doing things.

Disable running rubocop autocorrect with guard. 

---

app/controllers/pupils/schools_controller.rb
app/controllers/schools_controller.rb
app/models/programme.rb
app/views/pupils/schools/show.html.erb
app/views/schools/_engagement_prompts.html.erb
app/views/schools/_prompt_recommendations.html.erb
app/views/schools/_prompt_recommendations_scoreboard.html.erb
app/views/schools/_prompt_to_complete_programme.html.erb
app/views/schools/recommendations/index.html.erb
app/views/schools/show.html.erb
config/locales/common.yml
config/locales/views/schools/schools.yml
spec/support/shared_examples/prompts.rb
spec/system/pupils/prompts_spec.rb
spec/system/schools/dashboard/prompts_spec.rb

The main point of this PR is to a link to the recommendations page from both adult and pupil dashboards. It does more though...
**Adult Dashboard**
* Adds a single prompt to the recommendations page
* Reworks the prompt spec to make it usable for the pupil dashboard prompts spec
**Pupil Dashboard:**
* Adds a single prompt to the recommendations page with 3 variations
* Also adds the prompt to complete a programme as discussed
* Have added a bunch of spec to check the prompt behaviour. Worth noting that current behaviour on this page is that all the prompts are visible regardless of if a user is logged in or not. Some of the prompts redirect to a login page when clicked, so is not ideal. For now, I have added these two prompts in the same way but we ought to revisit this when we discuss …

Adult and pupil dashboards: add a prompt to complete recommended pupil or adult led activities

---

lib/tasks/schools/fuel_data_analysis_report.rake

Adds a rake task to generate an ad hoc report for extracting summary of school information along with what fuel types and data they have. Will be run manually for the moment whilst I'd doing some analysis of data availability. Will automate later.

Add adhoc report for summarising school data availability

---

app/components/date_picker_form_component/date_picker_form_component.js
app/components/panel_switcher_component/panel_switcher_component.js

Looks like window.onload overwrites any previous settings of itself - this meant that when the new panel switcher component was added, which also used window.onload, it was overwriting the window.onload for the date picker form component - which is also where it's locale was set.
Fortunately we can use window.addEventListeners instead which appends rather than overwrites
(Jquery is not available at the point this is called, so we use full fat JS)

Fix tariff editor page calendar language

---

app/models/amr_data_feed_reading.rb
spec/models/amr_data_feed_reading_spec.rb

Add another format specific check to the unvalidated readings report.
I'm not sure if the cause here is the date format being updated and so historical data is now problematic. Or recent data was loaded with an unexpected date format.
Need to tackle the longer term fix of actually storing the parsed dates on the unvalidated readings table, not reparsing later. That warrants a separate discussion and PR.

Add another special case for unvalidated reading report

---

.rubocop_todo.yml
app/controllers/schools/transport_surveys_controller.rb
app/models/observation.rb
app/models/transport_survey.rb
app/views/schools/observations/timeline/_observable.html.erb
app/views/shared/_dashboard_timeline.html.erb
config/locales/common.yml
config/locales/views/schools/schools.yml
config/routes.rb
db/migrate/20231121141221_add_polymorphism_to_observation.rb
db/schema.rb
lib/tasks/deployment/20231122132353_backfill_transport_observations.rake
spec/models/observation_spec.rb
spec/models/transport_survey_spec.rb
spec/system/admin/transport_types_spec.rb
spec/system/schools/dashboard/timeline_spec.rb
spec/system/schools/transport_surveys_app_spec.rb
spec/system/schools/transport_surveys_spec.rb

* Makes observation polymorphic
* Adds transport observation using a generic template. Suspect when we move the others over, that they will mostly all need their own template still though
* Backfills old transport observations
* Also does a bit of a rubocop cleanup on the transport stuff (I removed all reference to transport from the rubocop todo and fixed it).

Make observations polymorphic and add transport survey observations

---

Gemfile
Gemfile.lock
app/components/meter_costs_table_component.rb
config/locales/cy/views/advice_pages/advice_pages.yml
config/locales/views/advice_pages/advice_pages.yml

Pulls in the changes from: https://github.com/Energy-Sparks/energy-sparks_analytics/pull/636.
Also updated the meter table component and translation keys so that the Climate Change Levy costs display correctly.

Ensure climate change levy displays on cost table

---

app/views/shared/_about_menu.html.erb
app/views/shared/_my_school_menu.html.erb
app/views/shared/_our_services_menu.html.erb

The main point of this PR was to make all elements of the "My school" menu accessible on smaller screens.
I’ve fixed this by making the menu scrollable. The Manage School menu was already scrollable, as we were having the same issue because it had so many items, even for bigger screens.
I’ve also added this to the Our services and About us menus, as whilst they are not quite as long, the same issue could occur on smaller screens such as a phone.

Make all dropdown menus scrollable so they can be seen on smaller screens

---

app/models/concerns/transifex_serialisable.rb
app/models/transport_survey/transport_type.rb
spec/models/transport_survey/transport_type_spec.rb

Moving the `TransportSurvey::TransportType`s to a module has broken the serialisation to transifex for this content.
By default the `TransifexSerialisable` concern uses the `i18n_key` of the class name to produce the default slugs that are passed to transifex. For `TransportSurvey` this now returns this:
```
2.7.6 :007 > TransportSurvey::TransportType.model_name.i18n_key
=> :"transport_survey/transport_type" 
```
The forward slash is not valid in Transifex and causes an API error.
This PR:
* Changes the default serialisation to use `param_key`, which produces e.g. `transport_survey_transport_type` so that it better supports namespaced models in future
* Overrides `tx_slug` in `TransportSurvey` to use the old name so that we can keep the existing translations, otherwise these would be seen …

Fix transport survey slugs for transifex

---

app/views/alert_mailer/alert_email.html.erb
spec/services/alerts/generate_email_notifications_spec.rb

The email alerts still have a link to the old advice page. This PR updates the alert template to fix the link and add explicit assertions for the expected urls to the spec, not just checks for the link text.

Fix link in alert emails

---

app/assets/stylesheets/base.scss
app/helpers/nav_helper.rb
app/views/layouts/application.html.erb
app/views/school_groups/_sub_nav.html.erb
app/views/shared/_nav.html.erb
app/views/shared/_navigation.html.erb
app/views/shared/_sub_nav.html.erb
spec/models/procurement_route_spec.rb

When not logged in and viewing this page, there is a margin for the sub nav but there is no sub nav present:
https://energysparks.uk/school_groups/prince-albert-community-trust
I've taken the complexity out of deciding to show a bigger margin or not and just created a switch that is set when the sub-nav is rendered. The logic for showing a sub-nav is rather complex (see shared/_navigation.html.erb) and not something that can be easily summed up in a one-liner.
This also (hopefully) fixes a flickering test

Don't add a margin for sub nav when not logged in

---

Gemfile
Gemfile.lock

Bump analytics to include bug fix for one of the alerts: https://github.com/Energy-Sparks/energy-sparks_analytics/pull/642

Upgrade to analytics 4.1.10

---

spec/services/programmes/creator_spec.rb

looks like `happened_on` defaults to yesterday so would create 2 activities with the same date and then sometimes pick the wrong one for the test

test flake at spec/services/programmes/creator_spec.rb:75

---

lib/tasks/deployment/20231206095905_update_peterborough_calendars.rake

Due to an admin error during setup, one school group was configured with the wrong calendar.
This after party task finds the relevant group and correct calendar, then resets all of the schools to use the right calendar.

Fix Peterborough calendars

---

app/models/transport_survey/transport_type.rb

I recently did a PR to fix synchronisation of the transport type model to Transifex: https://github.com/Energy-Sparks/energy-sparks/pull/3249
In that PR I override the `tx_slug` method to change the URL path for the resource created in the Transifex API, to a legal value.
But I should have overridden `resource_key` as that is used to create the slugs AND to index into the returned JSON to extract the data for the translated object.
Because I only overrode `tx_slug` we were doing the push correctly, but the pull was failing. This fixes that issue.

Override resource key not tx_slug

---

app/controllers/schools/charts_controller.rb
app/models/chart_data.rb
app/services/schools/generate_analysis_chart_configuration.rb
app/services/schools/generate_dashboard_chart_configuration.rb
spec/controllers/schools/charts_controller_spec.rb

We recently changed the application to log all errors from the charting framework. Previously errors were swallowed up in the analytics code making it hard to identify when broken charts were displayed to users.
So we now request that the analytics re-raises exceptions, and then log them to Rollbar in some circumstances. A user only ever sees an error message.
However the admin pages for reviewing and fixing gas modelling errors are too noisy: they have a lot of charts and lots can break. this triggers our alarm threshold for frequent errors.
To avoid this I've revised how we log chart errors:
- they should be logged outside of production
- they should be logged on the test server (which is technically 'production' in Rails terms)
- they should be logged on production, but only for non …

Change how chart errors are logged

---

app/views/schools/advice/storage_heaters/_analysis.html.erb
app/views/schools/advice/thermostatic_control/_analysis.html.erb
spec/system/schools/advice_pages/storage_heaters_spec.rb
spec/system/schools/advice_pages/thermostatic_control_spec.rb

The thermostatic analysis charts plot consumption (kWh) against temperature. This is to show how the linear regression has associated usage across different temperatures with periods when the heating is on or off.
The charts don't support viewing the data as cost or co2 emissions vs temperature.
This PR ensures that the chart axis controls are disabled for these charts on the gas and storage heater analysis pages.

Remove axis choices for thermostatic analysis charts

---

app/views/schools/advice/solar_pv/_analysis_has_solar_pv.html.erb
config/locales/cy/views/advice_pages/solar_pv.yml
config/locales/views/advice_pages/solar_pv.yml
spec/system/schools/advice_pages/solar_pv_spec.rb

When a school has solar pv we show the benefits of having the solar panels.
There's currently a bug in this version of the page. The table summarising the benefits if the school owns the panels should include how much energy the panels produced, as well as an estimate of the export value of that energy they've exported.
Currently the page just has hard-coded figures: a mistake from when the pages were rebuilt.
This PR replaces the hard-coded text with the actual values and updates the description of the Solar Export Guarantee with new text. We don't know the actual price that a school may be getting, so we now just show our estimate along with an indication of the likely range.
I've updated the system specs to check for these values.

Add correct variables to solar pv page

---

app/components/timeline_component.rb
config/locales/views/components/timeline.yml
spec/components/timeline_component_spec.rb

Just remembered that I changed the intervention timeline message to be "Completed an action: %{name of intervention}"
Where it should just be "%{name of intervention}"
This fixes that

Make intervention message the same as production

---

spec/models/school_group_spec.rb

seen on https://github.com/Energy-Sparks/energy-sparks/actions/runs/7140745146/job/19446635050
not exactly sure why this happens but able to reproduce locally by just running the failing test - appears to be an issue when this tests runs before the SchoolGroup.delete_all on line 51 and having a duplicate let school_group variable

fix test flake

---

app/components/timeline_component.rb
app/models/observation.rb
app/models/programme.rb
db/migrate/20231207104401_move_programme_observation.rb
db/schema.rb
spec/components/previews/compact_timeline_component_preview.rb
spec/components/previews/timeline_component_preview.rb
spec/components/timeline_component_spec.rb
spec/factories/observations_factory.rb
spec/models/programme_spec.rb
spec/system/schools/dashboard/timeline_spec.rb

Move observations for programmes to use the new polymorphic relationship.
Keeps the old programme_id column in the table for now, will remove all these when they are all moved.
Worth noting that I don't think there are any observations of these types in the database - has nobody ever completed a programme? Or maybe it's not working (there are tests which indicate the code should be working)?

Move programme observation

---

config/routes.rb

The annotations controller doesn't have a default format set, but always returns JSON. So we get a bit of noise in Rollbar when crawlers do a GET request without an Accept header. Add a default format to the route to stop this.

Add default format

---

app/controllers/schools/school_targets_controller.rb
app/views/schools/school_targets/_target_table.html.erb
app/views/schools/school_targets/_target_table_row.html.erb
spec/system/schools/school_targets_spec.rb

There's a bug on the school target progress report page. The school targets controller was using the ProgressService to create the progress summary to display for the target.
For a current target this is fine, as the ProgressService loads that. But for an expired target it means we show the current progress, not the summary for the expired target.
The functional change in this PR is to update the controller to just call `.to_progress_summary` on the target.
I've also updated the specs to:
- add a test for this situation to ensure the bug is fixed
- improve the tests for the progress reporting so that it checks explicitly for the expected summary for gas and electricity data
- improve the tests for the fallback when we have limited data so its checking what data is shown and not just …

Ensure we show correct progress summary

---

app/services/targets/generate_fuel_types.rb
app/services/targets/generate_progress_service.rb
spec/services/targets/generate_fuel_types_spec.rb
spec/services/targets/generate_progress_service_spec.rb

The analytics throws some exceptions when it cannot properly generate a progress report and other data associated with a school target.
Currently we log all these in Rollbar, but some of them can be ignored as they are data issues rather than bugs. For example it throws an exception if the gas data doesn't start before the target period. This can happen because schools can set targets regardless of how much data they have. We just give them a more limited report.
So while its valid to throw an exception because the analytics can't do anything for that fuel type, we don't need to report this to Rollbar as an error or warning.
This PR catches this expected exception and does not log to Rollbar. This will reduce a small number of persistent reports.

Reduce Rollbar noise from expected exceptions in the school targets feature

---

Gemfile
Gemfile.lock

Add the webdriver gem back in to work around chromedriver install issues.
May need to be reverted in Ruby 3.0 branch.
Previous issues:
- having to pin driver: https://github.com/Energy-Sparks/energy-sparks/pull/2922
- them update to webdrivers, removing need to pin: https://github.com/Energy-Sparks/energy-sparks/pull/2992

Reinstate webdrivers

---

app/controllers/compare_controller.rb
app/views/compare/no_schools.html.erb
config/locales/cy/views/compare/compare.yml
config/locales/views/compare/compare.yml
spec/system/compare_spec.rb

Currently if a user filters the list of schools to an empty list we still try and run the school benchmark. This causes an error in the analytics which is logged to Rollbar. This seems to be happening quite often, sometimes from crawlers/bots.
I've amended the controller so:
- it loads the list of schools as a before action
- checks whether there are any schools before displaying list of benchmarks, using some existing translations for the text
- also checks whether the list is empty after running, a user shouldn't be able to get to that screen but crawlers/bots rechecking existing URLs may do

Check if all schools have been filtered before running comparison

---

app/services/schools/advice/recent_changes_service.rb
spec/services/schools/advice/recent_changes_service_spec.rb

The recent changes service calculates the usage for and aggregate meter:
- the usage for the last week of data
- the usage for the previous week 
- change
To align with other parts of EnergySparks it doesn't look at last 7 days, but last calendar weeks.
There's a bug in the code where if there's >7 days but <14 days the previous week check fails with an error. This is currently affecting 1 school.
The PR fixes that with a small change to the `full_previous_week?` method. I've also removed some unused methods from the class and refactored the spec to push it more in line with our preferred approach.

Fix error in recent changes service

---

app/services/schools/advice/baseload_service.rb
spec/services/schools/advice/baseload_service_spec.rb

If a school has just short of a years data for some meters, then the seasonal and intraweek variation analysis for those meters breaks. There's a discrepancy between the date checking between the services.
To fix this now, I've changed the BaseloadService to call the analysis Baseload::BaseloadAnalysis class directly for the individual meter breakdown. This fixes a broken page for one school so they can properly access their baseload analysis.

Change data check to use BaseloadAnalysis class

---

app/views/shared/_my_school_menu.html.erb
spec/system/schools/dashboard/navigation_spec.rb

Testing out the school admin pages I noticed that one of the links in the "My school" menu is linking to the school's list of interventions, rather than the energy saving action index page.
I've fixed that and updated the tests so they're doing something a bit more useful.
I've left off revising other parts of the menu, e.g. to add link to recommendations page, as we can review that in 2024.

Fix link in my school menu

---

app/services/targets/admin_report_service.rb

Minor issue. There's a weekly admin report that runs on a Friday that sends a summary of state of the targets feature to admins.
The service used to generate the summary for each school may return nil if there's an unexpected error in running the school target, this isn't being checked for in the calling service. So I've fixed that.
The underlying errors are already being logged, so this will fix the report but we've already got visibility of the other issues.

Check for nil result in admin target report

---

app/assets/javascripts/select.js
app/views/activity_types/_prompt_score.html.erb
app/views/activity_types/_prompt_score_for_group.html.erb
app/views/intervention_types/_prompt_score.html.erb
app/views/intervention_types/_prompt_score_for_group.html.erb

This does a few things.
- Changes the style of the disabled button on record activity and action pages.
- Makes the notice that contains this form full width on the activity pages to match the style of the action pages
- Adds a tooltip to the disabled button when disabled (and removes when not)
- Changes the alignment a bit of this form
All of which is up for discussion... see what you think!

Change style of disabled button on record activity / action pages

---

app/components/observation_component/observation_base.html.erb
app/components/scoreboard_summary_component.rb
spec/components/scoreboard_summary_component_spec.rb

Also reduces the amount observations shown from 5 to 4, which looks slightly better given the extra padding on each row.

Spread out compact observations slightly

---

spec/factories/calendars_factory.rb
spec/models/school_group_spec.rb
spec/models/scoreboard_spec.rb
spec/support/shared_examples/scorable.rb
spec/system/school_groups_spec.rb

Some recently added tests around the scorable concern rely on creating a calendar for the `Scorable`. The calendar needs to have some terms and a correct set of calendar years.
Currently the academic years were being created as a side effect of adding the terms. And the logic for that was just creating academic years for the previous and next _calendar_ year.
This works fine between 1st September and 31st December because the previous school year is in the previous calendar year.
But the test data is incorrect from 1st January as the previous school year begins two calendar years before that. E.g. on 1st January 2023 the school year is the Sept 2023-August 2024 period and the previous school year is Sept 2022-August 2023.
The incorrectly setup data causes three sets of specs to fail.
I've …

Add trait for creating previous and next academic years to calendars factory

---

spec/models/concerns/transifex_serialisable_spec.rb

This spec selects a class that implements TransifexSerialisable and then confirms that the `has_content` method works correctly with and without attributes set.
It currently builds a list of all the classes that implements the model than selects the first one. The `AlertTypeRatingContentVersion` model relies on having an associated `AlertTypeRating` instance to guide how it is serialised. If this class ends up being the first in the list, then the spec fails as the dependent object hasn't been created.
Have updated the test to use a specific implementing class (`ActivityCategory`) to test the generic behaviour.

Fix flickering TransifexSerialisable test

---

app/components/podium_component.rb
app/components/podium_component/podium_component.html.erb
app/models/podium.rb
config/locales/views/components/podium.yml
spec/components/podium_component_spec.rb
spec/system/activities_spec.rb
spec/system/interventions_spec.rb
spec/system/pupils/prompts_spec.rb

The podium text now includes national position:

Include national scoreboard position on the podium

---

app/services/scoreboard_all.rb

Assuming it's ok to use the England and Wales calendar still, have just added Scotland in to the list of schools.
Which I'm not sure it is this simple now I've thought about it. To quote Claudia:
"We want to include the points accrued during the Scottish school year 2023/2024 with the England and Wales school year 2023/2024 and have both in the national scoreboard."
English and Welsh scoreboards use the "England and Wales" calendar
Scottish scoreboards use the "Scotland" calendar

Add Scotland to national scoreboard

---

Gemfile
Gemfile.lock
spec/mailers/bill_request_mailer_spec.rb
spec/mailers/consent_grant_mailer_spec.rb
spec/mailers/consent_request_mailer_spec.rb
spec/mailers/dcc_mailer_spec.rb
spec/mailers/energy_sparks_devise_mailer_spec.rb
spec/mailers/energy_tariffs_mailer_spec.rb
spec/mailers/onboarding_mailer_spec.rb
spec/mailers/recent_activities_mailer_spec.rb
spec/services/activation_email_sender_spec.rb
spec/services/alerts/generate_email_notifications_spec.rb
spec/services/rollbar_notifier_service_spec.rb
spec/services/schools/bill_request_service_spec.rb
spec/services/schools/consent_request_service_spec.rb
spec/services/targets/target_mailer_service_spec.rb
spec/support/shared_examples/admin_school_group_onboardings.rb
spec/system/admin/meter_reviews/consent_requests_spec.rb
spec/system/admin/school_onboarding_spec.rb
spec/system/password_reset_spec.rb
spec/system/schools/consent_documents_spec.rb

looks to relate to https://github.com/bootstrap-email/bootstrap-email/releases/tag/1.3.0 where plain text email support was added so need to change how the email body is accessed

bootstrap-email gem update

---

app/models/alert_type_rating_content_version.rb
spec/models/alert_type_rating_content_version_spec.rb

A while ago we removed the "find out more" fields from the editable fields on the alert type rating forms. But the validation associated with those fields was accidentally left in place. This means it's not possible to edit the content of some ratings as the update fails validation for fields not shown to the user.
This PR removes those validation rules. 
I will separately do another, larger PR to properly retire the old "find out more" feature which is otherwise inactive.

Remove validation on fields removed from alert type rating forms

---

app/models/amr_data_feed_reading.rb
spec/models/amr_data_feed_reading_spec.rb

Add another exception to the admin report to handle incorrectly loaded reading dates. These cause the report to fail, but not the loader.
I'll get the broader fix for this issue (storing parsed dates at loading time rather than reparsing prior to validation) moved up the priority list.

Add further exception for incorrectly formatted dates

---

Gemfile
Gemfile.lock
app/services/charts/annotate.rb
spec/services/charts/annotate_spec.rb

* Update analytics to include fix for solar charts: https://github.com/Energy-Sparks/energy-sparks_analytics/pull/661
* Small change to the Annotate service so that it doesn't throw an error if the series are missing. This can happen if the chart being annotated fails to load. Reduces some noise in Rollbar.

Fix solar charts

---

app/views/shared/activities/_previous_records.html.erb

This fixes the word activity appearing twice in this notice:

Make the word "Activity" only appear once

---

app/controllers/admin/reports/funder_allocations_controller.rb
app/models/funder.rb
app/models/school.rb
app/views/admin/reports/funder_allocations/show.html.erb
spec/models/funder_spec.rb

There's a problem with the funded school count on the funder allocation report.
Schools can be associated with a funder either
- by a direct association
- indirectly, via their school group
Currently the numbers only include schools that are directly linked to schools, so undercounts the total for each funder. The unfunded school count is also incorrect as its not allowing for schools linked via their school group.
I've written a SQL query that correctly selects, groups and counts the data and added a method to the Funder model. I've also added a scope to School to count unfunded schools which aren't returned by that query.
The report table has been updated to include numbers of visible and data enabled schools as separate columns.
There might be a more elegant way to write the query, but …

Rework funded schools report

---

spec/system/schools/advice_pages/electricity_out_of_hours_spec.rb
spec/system/schools/advice_pages/gas_out_of_hours_spec.rb

Resolves some date issues in the recently updated out of hours specs. Using relative dates (e.g. `30.days.ago`) introduced some date dependencies. Have switched the failing tests over to use fixed dates.
I think the others are OK as they are less reliant on having specific meter data and holiday dates aligning correctly.

Use fixed dates in specs

---

app/models/energy_tariff_charge.rb
lib/tasks/deployment/20240206121518_metering_agent_charge.rake

There is some incorrect configuration in the tariff editor. The metering agent charge and automatic meter reading charges should be configurable for day/month/year and not kwh.
This PR fixes the issue and migrates any existing charges with invalid configuration. I've already manually fixed the only example I've found as it was breaking school regeneration.

Fix metering agent charges

---

app/views/schools/advice/long_term/_recent_trend.html.erb
spec/system/schools/advice_pages/electricity_long_term_spec.rb
spec/system/schools/advice_pages/gas_long_term_spec.rb

Temporarily change the long term usage page so that a broken chart only displays when there is 2 years data.
This avoids a bug in the chart whilst working on a proper fix in the analytics.

Temporarily require 2 years data for monthly comparison chart

---

app/controllers/schools/advice/base_long_term_controller.rb
app/views/schools/advice/electricity_out_of_hours/_analysis.html.erb
app/views/schools/advice/gas_out_of_hours/_analysis.html.erb
app/views/schools/advice/gas_out_of_hours/_by_day.html.erb
app/views/schools/advice/long_term/_recent_trend.html.erb
app/views/schools/advice/out_of_hours/_last_year.html.erb
spec/system/schools/advice_pages/electricity_long_term_spec.rb
spec/system/schools/advice_pages/electricity_out_of_hours_spec.rb
spec/system/schools/advice_pages/gas_long_term_spec.rb
spec/system/schools/advice_pages/gas_out_of_hours_spec.rb

Fixes several issues with the advice pages:
- Revise section heading on out of hours page so its says "Recent trend" instead of "Last 12 months" if there's less than a year of data. Have reused translation key to keep consistent with long term trend page
- Restores the chart title and subtitle to the first chart on the long term usage page. We switch charts if there's <1 year but all charts should have a title and subtitle. As this chart is used on another page I've reused the translation key again
- Hide the heating use by day chart on the gas out of hours page if there's less than a month of data. Otherwise the chart fails to run. The analytics is not very clear on minimum data required for a fit, but 30 days seems to be a key threshold

Fix some additional text and chart issues with the advice pages

---

app/controllers/admin/prob_data_reports_controller.rb
app/views/admin/prob_data_reports/index.html.erb

Fixed issue in query for PROB data report and makes table sortable.
I'm sure this used to work, so maybe broke with Rails upgrade. Error from query was:
`ActiveRecord::UnknownAttributeReference: Query method called with non-attribute argument(s): "count(*) DESC"`

Fix PROB data report

---

app/services/schools/advice_page_benchmarks/long_term_usage_benchmark_generator.rb
spec/services/schools/advice_page_benchmarks/long_term_usage_benchmark_generator_spec.rb

The long term usage service now only requires 90 days of data, but for benchmarking we need a year.
This PR updates the benchmark generator that generates the grading shown on the advice page index to use a year of data.
Also reworks the spec to actually run the benchmark end to end rather than using mocks.

Long term benchmarks require a year

---

app/assets/javascripts/usage_charts.js

We have some charts that provide date picker components, e.g.
/schools/st-mary-s-fields-primary-school/advice/electricity_recent_changes/analysis
/schools/st-mary-s-fields-primary-school/usage?period=weekly&supply=electricity
/schools/st-mary-s-fields-primary-school/usage?period=daily&supply=electricity
The default dates for each picker is initialised in the javascript. Currently the way these are setup the most recent date ends up in the first picker and the older date in the second. This is a bit counter-intuitive as you'd expect the older date to be first.
There's a suggestion to reverse this to make it clearer. A user can end up choosing whatever series they want in whatever order, but this introduces a better default on page load.

Init date pickers in reverse order

---

Gemfile
Gemfile.lock

Avoid an issue with baseload page failing to load with lagging data and newer tariffs

Update analytics to include bug fix for tariff service

---

app/models/advice_page.rb
app/models/alert_type.rb
app/models/comparison/metric_type.rb
app/models/concerns/enum_fuel_type.rb
app/services/comparison/metric_migration_service.rb
app/views/schools/advice/index/_page_list.html.erb
spec/services/comparison/metric_migration_service_spec.rb

Adds a service that reads the existing benchmark metrics defined in the analytics alert classes and then creates new `MetricType` records for the new school comparison tool.
The mapping:
- handles the variety of different units supported by the analytics, mapping them into a new simpler range.
- ignores some existing metrics that are just copies of attributes from other models, e.g. the school name, that can be easily added to templates
- identifies the fuel type from the metric based on the alert type configuration or, failing that, the name or configuration of the metric. Some values are for multiple fuel types, e.g. annual total energy consumption. A new `:multiple` fuel type is added to support that, but this required some tweaks (and erblint tidying) to the advice pages
In addition …

Write migration to populate `Comparison::MetricType` with existing benchmark variable definitions

---

app/components/comparison_chart_component.rb
app/components/comparison_chart_component/comparison_chart_component.html.erb
app/controllers/comparisons/base_controller.rb
app/controllers/comparisons/baseload_per_pupil_controller.rb
app/views/comparisons/base/_charts.html.erb
spec/components/comparison_chart_component_spec.rb
spec/components/previews/comparison_chart_component_preview.rb

Adds a view component for creating stacked barcharts for use in the school comparison report. This will replace the `benchmark_chart` helper once we retire the old pages.
Includes: 
- support for adding a title and subtitle to align display with other charts on the site.
- a basic preview
- reworks the existing baseload_per_pupil report and its base class to use the component
- adds support for displaying multiple charts (if needed) in the comparison page template

Create component for displaying comparison charts

---

app/models/comparison/report.rb
app/views/admin/comparisons/reports/index.html.erb
lib/tasks/deployment/20240223113901_migrate_benchmark_content_to_reports.rake
spec/models/comparison/report_spec.rb
spec/system/admin/comparisons/reports_spec.rb

Tried a few different ways of getting the benchmark keys, hopefully the way I have settled on gets all the ones we need.
For the purposes of this import, the title and introduction text have come straight from the yaml, however, analytics also seems to occasionally include other text (such as caveat_text) for some benchmarks along with the introduction_text. However have left it has the pure introduction from the yaml for now, let me know if this is right @ldodds 🙏 
Also makes some minor changes to the reports admin index now we have content:
Makes the reporting_period optional for now too.

Migrate benchmark info to new report model

---

app/models/meter.rb
app/services/meter_review_service.rb
lib/data_feeds/n3rgy/consent_api_client.rb
lib/tasks/deployment/20240229143940_remove_sandbox_meters.rake
spec/services/meter_review_service_spec.rb

- fixed environment variable name in consent api client. I obviously hadn't pushed this fix to my previous branch
- changes frequency at which we check whether a meter is in n3rgy to 1 week from 1 month, so they'll be ready for review quicker
- only include active schools in list of meter reviews as a quality of live improvement for admins
- remove the 'sandbox' meters we had configured for v1 of the n3rgy API. These are no longer needed.

Misc bug fixes for n3rgy consent and meter review workflow

---

app/services/amr/n3rgy_downloader.rb
spec/services/amr/n3rgy_downloader_spec.rb

The new n3rgy API is designed to support a wider range of metering scenarios than v1. Specifically it allows for a scenario where a HAN (Home Area Network) has multiple devices for the same type. E.g. multiple electricity meters.
In a domestic setting this is very unlikely to happen and, so far, it doesn't seem to be the case with schools. All currently schools only have one meter of each type (gas, electricity).
This PR adds a Rollbar warning if, after retrieving data, we find readings for multiple meters. It still continues to return readings but warns us so we can investigate.
This seems an unlikely scenario. It's more likely that any additional meters will have their own MPANs and, presumably, networks. But this should reduce the likelihood of us incorrectly loading data if it does …

Add Rollbar warning for multiple devices in HAN

---

app/controllers/schools/configuration_controller.rb
app/views/schools/configuration/_form.html.erb
spec/system/admin/school_configuration_spec.rb
spec/system/admin/school_editing_spec.rb

The School model has fields for region (Government Office Region) and local authority area (Local Authority Districts). These currently don't support any direct functionality and are just used to support funder allocation and reporting.
The fields were originally populated by matching school geographic areas to the region polygons in QGIS. There's a separate PR refreshing that data.
This PR makes the fields available for admins to manage in the School Configuration page.
The functional changes are:
- add fields for region, local authority area and country to allow these to be managed in one place
- updates to controller
- added a basic set of tests to confirm form fields work
Non-functional changes:
- adding some sub-headings and comments to the configuration page to improve the layout …

Add geographic area form fields to school configuration

---

app/services/meter_management.rb
lib/tasks/amr_importer/import_n3rgy_readings.rake
lib/tasks/amr_importer/import_n3rgy_tariffs.rake
spec/services/meter_management_spec.rb

Currently when we deactivate a meter we issue a "withdraw consent" request to the n3rgy API.
It turns out that n3rgy actually handle consent slightly differently to what we expected. Issuing consent for a given MPxN actually results in consent being granted for all meters at that address, not the specific meter used in the API request. So, for example, using the electricity meter MPAN will also grant consent to access the gas data. There's not a more granular way to grant/withdraw consent that for the whole address (or more accurately the HAN to which the MPxN is connected).
This means our current approach of removing consent if the electricity meter is disabled may end up removing access to the gas data, which isn't what was intended.
This PR changes the meter management service so that: …

Change when consent is withdrawn via n3rgy API

---

app/assets/stylesheets/comparisons.scss
app/controllers/comparisons/base_controller.rb
app/controllers/comparisons/change_in_electricity_since_last_year_controller.rb
app/helpers/comparisons_helper.rb
app/models/comparison/change_in_electricity_since_last_year.rb
app/views/comparisons/base/index.html.erb
app/views/comparisons/change_in_electricity_since_last_year/_introduction.html.erb
app/views/comparisons/change_in_electricity_since_last_year/_tables.html.erb
config/routes.rb
db/migrate/20240221154525_create_change_in_electricity_since_last_years.rb
db/schema.rb
db/views/change_in_electricity_since_last_years_v01.sql
spec/support/shared_examples/school_comparison_reports.rb
spec/system/comparisons/baseload_per_pupil_spec.rb
spec/system/comparisons/change_in_electricity_since_last_year_spec.rb

Implements the `change_in_electricity_since_last_year` (Annual change in electricity) report.
- adjusted base templates to make tabs option is no charts are provided by the controller, as this comparison doesn't have a chart currently
- added a `sticky-heading` style that can be applied to `thead` this [makes the table header sticky](https://btxx.org/posts/Please_Make_Your_Table_Headings_Sticky/) so if a user scrolls with a long table the heading stays visible. it doesn't work so well for tables with multiple header rows but have left in place here, will be fine with others.
- I've pushed the sorting into the database by calculating the percentage change in the order by clause
- I've center aligned the column groups so they display better
- replace the values in the "Estimated" column …

Annual change in electricity since last year report

---

app/helpers/application_helper.rb
app/helpers/comparisons_helper.rb
app/views/compare/benchmarks.html.erb
spec/helpers/comparisons_helperer_spec.rb

Rails route helpers append _index only for singular named routes to the collection resource. This does not apply for plural named routes which was assumed when linking to benchmarks. This changes the link to work for both kinds.

Fix benchmark links

---

app/controllers/comparisons/base_controller.rb
app/controllers/comparisons/electricity_targets_controller.rb
app/models/comparison/electricity_targets.rb
app/views/comparisons/electricity_targets/_tables.html.erb
config/initializers/rails_7/generators_actions.rb
config/routes.rb
db/migrate/20240229162518_create_electricity_targets.rb
db/schema.rb
db/views/baseload_per_pupils_v01.sql
db/views/electricity_targets_v01.sql
lib/generators/comparison_report/USAGE
lib/generators/comparison_report/comparison_report_generator.rb
lib/generators/comparison_report/templates/_tables.html.erb.tt
lib/generators/comparison_report/templates/controller.rb.tt
lib/generators/comparison_report/templates/model.rb.tt
lib/generators/comparison_report/templates/system_spec.rb.tt
spec/system/comparisons/electricity_peak_kw_per_pupil_spec.rb
spec/system/comparisons/electricity_targets_spec.rb

Includes a generator to make the files required for a benchmark. It puts some code in there that can be used as an example, not sure how useful it is. Please modify as you see fit!
To use:
`rails generate comparison_report benchmark_key`
Also brings in rails 7 version of generator actions - this is because the route generator didn't have the ability to add to a namespace without writing out a whole new namespace every-time.

Progress against electricity target

---

app/services/meter_review_service.rb
spec/services/meter_review_service_spec.rb

I missed a place in the code where we call n3rgy, prior to completing the meter review service. So its still using v1 and not working for the meters that are only accessible via v2.
Adds a conditional check for feature flag and specs.
Later in the week I'm going to remove all v1 code but wanted to give it another day or two.

Ensure meter review service uses v2 of n3rgy

---

lib/generators/comparison_report/templates/_table.csv.ruby.tt
lib/generators/comparison_report/templates/_table.html.erb.tt

Fixes a bug in the table template
Makes the loop variable names consistent
Adds a default header and column to the CSV download

Tweaks for _table files

---

app/components/comparison_table_component.rb
app/components/comparison_table_component/comparison_table_component.html.erb
app/controllers/comparisons/base_controller.rb
app/controllers/comparisons/baseload_per_pupil_controller.rb
app/controllers/comparisons/change_in_electricity_since_last_year_controller.rb
app/views/comparisons/base/_tables.html.erb
app/views/comparisons/base/index.html.erb
app/views/comparisons/baseload_per_pupil/_table.csv.ruby
app/views/comparisons/baseload_per_pupil/_table.html.erb
app/views/comparisons/change_in_electricity_since_last_year/_table.csv.ruby
app/views/comparisons/change_in_electricity_since_last_year/_table.html.erb
lib/generators/comparison_report/templates/_table.html.erb.tt
spec/components/comparison_table_component_spec.rb

This is a draft to illustrate an alternate approach, to see if we prefer the syntax/setup. We don't have to use this, but I thought a concrete example would be helpful.
Adds a view component for handling formatting of comparison tables.
- headers are defined in the controller and passed to the component and reused across both the HTML and CSV views
- for tables with multi-line headers, controllers can implement `col_group` to provide an array of column group configuration. Used in the component only currently, but could be used in CSV too
- supports a `school` slot for providing the school name and footnote text in the first column
- supports a `footer` slot for content to be added to the table footer
- supports row and column formatting, with cell contents specified using a `var` slot. …

Initial version of comparison table component

---

app/controllers/comparisons/change_in_electricity_since_last_year_controller.rb
app/controllers/comparisons/change_in_solar_pv_since_last_year_controller.rb
app/models/comparison/change_in_electricity_since_last_year.rb
app/models/comparison/change_in_solar_pv_since_last_year.rb
app/models/comparison/view.rb
app/views/comparisons/change_in_solar_pv_since_last_year/_table.csv.ruby
app/views/comparisons/change_in_solar_pv_since_last_year/_table.html.erb
config/routes.rb
db/migrate/20240307181846_create_change_in_solar_pv_since_last_years.rb
db/schema.rb
db/views/change_in_solar_pv_since_last_years_v01.sql
lib/generators/comparison_report/templates/system_spec.rb.tt
spec/system/comparisons/change_in_solar_pv_since_last_year_spec.rb
spec/system/comparisons/solar_generation_summary_spec.rb
spec/system/comparisons/solar_pv_benefit_estimate_spec.rb

Implements the annual change in solar production table, but also sorts a couple of other issues:
* There was a bug in the generator template, so the specs had the wrong shared context name, this was masking test failures
* Fixed failing spec for other report 
* Adds a shared scope to `Comparison::View` for doing percentage changes, allowing for NULL values. Should be consistent with the function currently used to sort values

Annual change in solar PV production and resulting CO2 savings

---

app/models/amr_data_feed_config.rb
app/services/amr/data_feed_translator.rb
app/services/amr/single_read_converter.rb
app/views/admin/amr_uploaded_readings/new.html.erb
db/migrate/20240311110540_add_convert_to_kwh_to_data_feed_config.rb
db/schema.rb
lib/tasks/deployment/20240311105041_ems_format.rake
spec/services/amr/data_feed_translator_spec.rb

Adds a flag to the data feed config model to indicate if values should be converted from m3 to kwh. Then updates the data feed translator to apply it.
Currently will just apply it to all readings if set and there is no reading type defined in the CSV. Or, if there is, then only to those marked as m3/M3.
Also adds a new config that uses this support and adds the `.cns` file type to the manual upload form.
CNS seems to be a pseudo CSV format used by gas suppliers.

Add support for m3 conversion and cns file upload

---

.ebextensions/cronjob.config

n3rgy have suggested running jobs at 10-11am to avoid data loading errors, so shifting the jobs back to then as a test. Waiting for them to confirm a better idea of timing.

Push back n3rgy jobs

---

app/controllers/comparisons/annual_change_in_electricity_out_of_hours_use_controller.rb
app/controllers/comparisons/annual_electricity_costs_per_pupil_controller.rb
app/controllers/comparisons/annual_electricity_out_of_hours_use_controller.rb
app/controllers/comparisons/base_controller.rb
app/controllers/comparisons/baseload_per_pupil_controller.rb
app/controllers/comparisons/change_in_electricity_consumption_recent_school_weeks_controller.rb
app/controllers/comparisons/change_in_electricity_holiday_consumption_previous_holiday_controller.rb
app/controllers/comparisons/change_in_electricity_holiday_consumption_previous_years_holiday_controller.rb
app/controllers/comparisons/change_in_electricity_since_last_year_controller.rb
app/controllers/comparisons/change_in_solar_pv_since_last_year_controller.rb
app/controllers/comparisons/electricity_consumption_during_holiday_controller.rb
app/controllers/comparisons/electricity_peak_kw_per_pupil_controller.rb
app/controllers/comparisons/electricity_targets_controller.rb
app/controllers/comparisons/solar_generation_summary_controller.rb
app/controllers/comparisons/solar_pv_benefit_estimate_controller.rb
app/controllers/comparisons/weekday_baseload_variation_controller.rb
app/models/comparison/view.rb
app/services/school_filter.rb
lib/generators/comparison_report/templates/controller.rb.tt
spec/services/school_filter_spec.rb

Optimise loading of school data for the comparison reports:
- adds a `.for_schools` scope to `Comparison:View` which loads data for a list of schools and includes the school model in the results. This avoids n+1 queries when loading data, e.g. for the chart
- adds an option to the `SchoolFilter` to just pluck specific columns. For the comparison reports we just need the ids, not the full model

Optimise comparison filter and load

---

app/controllers/compare_controller.rb
app/controllers/comparisons/base_controller.rb
app/services/school_filter.rb
app/views/compare/tab_content/_groups.html.erb
spec/services/school_filter_spec.rb
spec/system/compare_spec.rb

Some school groups and schools are not visible on the site.
This PR:
- ensures those groups are not listed in the filters on the comparison index page, unless the user is a member of that group. This involved just changing how the control was populated.
- non-public schools are filtered from the list of results. There was an existing ability check but this wasn't actually returning the filtered schools, so wasn't being applied. For the newer controller I've used `accessible_by` which seems to do the right thing.
I've had to refactor the SchoolFilter slightly to allow for both this check and the `.pluck` optimisation to work.

Ensure non public schools are filtered

---

app/components/comparison_table_component.rb
app/controllers/comparisons/recent_change_in_baseload_controller.rb
app/helpers/application_helper.rb
app/models/comparison/recent_change_in_baseload.rb
app/views/comparisons/recent_change_in_baseload/_introduction.html.erb
app/views/comparisons/recent_change_in_baseload/_table.csv.ruby
app/views/comparisons/recent_change_in_baseload/_table.html.erb
config/routes.rb
db/migrate/20240307163123_create_recent_change_in_baseloads.rb
db/schema.rb
db/views/recent_change_in_baseloads_v01.sql
lib/generators/comparison_report/templates/_table.csv.ruby.tt
lib/generators/comparison_report/templates/_table.html.erb.tt
lib/generators/comparison_report/templates/controller.rb.tt
lib/generators/comparison_report/templates/system_spec.rb.tt
spec/helpers/application_helper_spec.rb
spec/system/comparisons/recent_change_in_baseload_spec.rb

Had a wee issue with up_downify sanitizing formatted values containing the `"&percnt;"` html symbol and them becoming double encoded (e.g. `"&amp;percnt;"`)
Analytics is inconsistent in how it presents it's percent symbols for :html formatted values:
```
> FormatEnergyUnit.format(:percent, 0.123, :html)
=> "12&percnt;"
> FormatEnergyUnit.format(:relative_percent, 0.123, :html)
=> "+12%"
> FormatEnergyUnit.format(:relative_percent_0dp, 0.123, :html)
=> "+12%"
> FormatEnergyUnit.format(:percent_0dp, 0.123, :html)
=> "12%"
> FormatEnergyUnit.format(:comparison_percent, 0.123, :html)
=> "+12&percnt;"
```
This looks to be an issue with how FormatEnergyUnit.format does it's translations paired with how our translations are configured. When asking for a :html formatted value, …

Recent change in baseload

---

app/assets/javascripts/table_sorting.js
app/components/comparison_table_component/comparison_table_component.html.erb
app/views/admin/reports/activity_types/index.html.erb
app/views/shared/_head.html.erb

Upgrades DataTables (which we use for showing sorted tables) to the latest version.
Have manually tested all the user facing tables and the majority of the admin reports (which is where this is mostly used) and all looks OK with updated options.
The new version has slightly better styling but, more importantly, includes some additional options. I've enabled table row hover on the new comparison reports. There's some other options which we could make use of to improve display further, e.g. adding paging to handle large tables; scrolling in place (via `scrollX`) to avoid long pages; hiding columns on mobile, etc.
The older version includes some of those options but this version has more options for styling and placement of any additional controls added to the table.

Upgrade data tables

---

app/controllers/comparisons/annual_gas_out_of_hours_use_controller.rb
app/controllers/comparisons/annual_storage_heater_out_of_hours_use_controller.rb
app/models/comparison/annual_gas_out_of_hours_use.rb
app/models/comparison/annual_storage_heater_out_of_hours_use.rb
app/views/comparisons/annual_gas_out_of_hours_use/_table.csv.ruby
app/views/comparisons/annual_gas_out_of_hours_use/_table.html.erb
app/views/comparisons/annual_storage_heater_out_of_hours_use/_table.csv.ruby
app/views/comparisons/annual_storage_heater_out_of_hours_use/_table.html.erb
config/routes.rb
db/migrate/20240314151022_create_annual_gas_out_of_hours_uses.rb
db/migrate/20240314165231_create_annual_storage_heater_out_of_hours_uses.rb
db/schema.rb
db/views/annual_gas_out_of_hours_uses_v01.sql
db/views/annual_storage_heater_out_of_hours_uses_v01.sql
spec/system/comparisons/annual_electricity_out_of_hours_use_spec.rb
spec/system/comparisons/annual_gas_out_of_hours_use_spec.rb
spec/system/comparisons/annual_storage_heater_out_of_hours_use_spec.rb
spec/system/comparisons/electricity_targets_spec.rb
spec/system/comparisons/recent_change_in_baseload_spec.rb

This adds `annual_gas_out_of_hours_use` and `annual_storage_heater_out_of_hours_use` at the same time (as I thought the storage heater one would be very similar but it's too different to share any functionality).
`annual_gas_out_of_hours_use` has many similarities to `annual_electricity_out_of_hours_use` though, however I have kept them separate for now as not all three fuels are the same.

Gas and storage heaters used out of school hours

---

app/controllers/comparisons/thermostat_sensitivity_controller.rb
app/models/comparison/thermostat_sensitivity.rb
app/views/comparisons/hot_water_efficiency/_table.html.erb
app/views/comparisons/thermostat_sensitivity/_table.csv.ruby
app/views/comparisons/thermostat_sensitivity/_table.html.erb
config/routes.rb
db/migrate/20240315093822_create_thermostat_sensitivities.rb
db/schema.rb
db/views/thermostat_sensitivities_v01.sql
spec/system/comparisons/thermostat_sensitivity_spec.rb

The original report has up_downify arrows on the column, which results in green down arrows for a negative number. I don't think down is positive from reading the report description but I could be wrong: 
> A negative value is indicative of very poor thermostatic control, where Energy Sparks’ modelling cannot make sense of the relationship between the school's gas consumption and outside temperature.
Have left it as the original for now, but wondered if we need to update up_downify to have the option to switch negative to be red if need be?

Annual saving through 1C reduction in thermostat temperature

---

app/helpers/application_helper.rb
app/views/management/schools/_overview_data.html.erb
app/views/schools/advice/baseload/_current_baseload.html.erb
app/views/schools/advice/electricity_intraday/_insights_your_current_peak_electricity_use_table.html.erb
app/views/schools/advice/long_term/_current_usage.html.erb
app/views/schools/school_targets/_limited_data.html.erb
app/views/schools/school_targets/_target_table_row.html.erb
app/views/schools/school_targets/progress/current.html.erb
app/views/schools/school_targets/progress/expired.html.erb

The format_unit helper requests :html formatted values from analytics - so now all html formatted percent values include `&percnt;`, where as before they were inconsistently `%` or `&percnt;` depending on the type of percentage format requested.
i.e. the format_unit helper calls:
`
FormatEnergyUnit.format(units, value, :html, false, in_table, user_numeric_comprehension_level).html_safe
`
The main issue was that up_downify by default calls sanitize on values, so now that it is being passed values containing `&percnt;` rather than `%` in some cases, it was outputting: `&amp;percnt;` which is rendered as `&percnt;`.
I've fixed these in the app by not sanitizing in this situation, assuming this is ok to do anyway.
The other issue we were having in a couple of places was that when passing a …

HTML percent issues

---

app/jobs/campaign_contact_handler_job.rb
app/mailers/campaign_mailer.rb
app/services/campaigns/contact_handler_service.rb
app/views/campaign_mailer/notify_admin.html.erb
lib/capsule_crm/client.rb
spec/lib/capsule_crm/client_spec.rb
spec/mailers/campaign_mailer_spec.rb
spec/mailers/previews/campaign_mailer_preview.rb
spec/services/campaigns/contact_handler_service_spec.rb

To support marketing efforts we will have a form on the webpage to allow prospective users to book a demo or request more information. To capture this we will be storing the information in CapsuleCRM.
This PR:
- Adds a basic CapsuleCRM client capable of creating a new Party (contact) and Opportunity (sales lead). This allows us to capture some basic information provided by users plus some tagging and a custom field value to support internal workflow
- A mailer to send an internal email when someone completes the form, with the provided details and links to Capsule
- A mailer preview for the above
- A service to coordinate creating parties and opportunities in Capsule and sending an email notification. If there are API/comms errors with capsule then the service ensures that the email is …

Create basic integration with CapsuleCRM

---

.tx/config
app/assets/javascripts/application.js
app/assets/javascripts/cookie_banner.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/cookie_banner.scss
app/controllers/home_controller.rb
app/models/video.rb
app/views/home/cookies.html.erb
app/views/layouts/application.html.erb
app/views/layouts/home.html.erb
app/views/shared/_cookie_banner.html.erb
app/views/shared/_cookie_buttons.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_google_analytics.html.erb
app/views/shared/_head.html.erb
config/locales/cy/views/shared/shared.yml
config/locales/views/home/cookies.yml
config/locales/views/shared/shared.yml
config/routes.rb
spec/models/video_spec.rb
spec/support/system.rb
spec/system/cookie_banner_spec.rb

Implements a cookie banner for Energy Sparks.
The banner is shown at the bottom of the browser window until user accepts or rejects analytics cookies. We then store their preference for one year and make calls to the Google Analytics consent API to update the consent status which by default is 'denied' for all options. This means GA will only set cookies if user has agreed.
For more clarity on our cookie policy I've added a separate Cookies page, as [recommended by this pattern](https://design-system.service.gov.uk/patterns/cookies-page/). This summarises what cookies are used and when they are expired. It also allows a user to update their preference after dismissing the cookie banner. Otherwise the banner isn't shown for a year.
I've added to register a new adapter for …

Cookie banner

---

app/views/shared/_footer.html.erb
public/404.html
public/422.html
public/500.html

We currently use static 404, 422 and 500 pages for routing and server errors in prod. These haven't been updated in some time so the header and footer are out of date.
As an interim improvement I've removed the old nav links and updated the footer.
Ideally these would share the same partials, but presumably this is to avoid recursive errors in layouts, etc.

Fix static 404 page

---

app/controllers/landing_pages_controller.rb
app/views/landing_pages/_form.html.erb
app/views/landing_pages/find_out_more.html.erb
spec/system/landing_pages_spec.rb

When a user hits the campaign landing page, ensure that the UTM codes are:
- passed on to the next page which has the contact form
- submitted with the form to the controller
- added to the redirect to the final page
This will allow us to track the codes through to conversion in all situations.

Pass UTM parameters through workflow

---

spec/system/schools/advice_pages/electricity_out_of_hours_spec.rb
spec/system/schools/advice_pages/gas_out_of_hours_spec.rb

A bug in the spec setup:
- was attempting to create no calendar, but factory was supplying on anyway
- reading end date was not being set properly for all specs
This caused the specs to fail today. Presumably some underlying date issue with the default holidays in the calendars created by FactoryBot
Fix was to create an empty calendar instead and explicitly set reading end date.

Fix date ranges in out of hours specs

---

app/assets/javascripts/cookie_banner.js
app/assets/stylesheets/cookie_banner.scss
app/views/home/cookies.html.erb
app/views/shared/_cookie_banner.html.erb
app/views/shared/_cookie_buttons.html.erb
config/locales/views/home/cookies.yml
spec/system/cookie_banner_spec.rb

Reworks the cookie preference buttons on the cookies page. These are separate to the banner and allow someone to change their preference after the banner has been dismissed.
The buttons will now toggle between showing the Accept / Reject button based on the current state of the cookie and will hide the banner if it is still being displayed (e.g. if the user has clicked 'learn more' in the banner and then used the buttons).

Rework cookie preference buttons

---

app/assets/javascripts/table_sorting.js
app/components/energy_tariff_table_component/energy_tariff_table_component.html.erb

The upgraded DataTables component is still creating alerts due to table errors. I think the default way of reporting errors may have changed in the upgrade which is why we're seeing them now.
The errors fixed before and the tariff table error fixed here are due to inconsistencies between number of cols in the `thead` vs `tbody`. The fix is to ensure they're consistent.
There are also errors in the baseload page when we are creating a row for a meter that doesn't have enough data for all columns. In this case we just add a `<td colspan="X">...</td>` with a message to say when that data will be available.
It turns out that DataTables doesn't support `colspan` or `rowspan` in the `tbody` so the table doesnt initialise properly. Presumably this was just silently failing before.
While I decide …

DataTables alerts

---

app/controllers/landing_pages_controller.rb

Rather than sort alphabetically, sort the org type based on who likelihood of use

Remove sort on org types in contact forms

---

app/controllers/schools/interventions_controller.rb
spec/system/interventions_spec.rb

We're getting errors from a crawler hitting the interventions page with the id for an activity (for the same school).
Either there's a problem with our internal linking or we previously had issues and the crawler is still fetching old/incorrect urls. I can't find any obviously incorrect urls in templates or redirects in our routes.rb.
As an interim fix, this PR checks to see if the observation that is loaded is actually an activity and, if so, redirects to the right location with a 301 Moved Permanently response.

Add redirect for incorrect urls

---

Gemfile
Gemfile.lock
app/controllers/comparisons/heat_saver_march_2024_controller.rb
app/helpers/comparisons_helper.rb
app/models/comparison/heat_saver_march_2024.rb
app/models/concerns/multiple_fuel_comparison_view.rb
app/views/comparisons/heat_saver_march2024/_electricity.csv.ruby
app/views/comparisons/heat_saver_march2024/_electricity.html.erb
app/views/comparisons/heat_saver_march2024/_gas.csv.ruby
app/views/comparisons/heat_saver_march2024/_gas.html.erb
app/views/comparisons/heat_saver_march2024/_storage_heater.csv.ruby
app/views/comparisons/heat_saver_march2024/_storage_heater.html.erb
app/views/comparisons/heat_saver_march2024/_table_title.html.erb
app/views/comparisons/heat_saver_march2024/_total.csv.ruby
app/views/comparisons/heat_saver_march2024/_total.html.erb
config/locales/analytics/alerts/gas/boilercontrol.yml
config/locales/analytics/benchmarking/content_base.yml
config/locales/views/comparisons/comparisons.yml
config/routes.rb
db/migrate/20240417104449_create_heat_saver_march_2024s.rb
db/schema.rb
db/views/heat_saver_march_2024s_v01.sql
lib/energy_sparks/calculator.rb
lib/tasks/deployment/20240417100759_heat_saver_march2024_config.rake
spec/models/concerns/multiple_fuel_comparison_view_spec.rb
spec/system/comparisons/heat_saver_march_2024_spec.rb

Implements a new report for the Winter Heat Saver competition.
The report uses some new period comparison alerts so the PR bumps the analytics and includes the database changes to register those and the new report.
The report consists of 4 tables (a total and one each for electricity, gas and storage heaters) and a chart.
The views can eventually be repurposed to become the basis for the new configurable period reports so I've spent a bit of time ensuring they have a sensible table structure and footnotes, although there's more that could be tidied.
I've also included a new concern `MultipleFuelComparisonView` which can be mixed into views that have columns for the three fuel types across multiple periods. The concern adds some helper methods for calculating totals and percentage changes. …

New report for Energy Sparks competition

---

app/controllers/admin/issues_controller.rb
app/controllers/schools/your_school_estates_controller.rb
app/controllers/schools_controller.rb
app/models/issue.rb
app/models/school.rb
app/views/admin/issues/index.html.erb
app/views/schools/_details_form.html.erb
app/views/schools/your_school_estates/edit.html.erb
app/views/shared/_manage_school.html.erb
config/locales/activerecord.yml
config/locales/views/schools/schools.yml
db/migrate/20240419090546_add_heat_pump_fields_to_schools.rb
db/schema.rb
spec/models/issue_spec.rb
spec/models/school_spec.rb
spec/system/admin/issues_spec.rb
spec/system/admin/school_editing_spec.rb

* Note search: wasn't sure if it was intended to just run an ad-hoc query to return a list of notes or to add a feature - it was as easy to add a search feature to issues/notes, so I did that. Hope that's ok. It looks in the title or description for search terms. You can do an or by typing in GSHP|ground source heat pump. 
* Added new fields - just the checkboxes to the edit school details page, but also the percent and notes fields to the school estates page (as per other similar fields)
* Removes your_school_estates feature flag, which can be removed from test/production env too once this has been deployed
Might benefit if we all had a new database dump as getting big conflicts for schema.rb ?

Add additional school features to edit school details & school estates page + issues search

---

app/services/amr/n3rgy_readings_download_and_upsert.rb
lib/tasks/amr_importer/import_n3rgy_readings.rake
spec/services/amr/n3rgy_readings_download_and_upsert_spec.rb

Revises the service used to load data from n3rgy so that it can reload all available data.
Adds a rake task to run the service using this configuration, for all n3rgy meters.

Add task to reload all n3rgy data

---

app/services/amr/n3rgy_readings_download_and_upsert.rb
spec/services/amr/n3rgy_readings_download_and_upsert_spec.rb

Further revision to the logic around loading data from n3rgy.
Their import processes regularly reloads the last 7 days of data to incorporate any missing readings. So ensure that we always reload the last 7 days every day to ensure that we have the latest data.
This means repeated daily requests, but ensures we still as current as possible.

Always reload last week of data from n3rgy

---

app/models/activity_type.rb
app/models/concerns/recordable.rb
app/models/intervention_type.rb
app/models/observation.rb
app/services/activity_creator.rb
db/migrate/20240429144652_add_maximum_frequency_to_recordables.rb
db/schema.rb
spec/models/activity_type_spec.rb
spec/models/intervention_type_spec.rb
spec/models/observation_spec.rb
spec/support/shared_examples/recordable.rb

Adds a `maximum_frequency` attribute to ActivityType and InterventionType
Adds a `Reportable` concern to try and centralise the logic around when to award a point score. This is implemented by the above. 
For the specs I've added some shared examples. These are parameterised to pass in the factories used to record the Recordable objects and the instances of the things that are recorded using them. Possibly slightly unusual, but seemed better than just duplicating the tests.
Reminds me that we need to iron out more of the inconsistencies around ActivityType and InterventionType and the related recordings.

Set maximum frequency for scoring on activities and interventions

---

app/controllers/comparisons/recent_change_in_baseload_controller.rb

Controller was not using the `for_schools` scope so was already returning the full list of schools.

Add `for_schools` scope

---

app/assets/javascripts/analysis.js
app/assets/javascripts/application.js
app/assets/javascripts/init_bootstrap.js

Currently Bootstrap tooltips and popovers are initialised in `analysis.js`
- all tooltips are initialised when page is ready, aftering setting up charts
- tooltips in chart annotations are initialised after the annotations have been loaded and added to the chart
- popovers are only initialised when a chart has been successfully loaded
This means that if a page doesn't have a chart then popovers don't work. Tooltips will be working everywhere though.
We also use popovers in the calendar views but these are explicitly initialised already.
I've changed things so that:
- there's a separate `init_bootstrap.js` file which initialises all tooltips and popovers. Seemed better to have that more clearly defined
- removed the call to initialise popovers in `analysis.js` as it doesn't seem to be …

Initialise tooltips and popovers on all pages

---

app/components/comparison_table_component.rb
app/components/footnote_modal_component.rb
app/components/school_group_comparison_component.rb
app/components/school_group_comparison_component/school_group_comparison_component.html.erb
app/controllers/comparisons/base_controller.rb
app/helpers/advice_page_helper.rb
app/views/comparisons/base/_unlisted.html.erb
app/views/comparisons/base/_unlisted_schools.html.erb
app/views/comparisons/base/index.html.erb
app/views/comparisons/base/unlisted.js.erb
app/views/comparisons/shared/arbitrary_period/_total.html.erb
app/views/school_groups/priority_actions.html.erb
app/views/schools/advice/_how_have_we_analysed_your_data_table_caption.html.erb
app/views/schools/advice/advice_base/insights.html.erb
config/locales/views/comparisons/comparisons.yml
config/routes.rb
lib/generators/comparison_report/comparison_report_generator.rb
spec/components/comparison_table_component_spec.rb
spec/components/footnote_modal_component_spec.rb
spec/helpers/advice_page_helper_spec.rb
spec/system/compare_spec.rb

Currently looks like this:
It derives the count of unlisted schools by subtracting the count of the result set from the original list of schools. 
Clicking on the list of schools runs the original queries again, subtracts the schools returned in the query from the filtered schools. It possibly could be made quicker to load by passing a list of unlisted schools extracted from the original query, but this would likely add processing time to the original page.
The modal links to the analysis page for each school - as well as the school. Not sure about the analysis link as it quite often is a link to a page where it shows no data... See what you think.
This PR also adds a Link component to the FootnoteModal component, so have added this in other parts of the codebase where for links where …

Display unlisted schools in comparison reports

---

Gemfile
Gemfile.lock
app/controllers/admin/comparisons/reports_controller.rb
app/controllers/compare_controller.rb
app/models/comparison/report.rb
app/models/comparison/report_group.rb
app/services/transifex/loader.rb
app/views/admin/comparisons/reports/_form.html.erb
app/views/admin/comparisons/reports/index.html.erb
app/views/admin/index.html.erb
app/views/compare/benchmarks.html.erb
config/initializers/flipper.rb
config/routes.rb
db/migrate/20240501145002_create_comparison_report_groups.rb
db/migrate/20240507101407_create_flipper_tables.rb
db/schema.rb
lib/tasks/deployment/20240502154836_migrate_benchmark_groups.rake
lib/tasks/deployment/20240507103733_enable_comparison_reports_for_admins_feature_flag.rake
spec/factories/comparisons/report_groups.rb
spec/factories/comparisons/reports.rb
spec/models/comparison/report_group_spec.rb
spec/models/comparison/report_spec.rb
spec/services/transifex/loader_spec.rb
spec/system/admin/comparisons/reports_spec.rb
spec/system/admin/flipper_spec.rb
spec/system/compare_spec.rb

**Adds flipper**
Doing the next tasks as a new branch
- Create admin interface for report groups and add inline edit buttons. Don't allow those attached to a report to be deleted. 
- Add Comparison admin menu to all comparison admin pages

Add comparison report groups

---

app/services/alerts/adapters/analytics_adapter.rb
spec/services/alerts/adapters/analytics_adapter_spec.rb

A quick fix to the issue reported by Leigh: https://app.rollbar.com/a/energysparks/fix/item/EnergySparksProduction/3411#detail
This is more of a sticking plaster fix, I think there is a better fix.
Quick investigation shows that reporting_period is not defined in all analysis_object objects, just those that inherit from AlertAnalysisBase, this is why the error is occurring when reporting_period is called on non-alert analysis objects. Other methods used in the same method (such as  front_end_template_data) are defined in ContentBase. 
So perhaps we need to check that the object is an alert before we call reporting_period on it. Or define reporting_period in ContentBase and have it returning nil - although I'm not sure that would be the right solution.

Reporting period quick fix

---

app/models/comparison/change_in_electricity_since_last_year.rb

Where clause was only removing schools where BOTH previous and current year kwh values were not null. It should be excluding any school whether EITHER value is null.

Fix where clause for annual change in electricity use

---

app/models/comparison/hot_water_efficiency.rb

Looking at the advice page there are additional relevance checks at https://github.com/Energy-Sparks/energy-sparks/blob/51fa420b14454b3f441b2e6ef5e65fbb8185e7d1/app/controllers/schools/advice/hot_water_controller.rb#L30 that  cause it to not show the analysis
Looks like for the efficiency to be infinite this estimate is coming out at zero
https://github.com/Energy-Sparks/energy-sparks_analytics/blob/53d0dfab07e93e972774429c2b84a10246f7f6d6/lib/dashboard/modelling/heating/hot_water_investment_analysis.rb#L61

Hot water efficiency - filter out 0 cost per pupil

---

app/models/comparison/thermostat_sensitivity.rb

If a school has very poor thermostatic control then our heating modelling cannot produce sensible savings from a 1C change in thermostat.
The current report just includes these schools with a note to explain negative values. For the new report we will filter these out.

Exclude schools with poor thermostatic control from 1C saving report

---

app/services/schools/advice/baseload_service.rb
spec/services/schools/advice/baseload_service_spec.rb

The BaseloadService currently attempts to generation seasonal (and intraday) variations for all electricity meters:
```
@electricity_meters ||= @meter_collection.electricity_meters
```
When a MeterCollection is setup by the application it initially includes all types of electricity meters, including solar generation and export meters. During the aggregation process the list of electricity meters is updated so that it only contains mains meters.
It turns out there's a subtle bug which can occur when there's an incompletely configured solar setup:
- an admin has added a solar_pv meter
- data has been loaded for the solar_pv meter, e.g. by backfilling from a CSV file
- the meter attributes configuring the solar panels have not been added
- a user visits the baseload analysis page
In the …

Fix issue with partially configured solar meters

---

app/controllers/comparisons/base_controller.rb
app/controllers/comparisons/hot_water_efficiency_controller.rb
app/models/comparison/hot_water_efficiency.rb
app/views/comparisons/base/_unlisted_schools.html.erb
app/views/comparisons/hot_water_efficiency/_unlisted.html.erb
config/locales/views/comparisons/comparisons.yml
spec/system/comparisons/hot_water_efficiency_spec.rb

Extracts the message for unlisted schools into a helper method that can be overridden on a per-controller basis.
Adds filter to where clause
Overrides the unlisted school modal to indicate whether a school has a swimming pool in the list.

Remove schools with swimming pools from hot water report

---

app/controllers/compare_controller.rb
config/routes.rb
lib/tasks/deployment/20240520102800_comparison_reports_redirect.rake
spec/system/compare_spec.rb

Have put the redirect from old report urls to new behind a comparison_reports_redirect feature flag, so we can revert if need be.
This PR also:
* Switches on comparison_reports_redirects for all
* Switches on new comparison reports for all on the benchmark list page
* Switches off comparison_reports_link_to_old (the current links on the benchmark list page) as it doesn't make sense to have them now
Hopefully this is right - wasn't sure if you'd rather switch these on manually or not - can always change them.

Add redirects from old comparison report urls to new

---

app/views/comparisons/heating_coming_on_too_early/_optimum_start_analysis.csv.ruby
app/views/comparisons/heating_coming_on_too_early/_optimum_start_analysis.html.erb
app/views/comparisons/heating_coming_on_too_early/_table.csv.ruby
app/views/comparisons/heating_coming_on_too_early/_table.html.erb

I recently changed the heating_coming_on_too_early comparison to order by school name.
Just noticed that there are additional calls to `.order` in the individual tables. These seem to be ignored as the spec is checking for sorting by name already.
However they do trigger ActiveRecord to run the query more than once. This can be slow when there is a lot of schools, so removing it optimises the report generation.

Remove additional ordering in heating_coming_on_too_early report

---

app/assets/config/manifest.js
app/assets/javascripts/transport_surveys/storage.js
config/initializers/assets.rb

The changes discussed earlier did indeed allow the code to be deployed, however, the transport app loaded, but still didn't work properly - erroring with the following files missing:
Which I think would make sense, as they are not listed in the precompile config line in assets.rb
(worked locally though, that's why I didn't add them)
I have now added them to this branch - which bought up a couple of similar uglifier issues using ||= operator in storage.js. Have also fixed those in this branch.
Ended up having to list all the individual assets, as transport_surveys/* glob doesn't appear to work
`rake assets:clobber assets:precompile` shows all assets compiling now.

Fix transport js

---

Gemfile
Gemfile.lock
config/locales/analytics/common.yml
config/locales/cy/analytics/common.yml
config/locales/cy/views/advice_pages/electricity_intraday.yml
config/locales/views/advice_pages/electricity_intraday.yml

* Capitalise "school day" series name. https://github.com/Energy-Sparks/energy-sparks_analytics/pull/698
* Update intraday page text to refer to Well Managed and Exemplar not benchmark and exemplar
* Fixes previously missed issue with chart sub title markup in Welsh version of electricity_intraday.yml

Correct 'school day' chart series label on electricity intraday chart

---

app/jobs/application_job.rb
app/jobs/campaign_contact_handler_job.rb
app/jobs/daily_regeneration_job.rb
app/jobs/dcc_checker_job.rb
app/jobs/dcc_grant_trusted_consents_job.rb
app/jobs/funder_allocation_report_job.rb
app/jobs/generate_subscriptions_job.rb
app/jobs/manual_data_load_run_job.rb
app/jobs/school_batch_run_job.rb
app/jobs/school_group_meter_report_job.rb
app/jobs/send_data_source_report_job.rb
app/jobs/send_procurement_route_report_job.rb
app/jobs/send_review_group_tariffs_reminder_job.rb
app/jobs/send_review_school_tariffs_reminder_job.rb
app/jobs/solar/base_solar_loader_job.rb
app/jobs/solar_area_loader_job.rb
config/application.rb
spec/jobs/daily_regeneration_job_spec.rb
spec/jobs/manual_data_load_run_job_spec.rb
spec/jobs/school_batch_run_job_spec.rb
spec/jobs/send_review_group_tariffs_reminder_job_spec.rb
spec/jobs/send_review_school_tariffs_reminder_job_spec.rb
spec/jobs/solar_area_loader_job_spec.rb
spec/support/shared_contexts/jobs.rb

Warning from GoodJobs:
> DEPRECATION WARNING: The next major version of GoodJob (v4.0) will change job priority to give smaller numbers higher priority (default: 0), in accordance with Active Job's definition of priority.
> To opt-in to this behavior now, set config.good_job.smaller_number_is_higher_priority = true in your GoodJob initializer or application.rb.
> To not opt-in yet, but silence this deprecation warning, set config.good_job.smaller_number_is_higher_priority = false.
Currently we set a priority of 5 for low priority jobs and 10 for high priority.
High priority jobs are:
* Requests for reports from admins
* Manual data loads or regenerations
* Daily school regenerations
Lower priorities are:
* Sending out alert emails. These need to be lower priority that the daily …

Change GoodJobs priority scores to disable deprecated warning

---

app/controllers/admin/data_sources_controller.rb
app/models/data_source.rb
app/services/amr/n3rgy_energy_tariff_loader.rb
app/views/admin/data_sources/_form.html.erb
db/migrate/20240530103709_add_load_tariffs_to_data_source.rb
db/schema.rb
lib/tasks/deployment/20240530110935_disable_tgp_energy_tariffs.rake
spec/services/amr/n3rgy_energy_tariff_loader_spec.rb
spec/system/admin/data_sources_spec.rb

We are now using the n3rgy API to load data for:
- real SMETS-2 meters
- some AMR meters which are provided by their API
The first set have tariffs the second do not. Currently we expect both to be available so get errors in Rollbar when trying to load tariffs for the AMR meters.
This PR disables loading of tariffs from the n3rgy API using a flag on the DataSource associated with a Meter. 
All of the AMR meters have associated with a specific DataSource and the changes include a database update to switch off the new flag for that.
This seemed best option as there's no reliable way to distinguish the meters via the n3rgy API.

Dont load tariffs for some n3rgy meters

---

app/controllers/schools/advice/gas_recent_changes_controller.rb
app/helpers/advice_page_helper.rb
app/views/schools/advice/gas_out_of_hours/_insights.html.erb
app/views/schools/advice/gas_recent_changes/_analysis.html.erb
app/views/schools/advice/gas_recent_changes/_insights.html.erb
app/views/schools/advice/out_of_hours/_current_usage.html.erb
lib/tasks/deployment/20240530133928_change_weekend_gas_alert_link.rake
spec/helpers/advice_page_helper_spec.rb
spec/support/shared_contexts/advice_pages.rb
spec/support/shared_examples/advice_pages.rb
spec/system/schools/advice_pages/gas_recent_changes_spec.rb

The above alert currently links to a section of the out of hours usage analysis page. It's also shown on the out of hours insights page.
But if a school has limited data (< 3 months) then we can still show this alert but they won't have access to that advice page.
This PR:
- moves the alert notice so that its included on the gas recent changes insights and analysis page instead
- updated the configuration of the alert type, so that the links are repointed
I've added a spec for the advice page and some shared context/examples to help with setup. The presence of these alerts wasn't being tested before so this starts to fill in a gap.
Also fixed an issue with displaying alerts for multiple types.

Change where weekend gas alert notice is shown on advice page

---

app/components/chart_component/chart_component.html.erb
app/views/shared/_analysis_controls.html.erb

Currently the axis controls for the charts are named after the chart type, e.g. `chart_gas_heating_season_intraday_up_to_1_year`. But if we have more than one chart of the same type on the page then the controls don't have unique names. Trying to change the axis of the second chart updates the first.
This is noticeable on the heating control analysis when a school has multiple gas meters. We show the `gas_heating_season_intraday_up_to_1_year` chart for the school then a separate section with options to view charts for each meter.
The charts are already named uniquely to avoid problems with loading data. So this PR just changes the controls to use the chart id as the basis for their names, rather than the type.
Tested manually but chart switching still works fine and resolves the problem …

Change id for chart axis controls

---

app/assets/javascripts/analysis.js

Currently if we get an error trying to display a chart we replace the entire `chart-wrapper` div with an error message. That means the title and controls are removed.
This isn't ideal for the meter breakdown charts where the chart wrapper also includes a select box allowing users to switch between meters. This means an error with one meter removes the ability for the user to look at other meters.
This can happen on the heating control pages where we should a breakdown of gas usage by meter. If we have limited data for a meter, or issues creating heating model the user can't switch to another meter.
This PR changes the standard `chartFailure` function in our javascript to:
- no longer display the chart id to users. This is internal and not necessary
- replace the div containing the …

Change how chart failures are displayed 

---

app/controllers/schools/school_targets/progress_controller.rb
app/views/schools/school_targets/progress/current.html.erb
app/views/schools/school_targets/progress/expired.html.erb

The school target analysis produces several difference performance metrics. 
One is a % comparison of actual usage vs their usage last year. So a simple % comparison.
The other compares their actual usage vs how much we estimate they would use in a similar month to last year. I believe this was originally done to make allowances for differences in temperature, number of school/holiday dates, etc. 
But this leads to some inconsistencies when its presented alongside the actual and target figures. So we've decided to switch to using the former as its clear to usage what is going on. 
This PR just switches which series is added as the final row in the progress report and to calculate the cumulative progress.

Change series used on targets report

---

app/services/alerts/generate_and_save_alerts_and_benchmarks.rb

Incorrectly named attribute referenced in alert code. Need to get this fixed as possibly masking underlying errors in alerts.

Fix attribute in AlertError

---

spec/factories/activity_types_factory.rb
spec/factories/intervention_types_factory.rb
spec/factories/schools_factory.rb
spec/models/alert_spec.rb

We have been getting some flaky tests in the comparison reports. Some of these, e.g. the heating coming on too early, involve sorting schools by name. And then asserting the order.
However the existing School factory creates names like: `test school #{n}`. 
When we get to around 100 schools then the specs can fail because we might have schools: "test school 98", "test school 99" and "test school 100". When sorted by name, they will be returned in the reverse order.
This PR updates the sequence of school name to be: `sequence(:name, 'School AAAAA1')` which produces names using [succ](https://apidock.com/ruby/String/succ). This should produce sensible sorts.
Also:
- fixes a flake in the Alert model spec. Spec asserts a fixed order in the array but the SQL doesn't impose an order
- updates …

Fix ordering issues in comparison report specs

---

lib/tasks/utility.rake

Fixes a utility rake task used to copy contents of s3 buckets so that it properly pages through all bucket contents and not just the first 1000.

Properly page through responses when copying across buckets

---

lib/tasks/deployment/20240619123745_fix_engie_config.rake

Database update to update the header and mpan_mprn column for the Engie config. The CSV files have changed format, although are currently still loading as the column is in the same position.

Update Engie configuration

---

lib/tasks/deployment/20240619125347_new_solar_for_schools.rake

Adds a new CSV format for loading data for Solar for Schools.
Disables the old format that we were last using in 2022. 
Have confirmed format works for manually uploaded files after setting up a couple of serial numbers.

New Solar For Schools CSV format

---

.rubocop_todo.yml
app/models/amr_data_feed_config.rb
app/services/amr/data_feed_translator.rb
app/views/admin/amr_uploaded_readings/new.html.erb
bin/importmap
db/migrate/20240619153937_add_delayed_reading_to_amr_data_feed_config.rb
db/schema.rb
lib/tasks/deployment/20240619171210_create_passiv_solar_format.rake
spec/services/amr/data_feed_translator_spec.rb
spec/system/admin/amr_uploaded_readings_spec.rb

The passiv system for collecting solar data is only able to produce CSV files that contain a timestamp for the day the readings were _collected_ rather than when the energy was consumed. So the timestamps are always a day behind.
As they are unable to change this, this PR:
* Adds a new option to our data feed configs to flag that there are "delayed readings"
* Refactors the existing data feed translator spec to clarify what is currently being tested and just tidy up. The test names didn't really reflect what was being asserts in many cases
* Changes the data feed translator to reformat the dates to a day earlier so we end up with the correct dates in the database
* Adds a configuration for the Passiv format, which uses this setting
* Adds a warning on the upload page for admins about the …

Passiv Solar Data Format

---

app/controllers/admin/amr_uploaded_readings_controller.rb
app/services/amr/single_read_converter.rb
lib/tasks/deployment/20240627154223_energy_assets_corona_format.rake
spec/services/amr/single_read_converter_spec.rb

Data format has changed for gas data for one of the largest groups.
The PR adds a new data feed config for the format. It uses a row per reading style with separate date and time columns.
The time format is currently rejected by our loader, so have had to tweak that to ensure its accepted

Add new Energy Assets/Corona format and time format

---

app/controllers/school_groups_controller.rb
app/services/school_groups/recent_usage_csv_generator.rb
app/views/school_groups/show.html.erb
spec/services/school_groups/recent_usage_csv_generator_spec.rb
spec/support/shared_examples/school_groups.rb
spec/system/school_groups_spec.rb

Currently we are showing all visible schools to everyone that can access the group. Using the new access control settings we should only be showing the schools that are visible to that user. User should also only be able to download CSV file with same list of schools.

Filter schools shown on school group recent usage tab and downloads by user permissions

---

app/components/podium_component/podium_component.html.erb
config/locales/views/components/podium.yml

The national scoreboard runs between 1st Sept to 30th June. 
This means when recording activities between 1st July and 31st August, if a school has not recorded any activities in the that time period, then they will not have a position on the national scoreboard. 
This causes an error. As a fix for this I've removed the message about national ranking from the podium.

Check for national scoreboard position

---

app/controllers/school_groups_controller.rb
spec/system/school_groups_spec.rb

Changing to use `accessible_by` on school group dashboard meant that admins now see a list of schools that included inactive (archive/removed) schools which isn't what we want.
This fixes that by always adding the `active` scope.

Hide inactive schools on group dashboard

---

app/controllers/school_groups_controller.rb
spec/factories/school_groups_factory.rb
spec/support/shared_examples/energy_tariffs.rb
spec/system/admin/emails_spec.rb
spec/system/admin/school_groups_spec.rb
spec/system/landing_pages_spec.rb
spec/system/school_groups_spec.rb

If all schools are filtered out for the current user on the school group dashboard, then we get a SQL error.
We're getting errors from crawlers but in some cases these are for groups that are no longer on the site, so they're following cached links. Will do a separate PR to add a flag to mark group as active/inactive
This PR fixes the immediate error by checking to see if the list of schools is empty and, if so, force the user to the map view. This makes it consisent with how we handle a group they don't have permission to view. The map view has been updated to list all the schools.

Better handling if all schools are filtered on group dashboard

---

app/controllers/schools/school_targets/progress_controller.rb
app/models/school.rb
app/services/targets/generate_progress_service.rb
spec/factories/school_targets.rb
spec/models/school_spec.rb
spec/models/school_target_spec.rb
spec/services/targets/generate_progress_service_spec.rb
spec/system/schools/progress_spec.rb

This PR fixes three issues with the current and expired target reports:
- ensures that we're using the right time series for reporting overall progress
- adds an extra check to whether we display a link to the previous years expired target, as we may have only had limited data last year and so there's nothing to actually display in that report
- revises how we decide which months to report on to ensure we only show up to 12 months of data
As most of the tests already cover the general rendering behaviour in most cases I've just tweaked the data setup to ensure only the right time series is available.

Fix current target progress

---

app/models/programme.rb
app/models/programme_type.rb
app/models/school.rb
app/services/activity_creator.rb
app/services/programmes/creator.rb
app/views/programme_types/_completed.html.erb
app/views/programme_types/_prompt.html.erb
app/views/programme_types/_prompt_login.html.erb
app/views/programme_types/_started.html.erb
app/views/schools/_prompt_join_programme.html.erb
config/locales/common.yml
config/locales/cy/views/programme_types/programme_types.yml
config/locales/views/programme_types/programme_types.yml
config/locales/views/schools/schools.yml
lib/tasks/deployment/20240624130949_complete_started_already_completed_programmes.rake
spec/models/programme_type_spec.rb
spec/models/school_spec.rb
spec/services/activity_creator_spec.rb
spec/services/programmes/creator_spec.rb
spec/support/shared_examples/prompts.rb
spec/system/programme_type_spec.rb
spec/system/schools/recommendations_spec.rb

New functionality has meant we encourage users to start programmes where a user has already completed activity types that are part of it. Something we'd not thought of is that a user might start a programme having already completed all activity types within a programme, meaning the activity is effectively complete immediately after starting it.
On production, someone had done this - all activities in a programme were marked as complete but the programme wasn't flagged as completed. This is because the programme creator didn't take this into account when starting a programme. This code fixes this. 
When I was working on this I also spotted an issue with the join programmes prompt. It was saying (on my local machine):
"You've recently completed 14 activities that are part of the Beat your …

Programme progress fix

---

app/views/robots_txts/allow.raw

Add a `Disallow` directive to mark the advice page index as not crawlable.
Also removes a duplicate line as we're linking to the sitemap twice.

Disallow advice page index

---

app/controllers/admin/alert_types_controller.rb
app/views/admin/alert_types/index.html.erb
lib/tasks/deployment/20240705133728_remove_old_alerts.rake

There are a number of alerts in the analytics that we haven't used for some time this includes:
- the "alerts" that generated the content for the old versions of the analysis pages. These are no longer available so the alerts can be safely disabled and removed
- some other alerts that were responsible for doing some old comparison reports, or which were just never used. These were all disabled some time ago. So this PR just removes the records as we won't be re-enabling them.
As the alerts were all disabled some time ago there's no other content to clear up as any historical analysis will already have been cleared out.
Largely just a clear out but will make it easier to start removing some code from the analytics where we know its not used.

Remove old alerts

---

app/views/schools/recommendations/index.html.erb
spec/system/schools/recommendations_spec.rb

The recommendations page has links to a schools advice page and recent alerts. These are still shown even if the school is not currently data enabled.
This PR adds a conditional to check whether those pages are available before adding the links.
The rest of the changes to the template are to make erblint happy.

Hide data enabled links on recommendations page

---

.ebextensions/bootsnap.config

saw this again
`An error occurred during execution of command [app-deploy] - [flip ruby application]. Stop running the command. Error: remove current dir failed: unlinkat /var/app/current/tmp/cache/bootsnap/compile-cache-iseq: directory not empty`

fix bootsnap deploy error

---

app/views/admin/school_groups/_onboarding_schools.html.erb
app/views/admin/school_onboardings/_form.html.erb
spec/system/admin/school_onboarding_spec.rb

On the school onboarding form the funder select box is not populating with the currently selected funder value. This PR fixes that.
The funder shown on the manage school onboardings and manage school group pages is also not showing. Its default to showing the schools funder and then the group. But groups no longer have funders, while the school onboarding does.
Changed it to show the school funder if available otherwise the saved option

Fix funder not displaying

---

app/controllers/schools/advice/electricity_recent_changes_controller.rb
app/controllers/schools/advice/gas_recent_changes_controller.rb
app/controllers/schools/usage_controller.rb
app/models/school.rb
app/views/pupils/analysis/electricity.html.erb
app/views/pupils/analysis/electricity_bar.html.erb
app/views/pupils/analysis/electricity_line.html.erb
app/views/pupils/analysis/gas.html.erb
app/views/pupils/analysis/gas_bar.html.erb
app/views/pupils/analysis/gas_line.html.erb
app/views/schools/advice/electricity_recent_changes/_analysis.html.erb
app/views/schools/advice/gas_recent_changes/_analysis.html.erb
app/views/shared/_usage_controls.html.erb
spec/models/school_spec.rb
spec/system/schools/advice_pages/electricity_recent_changes_spec.rb
spec/system/schools/advice_pages/gas_recent_changes_spec.rb

We currently allow pupils to filter some charts by meter. But when we incorporated those charts into the advice pages, we didn't enable that feature.
As part of providing more options for viewing usage by meter, this PR enables that option. The primary functional change is setting `split_meters: true` when we render a partial. The rest of the changes are tidying for ERBLint plus some basic tests.
The PR also fixes a long standing bug in `School.filterable_meters`. Currently this disallows access to filtering any meters, if a school has solar or storage heaters. But they should still have option to filter gas meters. A future PR will revisit whether we disallow filtering of solar/storage.

Enable meter filtering options on recent change advice pages

---

app/controllers/admin/school_onboardings/configuration_controller.rb
app/controllers/admin/school_onboardings_controller.rb
app/models/school_onboarding.rb
spec/models/school_onboarding_spec.rb
spec/system/admin/school_onboarding_spec.rb

There's a long standing bug in how the admin school onboarding forms were written.
Currently the populating the school onboarding with the default values from the school group are done in the `edit` action on the configuration controller. So when an admin first visits that form the defaults are copied over and can then be accepted or customised.
The bug is that if they visit the form again later as making other changes, then the group default values are reapplied before displaying the form. So the form state looks like any original selections were never saved as its no longer reflecting the database state. 
This PR fixes that bug so that the school group defaults are applied when the school onboarding is initially created.

Fix setting defaults on school onboarding forms

---

app/models/amr_data_feed_config.rb
app/services/amr/data_feed_validator.rb
app/services/amr/data_file_to_amr_reading_data.rb
app/services/amr/single_read_converter.rb
app/views/admin/amr_data_feed_configs/edit.html.erb
spec/services/amr/csv_parser_and_upserter_spec.rb
spec/services/amr/data_feed_validator_spec.rb
spec/services/amr/single_read_converter_spec.rb

We currently support an option on `AmrDataFeedConfig` called `missing_readings_limit`. If set then any day that has more missing half hourly readings that this limit will automatically be rejected by the data loader. It allows us to silently reject incomplete data without generating lots of warnings for the admins.
While this was previously used on some older configs, it's not currently used. When set it's applied by the `DataFeedValidator`.
Separately the `SingleReadConverter` uses a hard coded `BLANK_THRESHOLD` when it is converting "row per reading" formats into the standard format. The value of that constant has always been 1.
For a new data supplier we need to be more tolerant of some missing half-hourly readings. Currently they are sending us data in a "row per reading" format that …

Rework how the SingleReadConverter drops rows

---

app/controllers/admin/school_onboardings_controller.rb
app/views/admin/school_onboardings/index.html.erb
spec/system/admin/school_onboarding_spec.rb

Limits the pages to only groups with incomplete onboardings
Adds link back to the top of the page
Fixes issue with download of all incomplete onboardings, as some records aren't associated with a group

Small quality of life improvements for school onboardings page

---

app/controllers/admin/reports/solar_panels_controller.rb
app/models/meter_attribute.rb
app/views/admin/reports/solar_panels/index.html.erb
spec/models/meter_attribute_spec.rb

Reworks the admin solar panel report so that it has:
- one table reporting on schools with metered solar
- one table reporting on schools with estimated solar
Tweaks the text on the page to better describe report and remove unnecessary columns.

Rework solar panel report report

---

config/initializers/devise.rb
spec/factories/users_factory.rb
spec/system/account_confirmation_spec.rb
spec/system/admin/school_users_spec.rb
spec/system/password_reset_spec.rb
spec/system/school_onboarding_spec.rb

Changes minimum password length from 6 to 12 as recommended by CyberEssentials.
I've left the maximum limit in place despite CyberEssentials say it should be unlimited as 128 chars is sufficient for a long passphrase.
I've manually confirmed (via testing and checking the validatable module in Devise) that changing the password length requirements doesn't impact existing users, just new passwords (new users, password resets).
Still need to add validation to pupil account passwords.

Change minimum password length

---

app/models/user.rb
config/locales/views/onboarding/onboarding.yml
spec/factories/users_factory.rb
spec/models/school_spec.rb
spec/models/user_spec.rb
spec/system/school_onboarding_spec.rb

Adds a validation for pupil passwords so they're a minimum of 12 characters. Updates the text on the form.

Add a minimum length to pupil passwords

---

app/views/schools/meters/show.html.erb
spec/components/podium_component_spec.rb
spec/system/scoreboard_spec.rb

- issue with specs that use national scoreboard
- issue with displaying dates from n3rgy, ruby default formatting when turning array of DateTime into string isn't quite RFC2822 (no zero padding on day number), so apply explicit formatting in template

Fix date issues in specs

---

app/classes/tables/summary_table_data.rb
spec/classes/tables/summary_table_data_spec.rb

Dashboard table showing an error when single value is missing:

Fix dashboard error

---

app/controllers/schools/visibility_controller.rb
app/controllers/sessions_controller.rb
app/helpers/application_helper.rb
app/models/school.rb
app/services/school_creator.rb
spec/helpers/application_helper_spec.rb
spec/models/school_spec.rb

Noticed when making changes to authentication that we are loading the models for all visible schools and school groups when serving the sign in form.
This PR has some optimisations that reduces unnecessary queries and memory usage:
- only load school list if we're not showing login for single school
- adds custom query to load school and school group name, returning a list
- caches results of looking up list of schools, expiring it whenever a new school is made (in)visible
Makes a big difference to speed with which page loads, although unlikely that its hit that often in production.

Optimise loading of schools for sign in form

---

app/components/adult_reminders_component.rb
app/components/adult_reminders_component/adult_reminders_component.html.erb
app/components/alerts_component.rb
app/components/alerts_component/alerts_component.html.erb
app/components/application_component.rb
app/components/dashboard_reminders_component.rb
app/components/prompt_component.rb
app/components/prompt_component/prompt_component.html.erb
app/components/prompt_component/prompt_component.scss
app/components/prompt_list_component.rb
app/components/prompt_list_component/prompt_list_component.html.erb
app/controllers/concerns/school_progress.rb
app/controllers/schools_controller.rb
app/services/targets/school_target_service.rb
app/views/layouts/dashboards.html.erb
app/views/schools/new_show.html.erb
app/views/shared/dashboards/_header.html.erb
config/locales/views/schools/schools.yml
lib/tasks/deployment/20240807133613_add_new_dashboard_feature.rake
spec/components/adult_reminders_component_spec.rb
spec/components/alerts_component_spec.rb
spec/components/previews/adult_reminders_component_preview.rb
spec/components/previews/prompt_component_preview.rb
spec/components/previews/prompt_component_preview/examples.html.erb
spec/components/previews/prompt_list_component_preview.rb
spec/components/previews/prompt_list_component_preview/examples.html.erb
spec/components/prompt_component_spec.rb
spec/components/prompt_list_component_spec.rb
spec/support/shared_examples/component.rb

Adds a new feature flag and initial components for the new school dashboards.
- Add feature flag to Flipper. Its off for everyone at the moment. Only the adult dashboard shows revised content when feature flag is active. 
- Adds new layout for school dashboard, to give more flexibility with page layout (new design has some full-width styles). Will later explore whether we can do partial upgrade to Bootstrap 5 in this layout
- Adds new common partial for dashboard title (likely to become component in next iteration)
- Adds new responsive PromptComponent for in-page user prompts
- Adds new responsive PromptListComponent for titled list of prompts with link to more information
- Adapts the AlertComponent to use PromptList when feature flag is active, so we can use this as a common component …

Initial components for new school dashboards

---

app/controllers/schools/advice/base_long_term_controller.rb
app/controllers/schools/advice/base_meter_breakdown_controller.rb
app/views/schools/advice/electricity_meter_breakdown/_analysis.html.erb
app/views/schools/advice/electricity_meter_breakdown/_insights.html.erb
app/views/schools/advice/gas_meter_breakdown/_analysis.html.erb
app/views/schools/advice/gas_meter_breakdown/_insights.html.erb
app/views/schools/advice/long_term/_analysis.html.erb
app/views/schools/advice/meter_breakdown/_analysis.html.erb
app/views/schools/advice/meter_breakdown/_usage_breakdown_table.html.erb

Fixes an issue in new meter breakdown table.
The table loops through all meters for a fuel type. But some schools have decommissioned/old meters which are active but are not included in the usage breakdown calculations because the meter data is >1 year old.
Added a fix to the template that is breaking to skip over any meters not included in the analysis.

Skip decommissioned meters in meter breakdown table

---

config/locales/cy/views/advice_pages/electricity_long_term.yml
config/locales/cy/views/advice_pages/electricity_out_of_hours.yml
config/locales/cy/views/advice_pages/gas_out_of_hours.yml

The rework I did to support meter breakdowns involved renaming some interpolation arguments. I missed a couple in the Welsh translations which are causing errors.
Have reviewed all the pages and only these are affected.

Fix interpolation arguments in updated translations

---

app/controllers/schools/programmes_controller.rb
app/models/programme.rb
app/services/programmes/creator.rb
app/views/programme_types/_completed.html.erb
app/views/programme_types/_started.html.erb
config/locales/cy/views/programme_types/programme_types.yml
config/locales/views/programme_types/programme_types.yml
spec/models/programme_spec.rb
spec/services/programmes/creator_spec.rb
spec/services/programmes/progress_spec.rb
spec/system/programme_type_spec.rb

- have assume not changing functionality via admin pages
- looks like programme_types.prompt.message_html - already looking at last academic year so seems like it should just work

Allow schools to complete programmes each academic year

---

app/components/energy_summary_table_component.rb
app/components/energy_summary_table_component/energy_summary_table_component.html.erb

Uses Bootstrap 4/5 display utilities to hide some of the columns on the dashboard table at small screen sizes.
Rotating the screen or at higher break points all the columns become visible. At `sm` breakpoint and above the table will have a horizontal scroll if needed.

Improve responsiveness of dashboard table

---

app/components/adult_reminders_component.rb
app/components/adult_reminders_component/adult_reminders_component.html.erb
app/components/dashboard_insights_component/dashboard_insights_component.html.erb
app/components/dashboard_reminders_component.rb
app/components/pupil_reminders_component.rb
app/components/pupil_reminders_component/pupil_reminders_component.html.erb
app/controllers/pupils/schools_controller.rb
app/views/pupils/schools/new_show.html.erb
spec/components/adult_reminders_component_spec.rb
spec/components/pupil_reminders_component_spec.rb

Creates initial version of redesigned pupil dashboard:
- conditionally show new template if feature active
- use previously created components to build the page
- add `PupilRemindersComponent` to generate the prompts for pupils to take action
- improve test coverage of the two dashboard reminder components
Adding the equivalences will come in another PR.

Initial version of new pupil dashboard

---

app/components/adult_reminders_component.rb
app/components/adult_reminders_component/adult_reminders_component.html.erb
app/components/pupil_reminders_component/pupil_reminders_component.html.erb
app/components/scoreboard_summary_component.rb
app/components/scoreboard_summary_component/scoreboard_summary_component.html.erb
app/views/pupils/schools/new_show.html.erb
app/views/schools/new_show.html.erb
config/locales/views/components/podium.yml
config/locales/views/components/scoreboard_summary.yml
spec/components/adult_reminders_component_spec.rb
spec/components/pupil_reminders_component_spec.rb

Changes following internal review of dashboards
- make notices about metering issues visible to all
- make programme prompts visible to all on adult dash, as they are on pupil
- remove prompt for activity as we have one in the scoreboard summary
- update links and intro in scoreboard summary
- update colours of adult reminders to mark some are negative, change ordering so negative issues are first to highlight them better

Rework reminders and activity prompt

---

app/components/scoreboard_activity_component/scoreboard_activity_component.html.erb
app/components/timeline_component/timeline_component.html.erb
config/locales/views/components/observation.yml
spec/components/observation_component_spec.rb
spec/components/scoreboard_activity_component_spec.rb
spec/components/timeline_component_spec.rb

Break out point scores into a column and reduce amount of text

Reduce repeated text in timeline and scoreboard activity tables

---

app/components/dashboard_insights_component.rb
spec/components/dashboard_insights_component_spec.rb
spec/support/shared_contexts/dashboard_alerts.rb

The `DashboardInsightsComponent` was loading only adult alerts, it should be using the audience parameter to load just the alerts to be displayed on each dashboard.
Fixes an issue with empty text being displayed on the pupil dashboard.

Ensure only pupil alerts shown on new pupil dash

---

app/components/dashboard_equivalences_component.rb

Shuffles the array of equivalences after fetching from the database. This is to inject a bit more randomness into what is displayed on the pupil dashboards.

Shuffle equivalences

---

app/assets/stylesheets/toggler.scss
app/components/page_nav_component.rb
app/components/page_nav_component/page_nav_component.html.erb
app/controllers/schools/advice/advice_base_controller.rb
app/controllers/schools/advice_controller.rb
app/helpers/application_helper.rb
app/views/admin/procurement_routes/show.html.erb
app/views/schools/advice/_nav.html.erb
config/locales/views/advice_pages/advice_pages.yml
spec/components/page_nav_component_spec.rb

Revises the nav bar shown on the advice page as shown in screenshot with new dashboard feature flag active
Most of the changes are in the `_nav.html.erb` partial which swaps in a different nav if the feature flag is active. I've had to move some default classes from the `page_nav_component.html.erb` file into here to make it easier to alter the styling.
I've had to make a couple of additional changes to the component:
- add a `toggler` flag for sections to disable adding the bootstrap toggle behaviour which we won't need for the recent alerts and priority action menu items
- added conditional check for feature flag in the component to allow some classes in the template to be excluded. This can later be removed
The `AdviceBaseController` has been updated to ensure that the counts displayed …

New advice page nav bar design

---

app/components/advice_page_list_component.rb
app/components/advice_page_list_component/advice_page_list_component.html.erb
app/components/advice_page_list_component/advice_page_list_component.scss
app/components/prompt_component.rb
app/components/prompt_component/prompt_component.html.erb
app/components/prompt_component/prompt_component.scss
app/views/schools/advice/show.html.erb
config/locales/views/components/advice_page_list.yml
spec/components/advice_page_list_component_spec.rb
spec/components/previews/prompt_component_preview/examples.html.erb
spec/components/prompt_component_spec.rb

The new advice page index design has a section "Your energy explained" which lists the links to the advice pages with Bootstrap pills for indicating how the school compares.
I've implemented this as a new component using TitledSection for the basic layout and an updated version of the PromptComponent for displaying each link. The tweaks to the prompt component allow for a `:compact` style which adds the link as a second column rather than below the prompt itself. I've also slightly reduced the padding size.

Create new energy explained component

---

app/components/adult_reminders_component.rb
app/components/adult_reminders_component/adult_reminders_component.html.erb
app/controllers/schools_controller.rb
app/models/audit.rb
app/services/audits/progress.rb
app/views/schools/_prompt_audit.html.erb
app/views/schools/show.html.erb
app/views/shared/navigation/second_nav/_my_school_menu.html.erb
config/locales/views/schools/schools.yml
config/locales/views/shared/shared.yml
spec/components/adult_reminders_component_spec.rb
spec/models/audit_spec.rb
spec/services/audits/progress_spec.rb

**Changes since last review @ldodds**
Now removes the audit link from the my school menu.
Also makes a change to how the audit prompt works. On dashboards etc, we now consistently display the "last audit", rather than the "recent audit". This is displayed if there are still activities or actions left to complete for the audit.
This also changes the prompt text to only use the word "recent", when the audit was created in the last year. i.e.
`You have completed 0/4 of the activities and 0/5 of the actions from your **recent** energy audit
`
Otherwise it would be
`You have completed 0/4 of the activities and 0/5 of the actions from your energy audit
`
Also fixes the icon in the for the audit prompt on the new dashboard.

Changes to My School menu

---

config/locales/mailers/mailer.yml
config/locales/views/schools/schools.yml

Remove several typos. "Pupil-lead" should be "Pupil-led". Spotted on new dashboard text but found other examples.

Fix 'pupil-lead' typos

---

app/components/advice_page_list_component/advice_page_list_component.html.erb
spec/components/advice_page_list_component_spec.rb

Adds sub-headings back into the list of advice pages shown on the page index.

Add sub headings to list of advice pages

---

app/components/page_nav_component.rb
app/components/page_nav_component/page_nav_component.scss
app/views/schools/advice/_nav.html.erb

The link highlighting wasn't working for the new alerts and priorities link in the advice nav.
This involved:
- making the `current` class force bold when active
- allowing the sections to override options provided from the main page nav component
- declaring `match_controller: false` on the sections
Also moved some of the classes specified on the items into the SCSS. Couldn't find a suitable bootstrap var to declare the border-bottom.

Add link highlighting for new advice page nav links

---

app/views/layouts/dashboards.html.erb

The new dashboards and advice page index have a full-width grey background section for the bottom of the page.
However the partner logos, that acknowledge sponsorship of schools using  Energy Sparks, are not in a similar section so we end up with a white space between the grey background and the footer.
This fixes the problem by updating the dashboard layout.

Wrap partner logos in grey background

---

app/components/pupil_explore_component.rb
app/components/pupil_explore_component/pupil_explore_component.html.erb

Reworks the pupil explore component to make the display more compact:
- uses 2 columns for icon and text rather than 2 rows as per original design
- reduce icon size
- reduce padding
- improve responsiveness, hiding icons on small screens
- increase size of link area using bootstrap `stretched-link` class which was used on the old version.

Rework pupil explore blocks

---

config/locales/cy/views/schools/schools.yml

Rollbar error due to missing interpolation key in Welsh version of the audit prompt. Have reworked the structure too.
Text should be roughly correct based on my limited Welsh but will get fixed when we submit the rest for translation.

Fix Welsh audit text

---

config/locales/views/components/observation.yml
spec/components/observation_component_spec.rb
spec/components/scoreboard_activity_component_spec.rb
spec/components/timeline_component_spec.rb

Remove some text prefixing activity and intervention descriptions as this looks repetitive when displayed on school dashboards.

Remove 'Recorded ' prefix in descriptions

---

app/components/dashboard_learn_more_component/dashboard_learn_more_component.html.erb
app/views/schools/new_show.html.erb
config/locales/views/advice_pages/index.yml

Fix typo in advice page index text
Add missing `</div>` tag to learn more component, which was breaking the footer.

Fix type and missing close tag

---

app/controllers/schools/advice/advice_base_controller.rb
app/views/schools/advice/_nav.html.erb
spec/system/schools/advice_pages/advice_pages_spec.rb

The revised advice page nav has some extra variables. These weren't being populated when the school either didn't have the right fuel type for the page or not enough data.
This change ensures the variables are populated earlier in the request cycle and makes the template tolerant to missing vars.

Ensure navbar vars are populated

---

app/components/advice_page_list_component/advice_page_list_component.html.erb
app/helpers/advice_page_helper.rb
spec/components/advice_page_list_component_spec.rb

Fixes an existing issue with the advice index page. 
The advice nav bar is only showing links to the meter comparison pages if a school has multiple gas or electricity meters. However the in-page list is still showing the links.
Fixes the component so that it uses the same helper method as the navbar

Dont show links to meter comparison advice pages if only a single meter

---

app/controllers/schools/advice/base_out_of_hours_controller.rb
app/views/schools/advice/out_of_hours/no_usage.html.erb
config/locales/views/advice_pages/advice_pages.yml
spec/system/schools/advice_pages/gas_out_of_hours_spec.rb

This change checks to see if the total out of hours usage is zero before allowing a user to access the out of hours usage page.
This cropped up for several schools where there seems to be a data issue as we have around 8 months of all zero data. The meters should have been deactivated, but while they were active the out of hours page triggered an error which isn't ideal. 
In another case a school only had data over the summer period where gas data might legitimately have been zero. E.g. if they had electric heating. In this case we needed a message for the user.
This PR checks to see if the total kwh usage for the reported period is zero before allowing access to the insights/analysis pages. If there's zero usage then there's no much to show them. Works similarly to the special case for …

Schools with limited gas data have failing out of hours analysis

---

app/components/dashboard_equivalences_component.rb
app/views/shared/_analysis_controls.html.erb

- Make the left/right margins added by the dashboard equivalence component only apply at `lg` sizes and above. Avoids unnecessary space on small screen sizes
- Add `flex-wrap` to chart controls and buttons, so on smaller screen sizes the controls wrap onto lines rather than being stretched/squashed.
Before for the chart change:
After for the chart change:

Minor responsive fixes for dashboards and advice index

---

app/controllers/admin/activity_type_previews_controller.rb
app/controllers/sessions_controller.rb

Traced a Rollbar error from someone visiting the login page to this returning nil:
`School.find_by(slug: params[:school])`
The param is a slug that identifies the school, but it was returning nil.
The reason is that the school name has recently been updated so the slug has changed. Looks like `find_by` with `slug` only checks the current slug but `FriendlyId` maintains a history. 
The School model will check history on a `find` because of this config:
```
friendly_id :slug_candidates, use: [:finders, :slugged, :history]
```
So have changed the form and one other occurence of using `.find_by(slug: ...)` to just use `.find` as its more flexible.

Error on login form for specific school

---

app/components/scoreboard_summary_component/scoreboard_summary_component.html.erb
spec/components/scoreboard_summary_component_spec.rb

Found a dashboard error for a school that is not visible. If they're not visible, then they're not included in the podium/scoreboard so don't have a position.
Only affects admins reviewing schools that have not completed onboarding.
Added specs to better test the component.

Dashboard error when admin views a non-visible school

---

app/controllers/pupils/public_displays_controller.rb

Removes two of the Rails default headers from specific routes in the public displays controller.
Looks like the signage software used by the MAT testing this feature obeys this directive, so have removed here only (although not sure it's considered a wider best practice any more).
Also removed the check for school in rails cache. This causes a redirect which may be also be causing issues. Might result in slower chart loads if school isn't in cache but otherwise safe.

Remove X-Frame-Options

---

app/mailers/alert_mailer.rb
app/services/alerts/generate_email_notifications.rb
app/services/alerts/generate_subscription_events.rb
app/services/alerts/generate_subscriptions.rb
lib/tasks/deployment/20240925164205_add_batch_email_feature.rake
spec/mailers/alert_mailer_spec.rb
spec/services/alerts/generate_email_notifications_spec.rb
spec/services/alerts/generate_subscription_events_spec.rb

Currently to send out our weekly alerts we do the following:
- generate the `Alert` records with the results of the analysis
- generate `AlertSubscriptionEvent` records, one per `Contact` receiving alerts for each `Alert`
- generate the emails using the above records, sending one email per `Contact`
This was to allow individual users to unsubscribe from receiving specific alerts in their emails. We track which alerts they've unsubscribed to using an `AlertTypeRatingUnsubscription` record. These are created using user specific links that are inserted into each weekly alert email.
This feature is very, very rarely used. Currently we only have a single user that has unsubscribed to a single AlertType.
We hit performance problems this week with the weekly alerts. They are using quite a bit of …

Rework how weekly alerts are generated

---

app/controllers/schools/advice/advice_base_controller.rb
config/routes.rb
spec/support/shared_examples/advice_pages.rb
spec/system/schools/advice_pages/baseload_spec.rb
spec/system/schools/advice_pages/electricity_costs_spec.rb
spec/system/schools/advice_pages/electricity_intraday_spec.rb
spec/system/schools/advice_pages/electricity_long_term_spec.rb
spec/system/schools/advice_pages/electricity_out_of_hours_spec.rb
spec/system/schools/advice_pages/electricity_recent_changes_spec.rb
spec/system/schools/advice_pages/gas_costs_spec.rb
spec/system/schools/advice_pages/gas_long_term_spec.rb
spec/system/schools/advice_pages/gas_out_of_hours_spec.rb
spec/system/schools/advice_pages/gas_recent_changes_spec.rb
spec/system/schools/advice_pages/heating_control_spec.rb
spec/system/schools/advice_pages/hot_water_spec.rb
spec/system/schools/advice_pages/meter_breakdown_spec.rb
spec/system/schools/advice_pages/solar_pv_spec.rb
spec/system/schools/advice_pages/storage_heaters_spec.rb
spec/system/schools/advice_pages/thermostatic_control_spec.rb

Introduces some extra routing to intercept HEAD requests to the insights, analysis and learn_more actions for all advice pages. The requests are handled by a generic action that returns OK and no content. The majority of the before_actions in the controller will be skipped as well, so its should be a quick response.
Rails default behaviour is to respond to a HEAD request by treating it as a GET request, running the same action and then throwing away the rendered content to just return the default headers. While it does allow actions to set additional headers, its wasteful in most cases. And particularly on our advice pages.
Seems like the email scanners that are doing these requests during our weekly alert email sending, don't always wait for the response anyway, as nginx is logging a 499 …

Handle HEAD requests to all advice pages

---

app/controllers/schools/advice/advice_base_controller.rb

Tidies the order of before_actions in the advice base controller.
Currently we check whether the school is in the rails cache only to end up showing a message to say the school doesn't have the right fuel type, we can't run the analysis, or that the user can't view the analysis.
Changes just tweak the order to put the above checks first so that we only check if the meter collection is in the cache if we're actually going to use it for this request.

Reorder before_actions to delay loading meter collection

---

app/mailers/alert_mailer.rb
spec/mailers/alert_mailer_spec.rb
spec/services/alerts/generate_email_notifications_spec.rb

Fixes an issue with revised way of sending alerts (one email per school).
The code was written to `cc` everyone. The rails default mail delivery used in development accepted that without any issues.
However the mailgun ruby library [expects a `to` address without checking if it exists](https://github.com/jorgemanrubia/mailgun_rails/blob/master/lib/mailgun_rails/deliverer.rb#L53C1-L53C41). So we got an error.
The [Mailgun API requires a `to` address](https://documentation.mailgun.com/docs/mailgun/api-reference/openapi-final/tag/Messages/#tag/Messages/operation/httpapi.(*apiHandler).handler-fm-19) as well, so even if the client was more robust there would still be an issue.
So this changes code to use To.
I thought SMTP allowed at least one of TO, CC, BCC but we're limited by Mailgun here.

Use to not cc

---

app/components/comparison_overview_component.rb
app/controllers/schools/advice_controller.rb
app/views/schools/advice/new_show.html.erb
spec/components/comparison_overview_component_spec.rb
spec/system/schools/advice_pages/advice_page_index_spec.rb

As originally implemented the ComparisonOverviewComponent requires the controller to full the school's MeterCollection from the Rails cache before it can be constructed.
For schools with limited data we will only end up using the MeterCollection to check if they have enough data for the comparison. 
This PR does a refactor to avoid loading the MeterCollection until it's actually needed to make an assessment. The component now fetches the MeterCollection directly from the cache and relies on the availability of an existing AdvicePageSchoolBenchmark to decide whether it can display a comparison.
Unlikely to make a big change to most schools, but where a school has limited data this removes the need to load the MeterCollection to render the advice page index.

Refactor Comparison Overview Component

---

Procfile

Old machine had 2 vCPUs. Regenerations with >2 jobs running didn't complete any quicker as the server was CPU bound.
The new machine has 4 vCPUs. Should be possible to increase queue size to 3 without maxing out all CPUs, whilst still reducing time in queue. 
Suggest we try this first to max most use of available resources before adjusting niceness levels so we can see the impacts of both. May not need to adjust nice level if we have spare CPU capacity during regenerations?

Bump regeneration queue size

---

app/views/shared/meter_attributes/_hash.html.erb
app/views/shared/meter_attributes/_time_of_day.html.erb
app/views/shared/meter_attributes/_time_of_day_30.html.erb
app/views/shared/meter_attributes/_time_of_year.html.erb
spec/system/admin/meter_attributes_spec.rb

Several of the forms used to create meter attributes are broken. They all have code like this:
```
:some_symbol + 'a string'
```
I've fixed the broken forms and added a spec to confirm that the forms for all attributes successfully display to plug hole in the spec coverage.
These forms were previously working. Am puzzled why its breaking now, so maybe related to a Rails or Ruby upgrade? Sometimes the field names are strings and sometimes symbols.
I've kept this to the smallest change rather than refactoring the forms further as I'm wary about breaking field naming conventions.

Fix meter attributes forms

---

app/controllers/schools_controller.rb
app/views/schools/_school_group.html.erb
app/views/schools/index.html.erb
spec/controllers/schools_controller_spec.rb

We're going to be rebuilding this page, but noticed that this page is still slow on live site which I think is due to the SQL queries. 
Looks like we're loading full school models even though we only need names and links.
So have tweaked the controller and templates to just pull in what is required for now

Optimise SQL on schools page

---

app/views/shared/meter_attributes/_time_of_day.html.erb
app/views/shared/meter_attributes/_time_of_day_30.html.erb
app/views/shared/meter_attributes/_time_of_year.html.erb
spec/system/admin/meter_attributes_spec.rb

We had an issue with the meter attributes forms which I thought I had fixed here: https://github.com/Energy-Sparks/energy-sparks/pull/3951
The forms were building fields using a SimpleForm helper. Previously that was all working OK even when the `form.input` helpers was being passed `:charge_start_time + '[hour]'` as a value. It was then correctly creating a nested field, e.g. `attribute[root][charge_start_time][hour]`.
Changing the symbol to a string fixed the concatenation error. But the naming was then broken: `attribute[root][charge_start_time[hour]]`. This has stopped the values being saved and edited correctly.
Am not clear what caused the error to start happening as creating and editing these attributes was previously working.
We've recently upgraded SimpleForm so maybe some …

Fix form field creation on Meter Attributes forms

---

app/services/schools/advice_page_benchmarks/school_benchmark_generator.rb
spec/services/schools/advice_page_benchmarks/school_benchmark_generator_spec.rb

We generate and `AdvicePageBenchmark` records for each school to note whether they are an examplar or well managed school. These are updated nightly, with records being removed if we can't generate a benchmark. E.g. because of a bug or if an admin has had to truncate the data
But we don't remove the benchmarks if all the meters for a fuel type are deactivated. This creates a bug in the refactored `ComparisonOverviewComponent` as it is checking for existence of these records before deciding whether to show a comparison.
This PR fixes these problems by:
- ensuring stale `AdvicePageBenchmark` records are removed
- the `ComparisonOverviewComponent` first checks the fuel type before proceeding to check for the benchmarks

Remove advice page benchmarks when meters are deactivated

---

app/assets/javascripts/analysis.js
app/assets/javascripts/common_chart_options.js.erb
app/assets/stylesheets/analysis.scss
app/assets/stylesheets/pupils.scss
app/components/equivalence_component/equivalence_component.scss
app/controllers/pupils/public_displays_controller.rb
app/views/pupils/public_displays/charts.html.erb
app/views/pupils/public_displays/equivalences.html.erb
config/locales/views/pupils/public_displays.yml
spec/system/pupils/public_displays_spec.rb

- Bar chart height was too large, due to default set in CSS. Revise JS to add classes, adjust CSS to fix height on public displays only
- Switch to `container` rather than `container-fluid` to centre page content and aim for fixed aspect ratio
- Switch to vertical layout for equivalence and increase image size
- Add Energy Sparks logo
- Redirect from weekly chart is data is >30 days out of date to avoid showing stale comparisons
- Tweak wording

Improve public display layout

---

app/components/dashboard_learn_more_component.rb
app/components/energy_summary_table_component/energy_summary_table_component.html.erb
app/components/energy_summary_table_component/energy_summary_table_component.scss
config/locales/views/components/learn_more.yml
spec/components/dashboard_learn_more_component_spec.rb
spec/components/energy_summary_table_component_spec.rb

Updates the adult dashboard with some changes to make our use of solar data at the school more obvious:
- revise table text to "Electricity and Solar PV"
- add solar icon to table
- change learn more component title to refer to "energy use and generation"

Make use of solar data more obvious

---

app/models/amr_data_feed_config.rb
app/services/amr/single_read_converter.rb
db/migrate/20241010131742_add_half_hourly_labelling_to_data_feed_config.rb
db/schema.rb
lib/tasks/deployment/20241011123520_add_half_hourly_labelling_to_edf.rake
spec/factories/amr_data_feed_config_factory.rb
spec/models/amr_data_feed_config_spec.rb
spec/services/amr/csv_parser_and_upserter_spec.rb
spec/services/amr/single_read_converter_spec.rb
spec/system/admin/amr_uploaded_readings_spec.rb

Half-hourly data  can be labelled either at the start or the end of the half-hourly period. E.g. the usage between 1.30am and 2.00am might be labelled as "01:30" or "02:00".
For CSV/Spreadsheet formats where there is a single row per day there is generally no ambiguity as we parse the 48 HH columns in the order presented.
But for `row_per_reading` formats there's some ambiguity. Without more context a column labelled as "8 Oct 2024 00:00" may refer to the usage from 23:30 to midnight on 7th October, or the usage from midnight to 00:30am on the 8th October.
When processing timestamps, our `SingleReadConverter` has been written with the assumption that fields are labelled at the end of the half hour and that "8 Oct 2024 00:00" refers to the final half-hourly period of the 7th October. Data …

Fix parsing of row_per_reading format with malformed dates

---

app/views/robots_txts/allow.raw

Plus a couple of gaps in the robots.txt. In particular disallows crawling of the comparison page results which can be slow.
These were previously all blocked, but the rework of the urls meant that this is currently permitted.

Add additional crawler exclusions

---

app/services/amr/upsert_validated_readings_for_a_meter.rb
spec/services/amr/upsert_validated_readings_for_a_meter_spec.rb

Rails 7 supportings additional options for upsert. This includes not adding a `RETURNING` clause to the query.
Have updated our custom query code to remove the clause as we don't do anything with the returned ids. 
This should avoid Rails loading all of the ids of the inserted or updated records. 
For majority of schools this is a small array, e.g. a few hundred integers, but for the largest schools it might be thousands of identifiers (one Bath school has 32960 validated readings).

Simplify validated reading upsert

---

app/jobs/manual_data_load_run_job.rb
app/models/amr_data_feed_config.rb
app/services/amr/csv_parser_and_upserter.rb
app/services/amr/data_feed_upserter.rb
app/services/amr/n3rgy_readings_upserter.rb
app/services/amr/process_amr_reading_data.rb
app/services/amr/single_read_converter.rb
app/services/solar/low_carbon_hub_upserter.rb
app/services/solar/rtone_variant_upserter.rb
app/services/solar/solar_edge_upserter.rb
app/views/admin/amr_data_feed_configs/edit.html.erb
app/views/admin/amr_uploaded_readings/new.html.erb
db/migrate/20241015163950_add_allow_merging_to_data_feed_config.rb
db/schema.rb
lib/tasks/deployment/20241016103355_allow_merging_in_edf_config.rake
spec/services/amr/data_feed_upserter_spec.rb
spec/services/amr/process_amr_reading_data_spec.rb
spec/services/amr/single_read_converter_spec.rb

A couple of "row per reading" formats that we are receiving contain data for partial days. For example we receive:
- 47 readings for one day
- 1 reading for the next
The next update does not contain a full reading for either day. We just get a cycle of partial readings. 
Our loader currently expects that a data file will contain all available data for a meter, rather than a rolling set of readings. This means we currently end up rejecting the days with very limited readings whilst loading the days that have partial readings that never get filled in.
This PR provides support for merging readings during our normal upsert. The behaviour is configured on individual feed formats and is currently only fully tested with "row per reading" files.
The new behaviour has been implemented by:
- …

Support merging of readings in data loader

---

.overcommit.yml
app/services/amr/data_file_parser.rb
spec/fixtures/amr_upload_data_files/energy_assets_invalid.csv
spec/services/amr/data_file_parser_spec.rb

Every so often the energy-assets2 config receives a CSV file which is actually an HTML page containing an error message warning about maintenance.
This causes errors in Rollbar and I have to remove the file. This PR adds a special case in the parser for this error so its treated as an empty file and ignored.

Ignore energy-assets2 recurring error

---

app/views/admin/schools/meter_reviews/new.html.erb
app/views/bill_request_mailer/notify_admin.html.erb
spec/system/admin/meter_reviews/meter_reviews_spec.rb
spec/system/schools/consent_documents_spec.rb

Admins needs to do a "meter review" to ensure we have up to date consent to access data and a recent energy bill. If consent is not up to date then the review can't be completed.
From the list of pending reviews we provide buttons that allow an admins to request consent or a bill if needed. But on the meter review form we don't provide those links. So an admin visiting from a notification email or via the meters page can't easily complete the next step.
PR adds additional buttons to the form and a note in the email received when a school uploads a bill.

Improve admin workflow when school has outdated consent

---

app/services/amr/data_feed_validator.rb
spec/services/amr/data_feed_validator_spec.rb

Surprised this hasn't happened already, but add spec and fix for when a CSV file is completely empty.

Handle completely empty files

---

.ebextensions/cronjob.config
app/jobs/amr_import_job.rb

The timings for when we receive data has changed over the last few years. Mostly due to changes in which portals and data providers are supplying us and when they send out their automated emails.
We now receive a small number of files between 2-5am but the bulk of the data is received from around 6am onwards, with some not arriving until around midday.
This PR:
- adds a second daily run of the AMR import at 22:15pm. This will end up processing the bulk of the data that arrives during the day, with the existing 5.15am run remaining to catch any files from the early hours.
- moves the population of the regeneration queue to 5.40am, so that it should complete earlier
- updates the amr import job to use the regeneration queue, so that any remaining files in the queue from the morning run, …

Update cron timings and queue for amr loads and regeneration

---

app/assets/stylesheets/colours.scss.erb
app/assets/stylesheets/school.scss

This is working as expected locally but not in production, so a bit odd. In production, `$fuel-name` was remaining as `electricity` with each loop iteration, where as locally it is the different fuel name (apart from electric, which is getting changed to electricity, as expected)
Also realised that site fuel colours were being used rather than the old chart ones for this, so have changed that too.

Fix chart usage controls

---

app/assets/stylesheets/bootstrap-overrides.scss
app/assets/stylesheets/links.scss
app/assets/stylesheets/nav.scss
app/assets/stylesheets/redesign/footer.scss
app/views/home/_mailchimp.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_head.html.erb
app/views/shared/navigation/top_nav/_about_menu.html.erb
app/views/shared/navigation/top_nav/_our_services_menu.html.erb
config/initializers/colours.rb
config/locales/views/home/home.yml
config/locales/views/shared/shared.yml
spec/spec_helper.rb
spec/system/admin/case_studies_spec.rb
spec/system/footer_spec.rb
spec/system/navigation/top_nav_spec.rb

The top image is the implemented version, the bottom is the actual design:
Differences I see as follows, aside from some text looking slightly bolder than the design and padding variations (looked better when it came to implementation):
'Contact us' is called 'Contact' (as per current top nav)
'Careers' is called 'Jobs' (as per current top nav)
'Workshops' is called 'Educational workshops' (as per current top nav)
'Privacy & Cookies Policy' is split into two separate links (as per current top nav)
Do we want to change these links to the design, and if so, do we want to change those in the top nav too?
Have added social media links based off what I think we have.
Perhaps this can go on test for an easier look when we're ready

Implement new footer design

---

app/models/advice_page_school_benchmark.rb
app/models/alert.rb
app/models/alert_subscription_event.rb
app/models/alert_type.rb
app/models/alert_type_rating_content_version.rb
app/models/alert_type_rating_unsubscription.rb
app/models/amr_data_feed_config.rb
app/models/amr_reading_warning.rb
app/models/calendar.rb
app/models/calendar_event_type.rb
app/models/dashboard_alert.rb
app/models/energy_tariff.rb
app/models/equivalence_type.rb
app/models/issue.rb
app/models/manual_data_load_run.rb
app/models/meter.rb
app/models/rtone_variant_installation.rb
app/models/school_batch_run.rb
app/models/school_group.rb
app/models/school_onboarding.rb
app/models/school_time.rb
app/models/staff_role.rb
app/models/team_member.rb
app/models/transifex_load.rb
app/models/transport_survey/response.rb
app/models/transport_survey/transport_type.rb
app/models/user.rb

ActiveSupport::DeprecationException: DEPRECATION WARNING: Defining enums with keyword arguments is deprecated and will be removed (ActiveSupport::DeprecationException)

run rubocop to change deprecated enum arrays to hashes

---

app/assets/stylesheets/base.scss
app/helpers/application_helper.rb
app/views/schools/meters/_active_meters.html.erb
app/views/schools/meters/_inactive_meters.html.erb
app/views/schools/meters/index.html.erb
config/locales/views/schools/schools.yml

Reworks the meter index page to:
- add break points to large titles
- combine some columns
- use icons in the admin view to save space

Fix button spacing and layout of meter index page

---

app/models/alert_type.rb
app/models/concerns/enum_fuel_type.rb
app/models/concerns/enum_reporting_period.rb
app/models/data_source.rb
app/models/help_page.rb
app/models/observation.rb
app/models/programme.rb
app/models/school_onboarding_event.rb
app/models/school_target_event.rb

ActiveSupport::DeprecationException:
DEPRECATION WARNING: Defining enums with keyword arguments is deprecated and will be removed
in Rails 8.0. Positional arguments should be used instead:

more enum future deprecation warnings

---

lib/tasks/deployment/20241030094408_crown_row_per_reading.rake

Adds a new row per reading format for some manually uploaded files.
Very similar to EDF format but uses serial number lookup and a different date format. As files contain partial days I've activated the new merging feature so we accumulate readings if we get updates.

Add Crown row per reading format

---

.ebextensions/cronjob.config
app/services/alerts/content_deletion_service.rb
app/services/alerts/delete_alert_generation_run_service.rb
app/services/alerts/delete_content_generation_run_service.rb
spec/services/alerts/content_deletion_service_spec.rb
spec/services/alerts/delete_alert_generation_run_service_spec.rb
spec/services/alerts/delete_content_generation_run_service_spec.rb

The daily regenerations produce a number of database artefacts, the largest being the alert records.
We currently run a job once a month to delete anything older than the start of the previous month. Which means today we have nearly 2 months of older data.
As the database is growing, we need to reduce threshold of what we're storing. In general for support purposes we rarely need more than a few days to a week.
Initially this PR changes the deletion threshold to 14 days and updates the cronjob to run weekly in the early hours of sunday morning.

Change content deletion threshold to 14 days

---

Gemfile
Gemfile.lock

* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/731
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/734
* https://github.com/Energy-Sparks/energy-sparks_analytics/pull/735
The last two PRs are the key changes here. Should reduce the amount of data generated by some alerts due to errors being captured and assigned to variables

Update analytics to 6.0.17

---

app/services/confirmation_reminder.rb
spec/factories/schools_factory.rb
spec/factories/users_factory.rb
spec/services/confirmation_reminder_spec.rb

Updated the confirmation reminder service so that it:
Specs have been reworked to exercise logic for all roles.

Fix confirmation email sending service to not contact some users

---

lib/tasks/deployment/20241105153838_update_crown_config_half_hourly_flag.rake

Changes the crown per row configuration to indicate that half-hourly labels are at the end of the half hour not the start.

Change Crown configuration

---

.github/workflows/knapsack.yml
.github/workflows/rubyonrails.yml

- from https://turso.tech/blog/simple-trick-to-save-environment-and-money-when-using-github-actions
also
- also updates to use upload-artifact@v4
- stop running job on master push as have linear knapsack timings job doing similar thing

cancel in progress github action when a new one appears

---

app/controllers/admin/reports/missing_alert_contacts_controller.rb
app/models/school.rb
app/views/admin/reports/index.html.erb
app/views/admin/reports/missing_alert_contacts/index.html.erb
config/routes.rb
spec/system/admin/reports/missing_alert_contacts_spec.rb

Adds an admin report that lists all schools that don't have anyone receiving weekly alerts.
Table includes enough context to allow admins to filter schools and decide next steps.

Add report of schools with no alert contacts

---

app/controllers/schools/meters_controller.rb
app/models/amr_validated_reading.rb
spec/support/data_helpers.rb
spec/system/schools/downloads_spec.rb

A user was confused by the individual meter download format:
- the MPXN is in the CSV file name but this gets truncated when imported into Excel which has a limit on size of tab names
- the CSV file itself doesn't contain the MPXN
The user was therefore unsure whether we had given them the right data.
Adjust the downloads to shorten the file name and add the mpxn and meter type into the CSV.

Adjust meter data download format

---

lib/generators/amr_data_feed_config/USAGE
lib/generators/amr_data_feed_config/amr_data_feed_config_generator.rb
lib/generators/amr_data_feed_config/templates/deploy.txt.erb
lib/tasks/deployment/20241113144957_stark_portal_gas.rake

Adds new data feed config for Stark Portal gas data.
I've also added a rails generator to try and make it easier to add these in future. I often just copy from an existing deploy task.
Generators provides a default config for a row per day format with notes about configuring other variants. Future improvements could be to add more options but this is a quick improvement.

Add stark portal gas config

---

app/models/weather_observation.rb
lib/tasks/data_feeds/meteostat_reload_zero_reading_days.rake

We've had a period where we seem to have incorrect readings from Meteostat. Reloading data for the period correctly imports updated data. It's affecting 7 weather stations on east of england.
I've added this Rake task to allow days to be selectively reimported if there are any zeroes. I've not done this as an after party task as I prefer to avoid running tasks that depend on external APIs during a release. So I will run the update manually after the next release.

Add rake task to reload zero reading periods from Meteostat

---

app/components/dashboard_equivalences_component.rb
app/components/dashboard_learn_more_component.rb
spec/components/dashboard_equivalences_component_spec.rb

Makes the dashboard equivalences component work similar to the components on the adult dashboards.
Normally we allow admins to see the data enabled view even if the flag has not yet been set so they can preview the school's data before making the data live.

Allow admins to see equivalences before school is data enabled

---

config/locales/cy/views/advice_pages/electricity_long_term.yml

Fixes a welsh translation which is failing because of missing interpolation argument. Think this was caused by some rework.
This is a temporary fix. Text will ready "monthly usage" rather than "monthly electricity usage" until we get updated translations after next Transifex sync

Removing interpolation argument from Welsh key

---

app/models/comparison/report.rb
spec/models/comparison/report_spec.rb

- destroy was too slow locally, delete_all seems ok
- assuming it's ok for the weekly vacuum to deal with the fallout if it isn't otherwise triggered

delete related alerts with a comparsion report

---

app/controllers/schools/batch_runs_controller.rb
app/views/schools/batch_runs/index.html.erb
app/views/shared/_school_status_buttons.html.erb
spec/system/school_batch_run_spec.rb
spec/system/schools/dashboard/manage_school_spec.rb

Not sure how there wasn't a check for this already. But its currently possible for an admin to run a regenerate even if a school doesn't have the process_data flag set. This by-passes the data validation checks in toggling that attribute and produces alerts with invalid data.
Changes:
- remove navbar link to regenerate if school is not set to process data
- change batch runs page to remove button and add warning message if process data is not set
- add a final check in the controller

Only allow regeneration if process_data is on

---

app/components/school_search_component.rb
app/components/school_search_component/school_search_component.html.erb
app/views/schools/index.html.erb
config/locales/views/components/school_search.yml
spec/system/schools_spec.rb

Revises the in-page label used for by the school search component so that its clearer than the total for admins is different.

Update school label for admins

---

lib/data_feeds/pv_live_api.rb

Sheffield PV Live endpoint has changed. Old version still available until February but applying change now.
Have confirmed loading still works correctly.

Change base uri

---

app/controllers/admin/reports/amr_validated_readings_controller.rb
app/views/admin/reports/amr_validated_readings/show.html.erb

The meter report colour codes the statuses applied to each days reading by the analytics.
But there are way more status codes that colours defined. At the moment if there's no mapping then we day is not colour coded, making it look like data is missing.
Provide a fallback colour so day with some substitution are always coloured.
A longer term improvement would be to map all the status codes into categories and use those to define colours.

Provide fallback colour for meter report

---

app/models/user.rb
spec/models/user_spec.rb

Observations are created by / updated by Users. Declare the association so we can still delete users.

Allow deleting of users with Observation

---

app/controllers/admin/reports/meter_loading_reports_controller.rb
app/helpers/s3_helper.rb
app/models/amr_data_feed_reading.rb
app/views/admin/reports/index.html.erb
app/views/admin/reports/meter_loading_reports/index.html.erb
config/routes.rb
spec/models/amr_data_feed_reading_spec.rb
spec/system/admin/reports/meter_loading_report_spec.rb

Adds a new admin report to summarise the loading activity for a specific meter.
Debugging loading issues for individual meters is tricky as you need to look across the original CSV files, the unvalidated readings and the loading logs in the database. Naming conventions for CSV files from suppliers are not obvious so can take a while to find out which files contain which data for which meters and when those were processed.
This report allows an admin to search for an MPXN and then we summarise the recently loaded data. The report includes what reading dates were loaded, from which files and the original sources. I've used a customised query to optimise things a little. And incorporated pagy to allow looking back over historical data.
For data provided via CSV there's a link to download the …

Add Meter Loading Report

---

app/services/mailchimp_tags.rb
app/services/marketing/mailchimp_csv_exporter.rb
lib/tasks/marketing/mailchimp_csv_export.rake
spec/factories/school_groups_factory.rb
spec/factories/schools_factory.rb
spec/factories/users_factory.rb
spec/services/marketing/mailchimp_csv_exporter_spec.rb

Adds a new Rake task and service to support repopulating Mailchimp audience with a better structured schema.
Rake task accepts an unzipped audience export and produces new CSV files for manual upload, one for each [Mailchimp Contact Type](https://mailchimp.com/help/about-your-contacts/) plus an additional list of users who are not currently signed up for the Newsletter.
This is first step in improving our use and integration with Mailchimp.

Tidy and repopulate mailchimp audience

---

app/views/schools/advice/electricity_costs/_analysis.html.erb
app/views/schools/advice/electricity_costs/_cost_comparison.html.erb
app/views/schools/advice/gas_costs/_analysis.html.erb
app/views/schools/advice/gas_costs/_cost_comparison.html.erb

Testing #4123 I noticed a long standing issue with the gas costs chart.
The issue only affects schools with a single gas meter and only on the 2 year comparison chart.
The cost pages use charts named with an `electricity_` prefix. The default definition of that is to show the electricity costs. However the charts override that by specifying a meter (either a real gas/electricity meter or the aggregate one), which means the charts then shows the costs for that meter.
When a school has a single meter, the 2 year comparison chart was not specifying a meter, so it was defaulting to the electricity costs.
I've fixed this by updating the partials to build a chart_config for the aggregate (gas or electricity) meter so the right values are used.
The naming is a hold-over from previous versions of …

Fix gas cost chart when there is a single meter

---

app/services/solar/low_carbon_hub_upserter.rb
app/services/solar/solar_edge_upserter.rb
spec/services/solar/low_carbon_hub_upserter_spec.rb
spec/services/solar/solar_edge_upserter_spec.rb

We automatically create meters when importing from solar monitoring systems.
This is fine during initial setup but recently we've had some SolarEdge monitoring systems return additional data for export and electricity meters, up to 6 months after we started fetching data. Unclear if this was an API change or due to installation of new metering. 
When these meters are created it can impact how we aggregate data for the school, so its not safe to make them active by default.
PR ensures that meters are inactive by default.

Ensure automatically created solar meters are inactive on creation

---

app/helpers/meters_helper.rb
app/views/schools/meters/_form.html.erb
config/locales/views/schools/schools.yml
spec/system/meter_management_spec.rb

The DCC meter status was recently changed from a boolean to an enum.
However the meter creation and editing form was still setup as a checkbox. This meant that the status wasn't showing or updating correctly. The status was being reset to "no" after an update. I think this might also have been triggering unnecessary re-checks of the status. 
I've updated the form and the spec to ensure the values are available.

Fix DCC Meter option on form

---

app/components/scoreboard_activity_component.rb
app/components/scoreboard_activity_component/scoreboard_activity_component.html.erb

The scoreboard activity component was relying on the Podium for the current school to work out the position of other schools.
But the Podium is only constructed with up to three schools, so unless the other school was in the top position it wasn't included.
This changes fixes that bug by switching to use the scored schools for the podium instead. The list is cached to avoid refetching from the database when rendering the dashboard.

Fix missing places on dashboard

---

app/models/user.rb
spec/models/user_spec.rb

This PR addresses two Trello tickets and also fixes another couple of relationships too. Tickets are as follows:
https://trello.com/c/0snT5p5E/4722-get-an-error-500-message-when-trying-to-delete-user-rhearnphillipslittleheathorguk-from-little-heath-school
```
ActiveRecord::InvalidForeignKey PG::ForeignKeyViolation: ERROR:  update or delete on table "users" violates foreign key constraint "fk_rails_60602a07b3" on table "energy_tariffs"
DETAIL:  Key (id)=(5619) is still referenced from table "energy_tariffs".
```
https://trello.com/c/74BsFqtW/4729-error-message-received-when-deleting-a-user
```
ActiveRecord::InvalidForeignKey PG::ForeignKeyViolation: ERROR:  update or delete on table "users" violates foreign key constraint "fk_rails_40250ac6eb" on table "activities"
DETAIL:  Key (id)=(5213) …
```

Fix user destroy issues

---

app/components/dashboard_reminders_component.rb
app/controllers/programme_types_controller.rb
app/views/schools/recommendations/index.html.erb
app/views/shared/_task_completed.html.erb
spec/system/programme_type_spec.rb

I noticed that it is possible to see inactive programme types via the complete programme prompt and also the dashboard reminders prompt. Which led me to see that you could also view programme type pages for those that are inactive. This fixes all issues.

Make sure only active programme types can be viewed

---

app/controllers/admin/school_groups/users_controller.rb

Adds extra fields to the school group user download so its similar to the main report.
Includes school type, whether they are active, funder, etc.

Add fields to school group user export

---

app/components/adult_reminders_component/adult_reminders_component.html.erb

Missed updating the audit prompt in the adult reminders component. This adds it in

Add in missed audit prompt update

---

app/assets/stylesheets/base.scss
app/helpers/application_helper.rb
app/views/admin/school_groups/_active_schools.html.erb
app/views/admin/school_groups/index.html.erb

Was using the interface and felt like I should be able to edit a dashboard message by clicking on the info icon. Could be wrong though! This meant the info icon is added in a greyed out form for when a message is not set.
Admin school group / view page
Admin school group / index page

Link to edit dashboard message from icon

---

app/models/intervention_type.rb
app/models/todo.rb
app/services/observation_removal.rb
lib/tasks/todos/import.rake
spec/support/shared_examples/todos.rb

Spotted a couple of things that needed changing after a good poke around. 
Firstly when observations are 'removed' via the frontend (via the ObservationRemoval service), if not in current academic year, visible is set to false, rather than it being removed. If they are in this academic year, they are destroyed, which automatically removes completed todos etc, which is how I assumed it worked all the time. So now this takes note of the visible flag in a number of places and removes completed todos when visible is set to false.
Also made sure that when picking the latest recording for a todo, there is a possibility that more than 1 recording occurs on the same day. Added code to make sure we always pick the last one created. It probably would have done this anyway, just wanted to be …

Todos sure up

---

app/views/shared/todos/_fields.html.erb
app/views/shared/todos/_task_type_form.html.erb
spec/system/admin/programme_type_spec.rb

Noticed that Nicky had added notes against programme activities and actions [on test](https://test.energysparks.uk/admin/programme_types/17/todos/edit)
It made me realise that notes against todos shouldn't be available to edit for programmes, as they are only intended to be used in audits as they are not translated. Assume this has been traditionally ok for them not to be translated for audits because the audit is all done in English too and not translated either.
https://trello.com/c/Pfi1FogC/3763-revise-programmes-to-include-adult-actions-and-not-just-pupil-activities
If we do want to add a shorter note, perhaps these should be added to activity type or intervention type models and not in the todo model. They would need to be translated too.

Hide notes field from programme admin interface

---

app/components/dashboard_header_component/dashboard_header_component.html.erb
app/components/dashboard_header_component/dashboard_header_component.scss
app/components/dashboard_learn_more_component/dashboard_learn_more_component.scss

Thought I would fix this while working on other similar stuff.
It was like this:
It is now like this:
Also reduced the padding on the header of the learn more component, as that was a bit bothersome too.

Fix alignment of school block in dashboard component

---

app/models/energy_tariff.rb
app/views/admin/reports/energy_tariffs/index.html.erb
spec/models/energy_tariff_spec.rb

Revise the admin tariff report to:
- only list groups with visible schools
- only include tariffs from active schools

Ensure tariff report ignores inactive schools

---

app/jobs/mailchimp/audience_updater_job.rb
app/jobs/mailchimp/base_job.rb
app/jobs/mailchimp/email_updater_job.rb
app/jobs/mailchimp/status_checker_job.rb
app/jobs/mailchimp/user_deletion_job.rb
lib/tasks/mailchimp/status_check.rake
spec/jobs/mailchimp/status_checker_job_spec.rb
spec/jobs/mailchimp/user_deletion_job_spec.rb
spec/models/user_spec.rb

Realised that there is a loophole in how I've avoided the Mailchimp updates running on the test server.
At the moment everything is restricted so that only users with a `mailchimp_status` will have updates pushed to Mailchimp. While the rake task for the main synchronisation code (`mailchimp:audience_updater`) won't run on the test server, the email update and deletion jobs will still be triggered if someone is testing other updates on the server. We obviously don't want that to happen, although the changes will be later reversed once the next update is pushed from production.
This PR reworks the code to more strongly enforce that certain jobs shouldn't run except in the production environment:
- new base class for the mailchimp jobs with a `can_run?` method that performs the environment …

Stronger environment checking in Mailchimp jobs

---

app/assets/stylesheets/base.scss
app/assets/stylesheets/home.scss
app/components/equivalence_carousel_component/equivalence_carousel_component.scss

Also have put some padding in the equivalence-carousel-component, as the text was touching the sides:
Before padding:
After padding:

Fix Carousel Indicators

---

Gemfile
Gemfile.lock
app/views/admin/index.html.erb
config/routes.rb
spec/factories/meters_factory.rb

Can now be found at `/admin/components` and also in the admin index
Turns out I'd put the gem in the in the `group :development, :test` rather than just the `group :development` as recommended. It's now in the `group :development, :production` so we can use it on the live boxes.
I've also changed the name of the transient variable `log` in the meters factory (and tested it locally), in case we do want to switch this on in test for whatever reason (docs don't mention doing this though).

Try lookbook

---

app/controllers/users/contacts_controller.rb
app/controllers/users_controller.rb
app/models/ability.rb
app/models/user.rb
app/views/shared/navigation/_second_nav.html.erb
app/views/users/_my_schools_summary.html.erb
app/views/users/_profile_footer.html.erb
app/views/users/_profile_summary.html.erb
app/views/users/_user_page.html.erb
app/views/users/contacts/index.html.erb
app/views/users/edit.html.erb
app/views/users/edit_password.html.erb
app/views/users/show.html.erb
config/locales/common.yml
config/locales/views/shared/shared.yml
config/locales/views/users/users.yml
config/routes.rb
lib/tasks/deployment/20250213151427_profiles_feature.rake
spec/factories/users_factory.rb
spec/support/shared_examples/account_pages.rb
spec/support/shared_examples/page_auth.rb
spec/system/navigation/second_nav_spec.rb
spec/system/user_profiles_spec.rb
spec/system/users/accounts_spec.rb
spec/system/users/alert_management_spec.rb

This PR adds a new `/profiles` route to allow users to manage their own accounts and preferences.
I've got some additional improvement to make (e.g. managing Mailchimp preferences, some admin options) but this feature covers the basics, so want to get this reviewed first.
There's a feature flag which toggles adding a user icon to the second nav which links to the pages.
Included some redacted screenshots below.

New user profile pages

---

app/models/mailchimp/contact.rb
app/models/user.rb
lib/tasks/deployment/20250217164840_disable_archived_users.rake
spec/models/mailchimp/contact_spec.rb
spec/models/user_spec.rb

Update status for locked accounts associated with removed/archived schools to set them as inactive. This is now the correct status when removing users like this.
Also updates the Mailchimp code to use the active attribute rather than the access locked status.

Update status for locked users

---

app/models/mailchimp/contact.rb
spec/models/mailchimp/contact_spec.rb
spec/system/users/email_management_spec.rb

Implements the rules that provide suggested default emails for different types of school, school group and other users.

Revise default interests for Mailchimp forms

---

app/views/schools/users/_form.html.erb
app/views/users/edit.html.erb

The forms to create users have a blank option in the Staff Role field. But a staff role must be set.
Adjust the form so there's an empty prompt instead so that there's no blank option.

Remove blank option from staff role

---

app/models/mailchimp/contact.rb
app/services/mailchimp/csv_exporter.rb
lib/tasks/mailchimp/csv_export.rake
spec/models/mailchimp/contact_spec.rb
spec/services/mailchimp/csv_exporter_spec.rb
spec/system/users/email_management_spec.rb

Revises the code that creates improved CSV files for importing into Mailchimp, so that it correctly adds in default interests. We will use this when doing the initial imports. The behaviour is optional so we can still run this code after the initial user import and ensure that we preserve interests.
The PR also removes some old code that was mapping between old Mailchimp fields and the new schema. The old fields have been removed from Mailchimp so we no longer need the code and specs.

Revise mailchimp export code to apply new defaults

---

app/components/scoreboard_summary_component.rb
app/models/observation.rb
spec/components/scoreboard_summary_component_spec.rb

Change ScoreboardSummaryComponent so that it:
- only shows point scoring activity from other schools (this excluding, e.g. having an audit or taking temperatures)
- uses `.sample` rather than `.limit` so that we add some randomness to what's displayed, otherwise we always show same recent activity

Only show scoreboard activity that has points

---

app/services/mailchimp/csv_exporter.rb
spec/services/mailchimp/csv_exporter_spec.rb

Fixes an issue with creating the list of emails associated with each contact in the CSV export.
Internally we manage the list of interests as a hash of name/id to true/false for each preference. But this has to be turned into a comma-separated list for the CSV export.
The interests for "organic" contacts was not being converted to a string. Bug crept through because Hash responds to `include`. So have added a check for the type of object as well as its contents.

Fix organic contact interests

---

Gemfile
Gemfile.lock

Updates analytics to include this bug fix: https://github.com/Energy-Sparks/energy-sparks_analytics/pull/759

Analytics 6.1.6

---

app/models/solis_cloud_installation.rb
spec/models/solis_cloud_installation_spec.rb
spec/services/solar/solis_cloud_download_and_upsert_spec.rb

`.latest_electricity_reading` returns a string but code in the base class and the upserter was expecting a date. Added a `Date.parse` call and a spec.

Fix date error when loading SolisCloud data

---

lib/tasks/deployment/20250317165722_change_volunteers_to_staff.rake

There is a `volunteer` role which isn't being used any more. Someone being a volunteer is captured in their staff role.
This updates the 2-3 users with the volunteer role to be staff, ahead of removing the role.

Change volunteers to staff

---

app/models/ability.rb
app/models/user.rb
app/services/confirmation_reminder.rb
app/views/onboarding/users/_form.html.erb
config/locales/cy/models/lists.yml
config/locales/models/lists.yml
spec/factories/users_factory.rb
spec/models/abilities_spec.rb
spec/models/mailchimp/contact_spec.rb
spec/services/confirmation_reminder_spec.rb
spec/services/mailchimp/csv_exporter_spec.rb
spec/system/admin/emails_spec.rb
spec/system/admin/settings/energy_tariffs_spec.rb
spec/system/school_groups/energy_tariffs_spec.rb
spec/system/schools/energy_tariffs_spec.rb

Removes the volunteer role as its no longer needed. Volunteers are flagged as staff users with a staff role of "Parent or Volunteer".
This simplifies some of the code and CanCanCan abilities.

Remove volunteer role

---

app/controllers/schools/cluster_admins_controller.rb
lib/tasks/deployment/20250324110936_fix_roles_for_cluster_admins.rake
spec/system/schools/users_spec.rb

When we add an existing user as a school admin, we're not currently setting the role correctly. The school is just added to the users list of schools, but their role is not updated.
Fix the issue in the controller and add a database fix to correct around 20 records.

Set role when adding existing user as school admin

---

app/assets/stylesheets/base.scss
app/components/elements/image_component.rb
app/components/layout/cards/testimonial_component.rb
app/components/layout/cards/testimonial_component/testimonial_component.html.erb
app/components/layout/carousel_component.rb
app/components/layout/grid_component.rb
app/controllers/admin/testimonials_controller.rb
app/models/testimonial.rb
app/views/admin/index.html.erb
app/views/admin/testimonials/_form.html.erb
app/views/admin/testimonials/edit.html.erb
app/views/admin/testimonials/index.html.erb
app/views/admin/testimonials/new.html.erb
app/views/home/index.html.erb
config/locales/views/components/testimonial.yml
config/locales/views/home/home.yml
config/routes.rb
db/migrate/20250324154639_create_testimonials.rb
db/schema.rb
lib/tasks/deployment/20250326161028_add_testimonial.rake
spec/components/layout/cards/testimonial_component_spec.rb
spec/components/layout/grid_component_spec.rb
spec/components/previews/layout/cards/testimonial_component_preview.rb
spec/factories/testimonials.rb
spec/models/testimonial_spec.rb
spec/system/admin/testimonials_spec.rb

* Adds testimonial model - it has an enum called category, so we can filter them for different pages. Not sure if testimonials need to be in multiple categories though, in which case we'll need to add a new category model  / relationship / more admin.
* Adds admin GUI & links to from admin dashboard
* Uses the new model on the front page
* Rearranges the testimonial component to better match the model

Add testimonials model & admin pages

---

app/components/page_nav_component/page_nav_component.html.erb
spec/components/page_nav_component_spec.rb

Add in a missing class required to properly style the page navigation component. Currently all the colour and hover stylings aren't working.
Looks like it might have gotten lost during some component refactoring. ApplicationComponent subclasses now add a HTML class based on the class name automatically, but PageNav doesn't extend that.
Haven't reworked the component for now but may look at as part of changes for the support pages.

Fix styling of advice page nav

---

app/models/activity_type.rb
app/models/cms/base.rb
app/models/intervention_type.rb
app/models/programme_type.rb
app/models/testimonial.rb
app/services/transifex/loader.rb
spec/models/concerns/transifex_serialisable_spec.rb
spec/services/transifex/loader_spec.rb

Include the `TransifexSynchronisable` in the `Cms::Base` class and implement `tx_resources` to only synch published content.
Noticed that the `Scoreboard` and `Testimonial` classes were not in the loader so have added those.

Add Transifex Synching for CMS module

---

lib/tasks/deployment/20250416121707_remove_edf_dashboard_messages.rake

Now data feed has been fixed, remove the dashboard messages for affected schools.
Basically reverts: https://github.com/Energy-Sparks/energy-sparks/pull/4385

Remove EDF dashboard messages

---

lib/data_feeds/pv_live_service.rb
lib/tasks/deployment/20250425105312_remove_region151_data.rake

PV Live API is returning zero readings and zero installed capacity for GSP id 151 (IMPK_1)
https://api.pvlive.uk/pvlive/api/v4/gsp/151?start=2025-04-24&extra_fields=installedcapacity_mwp
Causing our loader to insert readings with `NaN` values rather than rejecting the whole day. Add a fix and a logging message.
Waiting to here from Sheffield whether this is to be expected. There was previously capacity at that identifier. Also unclear if we should get some readings for any area.

Handle zero installed capacity

---

lib/tasks/deployment/20250425105643_remove_old_solar_areas.rake

Remove the old Sheffield PV Live areas. We've already inserted new ones with updated centroids and reloaded the data.

Remove old Solar Areas

---

app/controllers/schools/advice/advice_base_controller.rb
spec/support/shared_contexts/advice_pages.rb

Prior to refactoring the solar pv controller was overriding the fuel type used for the advice page to be `:electricity` as that is the meter we are reporting on. I've fixed the base controller to use the `advice_page_fuel_type` method again.
Also fixed the shared context which was using electricity, hence no failures during refactoring.

Fix fuel type used for solar pv advice page dates

---

app/views/schools/configuration/_form.html.erb

Allow blank option in scoreboard drop-down. Otherwise the value defaults to East Midlands scoreboard (alphabetically first in the list) so updates the school when saved.

Allow blank scoreboard option

---

app/services/aggregate_school_service.rb
config/environments/production.rb
lib/energy_sparks/file_store.rb

Extends FileStore to provide a method that checks if an cache entry exists on disk, but without loading it to check for expiry.
While not suitable for use in all cases, this avoids the need to actually load a MeterCollection when we just need to check whether it's in the cache. This means when we're caching partials we can completely remove loading the MeterCollection from the request.
Its reliant on there being no expiry on the cached meter collections, but we're unlikely to change that any time soon.
Try locally:
```
require './lib/energy_sparks/file_store'
config.cache_store = EnergySparks::FileStore.new("tmp/rails_cache_store")
```

Extend FileStore

---

app/assets/stylesheets/bootstrap-overrides.scss
app/assets/stylesheets/links.scss
app/assets/stylesheets/themes.scss
app/components/elements/image_component.rb
app/components/layout/cards/testimonial_component/testimonial_component.html.erb
app/components/layout/grid_component.rb
app/views/home/education_workshops.html.erb
app/views/home/energy_audits.html.erb
app/views/home/index.html.erb
config/locales/common.yml
config/locales/views/home/education_workshops.yml
lib/tasks/deployment/20250508193906_add_new_workshops_page_feature.rake
spec/components/layout/grid_component_spec.rb
spec/components/previews/layout/cards/feature_component_preview.rb
spec/system/home_spec.rb

Builds education workshops page. 
Also - adds xxl viewport, for more flexibility on wider screens
Fiddles with margins / padding a bit more elsewhere and I expect to build this more into standard component behaviour as we build more pages.
Also changes the 2 col layout to break to 1 col on md size screens and lower (tablets). I think this looks better than the squished / misaligned version with 2 columns on this size.
Keen to get this on test if ok'd with you @ldodds as Sarah is reviewing the other pages as we speak.

Build education workshop page from new components

---

app/mailers/alert_mailer.rb
spec/mailers/alert_mailer_spec.rb

Used the Mailgun [o:deliverytime](https://www.mailgun.com/blog/email/tips-tricks-scheduling-email-delivery/) parameter to time shift the alert email deliveries.
Delivery time is set for 15 minutes after the call to send the email, to help offset the peak of Wednesday morning load caused by email generation from the additional load caused by the increase in (automated) traffic from the emails being delivered.
In theory all emails should be delivered around 15 minutes after the last `GenerateSubscriptionsJob`.

Time shift alert email delivery

---

app/controllers/schools/advice/base_out_of_hours_controller.rb
app/services/schools/advice/out_of_hours_usage_service.rb
app/views/schools/advice/electricity_out_of_hours/_analysis.html.erb
app/views/schools/advice/electricity_out_of_hours/_insights.html.erb
app/views/schools/advice/electricity_out_of_hours/_insights_intro.html.erb
app/views/schools/advice/gas_out_of_hours/_analysis.html.erb
app/views/schools/advice/gas_out_of_hours/_insights.html.erb
app/views/schools/advice/gas_out_of_hours/_insights_intro.html.erb

Adds template caching to the out of hours pages.
- Add OutOfHoursUsageService for use by the templates
- Refactor controller and templates to use the service
- Add caching to insights and analysis templates

Cache out of hours pages

---

app/views/schools/configuration/_form.html.erb

Was trying to diagnose a problem with a school not have solar data area. Turns out the form doesn't allow blanks so it was looking like the area was first on the list, rather than empty.
Adding a blank option so its clear if the area is missing (which shouldn't happen in practice).

Allow blank option in form

---

app/services/solar/low_carbon_hub_downloader.rb

There are was an API outage in the Low Carbon Hub api today. We ended up with multiple errors in Rollbar:
- one triggered by a failure to parse the response (it was HTML, not JSON) which was logged in the downloader
- a second error triggered by the upserter code continuing to run with a nil response from the downloader
There's already an exception handler in BaseDownloadAndUpsert which captures and logs unhandled exceptions. So there's no need for one in the downloader.
Avoids getting a flurry of additional unrelated errors when there's an API problem.

Remove exception handler in Low Carbon Hub Downloader

---

app/views/schools/your_school_estates/edit.html.erb

Fix button on your school estate page

---

app/controllers/pupils/sessions_controller.rb
app/controllers/redirects_controller.rb
app/views/redirects/choose_school.html.erb
config/locales/views/home/home.yml
config/routes.rb
spec/system/redirects_spec.rb

Adds a new set of short-links that attempts to redirect a user to the right location for their school. These are intended to be used from the new support pages, but might be used elsewhere (e.g. in newsletters).
The syntax is: `/s/:path`
If a user is logged in as a pupil or school user, we redirect them to the appropriate place. 
If `:path` is `dashboard` then we redirect to the school dashboard. If it is `pupils` we redirect to the pupil dashboard. Otherwise the path is assumed to be a school relative link. E.g. `/s/advice` would redirect to something like `/s/some-primary-school/advice`.
This allows all the school relative admin pages, advice, etc to be targeted.
If the user is not currently signed in, then they are prompted to login and are then redirected. Group admins or school …

School page short-links

---

lib/tasks/deployment/20250623103547_add_new_entrust_data_config.rake

The files from Entrust that come in to the data inbox now have an additional column for the ‘Total Units’.
I have also noticed the last reading column is 00:00:00 and not 24:00 as before, so have changed this too. 
A new config was requested rather than an update to the last.
Have tested it with the sample and it seems to work

New Entrust data config

---

app/services/school_creator.rb
spec/factories/schools_factory.rb
spec/services/school_creator_spec.rb
spec/support/shared_examples/admin_school_group_onboardings.rb
spec/system/school_onboarding_spec.rb
spec/system/schools/dashboard/manage_school_spec.rb

Changes where we apply the assertion that we have consent to collect and store data to when the school is made data visible, rather than visible. Otherwise school users cannot login to grant consent.
Works around an issue for schools that joined before the current workflow and we don't have a consent document stored in the database (just elsewhere).

Check for consent to collect and store data on making data visible, not visible

---

app/views/dcc_mailer/dcc_meter_status_email.html.erb
spec/factories/school_groups_factory.rb
spec/factories/schools_factory.rb
spec/mailers/dcc_mailer_spec.rb
spec/services/confirmation_reminder_spec.rb
spec/services/mailchimp/csv_exporter_spec.rb
spec/system/admin/reports/engaged_schools_report_spec.rb
spec/system/admin/reports/mailchimp_status_spec.rb
spec/system/admin/reports/manual_reads_spec.rb
spec/system/admin/school_groups_spec.rb
spec/system/school_groups_spec.rb

Add the school group and admin name to the email.
Changed the school group factory so that by default it has an admin user, as that matches real data more closely. As a result i needed to update some specs.

Add columns to smart meter email

---

lib/tasks/deployment/20250709140550_fix_regent_config.rake

Fix issue with config created in https://github.com/Energy-Sparks/energy-sparks/pull/4515.
Files provided as examples had been opened and saved in Excel so date formats had changed. Should be 2 year date.
As some data has been loaded i've renamed and disabled the old config and created a new one with same identifier.

Fix regent config

---

app/controllers/pupils/analysis_controller.rb

Possibly crawlers accessing links as “storage+heaters” rather than “storage_heaters”. I don’t believe we publish the former as links anywhere. But fixing to reduce noise in rollbar

Fix for incorrect url parameters

---

app/controllers/admin/newsletters_controller.rb
app/controllers/case_studies_controller.rb
app/controllers/newsletters_controller.rb
app/models/case_study.rb
app/models/cms/category.rb
app/models/cms/page.rb
app/models/concerns/publishable.rb
app/models/newsletter.rb
app/views/admin/case_studies/_form.html.erb
app/views/admin/cms/categories/index.html.erb
app/views/admin/cms/pages/index.html.erb
app/views/admin/cms/sections/index.html.erb
app/views/admin/newsletters/_form.html.erb
app/views/admin/newsletters/_title_and_navigation.html.erb
app/views/admin/newsletters/edit.html.erb
app/views/admin/newsletters/index.html.erb
app/views/admin/newsletters/new.html.erb
app/views/admin/newsletters/show.html.erb
app/views/case_studies/index.html.erb
app/views/newsletters/index.html.erb
config/locales/views/home/home.yml
db/migrate/20250711133624_add_published_to_newsletters.rb
db/schema.rb
spec/models/case_study_spec.rb
spec/models/newsletter_spec.rb
spec/system/admin/case_studies_spec.rb
spec/system/admin/newsletter_spec.rb
spec/system/case_studies_spec.rb

* Added published flag and change history functionality to newsletter model and admin interfaces. Also changed newsletter and case studies to only be publishable if an image is present (hope this is ok, makes sense to me).
* Added better rpsec for newsletters. 
The titles can be quite inconsistent for newsletters:
Example 1: 2024/25 Term 1:4: Half term switch off reminder
Example 2: Tips for identifying and fixing lighting problems in your school - Getting the most out of Energy Sparks
Example 3: 2024/25 Term 2:2 LUPD
We either could do with changing some so they are consistent or the other option (which I've just thought of) is to add tags list like we do for case studies, for the '2024/25 Term 1:4' bit and then also have a more descriptive title.

Redesign newsletters page

---

app/services/aggregation/validate_amr_data.rb
spec/services/aggregation/validate_amr_data_spec.rb

A previous change to the validator [made here](https://github.com/Energy-Sparks/energy-sparks/pull/4543/files#diff-1a0f2510fb6b3b861ad7f07f0557f39c3ee002c4b9d061096abe28949003140aL595) changed the behaviour for handling days with partial or all missing readings.
Previously days with all or partial missing readings were removed from the AMRData then later substituted or interpolated. If the substitution failed then the day had already been removed, so it would later be substituted again, filled with PROB data or, for large amounts of missing reading, replaced with an LGAP reading. It would also mean that partial/missing readings would not be used for later substitutions.
With the current code the invalid readings are left in place.
I've restored the behaviour to fix an issue encountered on …

Remove entire day if all readings are negative

---

app/views/schools/downloads/index.html.erb
app/views/schools/meters/_active_meters.html.erb
app/views/schools/meters/index.html.erb
spec/system/meter_management_spec.rb

Group admins can access school meter data downloads, but there's no obvious link to the page currently.
PR:
- revises meter page to allow direct links to download data for all school users and group admins
- add link to school download page for all school users and group admins

Add links to meter downloads for group admins

---

app/models/activity.rb
spec/system/activities_spec.rb

If a user corrects the date on a previously recorded activity, the system doesn't currently update the `.at` field of the link observation(s).
This PR adds a basic spec for the editing workflow and a callback on the model to ensure they stay in sync.

Updated observation time when activity edited

---

app/components/cms/search_results_component/search_results_component.html.erb
app/components/cms/search_results_component/search_results_component.scss
app/models/concerns/searchable.rb
spec/models/cms/section_spec.rb

Fixes issue in `Searchable`, results should be in descending rank. Also adds the [`MaxFragments`](https://www.postgresql.org/docs/current/textsearch-controls.html#TEXTSEARCH-HEADLINE) parameter to the `ts_headline` function to improve snippets -- this seems better at producing longer snippets with whole sentences.
Minor improvements in the styling in the results so that the category badges are blue.

Fix support page searching and results

---

app/components/page_nav_component.rb
app/components/page_nav_component/page_nav_component.scss
app/views/schools/advice/_nav.html.erb
spec/components/page_nav_component_spec.rb
spec/system/schools/advice_pages/advice_page_index_spec.rb

The PageNavComponent has some styling issues:
Fix the styling by refactoring the HTML slightly to add spans for labels and toggle icons and then use flex box to layout the content.
Also updated the component so that items can have a "note" which will allow some text to be put into the same location as the toggle icons. Switched the advice navbar to use this so that the recent alert and opportunities counts are laid out better.

Improve layout of page nav component with longer items

---

app/mailers/onboarding_mailer2025.rb
app/models/management_priority.rb
app/models/school.rb
app/services/schools/priorities.rb

Two of the management opportunities we might recommend to schools involve some capital investment: installing solar and lagging hot water pipes. Exclude these from the data enabled emails as we want them to focus on quick wins from behaviour change.
Also sort the opportunities presented here based on kWh reduction not cost, so they can see the biggest energy efficiency and carbon saving.

Exclude capital investment opportunities in data enabled email

---

Gemfile
Gemfile.lock
lib/tasks/schools/download_gias_data.rake

Add a Rake task (`school:download_gias_data`) to download data from gov.uk.
Downloads "establishment fields" and "establishment links" from https://get-information-schools.service.gov.uk/Downloads.

Add task to download Get Information about Schools data

---

app/views/admin/case_studies/_form.html.erb
app/views/case_studies/index.html.erb
spec/system/admin/case_studies_spec.rb

* Adds missing position field to case studies admin interface
* Also sorts out the rounding used for the text portion of a case study on the case studies index. Not sure what happened there as I'm sure it was right. It is currently like this on production:

Sort out the priority numbering for case studies

---

app/components/charts/comparison_chart_component.rb
app/controllers/comparisons/base_controller.rb
app/controllers/comparisons/change_in_electricity_since_last_year_controller.rb
app/controllers/comparisons/shared/change_in_consumption_controller.rb
app/services/charts/comparison_chart_data.rb
spec/services/charts/comparison_chart_data_spec.rb

There's a severe bug with the stacked comparison charts.
If the chart has multiple series and a school doesn't have a value for that series, then the chart does not display correctly. The values for the series end up shifting, so the chart isn't displaying the actual values for the school.
Manifests as:
- missing series for a school (because value is shifted to a previous school)
- incorrect sorting on chart (again, because the values are shifted)
This PR extracts the code that formats the chart data and adds specs. It fixes this bug and also addresses another display issue.
Sometimes the % change between holidays is very large (e.g. little or no usage during holiday, then sudden increase when gas is turned on). The old comparison reports used a `x_min_value` and `x_max_value` …

Fix sorting and display issues on stacked comparison charts

---

app/components/dashboards/group_savings_prompt_component.rb
app/components/dashboards/group_savings_prompt_component/group_savings_prompt_component.html.erb
app/views/school_groups/show.html.erb
config/locales/views/components/dashboards/group_savings_prompt.yml
spec/components/dashboards/group_savings_prompt_component_spec.rb
spec/components/previews/dashboards/group_savings_prompt_component_preview.rb
spec/system/school_groups/dashboard_spec.rb

Change behaviour of group savings prompt component

---

app/components/page_nav_component.rb
app/components/page_nav_component/page_nav_component.html.erb
app/components/page_nav_component/page_nav_component.scss
app/controllers/school_groups/secr_controller.rb
app/models/ability.rb
app/views/school_groups/advice/shared/_nav.html.erb
config/locales/views/school_groups/school_groups.yml
spec/components/page_nav_component_spec.rb
spec/support/shared_examples/school_groups.rb
spec/system/school_groups/advice/index_spec.rb
spec/system/school_groups/secr_spec.rb

Adds SECR report link to group advice nav.
I am a bit confused about permissions. Should a group admin from a group be able to see another group's secr link and report? I think all school group admins can see any secr report at the moment for any school group. Currently am using can? (:show_management_dash) for the link which only allows group admins to see their own but not sure this is right @ldodds ?
Made some other nav changes while I was there - the nav was highlighting Energy use charts when on any of the top items. i.e.
For the report section (i.e. a non fuel type section) the current and hover was not rounded (like the fuel type ones were). The section header had a grey hover when the fuel sections didn't. Just made them consistent, hope that's ok.
Also added the ability to …

Add secr to advice page nav plus a few other fixes

---

app/controllers/concerns/school_group_advice.rb
app/controllers/school_groups/advice_controller.rb
app/helpers/school_groups_helper.rb
app/services/school_groups/alerts.rb
app/services/school_groups/priority_actions.rb
app/views/comparisons/base/index.html.erb
app/views/school_groups/advice/alerts.html.erb
app/views/school_groups/advice/base/analysis.html.erb
app/views/school_groups/advice/base/insights.html.erb
app/views/school_groups/advice/charts.html.erb
app/views/school_groups/advice/comparison_reports.html.erb
app/views/school_groups/advice/priorities.html.erb
app/views/school_groups/advice/scores.html.erb
app/views/school_groups/advice/shared/_advice_page.html.erb
app/views/school_groups/advice/shared/_nav.html.erb
app/views/school_groups/advice/show.html.erb

- Switch to cache_if for groups. to ensure we're not caching content for `data_sharing_private` or `data_sharing_within_group` schools. Uses new helper
- Extract partial for group advice pages
- Add helper for building cache key for consistency

Additional group caching changes

---

app/models/alert.rb
app/models/management_priority.rb
app/services/school_groups/priority_actions.rb

The EXPLAIN ANALYZE for the `Alert.summarise_alerts` query is faster with the new query which optimises the JOINS and pulls out latest_runs into a CTE with is also filtered.
The results for `ManagementPriority.for_schools` is also slightly faster. Again switches to use a CTE but also uses `JOIN LATERAL ... ON TRUE` to only parse json for the rows being returned.

Optimising loading of alerts content for group advice
